### ISSUE TITLE
[BUG] linesegments failing to show all segments

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Makie.jl#1009]
Consider the following data: https://gist.github.com/juliohm/f93db700b13799364aa794a7ec63b5e6

You can load it with:

```julia
using DelimitedFiles

data = readdlm("debug.dat")
xy = [Tuple(row) for row in eachrow(data)]

6031-element Vector{Tuple{Float64, Float64}}:
 (-68.10552979, -10.72191715)
 (-68.0042572, -10.65369987)
 (-67.70793152, -10.71080971)
 (-67.4079361, -10.37423038)
 ⋮
 (-49.36944199, -13.27460289)
 (-49.23532486, -12.89366913)
 (NaN, NaN)
 (NaN, NaN)
```

Using Plots.jl the line segments are shown correctly:

```julia
using Plots

plot(xy)
```
![image](https://user-images.githubusercontent.com/3345261/120120440-99c29c80-c173-11eb-969a-5ecb0e820888.png)

Using Makie.jl there are missing line segments:

```julia
using GLMakie

linesegments!(xy)
```
![image](https://user-images.githubusercontent.com/3345261/120120453-bced4c00-c173-11eb-916f-05750869ad7e.png)

Appreciate if you can take a look.

**Comment by juliohm** [comment]
The issue may have to do with the way linesegments handles the pairs of points in the vector. In Plots.jl every pair of points is handled whereas in Makie.jl it seems that pairs are skipped two-by-two. In the presence of NaN this may be problematic.

**Comment by jkrumbiegel** [comment]
`lines` is for continuous lines, `linesegments` only for straight segments with 2 points each

**Comment by juliohm** [comment]
Oh I missed that! There must be a good reason for both to exist. Closing the issue.
