### ISSUE TITLE
Lines function name

### ISSUE THREAD

**Issue by jtrakk** [JuliaPlots/Makie.jl#1017]
Afaict, this function makes one curve, not multiple. Why is it named “lines” plural? I always forget how to use it and have to check the docs. I think it will be easier to remember if it uses the name line!/curve!.

https://makie.juliaplots.org/stable/plotting_functions/lines.html

**Comment by jlchan** [comment]
It can make multiple using NaN separators - for example
```julia
x = vcat(1:4,NaN,5:8)
lines(x)
```
gives
<img width="512" alt="Screen Shot 2021-06-01 at 11 01 53 PM" src="https://user-images.githubusercontent.com/1156048/120422186-5ca20a00-c32d-11eb-84a7-dcd3cf6552a9.png">

**Comment by DNF2** [comment]
That's still just one single line object, just with a part masked out, isn't it? For comparison, Matlab uses `line`, and can do the `NaN` trick. Not that Matlab is the ideal model, but it makes sense here.

**Comment by jtrakk** [comment]
To plot a line, I'd like to call `line`. If I want multiple lines I'll call it multiple times or use `linesegments`. The NaN trick doesn't seem like it should be part of a green-field API.

**Comment by jkrumbiegel** [comment]
I'm not sure if this is worth changing now, as the lines name has been around for so long. I also think singular is a bit better, though.

**Comment by aramirezreyes** [comment]
I agree with that it may not worth changing now, however it can still be considered before reaching 1.0, in case it was deemed too important.

**Comment by jtrakk** [comment]
> I'm not sure if this is worth changing now, as the lines name has been around for so long.

Makie's future is hopefully much longer than its past. From a user perspective, I would rather be annoyed once than confused continually.

**Comment by piever** [comment]
I'm also not sure it is worth changing. IMO, the name `line` is equally or more confusing. We have `Makie.vlines!` and `Makie.hlines!` to draw several straight lines and `Makie.abline!` to draw one straight line. This would suggest that `Makie.line!` draws one straight line, and not a path connecting a finite set of points.

If we were to change this, I think that `path` is the clearest name. This corresponds to `seriestype=:path` in Plots, which is the Plots equivalent of this recipe.

**Comment by jtrakk** [comment]
That's a great point @piever. `path` is a better name than `line`.

**Comment by mschauer** [comment]
Well, it's a [line plot](https://en.wikipedia.org/wiki/Line_chart), not a path plot. Interestingly, the "Liniendigramm"  has that plural :-)

**Comment by jtrakk** [comment]
```
fig = Figure()
Axis(fig[1,1])
n = 30; xs = rand(30); ys = rand(30); lines!(xs, ys)
fig
```
<img src="https://user-images.githubusercontent.com/43392409/120697193-46e23100-c462-11eb-8bc0-144aa90cfbb1.png" width="300" height="300">


This looks like a path to me, no?

**Comment by SimonDanisch** [comment]
I don't think its worth changing the name...
