### ISSUE TITLE
CairoMakie: `visible=false` does not work for childplot in recipe

### ISSUE THREAD

**Issue by hexaeder** [JuliaPlots/Makie.jl#1018]
Using the visible kw for subplots in a recipe does not work in CairoMakie. Works as expected in GLMakie.
```julia
using CairoMakie
CairoMakie.activate!()

@recipe(MyScatterLines) do scene
    Attributes()
end

function Makie.plot!(p::MyScatterLines)
    lines!(p, p[1]; visible=true)
    scatter!(p, p[1]; visible=false)
end

f = myscatterlines(rand(Point2f0,5))
save("plot.png", f)
```
<img width="400" alt="Screenshot 2021-06-02 at 12 38 23" src="https://user-images.githubusercontent.com/35867212/120466805-c8bd5600-c39f-11eb-9019-ea51fe8ff197.png">

```julia
using GLMakie
GLMakie.activate!()
f = myscatterlines(rand(Point2f0,5))
```
<img width="400" alt="Screenshot 2021-06-02 at 12 39 05" src="https://user-images.githubusercontent.com/35867212/120466846-d246be00-c39f-11eb-88a0-7c7bc303c593.png">

**Comment by SimonDanisch** [comment]
Oh, I see why this happens: https://github.com/JuliaPlots/CairoMakie.jl/pull/172

**Comment by hexaeder** [comment]
thanks for the fix :)
