### ISSUE TITLE
Individual colors in a merged mesh

### ISSUE THREAD

**Issue by loicspace** [JuliaPlots/Makie.jl#103]
Hi!
I'm (finally) starting to transition from GLVisualize to Makie and I'm not understanding a behavior. I am reproducing the coordinate frame - like mesh from one [GLVisualize example](http://simondanisch.github.io/examples/meshes/) -- the red/gree/blue mesh assembly, and it mostly works except that I seem to need to call the Makie mesh function with an unnecessary attribute, i.e.:

colors = []
Makie.mesh(sc,color=colors)

whereas, calling:

Makie.mesh(sc)

where sc contains the merged color meshes renders an entirely red mesh. I might be missing something, of course.
Here is a code snipped that will reproduce the behavior (output png attached):

```
using Makie, GeometryTypes, Colors

function coordinateFrame(x,scale)

    baselen = 0.2f0 * scale
    dirlen = 1f0 * scale
    # create an array of differently colored boxes in the direction of the 3 axes
    rectangles = [
    (HyperRectangle(Vec3f0(x), Vec3f0(dirlen, baselen, baselen)), RGBA(1f0,0f0,0f0,1f0)),
    (HyperRectangle(Vec3f0(x), Vec3f0(baselen, dirlen, baselen)), RGBA(0f0,1f0,0f0,1f0)),
    (HyperRectangle(Vec3f0(x), Vec3f0(baselen, baselen, dirlen)), RGBA(0f0,0f0,1f0,1f0))
    ]
    meshes = map(GLNormalMesh, rectangles) 
    return meshes
end


function testframe()

    x_sc = Vec3f0(0)
    sc = coordinateFrame(x_sc,1)
    sc = merge(sc)
    colors = []
    scene = Scene(resolution = (500, 500))
    Makie.mesh(sc,color=colors)

    x_sc = Vec3f0(2)
    sc = coordinateFrame(x_sc,1)
    sc = merge(sc)
    Makie.mesh(sc)
    center!(scene)
end

testframe()

```
![frames](https://user-images.githubusercontent.com/17835401/42399529-f7c64a1e-8122-11e8-9013-bccaa09a9669.png)

**Comment by SimonDanisch** [comment]
Should be fixed on master!
I also added an example: https://github.com/JuliaPlots/Makie.jl/blob/master/examples/library.jl#L350

Note that you also need to checkout `Pkg.checkout("AbstractPlotting")`
