### ISSUE TITLE
CairoMakie: Heatmap pdf size increased with latest release

### ISSUE THREAD

**Issue by elkaps** [JuliaPlots/Makie.jl#1044]
The pdf created for the following heatmap is 15.7MB when using CairoMakie v0.5.9 and only 335kB when using CairoMakie v0.5.7.
```
f = Figure()
Axis(f[1, 1])

xs = LinRange(0, 10, 1000)
ys = LinRange(0, 15, 1000)
zs = [cos(x) * sin(y) for x in xs, y in ys]

heatmap!(xs, ys, zs)

save("fig.pdf", f)
```

**Comment by jkrumbiegel** [comment]
There was a bug introduced in an earlier version that used a fast path for non-interpolated heatmaps, which usually results in interpolated display in pdf or svg. This was reverted after 0.5.7, and again non-interpolated heatmaps are drawn via (more expensive) rectangles. Setting `heatmap!(xs, ys, zs, interpolate = true)` should use the fast path again.
