### ISSUE TITLE
display does not refresh during animation

### ISSUE THREAD

**Issue by Benoit9** [JuliaPlots/Makie.jl#105]
I replaced the `record` loop with a plan `for` loop with sleep in the animation example. Only a few frames are displayed.
If I add a `display(Makie.global_gl_screen(), scene)` in the loop, I see the updates but against a flashing black background. Is there another function that forces a refresh?
Thanks!
(Ubuntu 18.04)

` using Makie, GeometryTypes, Colors

scene = Scene(resolution = (500, 500))

f(t, v, s) = (sin(v + t) * s, cos(v + t) * s)
time = Node(0.0)
p1 = scatter!(scene, lift(t-> f.(t, linspace(0, 2pi, 50), 1), time))[end]
p2 = scatter!(scene, lift(t-> f.(t * 2.0, linspace(0, 2pi, 50), 1.5), time))[end]
lines = lift(p1[1], p2[1]) do pos1, pos2
    map((a, b)-> (a, b), pos1, pos2)
end
p3 = linesegments!(scene, lines)

for i in linspace(0, 10, 100)
	push!(time, i)
	sleep(0.1)
end `

**Comment by SimonDanisch** [comment]
`force_update!()` should do what you want!
