### ISSUE TITLE
Heatmaps saved as pdf and svg are always interpolated using CairoMakie

### ISSUE THREAD

**Issue by CaptainKubi** [JuliaPlots/Makie.jl#1052]
Whenever I plot a heatmap using CairoMakie and save it as an svg or pdf the output plot is interpolated even if `interpolation=false`is given in the `heatmap!` plot command.

## Example
The following code snippet
```julia
using CairoMakie
CairoMakie.activate!()
z = [1 2 3; 0 0 0; 4 5 6]
fig=Figure()
ax = fig[1,1] = Axis(fig)
heatmap!(z; interpolate=false)
fig |> display
save("test.pdf", fig)
```
should create following output: This is was is seen when it is saved as png and also what is displayed in VSCodes plot tab.
![test](https://user-images.githubusercontent.com/50375248/121806942-43189080-cc52-11eb-894b-9b57366955b0.png)

When saved as pdf or svg the output however looks like this:
![image](https://user-images.githubusercontent.com/50375248/121806981-74915c00-cc52-11eb-9f40-06714b078870.png)

Unfortunately, I could not create a heatmap plot without interpolation. Thank you for any help you can provide. 😄 

## Package and Julia Versions
- CairoMakie v0.5.7
 - Makie v0.13.12
 - Julia 1.6.1

**Comment by jkrumbiegel** [comment]
We had a regression with heatmaps in that specific CairoMakie version, can you update to 0.6.0? That version doesn't have this problem on my machine.
