### ISSUE TITLE
If Y axis is reversed, text in data space is drawn upside down

### ISSUE THREAD

**Issue by hyphz** [JuliaPlots/Makie.jl#1054]
If text is drawn with `space=:data` into an axis with `yreversed` set true, then the text is drawn upside down. There appears to be no way around this as there is no option to apply inversion to the text alone.

While I understand this is technically correct in computer graphics, as the text is being drawn in an inverted coordinate space, it does not seem to be be appropriate in plotting. While the direction of the axis may change the way in which data representations are arranged, it should not change those representations.

**Comment by jkrumbiegel** [comment]
Why are you using `space = :data` if you don't want the text orientation to be affected by the projection? That's what `space = :screen` is for

**Comment by hyphz** [comment]
`space = :screen` causes the position to be in screen space, which is not correct. The text does correspond to the data; the fact that I want the text to correspond to the data should in no way imply that I want it not to be readable text.

**Comment by jkrumbiegel** [comment]
No the position is always given in data space. The projection is different

**Comment by jkrumbiegel** [comment]
http://makie.juliaplots.org/stable/plotting_functions/text.html#Examples

**Comment by hyphz** [comment]
Ah, I was caught out by the fact that textsize also varies between spaces.
