### ISSUE TITLE
Passing Makie figure as an image

### ISSUE THREAD

**Issue by mjyshin** [JuliaPlots/Makie.jl#1067]
This may be a strange thing to try, but I was wondering if there was a way to (very) quickly convert a Makie figure as, say, a JuliaImage object so I could plot it with a different plotting package like Plots? Something like...

```Julia
using Makie, Plots
fig = Figure() # ... create figure ...
img = convert_to_img(fig)
Plots.plot(img)
```

Thank you for the help!

**Comment by SimonDanisch** [comment]
There is: ` Makie.colorbuffer(fig.scene)`
