### ISSUE TITLE
Out-of-focus plot window does not always redraw fully after center!()

### ISSUE THREAD

**Issue by Benoit9** [JuliaPlots/Makie.jl#107]
When the plot window does not have focus (because the terminal window does), a call to `center!(scene)` leaves it black or partially drawn. 
That seems to happen when the plot window is partially occluded.
Bringing it back in focus makes everything redraw OK. As does a call to `force_update!()`

I am on Ubuntu 18.04 / Unity

**Comment by SimonDanisch** [comment]
Can you point out an MWE? This should likely be fixed on master of Makie + AbstractPlotting

**Comment by SimonDanisch** [comment]
please reopen if you find this not to be true
