### ISSUE TITLE
GLMakie: duplicate code line in recent commit (no impact)

### ISSUE THREAD

**Issue by kragol** [JuliaPlots/Makie.jl#1099]
A recent commit ended up duplicating a line by mistake: GLMakie/src/drawing_primitives.jl#L345

**Comment by SimonDanisch** [comment]
Fixed in https://github.com/JuliaPlots/Makie.jl/commit/9f3ee112f0595facbe50c3b285ff15a9e4677eda

Btw, on any file here on Github, you can click "edit" and just create a PR like that ;)
