### ISSUE TITLE
MethodError applying `xticks!` with labels to existing Axis

### ISSUE THREAD

**Issue by NHDaly** [JuliaPlots/Makie.jl#1110]
I was attempting to follow the example in http://makie.juliaplots.org/stable/plotting_functions/barplot.html#barplot, but I wanted to adjust the `xticks` on an _existing_ Axis, rather than setting them when constructing the axis.

However, when I tried that, I get the following MethodError:
```julia
julia> using GLMakie

julia> fig = Figure()

julia> ax = fig[1,1] = Axis(fig)
Axis with 0 plots:


julia> xticks!(ax, xtickrange=1:3, xticklabels=["left", "middle", "right"])
ERROR: MethodError: no method matching getindex(::Axis, ::Type{OldAxis})
Stacktrace:
 [1] tickranges(scene::Axis)
   @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/shorthands.jl:168
 [2] xticks!(scene::Axis; xtickrange::UnitRange{Int64}, xticklabels::Vector{String})
   @ AbstractPlotting ~/.julia/packages/AbstractPlotting/M8Nlv/src/shorthands.jl:220
 [3] top-level scope
   @ REPL[150]:1
```

I originally thought I should be able to just call `xticks!(ax, (1:3, ["left", "middle", "right"]))` to match the format in the constructor, but that doesn't seem to be supported either:
```julia
julia> xticks!(ax, (1:3, ["left", "middle", "right"]))
ERROR: MethodError: no method matching xticks!(::Axis, ::Tuple{UnitRange{Int64}, Vector{String}})
Closest candidates are:
  xticks!(::Any; xtickrange, xticklabels) at /Users/daly/.julia/packages/AbstractPlotting/M8Nlv/src/shorthands.jl:219
Stacktrace:
 [1] top-level scope
   @ REPL[151]:1
```

**Comment by NHDaly** [comment]
And the whole reason I was trying the above, is that the tick labels in the mutating `barplot!()` constructor seem to be ignored. I think that's probably a bug, too?

Here's the original example from the tutorial:

```julia
julia> using GLMakie

julia> tbl = (x = [1, 1, 1, 2, 2, 2, 3, 3, 3],
              height = 0.1:0.1:0.9,
              grp = [1, 2, 3, 1, 2, 3, 1, 2, 3],
              grp1 = [1, 2, 2, 1, 1, 2, 1, 1, 2],
              grp2 = [1, 1, 2, 1, 2, 1, 1, 2, 1]
              )
(x = [1, 1, 1, 2, 2, 2, 3, 3, 3], height = 0.1:0.1:0.9, grp = [1, 2, 3, 1, 2, 3, 1, 2, 3], grp1 = [1, 2, 2, 1, 1, 2, 1, 1, 2], grp2 = [1, 1, 2, 1, 2, 1, 1, 2, 1])

julia> barplot(tbl.x, tbl.height,
               stack = tbl.grp,
               color = tbl.grp,
               axis = (xticks = (1:3, ["left", "middle", "right"]),
                       title = "Stacked bars"),
               )
```
<img width="512" alt="Screen Shot 2021-07-11 at 3 51 37 PM" src="https://user-images.githubusercontent.com/1582097/125208370-e8c61c00-e25f-11eb-8811-c9377b0abbf0.png">


But when i use the mutating function, the `axis` modifications are all silently ignored:

```julia
julia> using GLMakie

julia> fig = Figure()

julia> ax = fig[1,1] = Axis(fig)
Axis with 0 plots:


julia> barplot!(ax, tbl.x, tbl.height,
               stack = tbl.grp,
               color = tbl.grp,
               axis = (xticks = (1:3, ["left", "middle", "right"]),
                       title = "Stacked bars"),
               )
BarPlot{Tuple{Vector{Point{2, Float32}}}}
```
<img width="512" alt="Screen Shot 2021-07-11 at 3 53 35 PM" src="https://user-images.githubusercontent.com/1582097/125208421-35a9f280-e260-11eb-86fb-b2394d6a0f2a.png">

**Comment by jkrumbiegel** [comment]
xticks! is an older function, it doesn't relate to Axis. You can do ax.xticks = ...

You still have abstractplotting in your stacktrace, that also means you're not on the current version, you might want to consider updating.

**Comment by NHDaly** [comment]
Thanks for both the comments. I'll try both.

**Comment by NHDaly** [comment]
👍 thanks, the setproperty syntax worked for me. 👍

**Comment by jkrumbiegel** [comment]
Axis keywords are only used when creating an axis, so only with the non ! syntax

**Comment by NHDaly** [comment]
k thanks. I'm closing this now, since my questions were answered (although would of course always love more informative error messages 😊 ).

Also, regarding the old version, it turned out to be that Blink was keeping me on an older version. Time to upgrade to Electron.jl, probably. 👍 Thanks!
