### ISSUE TITLE
Observables in axis tics

### ISSUE THREAD

**Issue by timo-berg** [JuliaPlots/Makie.jl#1116]
I want to scroll through data via a slider. The scrolling itself works fine because `lines!` can handle observables as input.
I haven't found a way however to also update the xticks as well.
Setting the xticks with an observable vector results in `MethodError: no method matching length(::Observable{StepRange{Int64, Int64}})`

Is there a way to update xticks on slider value change?
Thanks!

**Comment by jkrumbiegel** [comment]
You don't set the `xticks` to an observable with a vector, you update them with a vector that can be stored in an observable if you want. `xticks` itself is an `Observable{Any}` attribute, so of course you can set the content to `Observable{Vector}` but then things will break as you saw.

```julia
on(slider.value) do value
    ax.xticks = some_valid_xticks
end
```

**Comment by timo-berg** [comment]
You are my hero! Thank you!
