### ISSUE TITLE
What triggers events.scroll?

### ISSUE THREAD

**Issue by timo-berg** [JuliaPlots/Makie.jl#1127]
I'm trying to make some interaction with the mouse wheel. I was assuming that the `events.scroll` responds to scrolling of the mouse. However, this doesn't seem to be the case. Mouse/Keyboard button presses work fine.

```Julia
on(events(fig).scroll , priority = 0) do event
    print(event)
    return Consume(false)
end
```

Is there something wrong with my code or is the `events.scroll` responding to something else?

**Comment by SimonDanisch** [comment]
You need to use a higher priority, since the default axis zoom already consumes that event:
```julia
on(events(fig).scroll , priority = 100) do event
    print(event)
    return Consume(false)
end
```
