### ISSUE TITLE
Title in example "Animations using Observables" not update as expected

### ISSUE THREAD

**Issue by lihua-cat** [JuliaPlots/Makie.jl#1128]
The example: [Animations using Observables](http://makie.juliaplots.org/stable/animation.html#Animations-using-Observables)

This code in the example should create a changeable title but it failed. 
```julia
fig = lines(xs, ys_1, color = :blue, linewidth = 4,
    axis = (title = @lift("t = $(round($time, digits = 1))"),))
```

**Comment by SimonDanisch** [comment]
That looks like a regression in 0.15... Started fixing it here: https://github.com/JuliaPlots/Makie.jl/pull/1130

**Comment by zioroboco** [comment]
Hey @SimonDanisch — I was watching this issue and noticed you'd closed the linked PR.

I came across #1133, which has merged. Was this addressing the same bug?

**Comment by SimonDanisch** [comment]
Yes, this should be fixed now!
