### ISSUE TITLE
Moving docs to Franklin

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/Makie.jl#1139]
This issue can serve as a hub for tracking what issues need to be solved to move the docs to a custom Franklin site. The problem with Documenter is that it is not very flexible to accomodate things we would like to have, such as galleries of generated plots and a layout or design that is more inviting and less formal than a purely docs-oriented approach.

The current work is on this branch: https://github.com/JuliaPlots/Makie.jl/tree/jk/franklin-docs

The biggest issue that needs to be solved is how to build the plot generating infrastructure, and how to access generated plots to build galleries or other overview sites. @tlienart this is where I hope you can help me, as I don't understand the Franklin process well enough to predict what is going to work.

You can see on this page https://github.com/JuliaPlots/Makie.jl/blob/jk/franklin-docs/docs_franklin/site/plotting_functions/scatter.md how I wrote a small helper lxfun to generate plots and input them at the same location with less boilerplate (this will repeat hundreds of times possibly). Then the index page of plotting functions should have a list of all the plotting functions that are in that folder, with thumbnails of their plots included. This means that I need access to the generated image files when the code here runs https://github.com/JuliaPlots/Makie.jl/blob/jk/franklin-docs/docs_franklin/site/plotting_functions/index.md.

Because I don't have access to the generated images, the current version looks like this:
![grafik](https://user-images.githubusercontent.com/22495855/126036784-eb7c2315-7ec2-4a8b-9e70-27c8afdd9a4d.png)

The code in `index.md` would also handle things like generating the thumbnails in the first place, as I want to have that logic centralized and not happen everywhere where a plot is saved.

@tlienart I hope this can be done without introducing a more complex multi-layered approach, where I first need to run generation-scripts manually, then run the Franklin build on top of that. But let me know if that can't be avoided, I want to gauge how much effort the whole project would be and if it's worth doing. Thank you!

**Comment by tlienart** [comment]
Hello Julius,

Could you look at this demo page:

https://tlienart.github.io/demoplotsgallery/

with source code

https://github.com/tlienart/demoplotsgallery

I used PyPlot because I know it well but the whole story should be the same with Make. Maybe run that page, modify the functions a bit, and let's iterate from there if you think I didn't address some of the stuff you'd like to do?

**Comment by jkrumbiegel** [comment]
Thanks a lot, I didn't have time for a thorough look yet but `@delay` seems to be the missing piece of the puzzle for me!
