### ISSUE TITLE
Idomatic way to delete plots in a dynamic scene

### ISSUE THREAD

**Issue by timo-berg** [JuliaPlots/Makie.jl#1140]
I have a scene in which data is plotted that updates on scroll (i.e. number of data points and what data points change). I want to draw vlines at certain time points  which need to be redrawn on scroll to remain at the correct time point.
I have tried different strategies:

1.  Save lines in an array and iterate over the array to delete. This results in "plot not in scene" error
```Julia
event_array = []
on(range) do value
    draw_events(event_array)
end

function draw_events(event_array)
    # Delete old events
    if !isempty(event_array)
        for i in 1:size(event_array)[1]
            delete!(axis, event_array[i])
        end
    end

    # Draw new events and store them in event array
    vis_events = evts_df[ lower_bound[] .< evts_df[:,:latency] .< upper_bound[],:]
    append!(event_array,[vlines!(axis, event.latency/srate, color = :red) for event in eachrow(vis_events)])
end
```
2.  Iterate over axis.scene.plots and check each plot if it is from the correct type. If yes, delete it.
This results in an BoundsError
```Julia
function draw_events()
    # Delete old events
    for i in 1:size(axis.scene.plots)[1]
        if typeof(axis.scene.plots[i]) == LineSegments{Tuple{Base.ReinterpretArray{Point{2, Float32}, 1, Tuple{Point{2, Float32}, Point{2, Float32}}, Vector{Tuple{Point{2, Float32}, Point{2, Float32}}}, false}}}
            delete!(axis, axis.scene.plots[i])
        end
    end

    # Draw new events and store them in event array
    vis_events = evts_df[ lower_bound[] .< evts_df[:,:latency] .< upper_bound[],:]
    event_lines = [vlines!(axis, event.latency/srate, color = :red) for event in eachrow(vis_events)]
end
```

I have the feeling that both approaches are wrong in general so I would like to know what an idomatic approach would be.
Thanks in advance!

**Comment by timo-berg** [comment]
I think I found a neat solution. I first create all plots with an observable position and set them invisible.
```Julia
event_plots = map(evts_df.latency) do latency
    plot_pos = @lift(latency-$lower_bound)
    vlines!(axis, plot_pos, visible = false)
end
```
When the view shifts, a function is called that makes plots in the view visible and plots outside of it invisible
```Julia
on(range) do value
    redraw_events(event_plots)
end

function redraw_events(plots)
    # Draw new events and store them in event array
    vis_events = lower_bound[] .< evts_df[:,:latency] .< upper_bound[]
    for event in plots[vis_events]
        event.visible = true
    end
    for event in plots[.!vis_events]
        event.visible = false
    end
end
```

Whether this is efficient or not I don't know but it seems to run smooth in my case.
Suggestions very welcome!

**Comment by SimonDanisch** [comment]
visible was definitely intended as a cheap "remove" operation ;)

**Comment by timo-berg** [comment]
So I guess it is cheaper computationally to toggle the visibility than to delete/redraw the plot?

**Comment by SimonDanisch** [comment]
Yeah, definitely! Creating a plot object is comparatively expensive
