### ISSUE TITLE
[feature request] text input widgets

### ISSUE THREAD

**Issue by HenriDeh** [JuliaPlots/Makie.jl#1149]
I was surprised to see that Makie does not feature the standard text input widgets. I'm mainly thinking about spinboxes and textboxes. But when I compare to what's available in Interact.jl, there are plenty more to add actually.

**Comment by ffreyer** [comment]
`Textbox` is for text input. I don't think it has a page in the docs though.

**Comment by jkrumbiegel** [comment]
Textbox should get a page. The reason there aren't more is that text is always tricky and it takes a lot of time to implement them from scratch.

**Comment by HenriDeh** [comment]
So spinboxes (for number, with + and minus buttons) should be more straightforward ?

**Comment by t-bltg** [comment]
@SimonDanisch I see that `TextBox` has docs now: https://makie.juliaplots.org/stable/examples/layoutables/textbox/index.html (added in https://github.com/JuliaPlots/Makie.jl/commit/9d6ba262206156d75f9620c0b73567edaf8be7fb).

Close ?

**Comment by HenriDeh** [comment]
Sure

**Comment by HenriDeh** [comment]
Oh sorry didn't see the @simon.

**Comment by t-bltg** [comment]
@HenriDeh, I meant anyone ;)
