### ISSUE TITLE
`BarPlot` not in `MakieCore`

### ISSUE THREAD

**Issue by Moelf** [JuliaPlots/Makie.jl#1155]
Is `BarPlot` a fundamental type? Or another way to ask would be: can one extends `barplot` and/or `hist` only depending on `MakieCore`?

**Comment by ffreyer** [comment]
It's not. [It uses `poly`](https://github.com/JuliaPlots/Makie.jl/blob/master/src/basic_recipes/barplot.jl), [which uses `mesh` + `wireframe`](https://github.com/JuliaPlots/Makie.jl/blob/master/src/basic_recipes/poly.jl), which are fundamental ones.

**Comment by Moelf** [comment]
thanks. the what would be the recommended approach to allow plotting of custome bars and hists?

**Comment by SimonDanisch** [comment]
I would likely still use Makie as a dependency right now... MakieCore isn't really well thought out yet, and the way to create all recipes with 0 dependencies is still in flux.

**Comment by Moelf** [comment]
I will hold off the effort for now then since my own pkg is <1000 lines, thanks for the info!

**Comment by SimonDanisch** [comment]
Yeah probably for the best...
Although, I think it will be relatively easy to implement the ability to use BarPlots from MakieRecipe, by having a plot type that's just based on symbols...
E.g. something like that:
```julia
struct Recipes end
struct PlotPlaceHolder{plot} 
    args
    kw
end
function Base.getproperty(::Type{<:Recipes}, field)
   return function plot(args...; kw...) 
           return PlotPlaceHolder{field}(args, kw)
    end
end
```
Then one can use `Recipes.barplot!(args..., kw...)` and in Makie we can create a conversion for that, to the real plot type ;)

**Comment by Moelf** [comment]
since now `MakieCore` is splited, we can close this.
