### ISSUE TITLE
Why so slow even after sysimage?

### ISSUE THREAD

**Issue by HackYardo** [JuliaPlots/Makie.jl#1164]
Julia is a just in time compile language, so run codes for every first time is slow. Luckily, we have the sysimage knack from PackageCompiler to accelerate first time run.
By sysimage, Plots can open a plot window in a second.
However, GLMakie can not open a plot window in ten seconds. Why?

versioninfo()
```
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```
create sysimage
```
using PackageCompiler
create_sysimage(:GLMakie; sysimage_path="sysimage.so",precompile_execution_file="precompile.jl")
```
precompile.jl
```julia
using GLMakie
x=range(0,10,length=100)
y=sin.(x)
lines(x,y)
scatter!(y,x)
current_figure()
```

**Comment by bvdmitri** [comment]
@HackYardo I had the same problem, I think the issue here is that you don't compile `display` function in your `precompile.jl` script. I tried it with 
```julia
using GLMakie
x=range(0,10,length=100)
y=sin.(x)
lines(x,y)
scatter!(y,x)
display(current_figure())
```
and plotting works almost instantaneously.

**Comment by HackYardo** [comment]
I add what you @bvdmitri said, it takes no time to open a plot window 😃
