### ISSUE TITLE
Setting limits in plots

### ISSUE THREAD

**Issue by StefanoGrava** [JuliaPlots/Makie.jl#118]
In the latest Makie and AbstractPlotting, upon:
`using Makie`
`x=linspace(0,3,50)`
`lines(x,sin.(x),limits=FRect(0,0,2,1))`
I get:
![lines_limits](https://user-images.githubusercontent.com/42062939/43638157-0b19e5e8-9718-11e8-883c-45a87532a996.png)
Naively I would expect every point outside the limits to not be plotted. 
Am I setting the limits for the plot correctly?
Is there a way to set the limits like in Plots (`xlims=(0,1)`)?

**Comment by ssfrr** [comment]
+1 to setting limits with `xlims`, `ylims`, `zlims` keyword arguments more like Plots. It avoids the need to invoke the mysterious `FRect` type and feels more intuitive to me.

**Comment by SimonDanisch** [comment]
Sure, that is planned.. But in the form of preprocessing of all kw-args! That's also how I plan to implement @mkborregaard much loved magic kw-args :)

**Comment by Jinwei1987** [comment]
"I would expect every point outside the limits to not be plotted" +1

**Comment by asinghvi17** [comment]
Perhaps the limit calculation pipeline could be invoked within a global attribute conversion?  The relevant code for limit calculations seems to be here:

https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/layouting/data_limits.jl

and a `convert_attributes` function definition would be straightforward to implement on top of that.

**Comment by Tokazama** [comment]
Just got this error in Makie

```julia
julia> xlims!((-1, 1))
ERROR: type Automatic has no field origin
```

What I'm gathering from this issue is that this isn't even implemented for Makie yet?

**Comment by kavir1698** [comment]
> Just got this error in Makie
> 
> ```
> julia> xlims!((-1, 1))
> ERROR: type Automatic has no field origin
> ```

I am getting the same error. Is there any update on this?

**Comment by hendri54** [comment]
Related: the examples in the documentation on setting axis limits throw method errors. See
https://makie.juliaplots.org/stable/makielayout/axis.html#Setting-half-automatic-limits

Is it actually possible right now to set half-limits?

**Comment by jkrumbiegel** [comment]
As a rule of thumb, if you get method errors for docs examples, you're not on the correct version. The docs examples are rerun every release, so they must work exactly as they are. The half open limits were added very recently.

**Comment by hendri54** [comment]
Thank you - I should have thought of that (although I updated very recently).
