### ISSUE TITLE
colormap with transparency?

### ISSUE THREAD

**Issue by jaehongpark-neuro** [JuliaPlots/Makie.jl#1188]
Hi,

I am trying to plot two contour plots with contourf!, so that I overlapped two to compare them.

I was trying to use colormap = (:reds, 0.1) as I do for color=(:red,0.1), but it didn't work.

Can you show me how to draw transparent contourf plots so that I can see both?

Thanks,

**Comment by SimonDanisch** [comment]
You'll need to do:
```julia
colormap = RGBAf0.(Colors.color.(to_colormap(:reds)), 0.1))
```
It would be pretty easy to add that as an convert_attribute:
```julia

function convert_attribute(cmap::Tuple{<: Symbol, Number}, ::key"colormap")
  RGBAf0.(Colors.color.(to_colormap(cmap[1])), cmap[2]))
end
```
With that, your solution should work

**Comment by jaehongpark-neuro** [comment]
oh thanks it works well
