### ISSUE TITLE
pkg> test GLMakie errors 

### ISSUE THREAD

**Issue by andrewmcconnell** [JuliaPlots/Makie.jl#1189]
After adding GLMakie, the first example in the Makie tutorial would open the Makie window but not add any plot features for the sin function and axes.
Running the >pkg test GLMakie resulted in an error,  : 
....
Pick a plot element or plot elements inside a rectangle: Error During Test at /home/andrew/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:27
  Got exception outside of a @test
  MethodError: Cannot `convert` an object of type Vector{Char} to an object of type Char
  Closest candidates are:
    convert(::Type{T}, ::Number) where T<:AbstractChar at char.jl:179
    convert(::Type{T}, ::T) where T<:AbstractChar at char.jl:182
    convert(::Type{T}, ::AbstractChar) where T<:AbstractChar at char.jl:181
    ...
  Stacktrace:
    [1] setproperty!(x::AbstractPlotting.PriorityObservable{Char}, f::Symbol, v::Vector{Char})
      @ Base ./Base.jl:34
...

Test Summary:                                             | Pass  Error  Total
unit tests                                                |    1      2      3
  Window handling                                         |    1      1      2
  Pick a plot element or plot elements inside a rectangle |           1      1
ERROR: LoadError: LoadError: Some tests did not pass: 1 passed, 0 failed, 2 errored, 0 broken.
in expression starting at /home/andrew/.julia/packages/GLMakie/rcykA/test/unit_tests.jl:9
in expression starting at /home/andrew/.julia/packages/GLMakie/rcykA/test/runtests.jl:14
ERROR: Package GLMakie errored during testing

**Comment by SimonDanisch** [comment]
Fixed by: https://github.com/JuliaPlots/Makie.jl/pull/1190

**Comment by SimonDanisch** [comment]
Oh, or so I thought :D Not sure what you're running into here, but CI passes just fine..
Make sure you're on the same versions as in the docs: http://makie.juliaplots.org/stable/#First-Steps 

Not sure how you display things, but e.g. when you're in the VSCode plotpane, you'll need to redisplay the figure

**Comment by andrewmcconnell** [comment]
I should clarify: This test was running on an Nvidia Jetson Nano. Currently their Jetpack version 4.5 only supports CUDA 10.

"JetPack 5.0 will be the next major release, and will include an upgrade to LTS Kernel 5.10 and Ubuntu 20.04. Other noteworthy changes include support for UEFI (replacing CBoot), support for OP-TEE (replacing Trusty as the trusted execution environment), and an upgraded compute stack including CUDA 11. The Developer Preview of JetPack 5.0 is planned for Q1-2022 and the production release is planned for 2H-2022."

**Comment by SimonDanisch** [comment]
As long as the Jetson has OpenGL it should work...
But the error doesn't look platform related at all, so I'd check if you're on these versions first:
http://makie.juliaplots.org/stable/#First-Steps
