### ISSUE TITLE
Graph plotting

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Makie.jl#119]
Can we make plots of graphs in Makie?

**Comment by SimonDanisch** [comment]
Should happen when we integrate the [graph recipes](https://github.com/JuliaPlots/PlotRecipes.jl/blob/master/src/graphs.jl)!

**Comment by Benoit9** [comment]
That'd be great! I am working on some distributed system simulations, and Makie's animation+interactions are perfect for that. I just use scatter, but having arrows and a layout engine (and maybe custom markers, i.e. each marker a tiny subplot) would be awesome.

> when we integrate the [graph recipes](https://github.com/JuliaPlots/PlotRecipes.jl/blob/master/src/graphs.jl)

What does that entail? Is there developer documentation somewhere that would help?

**Comment by gszep** [comment]
click + drag on nodes would be amazing :+1:

**Comment by VarLad** [comment]
Any update on this?

**Comment by SimonDanisch** [comment]
With https://github.com/JuliaGraphs/NetworkLayout.jl , scatter + text + linesegments, it shouldn't be hard to quickly wip something up.
It would be nice to have some basic functionalities like this live in a package.
I know that various people have written some adhoc code for this, maybe we can start colecting them in a package.
I  saw on [discourse](https://discourse.julialang.org/t/interactive-network-visualization/49054), that @elkaps created some code, maybe we can start from there?
There have been at least a handful of other people, but I don't remember their github handle :(

**Comment by mschauer** [comment]
I think what Makie could provide is plotting a graph with labels, fancy edges where the location of the vertices is provided by the callee (using e.g. one of the network layouts.)

**Comment by elkaps** [comment]
@SimonDanisch My solution is not perfect but it does the job for me. Here is the code :)
```julia
using NetworkLayout
using LightGraphs
using Makie
using LinearAlgebra


"""
    closest_point(p, positions)
Returns the index of the point in `positions` closest to `p`
"""
function closest_point(p, positions)
	norms = [norm(p - v) for v in positions]
	return findmin(norms)
end

function make_axis(f::Figure)
    ax = f[1, 1] = Axis(
        f,
        xticklabelsvisible=false,
        yticklabelsvisible=false,
        xticksvisible=false,
        yticksvisible=false,
        xgridvisible=false,
        ygridvisible=false,
        strokevisible=false,
        visible=false,
        xrectzoom=false,
        yrectzoom=false,
        leftspinevisible=false,
        rightspinevisible=false,
        topspinevisible=false,
        bottomspinevisible=false,
    )
end

function plot_graph(g::Graph)

    f = Figure(resolution=(800, 800))

    ax = make_axis(f)

    # create initial vertex positions
    A = adjacency_matrix(g)
    layout = [Point2(p[1], p[2]) for p in NetworkLayout.Spring.layout(A)]
    layout_node = Node(layout)
    
    # create inital edge lines
    edge_lines = [[layout[e.src], layout[e.dst]] for e in edges(g)]    
    line_nodes = Node.(edge_lines)
        
    # initialize for drag & drop
	mouse_left_pressed = false
	selected_vertex = 1

	# handle mouse position
	on(ax.scene.events.mouseposition) do mp		
		pos = to_world(ax.scene, Point(mp) - [30, 30]) # offset fixes https://github.com/JuliaPlots/Makie.jl/issues/457

		if ispressed(ax.scene, Mouse.left)
			
            # if Mouse.left was not pressed before, select vertex
			if !mouse_left_pressed

				d, selected_vertex = closest_point(pos, layout)

				if d > 0.2
					return
				end
				
				mouse_left_pressed = true				
			end

            # update the position of the selected vertex
            layout[selected_vertex] = pos
			
			layout_node[] = layout
            
            for (line, e) in zip(line_nodes, edges(g))
				line[] = [layout[e.src], layout[e.dst]]
			end

        else
			mouse_left_pressed = false
        end
    
    end

    # plot edges
    for line_node in line_nodes
        lines!(ax, line_node)
    end

    # plot vertices
    scatter!(ax, layout_node; )

    f
end
```

**Comment by SimonDanisch** [comment]
I put some initial version into: https://github.com/JuliaPlots/GraphMakie.jl

**Comment by VarLad** [comment]
@SimonDanisch How do I use GraphMakie though....

**Comment by elkaps** [comment]
@VarLad You can do 
```julia
using Makie, GraphMakie, LightGraphs
g = complete_graph(5)
plot_graph(g)
```

**Comment by elkaps** [comment]
I'm not sure how to do the labels though. `scatter!` for strings seams to support one letter only and re-scales it.
With `text!` the size in pixels is not fixed.

**Comment by jkrumbiegel** [comment]
> With `text!` the size in pixels is not fixed.

If I understand you correctly, then you are probably on an older version and should try the recently added `text` function which leaves text constantly sized in pixels as long as `space = :screen` is set (which is the default).

Something like `text!(text_array, position = positions_array)` should do the trick

**Comment by elkaps** [comment]
@jkrumbiegel Sorry for not being more precise. What I meant is that if you zoom in or out of the figure, the size of the scatter points in pixels will be constant while the size of the text changes.

**Comment by jkrumbiegel** [comment]
But that's what I meant, with space = :screen in recent versions which is the default anyway, text should have constant size no matter the zoom level

**Comment by elkaps** [comment]
Thank you @jkrumbiegel I had Makie installed the old way so it was keeping `AbstractPlotting` from updating. Then `text!` should be perfect for adding labels.

**Comment by SimonDanisch** [comment]
I forgot to push an update to add labels, which I have locally... 
It's just not as usable yet without background rectangles, and a easy way to generate an offset in screen space
