### ISSUE TITLE
GLMakie tests failing

### ISSUE THREAD

**Issue by afkowalski** [JuliaPlots/Makie.jl#1214]
Hi there,

I'm running Julia 1.6.2 on Linux and I have been unable to get "test GLMakie" to work.  It fails on all the tests, and here is an example of a long error message spit to the screen.

Thanks in advance for your time,
Adam

Running animated_surface_and_wireframe
┌ Warning: Example Animated surface and wireframe failed
│   exception =
│    LoadError: MethodError: no method matching shadertype(::FileIO.File{FileIO.DataFormat{:UNKNOWN}, String})
│    Closest candidates are:
│      shadertype(::GLMakie.GLAbstraction.Shader) at /home/adamkowalski/.julia/packages/GLMakie/Pway1/src/GLAbstraction/GLShader.jl:63
│      shadertype(::FileIO.File{FileIO.DataFormat{:GLSLShader}, Name} where Name) at /home/adamkowalski/.julia/packages/GLMakie/Pway1/src/GLAbstraction/GLShader.jl:64
│      shadertype(::AbstractString) at /home/adamkowalski/.julia/packages/GLMakie/Pway1/src/GLAbstraction/GLShader.jl:67
│    Stacktrace:
│      [1] compile_shader(path::String, source_str::String)
│        @ GLMakie.GLAbstraction ~/.julia/packages/GLMakie/Pway1/src/GLAbstraction/GLShader.jl:145
│      [2] (::GLMakie.GLAbstraction.var"#53#54"{String, Dict{String, String}, Dict{Symbol, Any}})()
│        @ GLMakie.GLAbstraction ~/.julia/packages/GLMakie/Pway1/src/GLAbstraction/GLShader.jl:170
│      [3] get!(default::GLMakie.GLAbstraction.var"#53#54"{String, Dict{String, String}, Dict{Symbol, Any}}, h::Dict{String, Vector{String}}, key::String)
│        @ Base ./dict.jl:465
│      [4] get_template!(path::String, view::Dict{String, String}, attributes::Dict{Symbol, Any})
│        @ GLMakie.GLAbstraction ~/.julia/packages/GLMakie/Pway1/src/GLAbstraction/GLShader.jl:162
│      [5] gl_convert(lazyshader::GLMakie.GLAbstraction.LazyShader, data::Dict{Symbol, Any})
│        @ GLMakie.GLAbstraction ~/.julia/packages/GLMakie/Pway1/src/GLAbstraction/GLShader.jl:250
│      [6] GLMakie.GLAbstraction.RenderObject(data::Dict{Symbol, Any}, program::GLMakie.GLAbstraction.LazyShader, pre::GLMakie.PostprocessPrerender, post::Nothing, bbs::Observable{GeometryBasics.HyperRectangle{3, Float32}}, main::Nothing)
│        @ GLMakie.GLAbstraction ~/.julia/packages/GLMakie/Pway1/src/GLAbstraction/GLTypes.jl:341
│      [7] RenderObject
│        @ ~/.julia/packages/GLMakie/Pway1/src/GLAbstraction/GLTypes.jl:309 [inlined]
│      [8] postprocess(color::GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{FixedPointNumbers.N0f8}, 2}, position::GLMakie.GLAbstraction.Texture{Vec{4, Float32}, 2}, normal_occlusion::GLMakie.GLAbstraction.Texture{Vec{4, Float32}, 2}, ssao_noise::GLMakie.GLAbstraction.Texture{Vec{2, Float32}, 2}, objectid::GLMakie.GLAbstraction.Texture{Vec2{UInt32}, 2}, color_luma::GLMakie.GLAbstraction.Texture{ColorTypes.RGBA{FixedPointNumbers.N0f8}, 2}, framebuffer_size::Observable{Tuple{Int64, Int64}})
│        @ GLMakie ~/.julia/packages/GLMakie/Pway1/src/glwindow.jl:92
│      [9] GLMakie.GLFramebuffer(fb_size::Tuple{Int64, Int64})
│        @ GLMakie ~/.julia/packages/GLMakie/Pway1/src/glwindow.jl:201
│     [10] GLMakie.Screen(; resolution::Tuple{Int64, Int64}, visible::Bool, title::String, kw_args::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│        @ GLMakie ~/.julia/packages/GLMakie/Pway1/src/screen.jl:333
│     [11] Screen
│        @ ~/.julia/packages/GLMakie/Pway1/src/screen.jl:291 [inlined]
│     [12] global_gl_screen
│        @ ~/.julia/packages/GLMakie/Pway1/src/screen.jl:363 [inlined]
│     [13] global_gl_screen(resolution::Tuple{Int64, Int64}, visibility::Bool, tries::Int64)
│        @ GLMakie ~/.julia/packages/GLMakie/Pway1/src/screen.jl:373
│     [14] global_gl_screen
│        @ ~/.julia/packages/GLMakie/Pway1/src/screen.jl:372 [inlined]
│     [15] backend_display
│        @ ~/.julia/packages/GLMakie/Pway1/src/gl_backend.jl:57 [inlined]
│     [16] VideoStream(scene::Scene; framerate::Int64)
│        @ AbstractPlotting ~/.julia/packages/AbstractPlotting/JCbJs/src/display.jl:370
│     [17] record(func::MakieGallery.##TempModule#335.var"#7#8", scene::Scene, path::String, iter::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}; framerate::Int64, compression::Int64, sleep::Bool)
│        @ AbstractPlotting ~/.julia/packages/AbstractPlotting/JCbJs/src/display.jl:559
│     [18] record(func::Function, scene::Scene, path::String, iter::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}})
│        @ AbstractPlotting ~/.julia/packages/AbstractPlotting/JCbJs/src/display.jl:559
│     [19] top-level scope
│        @ animated_surface_and_wireframe:17
│     [20] eval
│        @ ./boot.jl:360 [inlined]
│     [21] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
│        @ Base ./loading.jl:1116
│     [22] include_string
│        @ ./loading.jl:1126 [inlined]
│     [23] eval_example(entry::MakieGallery.CellEntry; kw_args::Base.Iterators.Pairs{Symbol, MakieGallery.var"#output_path#137"{String}, Tuple{Symbol}, NamedTuple{(:outputfile,), Tuple{MakieGallery.var"#output_path#137"{String}}}})
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/database.jl:583
│     [24] (::MakieGallery.var"#95#96"{Bool, Base.Iterators.Pairs{Symbol, MakieGallery.var"#output_path#137"{String}, Tuple{Symbol}, NamedTuple{(:outputfile,), Tuple{MakieGallery.var"#output_path#137"{String}}}}, MakieGallery.var"#135#138"{Tuple{Int64, Int64}, Bool, String, Vector{Any}}})(entry::MakieGallery.CellEntry)
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/database.jl:613
│     [25] enumerate_examples(::MakieGallery.var"#95#96"{Bool, Base.Iterators.Pairs{Symbol, MakieGallery.var"#output_path#137"{String}, Tuple{Symbol}, NamedTuple{(:outputfile,), Tuple{MakieGallery.var"#output_path#137"{String}}}}, MakieGallery.var"#135#138"{Tuple{Int64, Int64}, Bool, String, Vector{Any}}}; start::Int64, exclude_tags::Nothing)
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/database.jl:539
│     [26] #eval_examples#94
│        @ ~/.julia/packages/MakieGallery/V0mvg/src/database.jl:611 [inlined]
│     [27] macro expansion
│        @ ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:290 [inlined]
│     [28] macro expansion
│        @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
│     [29] record_examples(folder::String; resolution::Tuple{Int64, Int64}, resume::Bool, generate_thumbnail::Bool, display::Bool, display_output_toplevel::Bool)
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:290
│     [30] record_examples(folder::String)
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:273
│     [31] top-level scope
│        @ ~/.julia/packages/GLMakie/Pway1/test/runtests.jl:16
│     [32] include(fname::String)
│        @ Base.MainInclude ./client.jl:444
│     [33] top-level scope
│        @ none:6
│     [34] eval
│        @ ./boot.jl:360 [inlined]
│     [35] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:261
│     [36] _start()
│        @ Base ./client.jl:485
│    in expression starting at animated_surface_and_wireframe:17
└ @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/database.jl:585
with source:
    
    
        scene = Scene();
        function xy_data(x, y)
            r = sqrt(x^2 + y^2)
            r == 0.0 ? 1f0 : (sin(r)/r)
        end
        
        r = range(-2, stop = 2, length = 50)
        surf_func(i) = [Float32(xy_data(x*i, y*i)) for x = r, y = r]
        z = surf_func(20)
        surf = surface!(scene, r, r, z)[end]
        
        wf = wireframe!(scene, r, r, lift(x-> x .+ 1.0, surf[3]),
            linewidth = 2f0, color = lift(x-> to_colormap(x)[5], surf[:colormap])
        )
        record(scene, "/home/adamkowalski/.julia/packages/GLMakie/Pway1/test/test_recordings/tmp/animated_surface_and_wireframe.mp4", range(5, stop = 40, length = 3)) do i
            surf[3] = surf_func(i)
        end
        
    
┌ Warning: Error thrown when evaluating Animated surface and wireframe
│   exception =
│    MethodError: no method matching save_media(::MakieGallery.CellEntry, ::Nothing, ::String)
│    Closest candidates are:
│      save_media(::Any, ::Scene, ::String) at /home/adamkowalski/.julia/packages/MakieGallery/V0mvg/src/io.jl:17
│      save_media(::Any, ::String, ::String) at /home/adamkowalski/.julia/packages/MakieGallery/V0mvg/src/io.jl:23
│      save_media(::Any, ::Stepper, ::String) at /home/adamkowalski/.julia/packages/MakieGallery/V0mvg/src/io.jl:31
│      ...
│    Stacktrace:
│      [1] macro expansion
│        @ ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:297 [inlined]
│      [2] macro expansion
│        @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
│      [3] (::MakieGallery.var"#135#138"{Tuple{Int64, Int64}, Bool, String, Vector{Any}})(example::MakieGallery.CellEntry, value::Nothing)
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:293
│      [4] (::MakieGallery.var"#95#96"{Bool, Base.Iterators.Pairs{Symbol, MakieGallery.var"#output_path#137"{String}, Tuple{Symbol}, NamedTuple{(:outputfile,), Tuple{MakieGallery.var"#output_path#137"{String}}}}, MakieGallery.var"#135#138"{Tuple{Int64, Int64}, Bool, String, Vector{Any}}})(entry::MakieGallery.CellEntry)
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/database.jl:614
│      [5] enumerate_examples(::MakieGallery.var"#95#96"{Bool, Base.Iterators.Pairs{Symbol, MakieGallery.var"#output_path#137"{String}, Tuple{Symbol}, NamedTuple{(:outputfile,), Tuple{MakieGallery.var"#output_path#137"{String}}}}, MakieGallery.var"#135#138"{Tuple{Int64, Int64}, Bool, String, Vector{Any}}}; start::Int64, exclude_tags::Nothing)
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/database.jl:539
│      [6] #eval_examples#94
│        @ ~/.julia/packages/MakieGallery/V0mvg/src/database.jl:611 [inlined]
│      [7] macro expansion
│        @ ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:290 [inlined]
│      [8] macro expansion
│        @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
│      [9] record_examples(folder::String; resolution::Tuple{Int64, Int64}, resume::Bool, generate_thumbnail::Bool, display::Bool, display_output_toplevel::Bool)
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:290
│     [10] record_examples(folder::String)
│        @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:273
│     [11] top-level scope
│        @ ~/.julia/packages/GLMakie/Pway1/test/runtests.jl:16
│     [12] include(fname::String)
│        @ Base.MainInclude ./client.jl:444
│     [13] top-level scope
│        @ none:6
│     [14] eval
│        @ ./boot.jl:360 [inlined]
│     [15] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:261
│     [16] _start()
│        @ Base ./client.jl:485
└ @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:308
Animated surface and wireframe: Test Failed at /home/adamkowalski/.julia/packages/MakieGallery/V0mvg/src/io.jl:309
  Expression: false
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:309 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] (::MakieGallery.var"#135#138"{Tuple{Int64, Int64}, Bool, String, Vector{Any}})(example::MakieGallery.CellEntry, value::Nothing)
   @ MakieGallery ~/.julia/packages/MakieGallery/V0mvg/src/io.jl:293

**Comment by besselfunct** [comment]
Dropping in to say I'm having the same issue. All 201 tests failed in my case.

**Comment by SimonDanisch** [comment]
I'm pretty sure that it's a FileIO version mismatch, which should be resolved in the newest version and correct version bounds.

**Comment by afkowalski** [comment]
Thanks Simon.  How do I know when this newest version is released and do you have an estimated time frame?   

I am confused why this was closed as the issue has not been resolved.

**Comment by SimonDanisch** [comment]
>I am confused why this was closed as the issue has not been resolved.

Which one? 
The one with the error ` shadertype(::FileIO.File{FileIO.DataFormat{:UNKNOWN}, String})` is very old, and should be resolved by `]add Makie@0.15.3`

**Comment by afkowalski** [comment]
Thank you Simon, I think I'm getting there.

I installed Julia 1.7.1 and then did ]add Makie@0.15.3.

I started running your tutorials, and I get the following error messages.  Can you help me resolve these?
https://makie.juliaplots.org/stable/tutorials/basic-tutorial/

julia> lines(x, y1)
ERROR: UndefVarError: lines not defined
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1

julia> lines!(x, y2)
ERROR: UndefVarError: lines! not defined
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1

julia> current_figure()
ERROR: UndefVarError: current_figure not defined
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1

**Comment by afkowalski** [comment]
I get the same error with:

using CairoMakie
f=Figure()

julia> f = Figure()
ERROR: UndefVarError: Figure not defined
Stacktrace:

**Comment by afkowalski** [comment]
I decided to do a clean wipe of everything julia from my system and reinstall.  It all works well now, thank you. 
I think the problem was with having some rogue AbstractPlotting package on my computer, but I'm not sure.
