### ISSUE TITLE
Using out of scope variables in own `show_data` method

### ISSUE THREAD

**Issue by fbanning** [JuliaPlots/Makie.jl#1219]
Hi,

the past days I've been working on creating my first plot recipe for Makie and extending its `show_data` method for `DataInspector`.

I'm not going to lie: I had my moments where I thought that I'll never get it working. 😅 But I think I've now understood how things work and my plot is created as I want it to. Yay for that already!

For now my own plot type is relatively simple and can be described as a wrapper around the scatter primitive. Extending on the functionality of `DataInspector`, I'm then trying to access an outside variable to use its value as the tooltip string.

```julia
using GLMakie

outside_var = "Hello from the other side."

# simple MyPlot recipe and plot! method go here

function GLMakie.Makie.show_data(inspector::DataInspector, plot::MyPlot, idx, ::Scatter)
    a = inspector.plot.attributes
    # method body goes here
    a._display_text[] = outside_var
    # rest of method body
end
```

Hovering a scatter point then naturally produces the `UndefVarError: outside_var not defined`.  
What would be the best way to let the `show_data` method access my outside variable?

Currently I can think of two ways to do this:

1. Should I put it in the Attributes of the `@recipe(MyPlot)` body and then use it in `show_data` like `plot[:outside_var]`? Would `outside_var` then have to be made an Observable for the tooltip to be able to track its current value or will it just be displayed on every new mouse-over/hover? I assume the former is the case. This seems like the natural approach to me but I'm unsure how to specifically tackle it.
2. Should I add an extra (kw)arg to `show_data` itself? If so, which other function would have to be changed/extended then as well? This would seem like hopping through a few too many hoops to achieve such a simple thing.

This whole question might seem a bit silly, sorry if that's the case. I've put in quite a bit of time to get to this point (i.e. generally understanding the recipe system) and would just appreciate a bit of guidance if possible. Thanks in advance for your tips, tricks and advice! 🙂

**Comment by ffreyer** [comment]
I don't think adding (kw)args to `show_data` makes much sense. It's called on mouse position updates, after some filtering (i.e. the inspectable attribute). You'd have to mess with the constructor and every `show_data` method to add (kw)args, I think.

I'm a bit surprised that your example doesn't work. Something like
```julia
x = 1.0
module A 
foo(x) = nothing 
end
using .A
A.foo() = x
A.foo()
```
works for me. Maybe you just need a `global outside_var` in there?

Otherwise I would add it to the plots attributes. `Attributes` will convert the inputs to nodes on its own and `show_data` is currently called on mouse movement, so you can use `a._display_text[] = plot.outside_var[]`.

```julia
@recipe(MyPlot, points) do scene
    attr = Attributes(
        outside_var = "init"
    )
end

# plot! code

function GLMakie.Makie.show_data(inspector::DataInspector, plot::MyPlot, idx, ::Scatter)
    a = inspector.plot.attributes
    # method body goes here
    a._display_text[] = plot.outside_var[]
    # rest of method body
end
```

**Comment by fbanning** [comment]
> You'd have to mess with the constructor and every show_data method to add (kw)args, I think.

Yes, that's what I expected. Thanks for the confirmation.

> Maybe you just need a global outside_var in there?

I've tried that and it sadly didn't work. :/

> Otherwise I would add it to the plots attributes. Attributes will convert the inputs to nodes on its own and show_data is currently called on mouse movement, so you can use a._display_text[] = plot.outside_var[].

Great, thanks for the info. I'm going to try that out and report back if it works as expected.

**Comment by fbanning** [comment]
> I'm a bit surprised that your example doesn't work.

So was I and that's why I posted on here. Now I was curious and tried my simplified MWE from above again. This time it worked as expected and the tooltip updates when `outside_var` changes.
![grafik](https://user-images.githubusercontent.com/65158285/129343665-3ae3beb0-d9f2-4059-9c8d-1e7cdafc6097.png)
Not sure what went wrong last time I tried it out. I probably messed sth up somewhere in the process.

Interestingly enough though, it still doesn't work once I use my actual implementation in which I don't add methods to `GLMakie.Makie´. Instead I implemented the Makie extensions within another used module. Here's a proper MWE because I think it might be helpful to know how I'm doing things:

```julia
module MakieMyPlot

using Makie

@recipe(MyPlot, pos) do scene
    Attributes(
        markersize = 10,
    )
end

function Makie.plot!(myplot::MyPlot{<:Tuple{Vector{Point2f0}}})
    scatter!(myplot, myplot[:pos]; markersize=myplot[:markersize])
    return myplot
end

function Makie.show_data(inspector::DataInspector, plot::MyPlot, idx, ::Scatter)
    a = inspector.plot.attributes
    scene = Makie.parent_scene(plot)

    proj_pos = Makie.shift_project(scene, plot, to_ndim(Point3f0, plot[1][][idx], 0))
    Makie.update_tooltip_alignment!(inspector, proj_pos)
    ms = plot.markersize[]

    global outside_var
    a._display_text[] = outside_var
    a._bbox2D[] = FRect2D(proj_pos .- 0.5 .* ms .- Vec2f0(5), Vec2f0(ms) .+ Vec2f0(10))
    a._px_bbox_visible[] = true
    a._bbox_visible[] = false
    a._visible[] = true

    return true
end

end

using .MakieMyPlot
using GLMakie

fig, = myplot(rand(Point2f0, 20))
outside_var = "Hello from the other side."
inspector = DataInspector(fig.scene)
fig
```

`outside_var` remains undefined. So the question seems to be: Which scoping rule am I blissfully ignoring right now?

**Comment by ffreyer** [comment]
`Main.outside_var` works

**Comment by fbanning** [comment]
> `Main.outside_var` works

That's true. But once I want to avoid global variables by wrapping things in a function, I'm stuck again.

```julia
function create_plot()
    fig, = myplot(rand(Point2f0, 20))
    outside_var = "Hello from the other side."
    inspector = DataInspector(fig.scene)
    fig
end
```

I suppose my best bet is to add my outside_var as a positional argument to the recipe as this will allow for more generic usage of the recipe and doesn't constrain that `outside_var` is directly defined in `Main`.

```julia
@recipe(MyPlot, pos, outside_var) do scene
    Attributes(
        markersize = 10,
    )
end

pos = rand(Point2f0, 20)
outside_var = "Hello from the other side."
myplot(pos, outside_var)
```

Inside `show_data` I can then write

```julia
a._display_text[] = plot.outside_var[]
```

This seems to have solved my problems/questions and works even if `myplot` is called from within a function. Thanks for your time and answers. :)
