### ISSUE TITLE
Could not import AbstractPlotting

### ISSUE THREAD

**Issue by hearnsj** [JuliaPlots/Makie.jl#122]
I installed Julia 0.6.4 and did a Pkg.checkout of Makie
I get the errors below. Apologies if I am doing something dumb here...

julia> using Makie
INFO: Recompiling stale cache file /home/hearnsj/.julia/lib/v0.6/Makie.ji for module Makie.
WARNING: could not import AbstractPlotting.arguments into Makie
WARNING: could not import AbstractPlotting.mouseover into Makie
WARNING: could not import AbstractPlotting.onpick into Makie
WARNING: could not import AbstractPlotting.pick into Makie
WARNING: using GLAbstraction.VecTypes in module Makie conflicts with an existing identifier.
WARNING: using GLAbstraction.boundingbox in module Makie conflicts with an existing identifier.
WARNING: using AbstractPlotting.IRect in module GLVisualize conflicts with an existing identifier.
WARNING: using AbstractPlotting.VecTypes in module GLVisualize conflicts with an existing identifier.
WARNING: using Makie.AbstractPlotting in module Main conflicts with an existing identifier.
WARNING: using Makie.Contour in module Main conflicts with an existing identifier.

**Comment by SimonDanisch** [comment]
These are warnings? Sorry, have been too lazy to clean them up before a propper release (which I'm currently working on ;) )
