### ISSUE TITLE
WGLMakie vs GLMakie

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaPlots/Makie.jl#1225]
Same code with different backends: 

<img width="905" alt="Screen Shot 2021-08-17 at 9 37 42 AM" src="https://user-images.githubusercontent.com/24194258/129632704-f19d8438-4cea-462b-a110-5fdc581f0e11.png">

looks different to docs example

http://makie.juliaplots.org/dev/examples/plotting_functions/band/#example_15083847939650193599 

<img width="822" alt="Screen Shot 2021-08-17 at 9 38 32 AM" src="https://user-images.githubusercontent.com/24194258/129632764-4bebc6cc-bd7a-45e3-9b16-b5763e9df680.png">

**Comment by ffreyer** [comment]
Fixed on master. Probably by #1330
