### ISSUE TITLE
nan_color does not work for GLMakie.image

### ISSUE THREAD

**Issue by MariusDrulea** [JuliaPlots/Makie.jl#1230]
I have a matrix "x" containing floating point values. It also contains invalid values, all set to NaN. According to documentation of GLMakie.image, there is this nan_color atribute. By default the NaN values are rendered fully transparent when displayed. However, this does not work. I am using GLMakie 0.4.0.

```
x = rand(50, 50)
x[15:25, :] .= NaN
image(x)
```

![image](https://user-images.githubusercontent.com/27725572/129905654-bea4c3f6-cc0e-4468-be25-903a853eb9e5.png)

If I try heatmap(x) instead, then yes, I do get the desired transparency.
![image](https://user-images.githubusercontent.com/27725572/129905684-4a8e0852-6fac-4eeb-a809-e5981ec441b7.png)

**Comment by MariusDrulea** [comment]
Update: NaN were initially displayed as black, but now the same code gives an error:
```
x = rand(50, 50)
x[15:25, :] .= NaN
image(x)
```

```
Error showing value of type Makie.FigureAxisPlot:
ERROR: Looking up a non-finite or NaN value in a colormap is undefined.
```

**Comment by SimonDanisch** [comment]
What backend is this?

**Comment by MariusDrulea** [comment]
It's GLMakie

**Comment by MariusDrulea** [comment]
Just tested today with the 0.16.5 release and NaN are rendered transparent by `image()`. `nan_color` property also works. 
@SimonDanisch thanks :)
