### ISSUE TITLE
Edit the doc on github ?

### ISSUE THREAD

**Issue by SimonCoste** [JuliaPlots/Makie.jl#1235]
On [the Makie doc](http://makie.juliaplots.org/stable/#), the "Edit on GitHub" button in the top page leads to a 404.

![edit](https://user-images.githubusercontent.com/13707870/130083568-a3a9cd0e-ec1c-4e03-8647-c9f6c6a26d90.png)

**Comment by jkrumbiegel** [comment]
this is fixed in the new docs, which are going to replace the old ones soon (currently under `dev`)
