### ISSUE TITLE
Hooking into Base.doc instead of having a separate help function

### ISSUE THREAD

**Issue by tshort** [JuliaPlots/Makie.jl#124]
This would help the user. They can just use `?`.

It's possible to dynamically generate help strings using `Docs.getdoc`. [Here](https://github.com/ModiaSim/Modia.jl/blob/2a23b2362f80c99896ed9089bde97f4761ac4c32/src/language/Instantiation.jl#L1076) is an example from Modia. For Makie, you could generate the equivalent of `help(something, extended = true)`.

**Comment by tshort** [comment]
Thinking some more, this probably won't work for Makie because there's no type to latch on to for `getdoc`.

**Comment by SimonDanisch** [comment]
I planned to look more closely into it, once the help functions works nicely - and then just dispatch to it for whatever `?` needs!
