### ISSUE TITLE
Make deafult color of tick labels black (or "non transparent")

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#128]
The default gray color can be problematic in two ways

1. One could never use a makie result in a publication without changing this, so it could disrupt the workflow.
2. In small plots (which is super common at least in Physics) it is very hard to tell the numbers if they are with this gray / transparent color. This is immediatelly obvious from the example from makie's own documentation. In fact it happens in many times:
    * http://makie.juliaplots.org/stable/examples-text.html#Stepper-demo-1
    * http://makie.juliaplots.org/stable/functions-overview.html#lines-1

I don't think anybody can look at those links and tell what the numbers of the ticks are without "some effort". Keep in mind that these numbers (most of the time) are actually the most important part of a Scene, since they establish all the information the plot actually gives.

**Comment by SimonDanisch** [comment]
I believe this got fixed
