### ISSUE TITLE
[docs] chasing `@ref` links

### ISSUE THREAD

**Issue by tlienart** [JuliaPlots/Makie.jl#1286]
There's a few `[...](@ref)` links which should be converted, e.g. in https://github.com/JuliaPlots/Makie.jl/blob/master/docs/tutorials/basic-tutorial.md there's a couple; replacing with the `\myreflink` defined in `config.md` should do the trick i.e.

```
[foo bar](@ref) --> \myreflink{foo bar}
```

**Comment by jkrumbiegel** [comment]
I think I got them in the last PR :)
