### ISSUE TITLE
aspect ignored for images

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/Makie.jl#1288]
The x and y axes don't scale properly when setting the aspect ratio to 1. 

Consider the following MWE: I plot a circle with an aspect ration of 1. I save it as an image (the resulting image looks right). I then load that image and display it with `image` and an `aspect = 1`.
```julia
using GLMakie

# plot a circle
h = lines(Circle(zero(Point2), 1), axis = (aspect = 1, ))

# save image
name = "circle.png"
save(name, h)

# load image
using FileIO
img = FileIO.load(name)

# plot it
h = image(img, axis = (aspect = 1, ))
@show h.axis.aspect[]
```
But that results in this:
![circle2](https://user-images.githubusercontent.com/3281957/132015426-34c3b8de-6500-4358-adfd-864709acfb08.png)
which doesn't have an aspect ratio of 1.

**Comment by jkrumbiegel** [comment]
The aspect controls only the axis lengths, not the scaling of the data. For that you need `autolimitaspect` (that can be a bit buggy as there's technically a circular observable dependency when using this). http://makie.juliaplots.org/stable/examples/layoutables/axis/#controlling_data_aspect_ratios

**Comment by yakir12** [comment]
Indeed, 
```julia
h = image(img, axis = (aspect = DataAspect(), ))
```
fixes it:
![circle2](https://user-images.githubusercontent.com/3281957/132042466-3ad49b2c-fe90-4d63-ac42-8fb16d202715.png)
With all the updates I missed on the nuance between aspect equaling 1 and  `DataAspect()`. Thanks!
