### ISSUE TITLE
Don't emphasize the zeros by default in 2D plots

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#129]
[In all the line plots of makie's documentation](http://makie.juliaplots.org/stable/basic-tutorials.html#Line-plot-1) the lines that cross `0` are emphasized by default.

This is problematic, as it conveys information the user did not choose to convey. Sometimes it is useful to emphasize a zero line, sometimes not. *Definitely it is not useful in every single possible case*.

The important part is that for a user it is trivial to do that **if they wish so**, by adding two `lines!` calls.

It is much more difficult, obscure, and unreasonable, to change the defaults of a plotting package, per plotting script!

Please give power to the users, and be much more restrained with the "installation defaults". There is a reason none of the great plotting packages that are used routinely in scientific publications don't emphasize things by default. The ones I know from the top of my head, GR, PyPlot and VegaPlot, do not do such an invasive thing by default.

**Comment by dlfivefifty** [comment]
In principle I'm fine with emphasising the coordinate axes, and I notice that Mathematica does this by default. But right now I'm staring at a beautiful mesh plot with a black line over the top 😰

**Comment by SimonDanisch** [comment]
this got fixed
