### ISSUE TITLE
Tutorial Fails with WGLMakie

### ISSUE THREAD

**Issue by bradcarman** [JuliaPlots/Makie.jl#1291]
When running the following code, I get a crash

julia```
using WGLMakie
f = Figure(resolution = (1000, 300))
ga = f[1, 1] = GridLayout()

axtop = Axis(ga[1, 1])
axmain = Axis(ga[2, 1], xlabel = "before", ylabel = "after")
axright = Axis(ga[2, 2])

labels = ["treatment", "placebo", "control"]
data = randn(3, 100, 2) .+ [1, 3, 5]

for (label, col) in zip(labels, eachslice(data, dims = 1))
    scatter!(axmain, col, label = label)
    density!(axtop, col[:, 1])
    density!(axright, col[:, 2], direction = :y)
end

f
```

The error is very long, but begins with

```
┌ Error: Type Observable{String} isn't supported for uniform: label
└ @ ShaderAbstractions C:\Users\CarmanBr\.julia\packages\ShaderAbstractions\zraST\src\program.jl:104
┌ Error: error handling request
│   exception =
│    Type String not supported
│    Stacktrace:
│      [1] error(s::String)
│        @ Base .\error.jl:33
│      [2] type_string(context::WGLMakie.WebGL, t::Type)
│        @ ShaderAbstractions C:\Users\CarmanBr\.julia\packages\ShaderAbstractions\zraST\src\uniforms.jl:142
│      [3] type_string(context::WGLMakie.WebGL, x::String)
│        @ ShaderAbstractions C:\Users\CarmanBr\.julia\packages\ShaderAbstractions\zraST\src\uniforms.jl:114
│      [4] type_string(context::WGLMakie.WebGL, t::Observable{String})
│        @ ShaderAbstractions C:\Users\CarmanBr\.julia\packages\ShaderAbstractions\zraST\src\uniforms.jl:140
```

This is using WGLMakie v0.4.6

**Comment by SimonDanisch** [comment]
This may fix it: https://github.com/JuliaPlots/Makie.jl/commit/b6c989d61a1224bbb36e76e68483300409c11da5

**Comment by bradcarman** [comment]
Thanks, that did the trick!
