### ISSUE TITLE
wrong direction of arrows in vector field generated by streamplot

### ISSUE THREAD

**Issue by chloehjw** [JuliaPlots/Makie.jl#1293]
Hi, I am trying to visualize the vector field of the SIS model, and here is what I found that might be an issue:

on the left side of the figure, the arrows point northwest should point the southwest (like the red rectangle I draw)
<img width="492" alt="aaa" src="https://user-images.githubusercontent.com/61025566/132124260-89823d34-a26a-4d83-9fe3-d331493c769d.png">

here is the code
```
using CairoMakie
let
β=0.5
μ=0.1
PP_SIS(S,I) = Point(-β*S*I+μ*I,β*S*I-μ*I)
fig = Figure(resolution = (1400, 800), fontsize = 20)
ax1 = fig[1, 1] = Axis(fig, xlabel = "S", ylabel = "I", title = "phase portrait of SIS model", aspect = 1, backgroundcolor = :black)

streamplot!(ax1, PP_SIS, 0..1, 0..1, colormap = Reverse(:plasma),
	  gridsize= (20,20), arrow_size = 20)

fig
end
```

**Comment by SebastianM-C** [comment]
This should also be fixed by https://github.com/JuliaPlots/Makie.jl/pull/1352

**Comment by ffreyer** [comment]
Ah thanks, you're probably right. If this does persist on master/post v0.15.2 we can reopen this.
