### ISSUE TITLE
[BUG?] `scatterlines` does not register color cycle

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#1306]
Doing 
```
set_theme!(;
    palette = (color = COLORS,), 
    fontsize = 30
)
```
and then doing
```
for data in datas
    scatterlines!(ax, data)
end
```

doesn't change the color of the plotted lines/markers. In fact they are all black which means that they don't register the default color cycle either. 

![image](https://user-images.githubusercontent.com/19669089/132713232-9d440413-f1e7-47bf-b66e-2847f87b27dc.png)

**Comment by KronosTheLate** [comment]
Additionally, the defaults are different and do not cycle for scatterlines - they are all black.

**Comment by KronosTheLate** [comment]
Friendly bump :)

**Comment by Datseris** [comment]
Fixed on master, but master isn't tagged yet.

**Comment by KronosTheLate** [comment]
Can confirm that it works like a charm now. Thank you so much, scatterlines is so lovely to visualize datapoints ^_^
