### ISSUE TITLE
violin plot orientation = :horizontal not working 

### ISSUE THREAD

**Issue by lazarusA** [JuliaPlots/Makie.jl#1312]
The orientation of violins in horizontal mode is not working: 
 
```
x = rand(1:3, 1000)
y = randn(1000)
fig, = violin(x, y; color = :black,  orientation=:horizontal)
```

**Comment by kimkroener** [comment]
This does not work because violin theme does not have an attribute orientation and the docstring doesn't match the implementation:
https://github.com/JuliaPlots/Makie.jl/blob/78820311c9b45347f0937caf8b31a25bbc27dd73/src/stats/violin.jl#L16
