### ISSUE TITLE
WGLMakie can't display on iPad, iPhone and mac

### ISSUE THREAD

**Issue by ChasingZenith** [JuliaPlots/Makie.jl#1313]
I have a problem using WGLMakie and iPad. I use this simplified tutorial in `Franklin.jl` as a live-evaluated code blocks.
```julia
using WGLMakie, JSServe
WGLMakie.activate!()
io = IOBuffer()
println(io, "~~~")
show(io, MIME"text/html"(), Page(exportable=true, offline=true))
app = JSServe.App() do
    return DOM.div(
        scatter(1:4), # this line is not commented
        surface(rand(4, 4)),
        JSServe.Slider(1:3) # this line is not comment
    )
end
show(io, MIME"text/html"(), app)
println(io, "~~~")
println(String(take!(io)))
```

And the plot displays well and is interactively in Chromium on my Arch Linux.

<img width="400" alt="Linux" src="https://user-images.githubusercontent.com/22112456/132972188-96480e4d-fc60-4ca0-bccb-bcf2e846733f.png">

But on my iPad and iPhone even though I enable WebGL 2.0. ( It is said that the browser supports WebGL on [get.webgl.org](https://get.webgl.org/) )

<img width="400" alt="WGLMakie + JSServe" src="https://user-images.githubusercontent.com/22112456/132972161-5b2613b9-4dfa-4226-9269-3821abd0cd90.png">

Also, when I visit [this demo](https://simondanisch.github.io/WGLDemos/soil/) on my iPad, I get the following: (You might need to download this video, because, it does not play well on my browser.)

https://user-images.githubusercontent.com/22112456/132971845-6bf7652b-e493-4e27-aeeb-34954ddba1b9.mov

Is WGLMakie supposed to work well with iPad with WebGL 2.0 open?

**Comment by SimonDanisch** [comment]
>Is WGLMakie supposed to work well with iPad with WebGL 2.0 open?

Well, I guess to answer that question one needs to ask apple ;) WebGL 2.0 is 100% cross platform, so if its implemented properly it should just work 🤷‍♂️  If you can look into the javascript console, there may be hints on what exactly is going wrong...

**Comment by ChasingZenith** [comment]
OK, looking at the Javascript console may be the best way, but it might not be easy to do that.

It is strange that my iPad **can** run almost all (I test around 15 of them) demos on [webglsamples.org](https://webglsamples.org/), but not WGLMakie plots.

**Comment by SimonDanisch** [comment]
>OK, looking at the Javascript console may be the best way, but it might not be easy to do that.

It'd say it's the only way ;)  Usually that should be easy!?

>It is strange that my iPad can run almost all (I test around 15 of them) demos on webglsamples.org, but not WGLMakie plots.

Well, WebGL 2.0 is a large and complex library, so it's easy that 15 example don't cover all features ;) 

Anyways, I'm using 100% the official WebGL 2.0 API, so if something's weird, it must be something with the browser...

Although, the gray rects instead of text have been coming up on chrome as well, usually a reload fixes those ... But haven't seen the black surface anywhere else...The video is just white?

**Comment by ChasingZenith** [comment]
> The video is just white?

No. It show the process when I move the slider how it works on this [soil demo](https://simondanisch.github.io/WGLDemos/soil/).
In case, you can't play that video, I put one more snapshot here.
![Untitled](https://user-images.githubusercontent.com/22112456/132996633-45a8ff39-e6cd-46f5-9175-ae1af58b7822.png)

I manage to open a Javascript console on iPhone. Yes, it is not very difficult but, sorry I am a newbie so I was not very confident on it.

When I visit the [soil demo](https://simondanisch.github.io/WGLDemos/soil/)
Several errors appears.
![Untitled](https://user-images.githubusercontent.com/22112456/132996317-8e627d94-cad9-40db-88ee-27ef2f6bda4c.png)

And Three.js show warnings. I think that is related to the problem of black surface.

![Untitled 2](https://user-images.githubusercontent.com/22112456/132996344-0f6b0c48-98e4-42e6-9294-244ea56c59b0.png)

When I visit the example in my first post, I get only these similar warnings:
`THREE.WebGLRenderer: EXT_color_buffer_float extension not supported`
![Untitled](https://user-images.githubusercontent.com/22112456/132996816-ecb9af15-d75e-4d05-b2a4-fd57e21a2c04.png)

It was in function `WebGLExtensions` Line 11389 in `three.js`
![Untitled](https://user-images.githubusercontent.com/22112456/132996894-ea6b4e40-d726-4f14-8f19-272d1b097505.png)

**Comment by SimonDanisch** [comment]
![image](https://user-images.githubusercontent.com/1010467/132997454-bf219e86-3d4b-47ee-9c9c-dc4369cc1a57.png)
Hah, well that explains it I guess ;)

**Comment by ChasingZenith** [comment]
Is there anything that I can help? Since you might not have an iOS device handy. 
If you have one and a MacBook I think these links are helpful to reproduce my cases:
1. [Enable WebGL 2.0 on iPhone](https://hummingbird-group.gitbook.io/panoform/how-to-enable-webgl-2.0-in-safari-for-ios#:~:text=Safari%20for%20iOS%20disables%20WebGL%202.0%20by%20default%2C,is%20not%20supported%20in%20iOS%2011%20and%20below.)
2. [Inspect element on iPhone](https://www.browserstack.com/guide/how-to-inspect-element-on-iphone)

I just learned Javascript for an hour and I can't figure out what is going on in this JS code. 

> Didn't realize ThreeJS needs to use an extension under the hood for that...

Will you add such an extension?

**Comment by SimonDanisch** [comment]
So, `EXT_ecolor_buffer_float` is a very standard extension... Since that has been a standard in very old OpenGL versions, I would have never thought that anyone wouldn't support this. So apple not supporting this seems just - lazy?! 

Is this safari on the iphone, and would switching to brave/firefox/chrome fix it?
If yes, that's what I'd do.

If not, it's quite a lot of work to work around a missing core extension like that, and there is absolutely no motivation for me to invest that work in my free time.

**Comment by ChasingZenith** [comment]
Oh, this is bad news for me. WGLMakie and JSServe do a really good job in creating an interactive static site. but that will be not available for iOS mac users (All blame Apple).

> Is this safari on the iPhone, and would switching to brave/firefox/chrome fix it?

No. I have tried firefox/chrome/edge on my iPhone. None of them works.

**Comment by SimonDanisch** [comment]
>I have tried firefox/chrome/edge on my iPhone.

Crazy, I thought they would have their independent implementation...

I want to leave this open, to track any progress on this...In theory, someone could hack around the missing extension - also, apple may decide at some point to release an update with `EXT_color_buffer_float`

**Comment by robsmith11** [comment]
> Crazy, I thought they would have their independent implementation...

Browsers on iOS aren't allowed to use their own rendering engines.   They're basically just reskins of Safari.  It's the same reason that Firefox has add-ons like uBlock on Android but not on iOS.

**Comment by SimonDanisch** [comment]
![](https://media3.giphy.com/media/3ELtfmA4Apkju/giphy.gif?cid=ecf05e47nydj3kbqecm5vrkejlk9epgl8er4xk5jwsxly71f&rid=giphy.gif&ct=g)

Man, apple really is something....

**Comment by ChasingZenith** [comment]
It seems that all these works now after updating my iPad and iPhone to iPadOS15 and iOS15!
