### ISSUE TITLE
contourf! ignores colors specified for extendhigh and extend low?

### ISSUE THREAD

**Issue by thomvet** [JuliaPlots/Makie.jl#1329]
The following example in the documentation (https://makie.juliaplots.org/v0.15.2/examples/plotting_functions/contourf/) seems not to produce the desired output currently (this should cut off low and high peaks in the data and fill in with :cyan or :magenta)

```julia
using CairoMakie
xs = LinRange(0, 10, 100)
ys = LinRange(0, 10, 100)
zs = [cos(x) * sin(y) for x in xs, y in ys]

f = Figure()
Axis(f[1, 1])

co = contourf!(xs, ys, zs, levels = -0.75:0.25:0.5,
    extendlow = :cyan, extendhigh = :magenta)

Colorbar(f[1, 2], co)

f
```

while it does keep the color constant for values below -0.75 (dark blue) and above 0.5 (bright yellow), it does not display the specified :cyan and :magenta colors, respectively. 

If this is not a bug, I am surprised how this option is different from setting extendhigh = :auto, which is the example provided below this one in the documentation. In fact, the output plots provided for the two examples in the documentation look identical to me (and they are identical when I run the examples in the REPL).

**Comment by jkrumbiegel** [comment]
Oh that is a bug, must have regressed at some point and I guess the high low thing wasn't covered by visual tests.

**Comment by thomvet** [comment]
Closing the issue, because this issue is resolved when I check on the newest versions.
