### ISSUE TITLE
[BUG] CairoMakie.mesh stopped working due to some issue in GeometryBasics.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Makie.jl#1350]
MWE:

```julia
julia> using CairoMakie

julia> coords = [0. 0.; 1. 0.; 0. 1.]
3×2 Matrix{Float64}:
 0.0  0.0
 1.0  0.0
 0.0  1.0

julia> faces = [1 2 3]
1×3 Matrix{Int64}:
 1  2  3

julia> CairoMakie.mesh(coords, faces)
```

Expected result is a mesh with a single triangle.

Appreciate if you can take a look.

**Comment by SimonDanisch** [comment]
What's the error?

**Comment by SimonDanisch** [comment]
I'm closing this, since I don't think the situation can be improved substantially.
If there is a way to make `to_vertices` not ambiguous, a PR would be welcome ;)

**Comment by juliohm** [comment]
Sorry I don't get it. This has been the standard example in the docs for months already: https://makie.juliaplots.org/stable/examples/plotting_functions/mesh/index.html

And I was relying on this behavior in MeshViz.jl to avoid fuzzing around with GeometryBasics.Point types.

I would strongly recommend the opposite: use built-in Julia types for end-user interfaces like Array an Tuple and only internally rely on types such as GeometryBasics.Point. Is there a different method that doesn't force the user to manually construct GeometryBasics.Point?

**Comment by juliohm** [comment]
You mean end-users are supposed to use a type signature that is the final target after layers of preprocessing? I find it super strange to be honest.

I was able to fix the issue with a vector of SVector, which is a better fix in my opinion:

```julia
coords = [SVector(0., 0.), SVector(1., 0.), SVector(0.,1.))
```

**Comment by SimonDanisch** [comment]
Yeah people don't always agree about APIs...
I know you don't like the point types, but they're pretty basic Makie types, so you can't just expect to avoid them.
There are lots of other overloads, but for meshes Point should be the main entry point. With SVector you'll get more conversions/copies...

**Comment by juliohm** [comment]
I think we disagree on the end-user API. It is completely fine to say that the final target signature uses Point. What is not fine in my opinion is force users to go to this level of detail to just plot a collection of coordinates + connectivity lists. A Julia user would just expect that a plotting library would accept tuples, arrays, etc.

So I retain my opinion that many Makie recipes should have overleads with basic tuples arrays, etc. It is about usability for most end-users out there. It is not an issue for people like you and me who know how to manipulate the internals.

**Comment by SimonDanisch** [comment]
Now that you say that, it does actually support tuples as well:

```julia
Makie.to_vertices([(0., 0.), (1., 0.), (0.,1.)])::Vector{Point}
```
and also x, y, z as separate arrays...

But for recipes, I prefer converting as quickly to the final type as possible, to avoid conversions ;)

**Comment by juliohm** [comment]
Yes, now the final task is to make sure that all recipes in the project accept the same end-user representation. I thought that a matrix with coordinates in the rows was the canonical representation based on the docs of mesh. It is apparently buggy with a single triangle. Lesson learned, now I am using another canonical representation hoping things wont't break in the future again 🙏🏽
