### ISSUE TITLE
Doc improvement, use of kwargs not clear (only for beginners?)

### ISSUE THREAD

**Issue by bardo84** [JuliaPlots/Makie.jl#1357]
[https://discourse.julialang.org/t/plots-and-subplots-with-makie/69113/4](https://discourse.julialang.org/t/plots-and-subplots-with-makie/69113/4)

Do you mind adding an example (also in the doc)?

scatter(1.0…10, sin)

How to change now the line color to red?
Not enough space here to show the permutations using color = :red I tried.
No experience with kwargs so far.

**Comment by jkrumbiegel** [comment]
does this section not cover what you need? https://makie.juliaplots.org/stable/tutorials/basic-tutorial/#attributes

**Comment by bardo84** [comment]
It does:
```
sc = scatter!(x, y2, color = :blue, markersize = 10)
sc.color = :green
```
RTFM, sorry.
