### ISSUE TITLE
First example on makie.juliaplots.org fails

### ISSUE THREAD

**Issue by MattEttus** [JuliaPlots/Makie.jl#1358]
The first example (Lorenz) on https://makie.juliaplots.org/stable/ fails due to the use of @OUTPUT --

`record(fig, joinpath(@OUTPUT, "lorenz.mp4"), 1:120) do frame`

It fails with:

`ERROR: LoadError: UndefVarError: @OUTPUT not defined
in expression starting at REPL[11]:1`

Perhaps this is an error in docs generation, or if @OUTPUT is correct, then maybe it is from some package which is not imported by default.

**Comment by jkrumbiegel** [comment]
that was something necessary in Franklin.jl, but it's fixed now and included in https://github.com/JuliaPlots/Makie.jl/pull/1359
