### ISSUE TITLE
GLMakie `image_like` spatial order error message inconsistency

### ISSUE THREAD

**Issue by stillyslalom** [JuliaPlots/Makie.jl#1370]
https://github.com/JuliaPlots/Makie.jl/blob/6b71a7f0b60aa0573309a4f236b9d5c56c4d4cc8/GLMakie/src/GLVisualize/visualize/image_like.jl#L11-L12
It's not clear to me whether the code or the error message is correct.

**Comment by SimonDanisch** [comment]
The error message is wrong 😅
