### ISSUE TITLE
Surface spits out endless message in Juno

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPlots/Makie.jl#138]
Running the surface example
```julia
N = 30
function xy_data(x, y)
    r = sqrt(x^2 + y^2)
    r == 0.0 ? 1f0 : (sin(r)/r)
end
lspace = range(-10, stop=10, length=N)
z = Float32[xy_data(x, y) for x in lspace, y in lspace]
x = y = range(0, stop=3, length=N)
surface(
    x, y, z,
    colormap = :Spectral )
```
works fine in the REPL, but in Juno I get a never ending error message:
```
...
1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0)RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0)]), 0x0000000000006200)
Fatal error:
```
Unfortunately the buffer is cut off so I don't know what it started out as.

**Comment by SebastianM-C** [comment]
I encountered something similar and the error was that `ImageMagick` was not found. I solved it by `]add`ing it. (It already was in the manifest file)

**Comment by dlfivefifty** [comment]
Adding ImageMagick fixed it for me too.

**Comment by SimonDanisch** [comment]
Great, wonder how I could make this more user friendly... I already have ImageMagick in the require, but I guess with Pkg3 it doesn't count as installed as long as you don't explicitly added it -.-. So this is likely an issue with FileIO & PKg3, where I don't immediately know how to proceed.

**Comment by ssfrr** [comment]
The other issue here is the super long printing. It took a few tens of seconds for the printing to finish in my Juno console. Maybe something needs a more concise `show` method?

If ImageMagick is being loaded from within FileIO, I wonder if the issue is that it's not in FileIO's `REQUIRE`. Though I can see how it's not sustainable to put all the packages that FileIO might load into its `REQUIRE`.

**Comment by ssfrr** [comment]
I wonder if you can wrap the `load` call (I'm assuming that's where this is happening) in a `try...catch` and print a more helpful error message?

**Comment by SimonDanisch** [comment]
I put a try catch around the offending lines like @ssfrr  recommended... That seems like a good enough workaround for now :)
