### ISSUE TITLE
Feature request: Patterned bar plots in CairoMakie

### ISSUE THREAD

**Issue by icweaver** [JuliaPlots/Makie.jl#1385]
Following up on the discussion from slack, it would be great if similar functionality to this example in GLMakie from [100daysOfMakie](https://github.com/lazarusA/100daysOfMakie#31-stripped-patterns) could be brought to CairoMakie as well

```julia
using Makie, GLMakie, Random
Random.seed!(3)
# patterns
# `'/'`, `'\\'`, `'-'`, `'|'`, `'x'`, and `'+'`
directions = [Vec2f0(1), Vec2f0(1, -1), Vec2f0(1, 0), Vec2f0(0, 1),
    [Vec2f0(1), Vec2f0(1, -1)], [Vec2f0(1, 0), Vec2f0(0, 1)]]
colors = [:white, :red, (:green, 0.5), :white, (:navy, 0.85),:black]
patterns = [Makie.LinePattern(direction= hatch; width = 5, tilesize=(20,20),
    linecolor = colors[indx], background_color = colors[end-indx+1])
    for (indx, hatch) in enumerate(directions)]
fig = Figure(resolution = (1200,800), fontsize = 32)
ax = Axis(fig[1,1])
for (idx, pattern) in enumerate(patterns)
    barplot!(ax, [idx], [idx*(2rand()+1)], color = pattern, strokewidth = 2)
end
ax.xticks = (1:6, ["/", "\\", "-", "|", "x", "+"])
save("strippedPatterns.png", fig)
fig
```

![strippedPatterns](https://user-images.githubusercontent.com/25312320/137185210-5b25ac63-3adc-4fc4-bd1d-51e23a56cdfc.png)

**Comment by Moelf** [comment]
I'd like to try implementing this, any pointer to a similar PR?

**Comment by greimel** [comment]
not sure if relevant, but here's the PR that added this to Plots.jl https://github.com/JuliaPlots/Plots.jl/pull/3107

**Comment by Moelf** [comment]
don't think so, this is CairoMakie, for the record:
```julia
julia> using CairoMakie

julia> p = Pattern('/');

julia> save("/tmp/f.png", barplot([1],[2], color=p))
ERROR: CanonicalIndexError: getindex not defined for Makie.LinePattern
Stacktrace:
  [1] error_if_canonical_getindex(::IndexCartesian, ::Makie.LinePattern, ::Int64, ::Int64)
    @ Base ./abstractarray.jl:1255
  [2] getindex
    @ ./abstractarray.jl:1235 [inlined]
  [3] _getindex
    @ ./abstractarray.jl:1281 [inlined]
  [4] getindex
    @ ./abstractarray.jl:1236 [inlined]
  [5] attr_broadcast_getindex(x::Makie.LinePattern, i::Int64)
    @ Makie ~/Documents/github/Makie.jl/src/utilities/utilities.jl:164
  [6] macro expansion
    @ ~/Documents/github/Makie.jl/src/utilities/utilities.jl:199 [inlined]
  [7] broadcast_foreach(::CairoMakie.var"#64#65"{CairoMakie.CairoScreen{Cairo.CairoSurfaceBase{UInt32}}}, ::Vector{GeometryBasics.HyperRectangle{2, Float32}}, ::Makie.LinePattern, ::Symbol, ::Int64)
    @ Makie ~/Documents/github/Makie.jl/src/utilities/utilities.jl:185
  [8] draw_poly(scene::Scene, screen::CairoMakie.CairoScreen{Cairo.CairoSurfaceBase{UInt32}}, poly::Combined{Makie.poly, Tuple{Vector{GeometryBasics.HyperRectangle{2, Float32}}}}, rects::Vector{GeometryBasics.HyperRectangle{2, Float32}})
    @ CairoMakie ~/Documents/github/Makie.jl/CairoMakie/src/overrides.jl:84
  [9] draw_plot(scene::Scene, screen::CairoMakie.CairoScreen{Cairo.CairoSurfaceBase{UInt32}}, poly::Combined{Makie.poly, Tuple{Vector{GeometryBasics.HyperRectangle{2, Float32}}}})
    @ CairoMakie ~/Documents/github/Makie.jl/CairoMakie/src/overrides.jl:13
 [10] draw_plot(scene::Scene, screen::CairoMakie.CairoScreen{Cairo.CairoSurfaceBase{UInt32}}, primitive::Combined{Makie.barplot, Tuple{Vector{Point{2, Float32}}}})
    @ CairoMakie ~/Documents/github/Makie.jl/CairoMakie/src/infrastructure.jl:255
 [11] cairo_draw(screen::CairoMakie.CairoScreen{Cairo.CairoSurfaceBase{UInt32}}, scene::Scene)
    @ CairoMakie ~/Documents/github/Makie.jl/CairoMakie/src/infrastructure.jl:192
 [12] backend_show(x::CairoMakie.CairoBackend, io::IOContext{IOStream}, #unused#::MIME{Symbol("image/png")}, scene::Scene)
    @ CairoMakie ~/Documents/github/Makie.jl/CairoMakie/src/infrastructure.jl:396
```

**Comment by ffreyer** [comment]
This should end up in https://github.com/JuliaPlots/Makie.jl/blob/174ef914759b64fdc271a4be26d692b97a5dfa09/CairoMakie/src/primitives.jl#L624 with a LinePattern in `color`

**Comment by Moelf** [comment]
right now it doesn't call this function at all, I guess one of the function on the current stack trace needs to be replaced by a specialization?

**Comment by Moelf** [comment]
too hard right now because first we probably want to solve:
https://github.com/JuliaPlots/Makie.jl/blob/174ef914759b64fdc271a4be26d692b97a5dfa09/CairoMakie/src/utils.jl#L243-L252

**Comment by ffreyer** [comment]
Ah right, poly has it's own backend code. 

I don't know Cairo well enough to know how these patterns should be implemented, but I don't think you need to worry about that branch. I assume you either need to make a new branch that transforms the pattern into an image and uses it as a repeated texture like opengl, or that Cairo has some version of hatching/patterns natively that you could use

**Comment by Moelf** [comment]
that branch takes a `Matrix` (image) pattern as color, I thought it would tile the `color` for the entire surface, but it's not (as the comment says).

If this branch were to work correctly, I can use it to draw the inside of the bar plot? or I guess this is not the correct way to go about it.

- - -
I also didn't find anything in Cairo, judging from https://juliagraphics.github.io/Luxor.jl/stable/reference/api/#Luxor.rule we have to DIY it

**Comment by Moelf** [comment]
https://gist.github.com/Moelf/f68af0015f96f98264194f05c544771d

![image](https://user-images.githubusercontent.com/5306213/175817636-187904d9-3473-4cec-8284-201d1707292f.png)

**Comment by asinghvi17** [comment]
We could also draw patterns onto a CairoRecordingSurface using Cairo intrinsics (set_line_width, move_to, line_to) and then set those surfaces as the pattern, and simply clip everything which is not within the area by using e.g. `cairo_clip` with `cairo_path_to`.  That would make the approach somewhat more flexible and probably render at better resolution in small or vector graphics.

**Comment by Moelf** [comment]
What's the difference between imagesirface and recordingsurface?

**Comment by Moelf** [comment]
@asinghvi17 I can't find any use of `CairoRecordingSurface` inside Makie, but I think it's much easier if we use `pattern_set_extend(pattern, Cario.EXTEND_REPEAT)`:
https://gist.github.com/Moelf/e380d20b307901a6947881dc163a6c62

![image](https://user-images.githubusercontent.com/5306213/177016165-0bce9cd8-df9d-4d92-885c-95de6c919ed4.png)

**Comment by Moelf** [comment]
```julia
julia> p = Pattern('/');

julia> save("/tmp/f.png", poly(Point2f[(0, 0), (2, 0), (3, 1), (1, 1)], color = p))
```
![image](https://user-images.githubusercontent.com/5306213/177017484-b57c06d1-12c7-43b1-a542-19ba6338fced.png)
