### ISSUE TITLE
Weight for hist?

### ISSUE THREAD

**Issue by henry2004y** [JuliaPlots/Makie.jl#1407]
Hello,

It seems to me that the current [`hist`](https://makie.juliaplots.org/v0.15.1/examples/plotting_functions/hist/) function does not have `weights` keyword implemented. The [`histogram`](http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/analyses/#AlgebraOfGraphics.histogram) function in Algebra of Graphics has `weights`, but maybe this should be directly supported by Makie?

**Comment by femtomc** [comment]
Bumping this issue. This should be supported somehow -- it's a generalization of what the current recipe does, and I think is useful in general.

If you go the `StatsBase.fit` and plot route, it seems like you lose access to styling -- which is exactly why someone like me turns to `Makie`, so it appears sub-optimal.

I also explored `StatsMakie` -- but in the documentation, there's not a lot of information on customization options for `plot(histogram(...), ...)` -- `StatsMakie` also appears to be deprecated and moved into `Makie`, so I have no idea how the functionality in the documentation is related to the current state of this project.

**Comment by jkrumbiegel** [comment]
> it seems like you lose access to styling

What do you mean by styling? I had assumed the recipe would just plot bars for each histogram bin, irrespective of how those bins were calculated, with or without weights. In principle we can of course add a weight option to the plotting command, I'm not sure though if there aren't even more options we'd need to cover for the full StatsBase functionality, and if it's not ok to have users go the slightly more verbose manual route in that case

**Comment by Moelf** [comment]
as soon as I come around and understand the recipe system, I will add support for plotting https://github.com/Moelf/FHist.jl for Makie

**Comment by rashidrafeek** [comment]
This seems to be implemented in #1816. Docs are [here](https://makie.juliaplots.org/v0.17.4/examples/plotting_functions/hist/#using_statistical_weights)
