### ISSUE TITLE
Plotting 2000x2000 image is slow. A large amount of allocations is created.

### ISSUE THREAD

**Issue by MariusDrulea** [JuliaPlots/Makie.jl#1412]
I have started to use GLMakie more intensively and noticed it is slow for the images I use. Bellow you can find a sample code.
heatmap, plot, image all takes about 0.15 seconds per call, and I have about 10 images to show, so this leads to 1.5 seconds, quite a lot. You can notice the amount of allocations per call: `1.00 M allocations: 50.724 MiB`. Looks like each value of the 2000x2000 image is copied and allocated into something else. This can be done in a more optimal way, a single allocation for all the values at once. I am currently debugging the issue, any hint is welcome.

```
julia> using GLMakie

julia> x = rand(2000, 2000)

julia> @time heatmap(x)
 57.865795 seconds (111.09 M allocations: 6.655 GiB, 2.91% gc time)

julia> @time heatmap(x)
  0.168210 seconds (1.01 M allocations: 50.836 MiB)

julia> @time heatmap(x)
  0.225403 seconds (1.01 M allocations: 50.836 MiB)

julia> @time plot(x)
  0.349197 seconds (1.29 M allocations: 67.006 MiB, 54.55% compilation time)

julia> @time plot(x)
  0.170603 seconds (1.00 M allocations: 50.724 MiB)

julia> @time plot(x)
  0.180033 seconds (1.00 M allocations: 50.724 MiB)

julia> @time plot(x)
  0.192559 seconds (1.00 M allocations: 50.724 MiB)

julia> @time image(x)
  1.026312 seconds (2.70 M allocations: 153.704 MiB, 3.97% gc time, 81.16% compilation time)

julia> @time image(x)
  0.152998 seconds (1.02 M allocations: 51.078 MiB)

julia> @time image(x)
  0.159101 seconds (1.02 M allocations: 51.078 MiB)
```

**Comment by SimonDanisch** [comment]
>When I display a single 2000x2000 image in the REPL, the GPU stays close to 100% most of the time. To me this looks like an over-use of GPU. Too high update frequency?

You could actually try using your own renderloop:

Create a function like this one https://github.com/JuliaPlots/Makie.jl/blob/master/GLMakie/src/rendering.jl#L17=,
change the render criteria from time based to whenever you update the image and then replace the renderloop with:
```julia
GLMakie.set_window_config!(renderloop=your_renderloop)
```

**Comment by SimonDanisch** [comment]
With https://github.com/MakieOrg/Makie.jl/pull/2336 we now have an on demand renderloop as the default!
Also, heatmap is much slower then image, which mostly supports the same color mapping options, but only treats the matrix as an rectangle in space, which makes the implementation much faster (heatmap creates rectangles for every pixel).
