### ISSUE TITLE
Latex text observables not work

### ISSUE THREAD

**Issue by jacobleft** [JuliaPlots/Makie.jl#1417]
As per the docs, changing  "a text object which has been instantiated with a normal String input to use a LaTeXString" can't be done.
But actually, changing a text object which has been instantiated with a LaTeXString input to use another LaTeXString can't be done, either.
For example,
```julia
using GLMakie
fig = Figure()
ax1 = Axis(fig[1, 1], title = L"\frac{x}{y}")
ax2 = Axis(fig[1, 2], title = "x/y")
ax1.title = L"x^2" #does not change the title
ax2.title = "x^2" #does change
fig
```

**Comment by JonasIsensee** [comment]
For completeness:
It is currently also not possible to alter e.g. font size after creation of a latex label.

```
fig = Figure()
ax = Axis(fig[1,1], xlabel="n_1", ylabel=L"n_2")
ax.xlabelsize[] = 40
ax.ylabelsize[] = 60 # doesn't do anything
```
