### ISSUE TITLE
poor data viz practice in multi-panel example

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPlots/Makie.jl#1430]
the example [here](https://makie.juliaplots.org/dev/tutorials/layout-tutorial/#panel_a) is poor data viz practice because the axis ticks and labels on the top and right panels are hidden---*without* ensuring the scales are the same (they are not). fine to hide them but only if the scales are set to be the same. so I think we need to enforce that the axis limits are the same e.g. y-axis on the main panel and y-axis on the right panel. 

![image](https://user-images.githubusercontent.com/30643894/140424147-9423b254-76ca-4911-9146-34bce01636d5.png)

can tell the densities do not like up with the scatter plot.

**Comment by SimonEnsemble** [comment]
I think adding this does the trick:
```
linkyaxes!(axmain, axright)
linkxaxes!(axmain, axtop)
```

**Comment by jkrumbiegel** [comment]
Ah yeah I noticed that the other day, too, I forgot that step when rewriting. Thanks for the heads up

**Comment by jkrumbiegel** [comment]
fixed in https://github.com/JuliaPlots/Makie.jl/pull/1477
