### ISSUE TITLE
Isolate frame rendering

### ISSUE THREAD

**Issue by DominiqueMakowski** [JuliaPlots/Makie.jl#144]
I know these have been very busy times with the updates and all, 

This is just a follow up on [this issue](https://github.com/JuliaGL/GLFW.jl/issues/163), discussing if it was possible to dissociate scene "loading" from frame rendering to maximize precision and control over stimulus display and response recording.

Thanks a lot :)

**Comment by SimonDanisch** [comment]
Sorry for taking so long for such a simple addition:

https://github.com/JuliaPlots/Makie.jl/blob/ab66329a53b6a9e8bcac52b0b4ed26206bc67462/examples/examples3d.jl#L522
That should be the first step for your use case!
