### ISSUE TITLE
Setting theme spine not working

### ISSUE THREAD

**Issue by CAlexZA** [JuliaPlots/Makie.jl#1486]
I am currently drawing plots with GLMakie (v0.4.7) and using `set_theme!(theme_dark())`.  I do not like the fact that the theme makes the graph have no borders, so I am trying to add borders using:

```
update_theme!(
  leftspinevisible = true,
  rightspinevisible = true,
  topspinevisible = true,
  bottomspinevisible = true,
  bottomspinecolor = :white,
  topspinecolor = :white,
  leftspinecolor = :white,
  rightspinecolor = :white
  )
```

However, this has no effect on my graph.

This might not help, but the following tests fail when doing `]test GLMakie`:

Reference image tests:
- examples2d_27_Arrowsonhemisphere.png
- text_202_3Dscreenspaceannotations.png
- attributes_26_isorange,isovalue.png
- short_tests_70.png
- short_tests_80_Unequalxandysizesinsurface.png
- short_tests_100_Matricesofdatainsurfaces.png
- examples2d_36_image.png

**Comment by jkrumbiegel** [comment]
These are `Axis` attributes, so you need to nest them under the `Axis` keyword like this:

```julia
update_theme!(
    Axis = (
        leftspinevisible = true,
        rightspinevisible = true,
        ...
  )

```

**Comment by jkrumbiegel** [comment]
https://makie.juliaplots.org/stable/documentation/theming/#theming_layoutable_objects

**Comment by CAlexZA** [comment]
Oh wow, my apologies, I am blind!  Thank you very much.

**Comment by SimonEnsemble** [comment]
@jkrumbiegel 

when I try:
```
update_theme!(fontsize=20, linewidth=4, Axis=(xgridstyle=:dashdot))
```
I get error when making my plots:
```
Subtheme is not of type Attributes but is Observable{Any} with 0 listeners. Value:

:dashdot

    error(::String)@error.jl:35
    subtheme(::Makie.Scene, ::Symbol)@helpers.jl:297
    var"#layoutable#251"(::Nothing, ::Base.Pairs{Symbol, String, Tuple{Symbol, Symbol}, NamedTuple{(:xlabel, :ylabel), Tuple{String, String}}}, ::typeof(Makie.MakieLayout.layoutable), ::Type{Makie.MakieLayout.Axis}, ::Makie.Figure)@axis.jl:13
    #_layoutable#11@layoutables.jl:69[inlined]
    var"#_layoutable#10"(::Base.Pairs{Symbol, String, Tuple{Symbol, Symbol}, NamedTuple{(:xlabel, :ylabel), Tuple{String, String}}}, ::typeof(Makie.MakieLayout._layoutable), ::Type{Makie.MakieLayout.Axis}, ::GridLayoutBase.GridPosition)@layoutables.jl:64
    #_#9@layoutables.jl:49[inlined]
    viz_data(::DataFrames.DataFrame, ::Float64)@[Other: 3](http://localhost:1235/edit?id=e740a538-fcd9-11ec-3784-39e4f045306c#)
    top-level scope@[Local: 1](http://localhost:1235/edit?id=e740a538-fcd9-11ec-3784-39e4f045306c#)[inlined]
```

for advanced theming, would be awesome to list all possible attributes of a theme to change in an example theme file, for the docs?

**Comment by jkrumbiegel** [comment]
You wrote Axis=(xgridstyle=:dashdot) but that is not a valid NamedTuple, use Axis=(; xgridstyle=:dashdot)

**Comment by Moelf** [comment]
or
```
Axis=(xgridstyle=:dashdot, )
```
