### ISSUE TITLE
Camera reset

### ISSUE THREAD

**Issue by mwlidar** [JuliaPlots/Makie.jl#1497]
I have a Mesh in a LScene with cam3d. If I now update other items in the surrounding figure, like a label or a colorbar the camera viewport is reset to the starting value. I don't know, if this is a feature or a bug. But if not a bug, is there a way to suppress this reset and leave the camera viewport as it was?

**Comment by ffreyer** [comment]
Can you give a concrete example? I tried
```julia
fig, ax, p = mesh(Sphere(Point3f(0), 1f0), color = :orange)
# move camera
str = Makie.Observable("test")
lbl = Label(fig[2, 1], str, tellwidth=false)
str[] = "foo"
```
on master and neither adding the label nor changing the string reset the camera for me.

(Adding plots to the scene is expected to reset its view unless you set `center = false` for the scene.)

**Comment by mwlidar** [comment]
For my setup your example shows exactly what I described!! This is with Julia 1.6.4 and GLMakie v0.15.3. Maybe this is a problem already solved in master...

**Comment by SimonDanisch** [comment]
Yeah, this shouldn't happen on master anymore...
I'm, guessing, you redisplay the scene/fig when adding something... Display previously called `center!(scene)` which resets the 3d camera.

**Comment by mwlidar** [comment]
It happens on an open display window, when I for example change the text of a label. Or the limits of a color scale. Not only if I redisplay the fig. Is there a plan for the next release? Or do you think it's safe enough to switch to master right now?

**Comment by SimonDanisch** [comment]
Hm, that sounds a bit different...
Can you give a concrete examples with the exact steps like @ffreyer requested? Since this may be specific to the display system, IDE & and how you eval code is important.

Master passes tests, so it's fairly stable ;) I plan to release a new version this week!

**Comment by jkrumbiegel** [comment]
This happens because the px_area observable of the LScene scene is triggered, because Label and Colorbar tick changes trigger a layout solve.

**Comment by SimonDanisch** [comment]
Hm, but that shouldn't reset the camera, or is there a connection I forgot? Maybe before master .. master doesn't touch the camera anymore whatsoever

**Comment by mwlidar** [comment]
This is on Windows 10:

```
julia> versioninfo()
Julia Version 1.6.4
Commit 35f0c911f4 (2021-11-19 03:54 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_DEVDIR = H:\pc\julia
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```
IDE is VSCode
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Datum: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
Betriebssystem: Windows_NT x64 10.0.19042

I can evalute the MWE of ffreyer either line by line in REPL or put it in a batchfile. 
```
using GLMakie

fig, ax, p = mesh(Sphere(Point3f(0), 1f0), color = :orange)
str = Makie.Observable("test")
lbl = Label(fig[2, 1], str, tellwidth=false)
display(fig)
zoom!(ax.scene, cameracontrols(ax.scene), 3.0)
update_cam!(ax.scene, cameracontrols(ax.scene))
#now we have small sphere for 30 s
sleep(30)
str[] = "foo" # camera reset!
```
Probably I will wait for the new release and report back.

**Comment by mwlidar** [comment]
I was curious enough to update to master and indeed the issue is gone!! Thanks very much for the great work!
(Now I have funny font renderings for labels, but that’s a different Story…)

**Comment by jkrumbiegel** [comment]
You need to delete the font cache for Makie, should be somewhere in the.julia subfolder I guess

**Comment by mwlidar** [comment]
Ah, looks much better now! Thank you again!!!
