### ISSUE TITLE
LaTeX example in documentation does not work

### ISSUE THREAD

**Issue by HenriDeh** [JuliaPlots/Makie.jl#1500]
Copy pasting the three lines of code [there](https://makie.juliaplots.org/stable/documentation/latex/index.html) does not work. First because one must do `using LaTeXStrings` first, otherwise the `L"..."` syntax is not defined. But even then, the produced plot has labels with $$ around plain text equations. 

I'm assuming the rendering in the documentation has another package loaded that allows it to render the equations (MathTexEngine does not do it for me). So I'd like to know how to actually use LaTeX in Makie please. I'll update the documentation if someone tells me.

Thanks

**Comment by jkrumbiegel** [comment]
Are you sure you're on the correct versions, same as in the footer of the web page? The docs are auto generated, so this example worked as it is with those versions

**Comment by HenriDeh** [comment]
Ha no, I'm at 0.14. I thought updating GLMakie would also update Makie in the Manifest (it's not in the project toml since you're not supposed to add Makie). 
`up Makie` does not work though, do you know how I'm supposed to update it ?
