### ISSUE TITLE
plotting in a standalone figure in jupyter notebook

### ISSUE THREAD

**Issue by jaehongpark-neuro** [JuliaPlots/Makie.jl#1509]
Hi,

When we run Makie.jl in a jupyter notebook, plots are embedded in the cells.

In PyPlot module, they can plot in a standalone figure, by putting pygui(true).

I was wondering whether Makie.jl has similar function or line to do the same job, so that I can move or zoom in and out the axis of my plots.

Thanks

**Comment by SimonDanisch** [comment]
display(fig) should do the trick... Maybe `Makie.inline!(false)` is needed as well.

**Comment by jaehongpark-neuro** [comment]
thanks!
