### ISSUE TITLE
ecdfplot() not available in Makie v0.15.3

### ISSUE THREAD

**Issue by mrazomej** [JuliaPlots/Makie.jl#1515]
Dear Makie team,

First of all, thank you so much for your work. The library is incredible! The last thing I needed to fully switch to a full-time Julia user. 

I am trying to make an ECDF plot as specified [here](https://makie.juliaplots.org/dev/examples/plotting_functions/ecdf/index.html), but I get the following error:
```
UndefVarError: ecdfplot! not defined
```
I have the latest version of the package (`v0.15.3`), so I'm not sure what is happening here.

**Comment by ffreyer** [comment]
We haven't had a new release since that got merged, so you need to switch to master if you want to use it.
