### ISSUE TITLE
Remove grids and change the ticks to be inside

### ISSUE THREAD

**Issue by songhanzhang** [JuliaPlots/Makie.jl#1530]
I would like to know if the following features can be achieved in Makie:
 
 - The grid lines are removed.
 - The ticks are changed to be inside the figure.

For the first one, the command `hidedecorations!(ax1)` removes all the grids, ticks and tick labels, which is not preferred. The feature 'LinearTicks(n)' can change the number of the involved grid lines, but n cannot be 0 (otherwise it comes out error information).

For the second one, the ticks are inside by default in Plots-GR, and this is usually required in many scientific journals. However, I have not found any useful command for implementing this.

The codes are provided below. It would be great if anyone can help. Thanks in advance!

```
using GLMakie
x = 0:0.1:10
y = sin.(x)
f = Figure(resolution = (1000,500), fontsize = 30)
Axis(f[1,1])
lines!(f[1,1], x, y, linewidth = 4)
f
```

![fig_GLMakie_grid](https://user-images.githubusercontent.com/67284799/147382161-111a16f5-58ec-47b6-938c-389edb84a45b.png)

```
using Plots
x = 0:0.1:10
y = sin.(x)
f = plot(size = (1000,500), grid = false, legend = false, frame_style = :box, tickfontsize = 20)
plot!(f, x, y, w = 4)
```

![fig_Plots_grid](https://user-images.githubusercontent.com/67284799/147382263-fb510076-1a73-438a-b6b9-2aefaeefea0e.png)

**Comment by jkrumbiegel** [comment]
Removing ticks
https://makie.juliaplots.org/stable/examples/layoutables/axis/#hiding_axis_spines_and_decorations

Tick positions are xtickalign and ytickalign, change to 1
https://makie.juliaplots.org/stable/documentation/api_reference/#Axis
