### ISSUE TITLE
GLMakie test LoadError 'libwand' not defined

### ISSUE THREAD

**Issue by delnatan** [JuliaPlots/Makie.jl#1533]
Hi

I'm using Julia on my Macbook Air (M1), installed via `homebrew` cask. 

Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.2.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)

After installing GLMakie in Pkg mode, running `test GLMakie` gives me a `LoadError` for libwand.

Here's the stacktrace:
ERROR: LoadError: InitError: UndefVarError: libwand not defined
Stacktrace:
 [1] magickgenesis
   @ ~/.julia/packages/ImageMagick/Fh2BX/src/libmagickwand.jl:21 [inlined]
 [2] __init__()
   @ ImageMagick ~/.julia/packages/ImageMagick/Fh2BX/src/libmagickwand.jl:27
 [3] _include_from_serialized(path::String, depmods::Vector{Any})
   @ Base ./loading.jl:768
 [4] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
   @ Base ./loading.jl:854
 [5] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1097
 [6] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1013
 [7] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:997
 [8] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [9] top-level scope
   @ none:6
during initialization of module ImageMagick
in expression starting at /Users/delnatan/.julia/packages/GLMakie/pFGSp/test/runtests.jl:6
ERROR: Package GLMakie errored during testing

Anyone else on an M1 mac and using homebrew-installed Julia having this error?

Thanks!
-Daniel

**Comment by SimonDanisch** [comment]
This is an ImageMagick issue and maybe a M1 issue... I'd take this to the ImageMagick repository!

**Comment by delnatan** [comment]
Thanks! just in case anyone comes across this. The ImageMagick.jl issue solved the problem: https://github.com/JuliaIO/ImageMagick.jl/issues/209
