### ISSUE TITLE
why must `vlines!` and `hlines!` be passed the axis unlike lines, scatter, etc.?

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPlots/Makie.jl#1535]
awkward to me:
```julia
	fig = Figure()
	ax = Axis(fig[1, 1])
	lines!(rand(10), rand(10)) # not necessary to pass axis
	vlines!(ax, [4])                   # necessary to pass axis, why?
```
suggestion = to make this work
```julia
	fig = Figure()
	ax = Axis(fig[1, 1])
	lines!(rand(10), rand(10))
	vlines!([4])
```

**Comment by jkrumbiegel** [comment]
`vlines!` etc are just not recipes, so that convenience method is simply not defined. But we could add it, I never did because I hoped we'd make them recipes sooner (that needs some projection system changes first)
