### ISSUE TITLE
modify the axis of a `Figure` from the `fig` object

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPlots/Makie.jl#1536]
suppose `viz(t, y)` makes a very complicated visualization of the input data that works for 95% of use cases. 

```julia
function viz(t, y)
  fig = Figure()
  ax = Axis(fig[1, 1], xlabel="default xlabel", ylabel="default ylabel")
  lines!(t, y)
  return fig
end
```

so 95% of the time, call signature is `viz(t, y)` in a Pluto notebook, then the `fig` nicely displays.

but then 5% of the use cases we need to modify the figure further.
*option 1*: `return fig, ax` so we can do `ax.xlabel="new xlabel"`, but then unfortunately it does not display nicely in the pluto notebook since it returns a tuple :-1: 
*option 2*: get the axis from the `Figure` then modify it:
```julia
fig = viz(t, y)
ax = Axis(fig[1, 1])
ax.xlabel = "new xlabel"
fig
```
but, then, it looks like there are two axes on top of each other! so the `ax` in the function `viz` is different than the `ax` here. is there a way to solve this, or I must go with option 1?

# [edited] the answer
option 1:
```julia
t = range(0, 1, length=100)
y = t .^ 2

fig = viz(t, y)
ax = current_axis()
ax.xlabel = "new xlabel"
fig
```
option 2:
```julia
fig = viz(t, y)
ax = content(fig[1, 1])
ax.xlabel = "new xlabel"
fig
```

**Comment by jkrumbiegel** [comment]
Maybe `ax = current_axis()` helps already?
Or `ax = content(f[1, 1])`.
`Axis(f[1, 1])` makes a new one, just as you noted.

**Comment by SimonEnsemble** [comment]
thank you! edited with the answer to help others. :+1:
