### ISSUE TITLE
Lines between points whose location coincides in one coordinate

### ISSUE THREAD

**Issue by mschauer** [JuliaPlots/Makie.jl#155]
The following plot does not work:

```julia
lines([0.0, 0.0, 0.002, 0.002, 0.004, 0.004, 0.006, 0.006, 0.008, 0.008], 
[0.0, 0.0, 0.00136516, 0.00136516, -0.0548893, -0.0548893, -0.0938577, -0.0938577, -0.0971103, -0.0971103])
```

It seems to me that the renderer trips over lines between points whose location coincides in one coordinate. A workaround is doing a small randomisation.

**Comment by ffreyer** [comment]
Has been fixed. See also https://github.com/JuliaPlots/Makie.jl/issues/30.
