### ISSUE TITLE
`save(...; update=false)` removed in `0.16`

### ISSUE THREAD

**Issue by t-bltg** [JuliaPlots/Makie.jl#1568]
Using `Makie@0.16.1`:
https://github.com/JuliaPlots/Makie.jl/pull/1393 removed the ability to save a figure without updating it (e.g. zoomed in figure) which was added in https://github.com/JuliaPlots/Makie.jl/pull/1118.
The keyword `update` is still present in the [docstring](https://github.com/JuliaPlots/Makie.jl/blob/c453051af7e1cccdf63b8465f4d805b0cdebabab/src/display.jl#L203) though.

May I ask why this was removed and what is the alternative now ?

**Comment by SimonDanisch** [comment]
It should now never call `update`/`center!` on save, so any zoom/pan operation should be preserved.
If one wants the old behavior of `update=true`, one needs to call `center!(scene)` manually, to reset the zoom...

**Comment by t-bltg** [comment]
Thanks for the explanation.

**Comment by edljk** [comment]
Using `Makie v0.16.1` and `GLMakie v0.5.0`
The following classical way to save a figure is ok

```julia
using GLMakie
xs = cos.(1:0.5:20)
ys = sin.(1:0.5:20)
zs = LinRange(0, 3, length(xs))
meshscatter(xs, ys, zs, markersize = 0.1, color = zs)
Makie.save("/tmp/test1.png", Makie.current_figure())
```
but the more recent way (from the documentation)
```julia
using GLMakie
xs = cos.(1:0.5:20)
ys = sin.(1:0.5:20)
zs = LinRange(0, 3, length(xs))
fig = Figure()
meshscatter(xs, ys, zs, markersize = 0.1, color = zs)
Makie.save("/tmp/test2.png", fig)
```
produces a blank image since the last `fig` call seams to clear the scene..

**Comment by SimonDanisch** [comment]
What's the problem? That's the expected behaviour, you're not plotting into that fig with `meshscatter`

**Comment by edljk** [comment]
Oups, sorry, all my apologize

```julia
using GLMakie
xs = cos.(1:0.5:20)
ys = sin.(1:0.5:20)
zs = LinRange(0, 3, length(xs))
fig = Figure()
meshscatter(fig[1, 1], xs, ys, zs, markersize = 0.1, color = zs)
Makie.save("/tmp/test3.png", fig)
```
is perfectly ok. My mistake
