### ISSUE TITLE
CairoMakie is blocking new window to display

### ISSUE THREAD

**Issue by islent** [JuliaPlots/Makie.jl#1578]
```julia
using CairoMakie
f = Figure()
display(f)

using GLMakie
f = Figure()
display(f)
```
It does not pop up a new windows. **And it also blocks `GLMakie` to display figure**. However, the figure can be properly saved to file.

Test environment:
```julia
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = E:\.julia
  JULIA_NUM_THREADS = 8

(@v1.7) pkg> st CairoMakie
      Status `E:\.julia\environments\v1.7\Project.toml`
  [13f3f980] CairoMakie v0.7.0

(@v1.7) pkg> st GLMakie
      Status `E:\.julia\environments\v1.7\Project.toml`
  [e9467ef8] GLMakie v0.5.0

(@v1.7) pkg> st Makie
      Status `E:\.julia\environments\v1.7\Project.toml`
  [ee78f7c6] Makie v0.16.1
```

I'm using `Windows 11`. Is that the source of problem?

**Comment by lazarusA** [comment]
after `using GLMakie` use:
`GLMakie.activate!()`

if you wan to go back and forward between backends, you need to activate them.

**Comment by islent** [comment]
That works. However, the first problem is not solved:
```julia
using CairoMakie
f = Figure()
display(f)
```
I mean, no window pops up in that whole procedure.

**Comment by SimonDanisch** [comment]
>CairoMakie can output beautiful static vector graphics, but it doesn't have the native ability to open interactive windows.

https://makie.juliaplots.org/stable/tutorials/basic-tutorial/index.html#preface

**Comment by islent** [comment]
Oh! Now I understand. Many thanks! And sorry for bothering.
