### ISSUE TITLE
Variable `arrow_size` in `streamplot` should be in "axis units" by default

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#1580]
With streamplots we have no real knowledge about the axis limits. For exactly the same arguments of why in a scatterplot the markersize should be in axis units instead of data units, in streamplot the same should be done for the marker of the "tip" of the arrows in a streamplot. E.g., by default I get:

```
fig, ax = streamplot(ds, (200..320), (200..320))
```

![image](https://user-images.githubusercontent.com/19669089/148946047-05bceb3f-e879-4a9c-9cd4-f28623d1f5df.png)

But I actually have to do:

```
fig, ax = streamplot(ds, (200..320), (200..320); arrow_size = 10)
```
![image](https://user-images.githubusercontent.com/19669089/148945970-aa3f3699-987a-4bd5-a7b1-6c44362780c4.png)

**Comment by ffreyer** [comment]
That should already be the default in the latest version
https://github.com/JuliaPlots/Makie.jl/blob/69d3709277d12134fc637bcf7878e7f6f1dbc08e/src/basic_recipes/streamplot.jl#L27

**Comment by Datseris** [comment]
Apologies for missing a MWE, here is one:
```julia
using GLMakie

const σ_stefan_boltzmann = 5.670374419e-8 # in W/m²/K⁴
const σ₄ = σ_stefan_boltzmann ^ (1/4) 

function ebm(u)
    T, TD = u
    Sf = 340.0
    α = 0.3 # ice_albedo_feedback(T) #+ C
    ε = 0.65
    η = 0.7
    dT  = Sf*(1-α) - ε*(σ₄*T)^4 - η*(T-TD)
    dTD = η*(T-TD) + TD*(1 - TD/200)
    return Point2f0(dT/c, dTD/cD)
end

# case 1:
streamplot(ebm, 200..320, 200..320)

# case 1:
streamplot(ebm, 200..320, 200..320; arrow_size = 10)

```

**Comment by Datseris** [comment]
@ffreyer thanks for the reply, and is it also true the the arrow size is NOT in data units? I.e., if I plotted the ranges of 0 to 10 million, would the arrow have the same relative size on the plot?

**Comment by SimonDanisch** [comment]
Yeah it should be in pixels!

**Comment by Datseris** [comment]
Okay, I think this is closed on master right? so I close this!

**Comment by SimonDanisch** [comment]
The units should have been in pixels for a while, and changing to a default that makes sense for pixel units should be tagged as of 0.16
