### ISSUE TITLE
[GLMakie] GLFW wait instead of poll

### ISSUE THREAD

**Issue by AlexEnerdyne** [JuliaPlots/Makie.jl#1584]
I see that `GLFW.PollEvents()` is being used instead of `GLFW.WaitEvents()`.  This causes my GPU to unnecessarily keep drawing scenes if there is no changes.  Would it be possible to add the option to choose `GLFW.WaitEvents()` for static scenes?

This becomes a problem when I draw large signals (millions of samples) but just want to look at the signal.  My GPU stays in overdrive, even though it is not necessary.

**Comment by SimonDanisch** [comment]
You can actually define your own renderloop...
Just copy [fps_renderloop](https://github.com/JuliaPlots/Makie.jl/blob/master/GLMakie/src/rendering.jl#L17), make your changes, and then replace it via [set_window_config!](https://github.com/JuliaPlots/Makie.jl/blob/master/GLMakie/src/rendering.jl#L70)

**Comment by AlexEnerdyne** [comment]
That is awesome!  Thanks!

**Comment by AlexEnerdyne** [comment]
Awesome stuff.  Thanks!
