### ISSUE TITLE
How to clear a figure?

### ISSUE THREAD

**Issue by jarbus** [JuliaPlots/Makie.jl#1595]
I'm making a UI for data exploration, and want to have a button that I can click to switch between different views of the data, kind of like tabs. For example, in one view, I have one big axis that takes up most of the figure, and in another view, I have two smaller axes that take up half of the figure each. In each view, I don't want to see the axes from the other view. 

Crucially, I don't want to have to switch between two figures, as that will launch another window. I need to use the same window, with the ability to change a figure's entire layout table on the fly.

Is there a way to clear, and then reconstruct, a Figure's layout table?

**Comment by Mo8it** [comment]
One can do a lot with Observables. Take a look at this page with the video:
https://makie.juliaplots.org/stable/documentation/nodes/index.html

But I would also appreciate an easy method to clear a figure. I did not find any.

**Comment by jarbus** [comment]
I got it, I need to delete entries in `Figure.content`

**Comment by fatihyaman661** [comment]
> I got it, I need to delete entries in `Figure.content`

And how do you delete the entries exactly😅
