### ISSUE TITLE
Text not rendered correctly with 3d orthographic camera

### ISSUE THREAD

**Issue by da-mi** [JuliaPlots/Makie.jl#1602]
I cannot understand the behavior of `near` and `far` planes for 3d orthographic camera in case of text:

```julia
using GLMakie
using GeometryBasics

scene = Scene()

mesh!(scene, FRect3D(Vec3f0(-15,-10,0), Vec3f0(30,20,5)), color = :blue)
p = poly!(scene, Rect2D(-5,-5,10,10), color = :red)
translate!(p, Vec3f0(0,0,10))
text!(scene, ". HELLO", position = Vec3f0(0,0,15))

cam = cam3d!(scene)
cam.attributes.projectiontype[] = Makie.Orthographic
# cam.attributes.projectiontype[] = Makie.Perspective #OK
center!(scene)
cam.attributes.fixed_axis[] = false
cam.eyeposition[] = Vec3f0(0, 0, 100)
cam.lookat[] = Vec3f0(0, 0, 0) 
cam.upvector[] = Vec3f0(0, 1, 0)

cam.near[] = 1
cam.far[] = 1000

update_cam!(scene, cam)
scene
```

The script above should set the camera of the following scene
<img src="https://user-images.githubusercontent.com/9463691/150143919-3a7880fb-71fa-4206-a224-94cc8ab6dc25.png" width="400">

as "top view", perpendicular to XY plane:
<img src="https://user-images.githubusercontent.com/9463691/150145931-c7f65da1-ede2-42ce-b801-f4cc7cad7f41.png" width="400">

Text is not rendered correctly even if camera settings should be ok:
- mesh Z crd: 0-5
- poly Z crd: 10
- text Z crd: 15
- eyeposition Z crd: 100
- near camera plane = 1
- far camera plane = 1000

Moreover, by setting:
- `cam.far` >190 text is hidden (?), mesh and poly visible [but everything is fine with Perspective projection]
- 95< `cam.far` <190 text, mesh and poly are visible (expected)
- 90< `cam.far` <95 text and poly are visible (expected)
- 90< `cam.far` <85 text only is visible (expected)
- 85< `cam.far` <1 text is still visible (?)

GLMakie v0.5.0
Makie v0.16.1

**Comment by ffreyer** [comment]
`near` and `far` set the minimum and maximum z-value in camera space. Everything outside that range gets clipped.
I think screen space text currently discards its real depth and takes some default value. It maybe end up at something like 0.5 (near + far)? With `space = :data` this shouldn't happen.

#1596 seems to fix this
