### ISSUE TITLE
Uncaught error when running `scatter()` i.e. with no args

### ISSUE THREAD

**Issue by IanButterworth** [JuliaPlots/Makie.jl#1604]
I was looking to create an empty scatter plot, so (arguably foolishly) tried this, which gave an uncaught error, rather than something I could act on.

```
julia> s = scatter()
ERROR: UndefVarError: not_implemented_for not defined
Stacktrace:
 [1] scatter()
   @ MakieCore ~/.julia/packages/MakieCore/S8PkO/src/recipes.jl:170
 [2] top-level scope
   @ REPL[3]:1
```

**Comment by SimonDanisch** [comment]
Ah, is this on the newest version? Because we should have fixed this...

**Comment by IanButterworth** [comment]
Ah no, v0.15.3
My bad!
