### ISSUE TITLE
Twin y-axis with wrong range

### ISSUE THREAD

**Issue by cossio** [JuliaPlots/Makie.jl#1608]
```julia
fig = Figure(resolution=(400, 400))
axPL = Axis(fig[1:2,1][1,1])
lines!(axPL, 1:50, range(start=-0.2, stop=-1.12, length=50))
ax∂ = Axis(fig[1:2,1][1,1], yaxisposition=:right)
hidespines!(ax∂)
hidexdecorations!(ax∂)
linkxaxes!(axPL, ax∂)
lines!(ax∂, 1.0:0.004170567707890033:50.0, 0.001randn(11750))
fig
```

![download](https://user-images.githubusercontent.com/10637482/150234514-864d1dfd-ff28-40ce-bbd2-82661ffcce7b.png)

The right twin y-axis is not picking up the correct range, so that data series is not visible in the plot.

**Comment by SimonDanisch** [comment]
Oh, is this on 0.16?

**Comment by SimonDanisch** [comment]
I think we never tagged https://github.com/JuliaPlots/Makie.jl/commit/78d71c5609684ebbeaea7e073740582798d59330 😅

**Comment by cossio** [comment]
@SimonDanisch Oh please do tag it :smiley:

**Comment by ffreyer** [comment]
You're missing a `linkyaxes!(axPL, ax∂)`

**Comment by cossio** [comment]
> You're missing a `linkyaxes!(axPL, ax∂)`

Are you sure? With ``linkyaxes!(axPL, ax∂)` both y-axis get the same range, which is not what I want.

**Comment by ffreyer** [comment]
Oh then I missunderstood. Without it I'm getting this on 0.16.2
![Screenshot from 2022-01-20 13-52-10](https://user-images.githubusercontent.com/10947937/150342135-435ca921-c060-4679-b538-759cc29ad6c7.png)
so I guess it's fixed with the new release?

**Comment by cossio** [comment]
Yep, fixed now! Thanks
