### ISSUE TITLE
Annotated heatmaps?

### ISSUE THREAD

**Issue by kir0ul** [JuliaPlots/Makie.jl#1637]
Hi there,

Is there a way in Makie to create annotated heatmaps [like in Seaborn](https://seaborn.pydata.org/examples/spreadsheet_heatmap.html) with the numeric values showed in each cell?

**Comment by SimonDanisch** [comment]
There is a test with an example:
https://github.com/JuliaPlots/Makie.jl/blob/master/ReferenceTests/src/tests/text.jl#L3

**Comment by kir0ul** [comment]
Thanks!
