### ISSUE TITLE
Error using Makie and very slow ploting

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#165]
Hi

I try to use Makie. When I run scene = Scene(), I got the following error

RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) RGB{N0f8}(1.0,1.0,1.0) .....

When I test and build the package, everything seems to work fine. Is there anything I can do to fix this problem?

**Comment by SimonDanisch** [comment]
`]add ImageMagick` should fix that!

**Comment by wsrinin** [comment]
Thank you.
