### ISSUE TITLE
WGLMakie 90% cpu utilization to display a 1000x1000 image

### ISSUE THREAD

**Issue by MariusDrulea** [JuliaPlots/Makie.jl#1650]
Displaying a simple image with WGLMakie leads to a 90% cpu utilization. Something similar happens if we plot a long array. It looks like Makie was only tested for really small data plots.
Just like GLMakie overloads the GPU: https://github.com/JuliaPlots/Makie.jl/issues/1427. 

**Image:**
```
using WGLMakie
plot(rand(1000, 1000))
```

**Array:**
```
using WGLMakie
plot(rand(1000*1000))
```

**Comment by SimonDanisch** [comment]
I don't think we need a separate issue for this, it's pretty much the same thing as #1427 ...
