### ISSUE TITLE
How to record part of plot?

### ISSUE THREAD

**Issue by jenka2014** [JuliaPlots/Makie.jl#1651]
In documentation i found record video example
```
record(fig, "time_animation.mp4", timestamps;
        framerate = framerate) do t
    time[] = t
end
```
but i can't record a part of figure?!!
```
record(fig[2,2], "time_animation.mp4", timestamps;
        framerate = framerate) do t
    time[] = t
end
```
How to do this?

**Comment by SimonDanisch** [comment]
What are you trying to do?
Do you want to record a video of a subplot?
That's currently not directly supported.
Can you give a bit more context?

**Comment by jenka2014** [comment]
I have a window in the center of which is a drawing. On the left side there are control buttons. placed in fig[1,2], fig[1,3] etc. 
when I want to save a video, the buttons fall into the video. But i want to save only image placed in fig[1,1].
how do I save a video without buttons?

**Comment by SimonDanisch** [comment]
`fig, ax = plot_command(fig[2,2], ...)` returns an axis... You can use that like this:
```
`record(ax.scene, ..)`

**Comment by jenka2014** [comment]
thank you

**Comment by warnerwarner** [comment]
Hi, to reopen this, it doesn't look like plot_command is a used function any more. Is there any way to record a subplot now? I'm in the same situation as prog900 was, I have controls around my figure and a LScene I want to record

**Comment by SimonDanisch** [comment]
plot_command -> plot/scatter/heatmap/etc

**Comment by SimonDanisch** [comment]
```julia
ax = LScene(...)
...
record(ax.scene, ..)
```

**Comment by warnerwarner** [comment]
That still plots the entire figure. Heres a basic outline of the code I have currently:

`fig = Figure(size=(800, 600))
lscene = LScene(fig[1:2, 1], show_axis=false, scenekw=(backgroundcolor=:black, clear=true, viewmode=:fit))
a_vol = volume!(lscene, a_data)
b_vol = volume!(lscene, b_data)

rot = 1:209
cam = cameracontrols(lscene);
record(lscene.scene, "test_animation3.mp4", rotation) do rot
    rotate_cam!(lscene.scene, Vec3f(0, -2*π/209, 0))
end
`

**Comment by SimonDanisch** [comment]
Well your entire figure is just that one lscene?!

**Comment by warnerwarner** [comment]
Sorry if I've misunderstood how lscene and figures interact, but how would I construct my figure differently so that it only recorded the single lscene? I thought that because the lscene is only a subsection of the figure then when I use the record function it would only record that section? Should I have made another lscene for the rest of the figure?

**Comment by SimonDanisch** [comment]
Oh, hm, that's actually a bug :-O 
Would have sworn this works...

**Comment by BambOoxX** [comment]
I can confirm that `record(ax.scene...)` records the entire figure on GLMakie v0.10.18
