### ISSUE TITLE
Wrapping custom plot function around makie atomic functions produce different result

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#166]
Hi

I am writing a function that will plot specific information about my custom type.

```Julia
function set_limits(x_min, x_max, y_min, y_max)
    return FRect(x_min, y_min, x_max-x_min, y_max - y_min)
end

function AbstractPlotting.plot!(box::Box{2, T}) where {T <:Real}
    sides = [
    box.minimum_coordinates => box.minimum_coordinates + box.B[1];
    box.minimum_coordinates + box.B[1] => box.maximum_coordinates;   
    box.minimum_coordinates => box.minimum_coordinates + box.B[2];
    box.minimum_coordinates + box.B[2] => box.maximum_coordinates;
            ]
    scene = Scene(resolution = (500, 500))
    linesegments!(sides, color = :red, linewidth = 2, limits = set_limits(-box.L[1], box.L[1], box.L[2], -box.L[2]))
end
```

It supposed to plot the boundaries of the tilted box in 2d. However, it seems that the axis labels and ticks of the plot are missing. If I don't wrap it around a function, it seem to work just fine. I also try to set it afterward as well but the tick and axis label still does not show up.  Why is this the case?

Best,

**Comment by SimonDanisch** [comment]
You should follow this recipe:
https://github.com/JuliaPlots/Makie.jl/blob/master/examples/recipes.jl#L10
That should show you how to correctly implement a recipe for your `Box{2, T}` type!

**Comment by wsrinin** [comment]
Thank you for your hard work on the package. Makie is indeed super awesome.

**Comment by SimonDanisch** [comment]
Thanks :) I'll close this, let me know if you have further problems with type recipes!
