### ISSUE TITLE
Is interactively zooming no longer available for Axis3?

### ISSUE THREAD

**Issue by Enterprixe** [JuliaPlots/Makie.jl#1667]
Recently, I have been trying some Makie plots. In some videos from the recent past (summer 2021), I saw that there was the possibility to interactively zoom using GLMakie. However, as of right now, that does not seem to be a possibility anymore. Is this intended behaviour?

**Comment by SimonDanisch** [comment]
Axis3 never had zoom, you need to use LScene for that...
