### ISSUE TITLE
Strange behavior if plotting in a different order

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#167]
Hi

I found something very strange with respect to plotting line in 3D. If I run this code

`scene3d = Scene(resolution = (500, 500, 500))
linesegments!([SVector(0.0, 0.0, 0.0) => SVector(1.0,0.5,1.0)], color = :red, linewidth = 3)
linesegments!([SVector(0.0, 0.0, 0.0) => SVector(1.0,1.5,2.0)], color = :blue, linewidth = 3)
linesegments!([SVector(0.0, 0.0, 0.0) => SVector(0.0,0.5,0.0)], color = :green, linewidth = 3)`

everything works fine. However, if I reverse to order of evaluation

`scene3d = Scene(resolution = (500, 500, 500))
linesegments!([SVector(0.0, 0.0, 0.0) => SVector(0.0,0.5,0.0)], color = :green, linewidth = 3
linesegments!([SVector(0.0, 0.0, 0.0) => SVector(1.0,1.5,2.0)], color = :blue, linewidth = 3)
linesegments!([SVector(0.0, 0.0, 0.0) => SVector(1.0,0.5,1.0)], color = :red, linewidth = 3)
)`

I get nothing. Why is this the case?

**Comment by SimonDanisch** [comment]
Ah, that's likely because the first plot creates bad limits -.- That needs some rework ;)

**Comment by SimonDanisch** [comment]
This is fixed
