### ISSUE TITLE
Saved Plot Centering

### ISSUE THREAD

**Issue by Alex-vZyl** [JuliaPlots/Makie.jl#1675]
I am creating graphs to put in my thesis and they currently look like this:

[LFM_PowerSpectrum.pdf](https://github.com/JuliaPlots/Makie.jl/files/8079025/LFM_PowerSpectra.pdf)

When using them in Overleaf, they look like this:

![image](https://user-images.githubusercontent.com/81622310/154247170-9a714126-2d2e-4862-8569-5a18f0a406e4.png)

When saving the graph Makie centers it according to the plot + the labels.  Is it possible to center it according to the plot?  So in other words, add some white space to the right of the plot.

I am using `CairoMakie`.

**Comment by lazarusA** [comment]
Yes, use `figure_padding = (left, right, bottom, top)`, or just one number for all sides.  As in this example: https://juliadatascience.io/datavisMakie_attributes#fig:custom_plot

**Comment by Alex-vZyl** [comment]
Thank you, that works!

**Comment by Alex-vZyl** [comment]
Thank you, that works!

I was hoping for a answer way to handle this dynamically, but this is sufficient.
