### ISSUE TITLE
automatic ticks too sparse

### ISSUE THREAD

**Issue by Moelf** [JuliaPlots/Makie.jl#1678]
```julia
using CairoMakie
with_theme(theme_light()) do
	N = 10^4
	data = randn(N)
	
	hist(
	data; color=:yellow2, strokewidth = 1,
	label = "MC",
	figure=(; resolution=(600,400))
	)
	limits!(-5, 5, 0, 1200)
	current_figure()
end
```
![image](https://user-images.githubusercontent.com/5306213/154609602-11cec2f5-673a-4065-8051-609926b1d92b.png)

(happy to help, need some pointer to the current hueristics maybe)

**Comment by SimonDanisch** [comment]
Maybe, if you have certain ticks in mind, rather use xticks in this case?
```julia
julia> ax.xticks = -5:1:5
julia> ylims!(ax, 0, 1200)
```

**Comment by SimonDanisch** [comment]
@jkrumbiegel will know better if this is intentional or an edge case we should fix ;)

**Comment by jkrumbiegel** [comment]
The tick finding algorithm uses a weighting of different factors: https://github.com/JuliaPlots/PlotUtils.jl/blob/master/src/ticks.jl#L79-L110

In this case, probably the "niceness" and "simplicity" weights encourage picking -5, 0, 5. You can actually set these parameters yourself with the `WilkinsonTicks` struct, I used the defaults (I don't know who picked those originally) but you can pick your own.
