### ISSUE TITLE
plotting line with three points doesn't plot 3 points

### ISSUE THREAD

**Issue by goretkin** [JuliaPlots/Makie.jl#168]
On `[ee78f7c6] Makie v0.9.0+ #master (https://github.com/JuliaPlots/Makie.jl.git)`

Plotting a line with four points: 
```
julia> using Makie

julia> (x,y,z) = (rand(4), rand(4), rand(4))
([0.752856, 0.0393552, 0.499543, 0.690117], [0.149045, 0.332351, 0.173926, 0.16516], [0.285563, 0.528791, 0.565671, 0.365775])

julia> lines(x[1:4], y[1:4], z[1:4])
```

Produces an expected result.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/581043/47041293-6ebbe380-d156-11e8-89f8-e9cc372be267.png">

Plotting with three points
```
julia> lines(x[1:3], y[1:3], z[1:3])
```

Seems to ignore the last point.
<img width="478" alt="image" src="https://user-images.githubusercontent.com/581043/47041343-84310d80-d156-11e8-8faf-ae65fc227334.png">

**Comment by ffreyer** [comment]
Has been fixed. See also #30
