### ISSUE TITLE
GLMakie rendering issue with transparency 

### ISSUE THREAD

**Issue by musm** [JuliaPlots/Makie.jl#1695]
Take a look at the axis  in the following figures.

![image](https://user-images.githubusercontent.com/4319522/155569854-aba7c4b1-8027-47b1-a57d-3564c8a7eefc.png)

<img width="768" alt="image" src="https://user-images.githubusercontent.com/4319522/155570284-b6ebfe45-bf65-4062-8feb-07a2e1e0a3d0.png">
expected (left), reality (right)

**Comment by musm** [comment]
```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

**Comment by fatteneder** [comment]
Could you please add a MWE for the last two plots?
And what kind of theming are you using here?
Also version `0.5.4` seems to be rather old.

**Comment by fatteneder** [comment]
I can't reproduce this behavior. I tested with `GLMakie v0.5.4, v0.5.2` and `Julia v1.7.1, v1.7.2`.

```julia
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)
```

**Comment by musm** [comment]
My thinking is that this might be hardware dependent. 
This basically happens on one of my machines that has an AMD GPU.

**Comment by SimonDanisch** [comment]
Hm, this could actually be the discard right here:
https://github.com/JuliaPlots/Makie.jl/blob/master/GLMakie/assets/shader/fragment_output.frag#L19
I think discard is notoriosly ill defined, so maybe that's where the vendors have different implementations.

**Comment by musm** [comment]
If you let me know what to tweak I'd be happy to tests fixes.

**Comment by SimonDanisch** [comment]
Finally got a chance to try out my AMD gpu and also reproduce this..
.I found the problem and fixed it here: https://github.com/JuliaPlots/Makie.jl/pull/1775
