### ISSUE TITLE
Hboxing plots

### ISSUE THREAD

**Issue by mschauer** [JuliaPlots/Makie.jl#170]
The following does not work (changing the -42 to 0 or running the code in the repl makes it work more or less).

Displays:
<img width="480" alt="makie1" src="https://user-images.githubusercontent.com/1923437/47258615-15c5b580-d49e-11e8-8415-ab982b3f82f3.png">

Should display (up to minor margin errors):
<img width="480" alt="makie2" src="https://user-images.githubusercontent.com/1923437/47258616-178f7900-d49e-11e8-962a-9e8492d96f66.png">

```
using Makie
using AbstractPlotting: hbox
using Random
function p()
    Random.seed!(123)
    t =  range(-122277.93103448274, stop=-14798.035304081845, length=29542)
    x = -42 .- randn(length(t))
    global sc1 = Scene(resolution = (2000, 300))
    scatter!(sc1, t, x, color=:black,  markersize=sqrt(length(t)/20))
    global sc2 = Scene(resolution = (2000, 300))

    lines!(sc2, t[1:end-1], diff(x), color=:blue)
    scene = hbox(sc2, sc1)
    display(scene)
end
p()
```
Looks almost like a version of #132

**Comment by SimonDanisch** [comment]
>(changing the -42 to 0 or running the code in the repl makes it work more or less

no, executing it multiple times seem to make it work -.-

I need to figure out what could be order dependent/racy here ... I thought that this should be much less the case with observables^^

**Comment by mschauer** [comment]
If you are running this example, also check that if the plot is created, then there is still something wrong with zooming: if zooming the lower figure it zooms towards the mouse pointer, if zooming the upper figure it zooms to a point outside.

**Comment by SimonDanisch** [comment]
yeah, I noticed too ;) Must be a wrong mapping of the mouse position in a subwindow

**Comment by mschauer** [comment]
No, I think there is really a connection to the -42, try to vary it while calling the function.

**Comment by SimonDanisch** [comment]
hm, but it definitely works without changing it - it probably just makes it less visible when it starts at 0;)

**Comment by mschauer** [comment]
No, really, maybe machine dependent but on fresh repls running with +4 and -42 as constant I get
<img width="480" alt="makie4" src="https://user-images.githubusercontent.com/1923437/47268220-61d03300-d54e-11e8-9691-813277f51641.png">
<img width="480" alt="makie42" src="https://user-images.githubusercontent.com/1923437/47268223-67c61400-d54e-11e8-8a72-69e47c205d49.png">

**Comment by SimonDanisch** [comment]
fixed on master AbstractPlotting + Makie
