### ISSUE TITLE
Makie showing both standalone and plot pane in Juno

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#172]
I thought I saw a discussion about this recently but I can't find it.

When plotting in Makie within Juno, it seems to pop up the standalone GL window and also tries to plot in the plot pane. Is there a way to disable the plot pane? From #87 I thought I could do `Makie.use_plot_pane(false)` but that doesn't seem to be defined anymore.

edit:this is on Makie 0.9.0

**Comment by SimonDanisch** [comment]
You need to disable it in the atom Julia settings!

**Comment by ssfrr** [comment]
It would be useful to have a programmatic way of doing it - usually I want the plot pane on and use it when I'm using Plots.jl. For interactive stuff I'm using Makie with the separate GL window, so it would be useful to be able to have my code determine where the plots go, rather than going into the Atom settings when I switch between projects.

**Comment by krcools** [comment]
Is there also a way to do the opposite? I want to only use the plot pane, not the external window. The external window demands the input focus upon update. As a result I have to alt-tab back into atom to enter the next graphics command.

**Comment by asinghvi17** [comment]
@krcools see https://github.com/JuliaPlots/Makie.jl/issues/341#issuecomment-482921928

**Comment by krcools** [comment]
Thank you. This solved things for me.
