### ISSUE TITLE
Node not defined

### ISSUE THREAD

**Issue by valerianfaber** [JuliaPlots/Makie.jl#1728]
I am working on an Apple M1 iMac under OS 12.2.1 using Julia 1.7.2.
I installed Makie and GLMakie with the package manager. When trying to run the following code from the Makie documentation (https://makie.juliaplots.org/v0.15.1/documentation/nodes/)
```
using GLMakie, Makie
x = Node(0.0)
```
I get the following error: "UndefVarError: Node not defined"
Running "test GLMakie" from the package manager reveals another error "UndefVarError: libwand not defined", but as a Julia beginner I don't know if these two are related or what I should do to get GLMakie running. See attached file for details.
[node_error.txt](https://github.com/JuliaPlots/Makie.jl/files/8190709/node_error.txt)
[glmakie_test.txt](https://github.com/JuliaPlots/Makie.jl/files/8190710/glmakie_test.txt)

**Comment by ffreyer** [comment]
Node got deleted in 0.16. Use `Observable` instead.
https://github.com/JuliaPlots/Makie.jl/blob/master/NEWS.md

**Comment by SimonDanisch** [comment]
The other one is: https://github.com/JuliaPlots/Makie.jl/issues/1533

**Comment by hewhocannotbetamed** [comment]
Take it out of the documentation.
