### ISSUE TITLE
plot pane error in Juno

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#173]
I get the following output in Juno from `heatmap(rand(100,100))`:

![image](https://user-images.githubusercontent.com/734386/47268156-57e10c80-d51b-11e8-81b0-e482c3df19c7.png)

This is on Makie 0.9.0

**Comment by ssfrr** [comment]
Not seeing this on `master`, closing.

**Comment by SimonDanisch** [comment]
I think that's an atom issue in any case! I've seen it a couple of times when closing the window before it's done rendering the plot pane, and I just think atom isn't handling that gracefully.
