### ISSUE TITLE
remove margins on default heatmap axes

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#174]
Currently `heatmap(rand(100,200))` gives this:

![image](https://user-images.githubusercontent.com/734386/47268213-fff6d580-d51b-11e8-8c7f-1c253eb53aad.png)

I humbly suggest that it would be more attractive if it didn't have the margins around the heatmap, so the plot went all the way to the axis ends.

I think usually heatmaps aren't thought of as being embedded in a larger space the same way that a scatter plot is, so the background margin seems somewhat jarring.

**Comment by SimonDanisch** [comment]
I guess that makes sense...
You can already do this by overwriting padding:
```
heatmap(rand(100, 100), padding = (0.0, 0.0))
```

**Comment by SimonDanisch** [comment]
I should rename that to margin :D

**Comment by ssfrr** [comment]
nice, thanks.

FWIW I don't have any preference for `margin` over `padding`

**Comment by ffreyer** [comment]
This produces zero margins by default now

**Comment by kchu25** [comment]
There's no attribute named `padding` nor `magin` in `heatmap` currently. What are the current options to deal with the white padding issue?

**Comment by ffreyer** [comment]
You can adjust the limits of the axis to create margins/paddings
