### ISSUE TITLE
weird plot scaling behavior with window resizing

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#175]
with a `heatmap(rand(100,100))`, dragging the corner of the window to make it taller leaves the plot height the same but reduces the width. e.g. here is the default and after resizing the window:

![image](https://user-images.githubusercontent.com/734386/47268319-629ca100-d51d-11e8-8a8d-0e387ede2f31.png)

![image](https://user-images.githubusercontent.com/734386/47268327-73e5ad80-d51d-11e8-81c6-7627e7e95388.png)

This is on Makie 0.9.0

**Comment by SimonDanisch** [comment]
master should incorperate a few changes to make this work better (master AbstractPlotting + Makie).

**Comment by SimonDanisch** [comment]
Ugh, and the font search still doesn't 100% work - it shouldn't be bold + italic like it's the case for you :(

**Comment by ssfrr** [comment]
Hmm, on `master` the plot doesn't resize, it just gets a black border for the parts outside of the original window area.

![image](https://user-images.githubusercontent.com/734386/47268981-98458800-d525-11e8-9888-438799e8f84a.png)

Fonts still seem a bit bold, though the sizing and change to `x` instead of `X Axis` is looking better!

**Comment by SimonDanisch** [comment]
Oh weird, thought I Fixed that :D that looks worse than fixed :P

**Comment by SimonDanisch** [comment]
ok pushed a fix!
Also this should work now:
```julia
using Makie
AbstractPlotting.set_theme!(; scene = (padding = (0.0, 0.0),))
s = heatmap(rand(100, 100))
```
Contemplating to move those attributes out of scene, and just have:
```Julia
set_theme!(padding = (0.0, 0.0))
```

**Comment by ssfrr** [comment]
Just pulled the latest `master` and it seem to be having the same w.r.t. the black border.

I can see the logic in applying the theme to a scene (and rather than global state), but it seems like it could be something like `settheme!(scene=defaultscene(); kwargs...)` so if you don't specify a scene it applies to the default one.

**Comment by SimonDanisch** [comment]
It's basically like that ;) I just need to implement `settheme!(scene; kw_args...)` ... right now you can only do this like:
```Julia
scene = Scene(padding = (0.0, 0.0))
# or 
theme(scene, :padding)[] = (0.0, 0.0)
```

**Comment by SimonDanisch** [comment]
>Just pulled the latest master and it seem to be behaving the same w.r.t. the black border.

Did you really pull both makie & abstractplotting and have the package manager actually use those? I just double checked and it behaves correctly and I pushed all changes

**Comment by ssfrr** [comment]
oh, sorry, I just pulled makie, not abstractplotting. working now!
