### ISSUE TITLE
source code?

### ISSUE THREAD

**Issue by DanielRivasMD** [JuliaPlots/Makie.jl#1766]
Hi, I was wondering where I can find the source code for the image / example in the README, the one by AlexisRenchon. Appreciated.

**Comment by AlexisRenchon** [comment]
Hi @DanielRivasMD, the source code is [here](https://github.com/Land-atmosphere-interface-heterogeneity/GIF-TEROS11-Julia/blob/master/MakieLayout_data_2D.jl), but this is a very old version of Makie, it wouldn't work today. Also, the data used is not published. 

I plan to update this soon, it will be hosted somewhere in that [organization](https://github.com/CUPofTEAproject).

**Comment by DanielRivasMD** [comment]
@AlexisRenchon Appreciated!
