### ISSUE TITLE
Trying to understand how lift function work?

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#177]
Hi,

I have trouble understanding how lift function work and how to use it in conjunction with do block. I can't find any document about this. 

Best,

**Comment by SimonDanisch** [comment]
that section should explain it: http://makie.juliaplots.org/stable/interaction.html

**Comment by SimonDanisch** [comment]
that section should explain it: http://makie.juliaplots.org/stable/interaction.html
