### ISSUE TITLE
Automatic extension of colorbar

### ISSUE THREAD

**Issue by natgeo-wong** [JuliaPlots/Makie.jl#1783]
Hi, as per advice a few days ago, I would like to open this issue for colorbar extensions to automatically extend the colormap for discrete colormaps.

Currently, the :auto: option for extending the colorbar results in the following:
<img width="366" alt="Screen Shot 2022-03-21 at 5 13 02 pm" src="https://user-images.githubusercontent.com/36907442/159806122-d292d616-f49e-432e-b1d5-5d924b6c6075.png">

But I would like something like this instead:
![01c-flsm_BRN](https://user-images.githubusercontent.com/36907442/159806184-00904ac3-cbbf-46a4-9eeb-2f088bc88852.png)

Where the colormap is automatically extended to fit.

**Comment by briochemc** [comment]
Just to be clear for the record here, the current issue is that in the discrete case, the `:auto` option uses the same color for the extension and for the last level inside the color range. 

For instance, the issue in the 1st image above is that the color between +4 and +5 is the same as the color above +5.

Instead it would be better to stretch the colormap (by one or two entries, depending on whether one or both extensions are requested) and then ensure that the extensions are colored with the next/previous color, as in the second image.

**Comment by jkrumbiegel** [comment]
Should be fixed by https://github.com/JuliaPlots/Makie.jl/pull/2183

**Comment by jkrumbiegel** [comment]
An example from the docs

<img width="677" alt="image" src="https://user-images.githubusercontent.com/22495855/182882954-56c36bbe-7007-4efd-847a-1f7efcede402.png">
