### ISSUE TITLE
Camera settings

### ISSUE THREAD

**Issue by neuralian** [JuliaPlots/Makie.jl#181]
How do I set camera properties (position, view target etc) in a scene? Where is this documented?

Edit: The "Moire" example shows how to set the position of the camera, the "lookat" target coordinates and how to orbit the camera around the target.

**Comment by SimonDanisch** [comment]
These manipulation functions are currently implemented: 

https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/camera/camera3d.jl#L151
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/camera/camera3d.jl#L203
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/camera/camera3d.jl#L126

Documentation PR more than welcome :)
