### ISSUE TITLE
CairoMakie + linesegments(overdraw = false)

### ISSUE THREAD

**Issue by edljk** [JuliaPlots/Makie.jl#1811]
Is there a way to avoid `linesegments` overdrawing in 3D plots using `CaiorMakie`? The (default) option `overdraw = false` seems to have no effect whereas it does the job using `GLMakie`.

**Comment by jkrumbiegel** [comment]
Cairomakie is not a 3d engine so it can only use the "painter's algorithm". That means the layer of your plot depends only on its z value / when it was created.

**Comment by edljk** [comment]
Thank you very much for this confirmation.
