### ISSUE TITLE
levels on contourf creating white border around plot

### ISSUE THREAD

**Issue by jewh** [JuliaPlots/Makie.jl#1812]
Specifying the colour limits in the `contourf` function using the `levels` keyword argument creates a white border around the plot. Seems like unintended behaviour?

MWE:

```
using CairoMakie

M = rand(10, 10)
fig = CairoMakie.Figure()
ax = Axis(fig[1,1])
cplot = CairoMakie.contourf!(fig[1,1], 1:10, 1:10, M, levels=0:0.1:1)
Colorbar(fig[1,2], cplot)
fig
```

![test](https://user-images.githubusercontent.com/33940814/162583278-905cccc2-2889-4106-bbf0-94e01af43753.png)

Worth noting that this issue is also displayed in the `Colorbar` examples on the Makie website: [link](https://makie.juliaplots.org/stable/examples/layoutables/colorbar/)

**Comment by BambOoxX** [comment]
Just a comment, this does not seem to occur with `GLMakie`, that may be a problem coming from Cairo itself...

**Comment by jewh** [comment]
Ahh okay, interesting

**Comment by jewh** [comment]
Following [discussion on the Julia forum](https://discourse.julialang.org/t/cairomakie-contourf-set-colour-limits/79261), seems like this is intended behaviour, so I'm closing the issue.

For anyone coming along later, `tightlimits!(ax)` fixes the problem.

**Comment by BambOoxX** [comment]
@jewh I see now that I did not understand your question correctly, I thought you were referring to the white lines between the different color levels. My bad, sorry!
