### ISSUE TITLE
Multi-line legend label not aligned correctly

### ISSUE THREAD

**Issue by ValentinKaisermayer** [JuliaPlots/Makie.jl#1820]
```julia
using CairoMakie
f = Figure()
ax = Axis(f[1,1])
lines!(cumsum(randn(1000)), label="Dummy")
lines!(cumsum(randn(1000)), label="Dummy with\ntoo long text")
Legend(f[1,2], ax)
f
```
![plot_67](https://user-images.githubusercontent.com/50108075/163545394-ce17b03d-5d37-4fe7-9e31-97e1b870acb4.png)

**Comment by jkrumbiegel** [comment]
I think this got fixed in the meantime by text layout changes I did 

![image](https://user-images.githubusercontent.com/22495855/177359889-b114ab57-2739-4f5b-b7a9-9c5ae1613c7d.png)
