### ISSUE TITLE
allow legend with title only

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPlots/Makie.jl#1824]
instead of needing to manually tune `text!`, would be dope to allow:
`Legend(fig[1, 1], [], [], "my title")`
so I can just have a box with text judicially place at top left etc.
forgive me if this is possible already, would have to know this trick!

**Comment by SimonEnsemble** [comment]
nice! this is great for *outside* of the figure but I am hoping to put the text inside the figure to save space.
<img width="505" alt="image" src="https://user-images.githubusercontent.com/30643894/164518277-f9942e1e-1ca9-4cae-a772-c959d0a1ea7b.png">

`Label(fig[1, 1], my_text)` does this!
<img width="505" alt="image" src="https://user-images.githubusercontent.com/30643894/164518416-c62ab56e-5447-40b0-8d85-0b288bf74160.png">

**Comment by asinghvi17** [comment]
You should set `tellwidth=false, tellheight=false` in Label, to avoid this.

**Comment by jkrumbiegel** [comment]
but you can do `halign = 0.2, valign = 0.8`
