### ISSUE TITLE
Porting code from GLMakie 4.7 to 5.x not documented

### ISSUE THREAD

**Issue by ufechner7** [JuliaPlots/Makie.jl#1836]
I am trying to port my (unregistered) package https://github.com/aenarete/KiteViewers.jl from GLMakie 4.7 to the current version, but I miss any documentation how to do this.

I understand that braking changes are to be expected with a package that is not yet at version 1.0, but if they happen there should be some documentation how to make things work again.

See also this discussion on Discourse: https://discourse.julialang.org/t/migrating-from-glmakie-0-4-7-to-current/79913/5

**Comment by lazarusA** [comment]
I believe that you are looking for https://github.com/JuliaPlots/Makie.jl/blob/bbafe08aee048d6cfd83ba1a49866951918d2b02/NEWS.md

there, you can see the changes and how to update your code.

**Comment by ufechner7** [comment]
Sorry, but this document is insufficient. For example, it does not explain how to replace the function layoutscene() which worked nicely in 4.7 but not longer exists. I have this line in my code:
```   scene, layout = layoutscene(resolution = (840, 900), backgroundcolor = RGBf0(0.7, 0.8, 1))
 ```
 And later I use both scene and layout for a lot of other commands. How shall I do that with GLMakie 5.x ?

**Comment by jkrumbiegel** [comment]
What was once

```julia
scene, layout = layoutscene(...
ax = layout[1, 2] = LAxis(scene, ...
```

is now usually

```julia
f = Figure()
# layout = f.layout
# scene = f.scene
ax = Axis(f[1, 2])
```

**Comment by SimonDanisch** [comment]
I think the train has sailed for this to be actionable and people skipping over that many versions will have to re-read the docs at this point.

**Comment by ufechner7** [comment]
Well, it is not completed. I might open a new issue stating "GLMakie 5.x unusable"... 

I mean, to make braking changes and leave SW projects in a unfixable condition is very bad style.

**Comment by jkrumbiegel** [comment]
Sorry to hear that you're having trouble updating. Most changes have been rather incremental and would probably not have been difficult to follow on their own, I can imagine that now a lot of things have accumulated for you and it gets much trickier. If you have specific problems upgrading you can definitely make more issues about those, we will not have the time though to write further upgrade guides for such old versions. I have answered your question about `layoutscene` above, so if there's more like that I can try to help.

**Comment by SimonDanisch** [comment]
We currently don't have any funding to polish past mistakes like that.
If you were the one paying for new releases, that seems like a fair attitude, but I believe especially the release we're talking about was created with lots of work by Julius and me mostly in our free time.

**Comment by SimonDanisch** [comment]
> I might open a new issue stating

Please rather refer to discourse and slack for this, since issues are reserved for "actionable" items.
If you don't want to ask on those platforms, the best alternative would be [github discussions](https://github.com/JuliaPlots/Makie.jl/discussions)

**Comment by ufechner7** [comment]
Well, I refered to discourse, but the issue was not resolved: https://discourse.julialang.org/t/migrating-from-glmakie-0-4-7-to-current/79913/10

I got support to fix the changed syntax, but the semantic also changed and the resulting graphic is unusable. From my point of view Makie 0.5.x is severely broken.

**Comment by Moelf** [comment]
It is breaking change after all :). What else would semVer good for

**Comment by SimonDanisch** [comment]
Maybe post the promised update after several people helped?

**Comment by aramirezreyes** [comment]
Saw this on the release notes sent today. If not known I have been very successful on upgrading by checking distinct versions of the docs (tutorial for 4.7 vs tutorial for 5.x). The examples have not changed that much so those docs are pretty much a Rosetta Stone for upgrades.
