### ISSUE TITLE
Legend inside axis of twin y plot

### ISSUE THREAD

**Issue by Lightup1** [JuliaPlots/Makie.jl#1841]
As the title, how to get legend inside axis of twin y plot?
When using 
`linkxaxes!(ax1,ax2)`
`axislegend(ax1)`
`axislegend(ax2)`
You get overlapping legends.
![image](https://user-images.githubusercontent.com/32999017/165435296-c94e46e4-941f-48ab-84b3-f16d10ea8b1e.png)

**Comment by Lightup1** [comment]
Is there anything like `linkaxis` to link legend from different axis? Since the twin axis is made by two independent axis object.

**Comment by asinghvi17** [comment]
You can create the legend manually - see the docs [here](https://makie.juliaplots.org/stable/examples/layoutables/legend/) and [here](https://makie.juliaplots.org/stable/tutorials/layout-tutorial/#legend)

**Comment by Lightup1** [comment]
Thanks I will try it.

**Comment by SimonDanisch** [comment]
These questions are a better fit for [discourse](https://discourse.julialang.org/) or [slack](https://julialang.org/slack/).
