### ISSUE TITLE
Twin axis grid align

### ISSUE THREAD

**Issue by Lightup1** [JuliaPlots/Makie.jl#1842]
How to align twin axis grid?
For example, is it possible to let the y1=y2=0 line aligned?

**Comment by Lightup1** [comment]
While linkyaxis is not useful for y axis with different scale, for example `[-0.1,0.1]` an `[-8,10]`, I just set ylimts by myself to adjust the zero line alignment

**Comment by SimonDanisch** [comment]
These questions are a better fit for [discourse](https://discourse.julialang.org/) or [slack](https://julialang.org/slack/).

**Comment by Lightup1** [comment]
Hi @SimonDanisch ,is there a Makie channel in slack?
![image](https://user-images.githubusercontent.com/32999017/165720383-455c13a4-5d69-4410-b33a-1713ac304fee.png)
