### ISSUE TITLE
GLMakie font rendering issue on latest Ubuntu

### ISSUE THREAD

**Issue by jipolanco** [JuliaPlots/Makie.jl#1854]
After upgrading to Ubuntu 22.04, I'm having font rendering issues when using GLMakie:

```julia
using GLMakie
fig = Figure()
ax = Axis(fig[1, 1]; xlabel = "x", ylabel = "y", title = "Title")
fig
```

![test](https://user-images.githubusercontent.com/3952024/166105270-908dba42-74c4-4186-a617-52548d89d691.png)

Unfortunately I'm not familiar enough with OpenGL to identify the issue, and I'm also not quite sure about how to provide a reproducer.

I tested both on Makie 0.16.6 and master, using Julia 1.8-beta3. I also tested using software rendering (using `xvfb`) and got the same results, so I'm not sure if it's a graphics driver issue. In any case, here's an extract of my `glxinfo`:

```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 620 (WHL GT2) (0x3ea0)
    Version: 22.0.1
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.1
OpenGL core profile shading language version string: 4.60
```

I also tested different fonts (making sure they were available) with no success. Besides, things work correctly with CairoMakie, so I don't think it's a font issue.

I also tested on a different system (with Fedora 36), which has the same Mesa and OpenGL versions and a slightly older integrated Intel GPU, and everything works just fine.

---

FWIW, I also managed to build and run [this OpenGL font rendering tutorial](https://learnopengl.com/In-Practice/Text-Rendering) ([code here](https://github.com/JoeyDeVries/LearnOpenGL)), which I think uses FreeType and GLFW. Text from the tutorial renders just fine on my system.

**Comment by jipolanco** [comment]
It seems to be an issue with my own compiled version of Julia (tested on 1.7.2 and 1.8-beta3). I don't use any special flags (all `USE_SYSTEM_*` are disabled, which is the default), so I'm a bit surprised. I'll update in case i identify the problem, in case anyone has the same issue.

The issue doesn't occur when I use the official binaries (and wipe the Julia depot), so I'm closing this.

**Comment by ffreyer** [comment]
In case more people run into this: It might also be enough to empty `.julia/makie`. Those files hold the cached font data, which should get regenerated on `using Makie`

**Comment by SimonDanisch** [comment]
Hm, that's weird, since there is a try catch around the serialization, so if that fails due to Julia changing its format, it should delete that file itself and re-generate it.
