### ISSUE TITLE
Better default shading for 3D

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#186]
The current **default** shading capabilities of Makie are not very top notch. Here is an example from a real-world setting:

```julia
function energy_dispersion_full(kx, ky; tprimeval = 0, λ=1, tval =2.8)
    a = 0.142
    f = 2cos(√3*kx*a) + 4cos(√3*kx*a/2)*cos(3ky*a/2)
    ε = λ*tval*sqrt(3 + f) -tprimeval*f
end
aa0 = √3 * 0.142
kx = range(-5/aa0, stop=5/aa0, length=100)
ky = range(-5/aa0, stop=5/aa0, length=100)
Z = energy_dispersion_full.(kx, ky')
```
```
shading = true
Makie.surface(kx, ky, Z, colormap = "viridis", shading = shading)
Makie.surface!(kx, ky, -Z, colormap = "viridis", shading = shading)

```

![image](https://user-images.githubusercontent.com/19669089/47500419-11fdae80-d863-11e8-91c2-d849c6f59706.png)

while setting `shading = false` produces

![image](https://user-images.githubusercontent.com/19669089/47500476-322d6d80-d863-11e8-9178-3fe626bc791c.png)

---

The first figure is _way_ too dark. It is so dark that it is hard to even see what is happening. On the otherside, the second figure has no shading whatsoever, which makes my puny human bran have big difficulty in understanding its 3D...

**Comment by asinghvi17** [comment]
Do you think this has been resolved?  @Datseris

**Comment by CarpeNecopinum** [comment]
Running into the same problem. For my case I'd ideally want to have the camera act like a light source itself.

I noticed that the underlying GLVisualize already contains a `light_calc` function that we could use to improve the lighting situation. However, I have no idea how to get to it from the Makie interface :neutral_face:

**Comment by ffreyer** [comment]
I think this issue has been resolved now.

> For my case I'd ideally want to have the camera act like a light source itself.

That is the default now. The plot now looks like this: (without any changes to the code)

![Screenshot from 2020-04-27 17-47-36](https://user-images.githubusercontent.com/10947937/80392279-38b10100-88af-11ea-8d75-5b2e8ea6cc43.png)

**Comment by Datseris** [comment]
Huh, odd I haven't seen notifications for this so far. Yeah the above plot looks resolved to me.

**Comment by SimonDanisch** [comment]
Also, you can finally tweak the shading with `ambient`, etc:
http://juliaplots.org/MakieReferenceImages/gallery//lighting/index.html

**Comment by SimonDanisch** [comment]
Ah damn, I broke the recording :D Will update recordings tonight -.-
