### ISSUE TITLE
Define reverse(:Symbol).

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#187]
It would be good to define (and document!!!)

`reverse(symbol) = reverse(to_colormap(symbol))`  that reverses the direction of a colormap.

**Comment by mkborregaard** [comment]
FWIW, PlotUtils supports simply adding `_r` to any color map to reverse it, e.g. `:Spectral_r`.

**Comment by SimonDanisch** [comment]
I implemented it in 162421b  as `Reverse(:viridis)` ... `_r` seems arbitrary and hard to understand for a newcomer...

**Comment by SimonDanisch** [comment]
I added the vizcon label for documentation :D

**Comment by mkborregaard** [comment]
Fair enough, just saw the slack convo.

**Comment by Datseris** [comment]
Was this documented?

**Comment by SimonDanisch** [comment]
No...

**Comment by Datseris** [comment]
Then why was it closed ? :P 

Noone can find the existence of this `reverse` unless it is documented.

**Comment by SimonDanisch** [comment]
*sigh* i guess you're right :D
