### ISSUE TITLE
stretched colorbar when aspect is adjusted

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPlots/Makie.jl#1874]
```
fig_test = Figure()
ax_test  = Axis(fig_test[1, 1], aspect=DataAspect())
hm_test = heatmap!(rand(4, 10))
Colorbar(fig_test[2, 1], hm_test, vertical=false)
fig_test
```
gives a very stretched colorbar.
(i) how can I automatically make the colorbar a reasonable size for the aspect or adjust it?
(ii) should defaults be better to make the colorbar aligned with this?
thx

![image](https://user-images.githubusercontent.com/30643894/166506822-891c000b-277e-404f-85d2-e75051ee20fd.png)

**Comment by SimonEnsemble** [comment]
found this discussion.
https://discourse.julialang.org/t/makie-jl-limiting-height-of-colorbar-to-that-of-a-nearby-equal-aspect-axis/55876/3
adjusting `height` works reasonably and not too bothersome to tune, but now when I save the fig there is a lot of awkward white space.

**Comment by asinghvi17** [comment]
One way to do it is to manually link the colorbar to the Axis's size:

```julia
fig, ax, plt = heatmap(rand(5, 10); axis = (aspect = DataAspect(),))
cb = Colorbar(fig[2, 1]; vertical = false, width = @lift Fixed($(pixelarea(ax.scene)).widths[1]))
fig
```
![iTerm2 27rRmL](https://user-images.githubusercontent.com/32143268/166516267-cab2cf8a-f7e8-4f98-a56d-e4dd4a7391b8.png)
Essentially, the @lift macro is a shorthand for Observables.lift - whenever the axis's area changes, so will the colorbar.

Now, if you want to adjust the figure's size, you can do:
```julia
julia> resize_to_layout!(fig)
(299.35938f0, 600.0f0)
```
which yields
![iTerm2 Wd79SI](https://user-images.githubusercontent.com/32143268/166516349-6505b7cd-6d6b-4fbd-ba1f-e75178bc0c0c.png)

This should probably be a tutorial in the docs somewhere...let me know if it makes sense!

**Comment by SimonEnsemble** [comment]
thx so much!
yes, a tutorial in the docs on this would be super helpful. :smile: 
this works perfectly for one of my plots, but the other, it's just a single row, and it puts the colorbar far from the main plot. how can I close this gap?
the extreme example :arrow_down: 
```
fig, ax, plt = heatmap(rand(10, 1); axis = (aspect = DataAspect(),))
cb = Colorbar(fig[2, 1]; vertical = false, width = @lift Fixed($(pixelarea(ax.scene)).widths[1]))
fig
```

![image](https://user-images.githubusercontent.com/30643894/166519043-e367fb8e-b303-4fa7-b181-41d211835de7.png)

**Comment by asinghvi17** [comment]
Ah..that's where we start running into what @jkrumbiegel said in the Discourse post you linked.  Basically, the "cell" in the grid layout still takes up all of the space of a normal Axis, not the current one with DataAspect.  So what you basically want to do here is force the row which holds the Axis to become smaller.  A crude way to do this is:
```julia
rowsize!(fig, 1, Fixed(pixelarea(ax.scene)[].widths[2]))
cb.flipaxis = false
resize_to_layout!(fig)
```
![iTerm2 g5uBiK](https://user-images.githubusercontent.com/32143268/166521340-08278101-e1b8-4859-bd83-2186a2da9d37.png)

**Comment by SimonEnsemble** [comment]
beyond my understanding of why this works, but thank you, I am in business! :bow: 
![image](https://user-images.githubusercontent.com/30643894/166523247-e053e002-0a79-4da1-ba16-e454cb1f3399.png)

**Comment by jkrumbiegel** [comment]
You could try if this tutorial helps with your understanding https://makie.juliaplots.org/stable/tutorials/aspect-tutorial/
