### ISSUE TITLE
slider behavior - changing value externally

### ISSUE THREAD

**Issue by rseydam** [JuliaPlots/Makie.jl#1879]
I am using a slider in my application. I realized that when changing the value of the slider the position of the slider is not adjusted automatically. I thought that maybe slider value and selected_index could be made an ObservablePair to achieve this. Would that be possible or would this be too complicated or break the slider? Maybe someone knows how that could be implemented. Thanks for the feedback!

**Comment by asinghvi17** [comment]
You can use `set_close_to!(slider::Slider, value)` to set the Slider's position and value to the element in its `range` closest to `value`.

**Comment by asinghvi17** [comment]
You can use `set_close_to!(slider::Slider, value)` to set the Slider's position and value to the element in its `range` closest to `value`.

**Comment by rseydam** [comment]
Thanks for the suggestion. It works well using `set_close_to!(slider::Slider, value)`. 
Here is a working example:
```
using Observables
using GLMakie

fig = Figure()
sl = Slider(fig;width=1000)
x = Observable(1.0)

Observables.ObservablePair(x, sl.value; f = identity, g = identity)
on(x) do x
    GLMakie.set_close_to!(sl,x)
end

fig
```
