### ISSUE TITLE
Highlight of some markers in 3D

### ISSUE THREAD

**Issue by edljk** [JuliaPlots/Makie.jl#1894]
The call 

```julia
scatter(rand(100, 3), markersize = 100, color = :blue)
```
produces the following plot.

![p3D](https://user-images.githubusercontent.com/14992507/167246059-ada56873-dbb1-4a75-a71e-14dd9f1eb9c4.png)

Is there a way to suppress the white arc of circles which highlight some (!) markers?
I was not able to identify a relevant attribute. This does not happen in 2D.

**Comment by ffreyer** [comment]
This is an anti-aliasing/order artifact. You can circumvent it with `scatter(rand(100, 3), markersize = 100, color = :blue, transparency = true)`, but that will let other things with `transparency = true` shine through (e.g. grid lines)

**Comment by edljk** [comment]
OK, thanks!
