### ISSUE TITLE
Incompatible to_colormap from v0.16 to v0.17

### ISSUE THREAD

**Issue by henry2004y** [JuliaPlots/Makie.jl#1900]
Hi,

In Makie v0.16.6 this is allowed (not tested, but based on my memory and previous codes)

```
colors = to_colormap(:viridis, 101)
```

However this is no longer the case in v0.17

```
julia> to_colormap(:viridis, 20)
ERROR: MethodError: no method matching to_colormap(::Symbol, ::Int64)
Closest candidates are:
  to_colormap(::Union{String, Symbol}) at ~/.julia/packages/Makie/umL6V/src/conversions.jl:1039
Stacktrace:
 [1] top-level scope
   @ REPL[17]:1
```

even though the document is not modified https://makie.juliaplots.org/dev/api/index.html#convert_attribute, or https://github.com/JuliaPlots/Makie.jl/blob/4e19bef19d9cf16ca78b329eafbfe07cd55c153e/src/conversions.jl#L727.

So what is the new way of specifying the number of color points? By default is it 256?

**Comment by henry2004y** [comment]
This is what I had previously

```julia
# Makie v.0.16
cmap = :turbo
colors = to_colormap(cmap, 101)
alphas = LinRange(0, 1, 101)
cmap_alpha = RGBAf.(colors, alphas)
```

The recent new changes seems to combine RGB with opacity together?

**Comment by SimonDanisch** [comment]
Ah yeah, not erveryone wants categorical colors. I added `Makie.resample_cmap(:turbo, 10; alpha=(0, 1))`, that does what you want

**Comment by henry2004y** [comment]
Great! I'll keep up with the cool new features. Thanks!
