### ISSUE TITLE
Menu appears in bottom left corner

### ISSUE THREAD

**Issue by tecosaur** [JuliaPlots/Makie.jl#1907]
Hi,

With GLMakie 0.6.0 / Makie 0.17.0 (and also having tried `HEAD`), I'm seeing Menu text/dropdowns all appear (overlapping) in the bottom right corner.

![image](https://user-images.githubusercontent.com/20903656/167753947-2ea6a405-586b-432c-8082-17a4f9596f22.png)

I've got no idea what's going on here, other than that this seems to be occurring consistently.

**Comment by jkrumbiegel** [comment]
Hm I thought I had fixed that on master a while ago. Blocks like Menu have a different Scene structure now and this changed some coordinate calculations for where things should be. @SimonDanisch did anything in that regard change recently? I definitely tested all Blocks to work with GLMakie before I merged that PR.

**Comment by SimonDanisch** [comment]
Oh, I may have incorrectly resolved some merge conflicts, e.g. here:
https://github.com/JuliaPlots/Makie.jl/pull/1818/files#diff-d8b9416e400a74c92f67c1c5d3b0685bc4a39b153f4b66b7890311ab1b38421e
![image](https://user-images.githubusercontent.com/1010467/167815458-320fc45d-be35-40ef-9574-71dfe356a361.png)

I made a PR, and as far as I can tell, things work again!
