### ISSUE TITLE
Legend dash and dashdot

### ISSUE THREAD

**Issue by Lightup1** [JuliaPlots/Makie.jl#1908]
dash and dashdot lines have same legend style.
A bug here.
```
lines!(ax2,x,Va2,linestyle=:dash,linewidth =3,label="Objective")
lines!(ax2,x,Vmat1*EVa2_raw,linestyle=:dashdot,linewidth =3,label="Result")
```
![image](https://user-images.githubusercontent.com/32999017/167759633-bc3d4128-04e2-4644-8052-816fd3e77156.png)

**Comment by jkrumbiegel** [comment]
I think the `patchsize` of the legend is just not wide enough to see the difference in pattern, it cuts off right at the dot. You can set it to something wider than the default.

**Comment by jkrumbiegel** [comment]
```julia
f = Figure()
ax = Axis(f[1, 1])
lines!(ax, 1..10, cos, linestyle=:dash,linewidth =3,label="Objective")
lines!(ax, 1..10, sin, linestyle=:dashdot,linewidth =3,label="Result")
axislegend(ax, patchsize = (60, 30))
f
```

![image](https://user-images.githubusercontent.com/22495855/177210442-7d94f39b-71cf-4978-ba3a-6037d51de0bd.png)
