### ISSUE TITLE
QOL: implement `set_xlabel` or `xlabel`

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#191]
A quality of life improvement:

define `set_xlabel!([axis,] label)` which sets the label of the current (or given) axis. Inspired from pyplot.

at the moment one has to do: 
```
axis = scene[Axis] # get the axis object from the scene
axis[:names][:axisnames] = ("x", "y = cos(x)")
```
which is a bit too much. 

Notice: I don't immediately see how the above expands to a scene with multiple subplots! But for having subplots, each subplot is a different axis.

**Comment by asinghvi17** [comment]
Could assert that `scene.plots` needs an Axis, and if it doesn't exist, error out with a message.
