### ISSUE TITLE
vspan! and hspan! is not defined

### ISSUE THREAD

**Issue by jaehongpark-neuro** [JuliaPlots/Makie.jl#1912]
Hi, 

For some reasons, Julia says vspan! and hspan! are not defined.

I once use these functions while ago but not any more.
Are these functions deprecated??

I use GLMakie (GLMakie v0.4.4) or CairoMakie, and all other functions working well, so I was wondering what's missing here.

Thanks,
Jaehong

**Comment by SimonDanisch** [comment]
vspan!/hspan! got added in https://github.com/JuliaPlots/Makie.jl/releases/tag/v0.15.2, so you need at least `0.4.6` ...Note that GLMakie 0.6 is the most recent version by now (although you may prefer to upgrade to 0.5.x instead for now).
