### ISSUE TITLE
Can we integrate a descriptive method error in convert_arguments?

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Makie.jl#1938]
Earlier, `convert_arguments` used to simply MethodError if the signature for the user's input could not be found.  This did sort of help at least see what had gone wrong and what alternatives existed.

I would like to add it back if possible, but don't know enough about how MethodErrors are raised or the closest applicable methods are found to do it.  If anyone else does, please comment here - I would be happy to take it forward in some time.

**Comment by SimonDanisch** [comment]
I did that in https://github.com/JuliaPlots/Makie.jl/pull/1810 ;)

**Comment by asinghvi17** [comment]
Ahh, I haven't update since then. Cool!
