### ISSUE TITLE
GLMakie fails to run on a headless system on Ubuntu 22.04

### ISSUE THREAD

**Issue by Octogonapus** [JuliaPlots/Makie.jl#1953]
I am creating this issue so we can track how to get GLMakie to run on Ubuntu 22.04 in headless mode. Currently running into this error when using the setup that worked on 20.04:
```
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
┌ Warning:     GLFW couldn't create an OpenGL window.
│     This likely means, you don't have an OpenGL capable Graphic Card,
│     or you don't have an OpenGL 3.3 capable video driver installed.
│     Have a look at the troubleshooting section in the GLMakie readme:
│     https://github.com/JuliaPlots/Makie.jl/tree/master/GLMakie#troubleshooting-opengl.
└ @ GLMakie ~/.julia/packages/GLMakie/TfSB1/src/screen.jl:339
ERROR: LoadError: GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: GLXBadFBConfig
```

That is with these dependencies installed: `build-essential cmake xorg-dev mesa-utils xvfb libgl1 freeglut3-dev` from following [this guide](https://nextjournal.com/sdanisch/GLMakie-nogpu).
Julia v1.7.2. Makie v0.16.6. GLMakie v0.5.5. Ubuntu 22.04.

**Comment by t-bltg** [comment]
Thanks, I'm trying to fix this on my side too, also in headless mode on 22.04.

**Comment by Octogonapus** [comment]
With the dependency `libgl1-mesa-dri` installed, I see `swrast_dri.so` inside `/usr/lib/x86_64-linux-gnu/dri/`, so I don't know why that search doesn't find it. Maybe need to do something like `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/dri/`

**Comment by Octogonapus** [comment]
@t-bltg Sounds like this has been reduced to this old issue then: https://github.com/JuliaGL/GLFW.jl/issues/198

**Comment by t-bltg** [comment]
Ha, good catch, this works:
```bash
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 julia -e 'using GLFW; GLFW.Window()'
```
Trying Makie now ...

**Comment by Octogonapus** [comment]
I would consider this closed, then. This is just https://github.com/JuliaGL/GLFW.jl/issues/198 with different wrapping.

**Comment by t-bltg** [comment]
Xref https://github.com/JuliaLang/julia/issues/34276.
