### ISSUE TITLE
Image contrast changed in v0.16.4

### ISSUE THREAD

**Issue by Octogonapus** [JuliaPlots/Makie.jl#1969]
The contrast of an `image!` plot changed in Makie v0.16.4. This also happens in v0.17. Using Julia v1.7.

MWE
```julia
import Pkg
Pkg.activate(;temp=true)
Pkg.add(name="Makie",version=ENV["MAKIE_VERSION"])
Pkg.pin(name="Makie",version=ENV["MAKIE_VERSION"])
Pkg.add(name="GLMakie")
Pkg.add(name="FileIO")

using GLMakie, FileIO

f = Figure(resolution=(100,100))
ax = Axis(f)
img = reshape([UInt8(i+j) for j in 1:10 for i in 1:40], (40,10))
image!(ax, img, interpolate = false, colorrange = (0, 255))
FileIO.save(joinpath(@__DIR__, "$(ENV["MAKIE_VERSION"])_img.png"), f)
```

Makie v0.16.3 (correct):
![0 16 3_img](https://user-images.githubusercontent.com/4064722/169865286-90f64b66-b4a5-44c9-8ac2-153e49302a9a.png)

Makie v0.16.4 (incorrect; image is different):
![0 16 4_img](https://user-images.githubusercontent.com/4064722/169865293-db897b5e-fd25-459d-9cc2-b6125db16e4d.png)

Makie v0.17.3 (also incorrect):
![0 17 3_img](https://user-images.githubusercontent.com/4064722/169865301-159ebe42-b3bd-4274-87a6-d623761013d7.png)

**Comment by IanButterworth** [comment]
Seems likely that the regression was in https://github.com/JuliaPlots/Makie.jl/pull/1654

Any idea @SimonDanisch? This is pinning us to v0.16.3

**Comment by SimonDanisch** [comment]
I can take a look tomorrow!
