### ISSUE TITLE
Search funcition broken on Makie docs (returns 0 results)

### ISSUE THREAD

**Issue by nickkeepfer** [JuliaPlots/Makie.jl#1971]
It seems the search function for the official Makie [docs](https://makie.juliaplots.org/) has broken

A search for any term returns zero results.

Navigation seems to be unaffected.

**Comment by kimlaberinto** [comment]
Yup can confirm this experience of not returning anything for me as well.

For example: a search for Axis: https://makie.juliaplots.org/stable/search/index.html?q=Axis

**Comment by aramirezreyes** [comment]
Can confirm

**Comment by ederag** [comment]
Duplicate of #1965 ?

**Comment by SimonDanisch** [comment]
Yes!
