### ISSUE TITLE
accessing node bug (or, How to See the Matrix)

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#198]
MWE

```
r1 = slider(0:0.001:4, raw = true, camera=campixel!, start = 0.0)
r2 = slider(0:0.001:4, raw = true, camera=campixel!, start = 4)
n1 = 500; n2 = 1000; a = zeros(n2, n1)
positions = Vector{Point2f0}(undef, n1 * n2)
r1node, r2node = r1[end][:value], r2[end][:value];
```
If one SKIPS the `;` of the last line and run it as an individual line in Atom, it never returns.

Similarly, if one runs this line on the REPL, one can see the Matrix. An infinite, never ending wall of text that is printed!

**Comment by SimonDanisch** [comment]
huh, so this is an Observable.jl problem...
