### ISSUE TITLE
Lines ignore theme color

### ISSUE THREAD

**Issue by kimauth** [JuliaPlots/Makie.jl#1984]
I was expecting that
```julia

xs = rand(10)
ys = rand(10)

mytheme = Theme(
    Lines = (
        color = :black,
        linewidth = 5,
        linestyle = :dash,
        ),
)

with_theme(mytheme) do 
    f, ax, p = lines(xs, ys)
end
```
would give the same figure as
```julia
f, ax, p = lines(rand(10), rand(10); color=:black, linewidth=5, linestyle=:dash)
```
but the first version seems to ignore the color attribute (while using the other ones). This is on Makie `0.17.3`. 

With `mytheme`:
![with_theme](https://user-images.githubusercontent.com/54391668/170530832-abb5a50f-cbb2-4ea8-893f-0a4b759bda86.png)

With keyword arguments:
![with_kwargs](https://user-images.githubusercontent.com/54391668/170531318-c592831e-78fd-4f2f-84b4-0a1da071f1ba.png)

**Comment by jkrumbiegel** [comment]
This is because the blue color comes from the cycler, not from the plot default.

**Comment by kimauth** [comment]
Ah, thank you!

For anyone who runs into this in the future: The cycler can be turned off by `cycle=nothing` and then the results are indeed identical.

```julia
mytheme = Theme(
    Lines = (
        color = :black,
        linewidth = 5,
        linestyle = :dash,
        cycle = nothing,
        ),
)

with_theme(mytheme) do 
    f, ax, p = lines(xs, ys)
end
```
