### ISSUE TITLE
Bad error when not passing named tuple

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPlots/Makie.jl#1988]
The error raised when forgetting the comma needed to make a named tuple is must unfelpful:
```
julia> plot(1:10, 1:10, figure=(title="Test"))
ERROR: BoundsError: attempt to access Char at index [2]
Stacktrace:
 [1] indexed_iterate(I::Char, i::Int64, state::Bool)
   @ Base .\tuple.jl:98
 [2] merge(a::NamedTuple{(), Tuple{}}, itr::String)
   @ Base .\namedtuple.jl:292
 [3] plot(::Type{Any}, ::UnitRange{Int64}, ::Vararg{UnitRange{Int64}}; axis::NamedTuple{(), Tuple{}}, figure::String, kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Makie C:\Users\Dennis Bal\.julia\packages\Makie\fEZv2\src\figureplotting.jl:16
 [4] #plot#13
   @ C:\Users\Dennis Bal\.julia\packages\MakieCore\oBlaS\src\recipes.jl:33 [inlined]
 [5] top-level scope
   @ REPL[15]:1
```

While this works
```
julia> plot(1:10, 1:10, figure=(title="Test",))
```

The same problem exists when using AlgebraOfGraphics's `draw` function, but perhaps it is a downstring issue from `Makie`, so I am raising it here first.

Can this be remedied by some sort of type-checking, or something else?

**Comment by lazarusA** [comment]
I don't see this as an issue and if I'm not mistaken is by design. I try to follow this syntax once I start using keyword arguments, no commas.

```
plot(1:10, 1:10; axis=(; title="Test"))
```

ok, maybe the error message is a little bit cryptic.

**Comment by asinghvi17** [comment]
I think it's definitely possible in the initial stages.  Perhaps we could check that a certain set of keys should be initialized as named tuples?

**Comment by jkrumbiegel** [comment]
Yeah this could be checked to some degree, Dicts etc should also work though, which makes it a bit trickier.
