### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by Salehman** [JuliaPlots/Makie.jl#199]
How would I animate a series of images?

I would like to animate a series of images and record them. I have 3D matrix (shot[n,m,z])
z is the frame number. At each frame, I want to plot shot[n,m].

**Comment by SimonDanisch** [comment]
In the gallery, you can select the `record` tag button, to filter for all examples recording frames:
https://simondanisch.github.io/ReferenceImages/gallery/index.html
This gallery is also integrated into the new `lastest docs` : http://juliaplots.org/MakieGallery.jl/stable/
