### ISSUE TITLE
Documentation search returns no results on all terms

### ISSUE THREAD

**Issue by tobydriscoll** [JuliaPlots/Makie.jl#1992]
Every search comes up empty. For example, [axis](https://makie.juliaplots.org/stable/search/index.html?q=axis), [color](https://makie.juliaplots.org/stable/search/index.html?q=color).

I seem to recall running into this problem myself with jupyter-book. That was a bug in a Sphinx version.

**Comment by SimonDanisch** [comment]
Duplicate of https://github.com/JuliaPlots/Makie.jl/issues/1965
