### ISSUE TITLE
animation example doesn't work

### ISSUE THREAD

**Issue by rambunctiousapple** [JuliaPlots/Makie.jl#1996]
This example in the [documentation](https://makie.juliaplots.org/v0.15.1/documentation/animation/index.html#:~:text=Animations.%20With%20Makie%20it%20is%20easy%20to%20create,animation%20you%20need%20to%20use%20the%20record%20function.) doesn't work:

```
using GLMakie
using Makie.Colors

fig, ax, lineplot = lines(0..10, sin; linewidth=10)

# animation settings
nframes = 30
framerate = 30
hue_iterator = range(0, 360, length=nframes)

record(fig, joinpath(@OUTPUT, "color_animation.mp4"), hue_iterator;
        framerate = framerate) do hue
    lineplot.color = HSV(hue, 1, 0.75)
end
```

gives this error:
```
ERROR: UndefVarError: @OUTPUT not defined
```

```
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
Environment:
  JULIA_EDITOR = code.cmd
  JULIA_NUM_THREADS = 8
```
(App) pkg> st
     Project App v0.1.0
      Status `C:\Users\seatt\OneDrive\Documents\github\App\Project.toml`
  [6e4b80f9] BenchmarkTools v1.3.1
  [c4b4474d] Bokeh v0.3.0
  [a8cc5b0e] Crayons v4.1.1
  [7da242da] Enzyme v0.9.6
  [e9467ef8] GLMakie v0.6.3
  [54eb57ff] InteractiveCodeSearch v0.4.2
  [c3a54625] JET v0.5.14
  [ee78f7c6] Makie v0.17.3
  [5fb14364] OhMyREPL v0.5.12
  [9b87118b] PackageCompiler v2.0.5
  [14b8a8f1] PkgTemplates v0.7.28
  [efd6af41] ProfileCanvas v0.1.0
  [295af30f] Revise v3.3.3
  [1986cc42] Unitful v1.11.0
  [8dfed614] Test

(App) pkg> 
```

**Comment by lazarusA** [comment]
you need to change `@OUTPUT` by your local directory. Here `@OUTPUT` is a macro used within the documentation.

**Comment by asinghvi17** [comment]
Is this an error in the doc generation?  I recall this not being there previously...

**Comment by lazarusA** [comment]
the docs are ok. Is just that is not clear that the end users should change this macro for their local directory.

**Comment by jkrumbiegel** [comment]
It's just the 0.15.1 version of the docs we're looking at here, which didn't have that point fixed yet.
