### ISSUE TITLE
Font / Text error 

### ISSUE THREAD

**Issue by zsoerenm** [JuliaPlots/Makie.jl#2003]
After some time, I've used GLMakie again.
I tried the following:
```julia
using GLMakie
positions = Observable(rand(Point2f, 10))
fig, ax, p = scatter(positions)
```
However, it seems that there is an error with the font.
![image](https://user-images.githubusercontent.com/375486/171153255-8f64c9f0-17fe-4f0b-8d58-09d326a3116b.png)
Each number is displayed as a box (see figure).
How can I regenerate the font? There is no error thrown.

**Comment by SimonDanisch** [comment]
Can you try `rm(Makie.get_cache_path())` ?

**Comment by zsoerenm** [comment]
Yes, this regenerated the font:
```julia
julia> fig, ax, p = scatter(positions)
[ Info: Makie is caching fonts, this may take a while. Needed only on first run!
```
However, the figure is still outputted with boxes instead of numbers (like in the figure above).

**Comment by jkrumbiegel** [comment]
Can you try any other previously unused font? Just to check that it's not font-related

**Comment by ffreyer** [comment]
Checking what `image(Makie.get_texture_atlas().data)` looks like might also be helpful

**Comment by ffreyer** [comment]
The entries in the texture atlas look pretty weird. Does this generate a normal looking "a"?

```julia
using Makie.FreeTypeAbstraction
image(renderface(findfont("Noto"), 'a', 100)[1][:, end:-1:1])
```

If not maybe rebuilding FreeTypeAbstraction helps?

**Comment by ffreyer** [comment]
But `text("a", font = "Noto")` renders a box too, right? Can you show me the texture atlas again after that?

Does

```julia
img = renderface(findfont("Noto"), 'a', 100)[1][:, end:-1:1]
sdf = Makie.sdistancefield(img, 4, 16)
image(sdf)
```

look like a blurry "a"?

**Comment by zsoerenm** [comment]
Yes, `text("a", font = "Noto")` renders a box in the center of the scene.

Texture atlas again after that:
![grafik](https://user-images.githubusercontent.com/375486/171178082-1758d79a-e83f-40b6-8a88-6b0423491868.png)

```julia
img = renderface(findfont("Noto"), 'a', 100)[1][:, end:-1:1]
sdf = Makie.sdistancefield(img, 4, 16)
image(sdf)
```
![grafik](https://user-images.githubusercontent.com/375486/171177524-9089338e-4e01-44d0-a189-dc4c8b897626.png)

**Comment by SimonDanisch** [comment]
Wow, what platform and Julia version is this? ` Makie.sdistancefield(img, 4, 16)` is pure julia code, and seems to be the culprit here...

**Comment by ffreyer** [comment]
For reference - this is what `image(sdf)` should look like:

![Screenshot from 2022-05-31 14-59-39](https://user-images.githubusercontent.com/10947937/171179312-768af356-0cf0-4fc1-9dbb-ecdb0127bf66.png)

The function is here:
https://github.com/JuliaPlots/Makie.jl/blob/c6931d0c08a929bc1449c8e4dc38a8cf7a396730/src/utilities/texture_atlas.jl#L238-L256


Maybe you can play around with it a bit to see what goes wrong? `in_or_out` should be a sharp "a" (i.e. with hard edges instead of antialiased ones). `sdf()` is from https://github.com/JuliaGraphics/SignedDistanceFields.jl I believe. The bug might also be there

**Comment by zsoerenm** [comment]
```julia
image(in_or_out)
```
![grafik](https://user-images.githubusercontent.com/375486/171185903-e14065bc-bf3d-47fc-b422-e5b21b955a4f.png)
```julia
image(Makie.sdf(in_or_out, xres, yres) ./ downsample)
```
![grafik](https://user-images.githubusercontent.com/375486/171186795-ebaed57f-088e-4868-ad7c-0675496a1dd9.png)
```julia
julia> maximum(Makie.sdf(in_or_out, xres, yres) ./ downsample)
24.218729870931817
```
```julia
image(Float16.(Makie.sdf(in_or_out, xres, yres) ./ downsample))
```
![grafik](https://user-images.githubusercontent.com/375486/171187159-92f8420b-84bc-43a1-9b5d-aede02b70b04.png)

**Comment by zsoerenm** [comment]
okay, the culprit does seem to be the LD_PRELOAD. I had to start Julia with the following, because of this error: https://github.com/JuliaGL/GLFW.jl/issues/198 :
```bash
LD_PRELOAD=/usr/lib64/libstdc++.so.6 /bin/julia
```
With the PRELOAD Float16 return garbage.

**Comment by zsoerenm** [comment]
Good news:
I upgraded to Julia v1.8.0beta3 and the error is gone. The LD_PRELOAD is, however, still necessary.
![grafik](https://user-images.githubusercontent.com/375486/171214896-1cb8c7bf-0c70-4a59-8ea8-78d3b8148107.png)
Thanks for all your help!
