### ISSUE TITLE
Mac's retina screen displays

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Makie.jl#202]
Makie doesn't hook into the "pixel doubling" on Mac's retina displays (and I guess other high-resolution computer displays). So you get really small plots:

<img width="650" alt="skaermbillede 2018-10-30 kl 17 29 49" src="https://user-images.githubusercontent.com/8429802/47733932-9b4d2080-dc69-11e8-821d-a3b4d04fc4bb.png">

**Comment by SimonDanisch** [comment]
Is that still an issue!?

**Comment by mkborregaard** [comment]
No, at least in Juno it now takes the size of the plot pane. Default dot size is quite insane but that is probably the other issue:
![skaermbillede 2019-02-13 kl 16 04 13](https://user-images.githubusercontent.com/8429802/52721080-2ea42a80-2fa9-11e9-93b6-810aa8fae6ca.png)

**Comment by SimonDanisch** [comment]
thanks!
