### ISSUE TITLE
Inappropriate behavior of text! function with space=:data argument.

### ISSUE THREAD

**Issue by danbulnet** [JuliaPlots/Makie.jl#2021]
Hello,

After update from v0.5.5 to v0.6.3 `text!` function with `space=:data` argument and `3dcam` set on the scene doesn't work as expected.

That's how it looks like in v0.5.5 (expected):
<img width="784" alt="image" src="https://user-images.githubusercontent.com/65168475/172010809-49936525-1cb8-403b-908a-fa4c28b8fecd.png">

... and after update to v0.6.3 (unwanted):
<img width="725" alt="image" src="https://user-images.githubusercontent.com/65168475/172011004-1a67cf09-6c08-4ca5-98a8-a258b40486ee.png">

Additionally, it seems that in docs something is wrong with this example:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/65168475/172011102-702a8c2f-e4a1-4a18-a410-2651219d354a.png">

Thanks for any help.

**Comment by ffreyer** [comment]
That attribute effectively got renamed to `markerspace`. `space` now handles how the `position` argument gets transformed instead.

**Comment by danbulnet** [comment]
It works :) Thanks a lot for your help.

**Comment by ffreyer** [comment]
The example still needs fixing https://makie.juliaplots.org/dev/examples/plotting_functions/text/#data_space_text
