### ISSUE TITLE
How can I cycle trough different marker symbols?

### ISSUE THREAD

**Issue by jbrea** [JuliaPlots/Makie.jl#2032]
I tried (with Makie v0.17.3 and CairoMakie v0.8.3 or GLMakie v0.6.3)
```julia
set_theme!(palette = (color = [:black], marker = [:circle, :rect, :utriangle, :dtriangle],))
scatter([1], [1])
scatter!([2], [2])
```
which produced at position (2, 2) also a circle marker.
Based on the [docs](https://makie.juliaplots.org/dev/documentation/theming/index.html#covarying_cycles) I expected to get something similar to
```julia
scatter([1], [1], marker = :circle)
scatter!([2], [2], marker = :rect)
```

**Comment by jkrumbiegel** [comment]
by default Scatter doesn't cycle markers, only colors. So in the theme you need to have `Scatter = (cycle = [:color, :marker],)` for example where it just says `:color` now.

**Comment by jkrumbiegel** [comment]
I see now that this is not actually explained in https://makie.juliaplots.org/v0.17.3/documentation/theming/index.html#cycles
