### ISSUE TITLE
Error while rendering a heatmap with RGB z-matrix

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Makie.jl#2033]
If I replace GLMakie by CairoMakie, the plot is rendered without problems:

```julia
julia> using Meshes, MeshViz

julia> import GLMakie as Mke

julia> g = CartesianGrid(10, 10)
10×10 CartesianGrid{2,Float64}
  minimum: Point(0.0, 0.0)
  maximum: Point(10.0, 10.0)
  spacing: (1.0, 1.0)

julia> viz(g, color = 1:100)

┌ Error: Error while rendering!
│   exception =
│    MethodError: no method matching gluniform(::Int32, ::Nothing)
│    Closest candidates are:
│      gluniform(::Integer, ::Union{ColorTypes.Colorant, StaticArrays.SMatrix, StaticArrays.StaticVector}) at ~/.julia/packages/GLMakie/vwLnZ/src/GLAbstraction/GLUniforms.jl:36
│      gluniform(::Integer, ::Enum) at ~/.julia/packages/GLMakie/vwLnZ/src/GLAbstraction/GLUniforms.jl:71
│      gluniform(::Integer, ::Observables.Observable{T}) where T at ~/.julia/packages/GLMakie/vwLnZ/src/GLAbstraction/GLUniforms.jl:73
│      ...
└ @ GLMakie ~/.julia/packages/GLMakie/vwLnZ/src/rendering.jl:242
```

**Comment by SimonDanisch** [comment]
Can you extract the underlying plot call, so that we can look into this without diving into the MeshViz code base?

**Comment by juliohm** [comment]
The ultimate plot call is this one:

https://github.com/JuliaGeometry/MeshViz.jl/blob/9f149a22a5c1283a327e55d09d0c35ba5e9279c8/src/cartesiangrid.jl#L34

**Comment by jkrumbiegel** [comment]
I think a heatmap call with arguments that cause this error would be the easiest.

**Comment by juliohm** [comment]
Got one:

```julia
heatmap(0.5:1.0:9.5, 0.5:1.0:9.5, rand(RGB, 10, 10))
```

**Comment by SimonDanisch** [comment]
Ah, I guess I didn't plan to support heatmap for Matrix{RGB} (image should be used for that), but I guess we ended up implementing that in CairoMakie.
Of course either there should be good error pointing to image, or we should implement it in all backends.

**Comment by juliohm** [comment]
Just a comment that it used to work fine in all backends, including GLMakie.

The second option of always supporting this signature with RGB arrays in all primitive Makie functions is much more useful, specially if people have other means to convert numbers to colors, like we do in MeshViz.jl.

**Comment by asinghvi17** [comment]
Huh, that is definitely odd.  For now, if you need a quick fix, you might try:
```julia
heatmap(0.5:1.0:9.5, 0.5:1.0:9.5, zeros(10, 10); color = rand(RGB, 10, 10))
```

**Comment by juliohm** [comment]
@asinghvi17 unfortunately the workaround doesn't work:

![image](https://user-images.githubusercontent.com/3345261/172846864-c60bad93-39b9-4bc4-b215-63acd73b88d4.png)
