### ISSUE TITLE
Contourf extendhigh/low is broken

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/Makie.jl#2042]
@ffreyer this commit broke extendhigh/low for `contourf` https://github.com/JuliaPlots/Makie.jl/commit/8fcf6ced671767f7d4fd259f0383d64e05058f44

Can we bring that functionality back without breaking inspector?

**Comment by ffreyer** [comment]
This is just manual handling fo low/highclip right? We should probably implement implement that in the backends

**Comment by jkrumbiegel** [comment]
Yes you mean via colormap lookup right? So that the default colormap handling includes lowclip highclip?

**Comment by ffreyer** [comment]
Yes. The mesh shaders in GLMakie and WGLMakie should both be able to handle that, so this should just need some corrections in Makie and maybe CairoMakie
