### ISSUE TITLE
resize_to_layout! not defined

### ISSUE THREAD

**Issue by DanielVandH** [JuliaPlots/Makie.jl#2072]
When I use the following:
```
julia> using CairoMakie;
julia> fig = Figure(); resize_to_layout!(fig)
```
I get the following error:
```
ERROR: UndefVarError: resize_to_layout! not defined
Stacktrace:
 [1] top-level scope
   @ REPL[209]:1
```
These are my package versions.
```
(@v1.7) pkg> st
      Status `C:\Users\licer\.julia\environments\v1.7\Project.toml`
  [13f3f980] CairoMakie v0.8.6 `https://github.com/JuliaPlots/Makie.jl.git:CairoMakie#master`
  [ee78f7c6] Makie v0.17.6 `https://github.com/JuliaPlots/Makie.jl.git#master`
```
Am I doing something wrong here? 

Looking into the code on this GitHub shows that this function should exist, but when I use `@edit Figure()` to see figures.jl I don't see the function. 

Actually, using `@edit Figure()` like this leads to a directory starting with `NL7Xw`, but I can click into a `xVGV7` directory which does have the function. I assume these are commit versions(?), but shouldn't using the master version give me this latest directory?

**Comment by fatteneder** [comment]
Indeed, this seems to be related to your global environment, since I don't see this problem on master.

Try removing both packages and then only adding `CairoMakie` again, this should be enough.

**Comment by DanielVandH** [comment]
Yes, removing everything showed that it is actually related to a separate package (ExactPredicates.jl) downgrading my Makie version for whatever reason... thanks.
