### ISSUE TITLE
Legend colors with theme ggplot2

### ISSUE THREAD

**Issue by hendri54** [JuliaPlots/Makie.jl#2082]
The [example line graph](https://makie.juliaplots.org/v0.17.7/documentation/theming/predefined_themes/#theme_ggplot2) in the documentation shows the legend colors as grey boxes for theme ggplot2 only.
In an example plot that I created, even setting the legend colors manually does not fix the legend colors in the plot. Sample code for this:

```
using CairoMakie, ColorSchemes;

set_theme!(theme_ggplot2());
f = Figure()
labelV = ["lbl $j" for j = 1 : 3];
n = length(labelV);
elements = [PolyElement(color = ColorSchemes.corkO[16 * i]) for i in 1:n];
# To verify that RGB values differ across entries
@show elements
Legend(f[1,1], elements, labelV);
f
```

results in:

![image](https://user-images.githubusercontent.com/10394718/174811553-0c713519-a60d-4588-8bbc-e3be6c85ad48.png)

The same with `theme_minimal()` works as expected:

![image](https://user-images.githubusercontent.com/10394718/174811844-3fa30b5a-920f-400a-99c3-fc96215dfdae.png)

**Comment by jkrumbiegel** [comment]
Ah must be wrong drawing order, in all but the ggplot themes the patch backgrounds are transparent

**Comment by hendri54** [comment]
Thank you!
