### ISSUE TITLE
Broken documentation example: pulsing marker under Julia 1

### ISSUE THREAD

**Issue by MaximeRivest** [JuliaPlots/Makie.jl#209]
Hello,

I am a long time R user and trying to move to Julia. I am trying out Makie. I had a hard time making the examples that are in the docs work. This one in particular: http://makie.juliaplots.org/v1.0.0/examples-scatter.html#pulsing-marker-1

Currently, this is the code:

```Julia
using Makie

N = 100
scene = scatter([0], [0], marker = '❤', markersize = 0.5, color = :red, raw = true)
s = scene[end] # last plot in scene
record(scene, "./docs/media/pulsing_marker.mp4", linspace(0, 10pi, N)) do i
    s[:markersize] = (cos(i) + 1) / 4 + 0.2
end
```

I had to change it to this:

```Julia
using Makie

N = 100
scene = scatter([0], [0], marker = '♥', markersize = 0.5, color = :red, raw = true)
s = scene[end] # last plot in scene
#Change the path to your preferred location.
record(scene, "CHOOSE_YOUR_PATH.mp4", 0:N:10pi) do i
    s[:markersize] = (cos(i) + 1) / 4 + 0.2
end 
```

Basically, I change `linspace` to `0:N:10pi` (note: I tried `range` but couldn't make it work I have a method error, I didn't figure out why). But this is a known issue. What I don't think is known is the problem with the path name. The current path didn't work. Afterward, It seemed obvious that I have to change the path but to a new comer, like me, it was hard to spot this problem. So, I recommend changing the path to "CHOOSE_YOUR_PATH.mp4" and maybe adding a comment on top of the function.

I would have liked to send a pull request to make it easier for the Makie developer(s) to introduce the change but I couldn't find the code for this section. 

If you let me where it is I could make a pull request for the next issue I encounter in the docs. I have seen a missing word and couldn't make other examples work. So, If I find how to fix it, I would gladly let you know.

**Comment by mschauer** [comment]
Check https://github.com/JuliaPlots/Makie.jl/blob/cfa902ea177ff2ee445469a2952af6e00548bbdf/examples/documentation.jl#L37
seems to be fixed in the source.

**Comment by MaximeRivest** [comment]
I can't figure out what is the `@outputfile` macro? Would be worth adding 
`#Change the path to your preferred location.` or something similar. Or should this path work for most people?

**Comment by SimonDanisch** [comment]
I could rename the macro to `replace_with_path`... that should be clearer?

**Comment by MaximeRivest** [comment]
Do you mean changing `@outputfile` to `@replace_with_path`? If so, I don't think it's necessary. Outputfile is obvious. What I meant by "I can't figure out what is `@outpufile`" was that I could not figure out if this macro was already changing the path that the user would see in the document as something like: `CHOOSE_YOUR_PATH.mp4`. If so, I imagine the docs just need to be updated following this code (but I think I understood that it is currently broken?). 

I think for a new user, like me, this pathname "./docs/media/pulsing_marker.mp4" is not the most important thing to change. If its hard for you to change... But I think it would help if it's surrounded with a comment pointing it out. It's a little thing, but it removes some of the friction to the learner. I feel the example are the best tool to quickly hit the ground running with a new package/language.

**Comment by SimonDanisch** [comment]
the macro outputfile is only used in test generation and will give it an appropriate path to also work with e.g. Documenter - it isn't defined in Makie, so if a user copies the example from the example folder, one will need to replace the macro with a reasonable path. So I guess `@replace_with_own_path` or something like that would be more appropriate
