### ISSUE TITLE
Error using glmakie while creating axis

### ISSUE THREAD

**Issue by wasiful** [JuliaPlots/Makie.jl#2098]
# shows error in the         ax1=fig[1,1] =Axis()       line
# using julia 1.7.3 and GLMakie 0.6.8
# got unsupported keyword argument "targetlimits"

fig = Figure(resolution = (3840, 2160))

ax1 = fig[1, 1] = Axis(fig,
    aspect = 1, targetlimits = BBox(-10, 10, -10, 10),
    titlegap = 48, titlesize = 60,
    xautolimitmargin = (0, 0), xgridwidth = 2, xticklabelsize = 36,
    xticks = LinearTicks(20), xticksize = 18,
    #properties of y axis
    yautolimitmargin = (0, 0), ygridwidth = 2, yticklabelpad = 14,
    yticklabelsize = 36, yticks = LinearTicks(20), yticksize = 18
)

**Comment by asinghvi17** [comment]
That's because targetlimits is not actually a keyword argument, but rather an internal field of the Axis struct.  As such, you would have better luck setting `limits = ((-10, 10), (-10, 10))` instead.
`
