### ISSUE TITLE
CairoMakie saving figures has broken markersizes

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#2099]
MWE:
```julia
using CairoMakie
fig, ax = scatter(rand(5), rand(5))
CairoMakie.save("test.png", fig)
using GLMakie; GLMakie.activate!()
GLMakie.save("test2.png", fig)
```

output:

CairoMakie
![test](https://user-images.githubusercontent.com/19669089/176162693-8b9210fc-6480-4d08-8c88-6a241f1c1b8f.png)

GLMakie
![test2](https://user-images.githubusercontent.com/19669089/176162699-8de0dbd1-8b2d-469b-99fd-4be509a706b9.png)

Versions:
```
pkg> st CairoMakie GLMakie
      Status `C:\Users\m300808\ownCloud\Projects\EquatorToPoleDeltaT\Project.toml`
  [13f3f980] CairoMakie v0.8.8
  [e9467ef8] GLMakie v0.6.8
  [ee78f7c6] Makie v0.17.8
```

**Comment by SimonDanisch** [comment]
I can't reproduce this on master... Any theme that you're setting?
Although I saw on slack that you're setting the markersize explicitly, so that couldn't be from a theme then...

**Comment by Datseris** [comment]
Nope I am not setting any theme. I have restarted Julia several times hoping that "the issue would go away" in classic naive programmer manner. It didn't :D hahaha

**Comment by Datseris** [comment]
Let me know how I can help, or I will close this if it actually goes away in the near future!

**Comment by SimonDanisch** [comment]
0.8.8 should be almost identical to master, so I'd be surprised if that makes the difference. I'd also be surprised if its something platform dependent, though :D Did you already try:
```julia
]activate --temp; add CairoMakie
using CairoMakie
fig, ax = scatter(rand(5), rand(5))
CairoMakie.save("test.png", fig)
```
I just tried that and it works well:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/1010467/176166716-4983826c-86f2-4f59-98cc-d2710a8f657a.png">

**Comment by Datseris** [comment]
Alright, so I just did in a new Julia session
```julia
]activate --temp; add CairoMakie
using CairoMakie
fig, ax = scatter(rand(5), rand(5))
CairoMakie.save("test.png", fig)
```
Also with `scatter(...; marker = 'x')`. I can confirm that on this pure envioronment everything went as expected. Very odd, as I updated my main project several times. Anyways, closing this, sorry for the timesink!

**Comment by SimonDanisch** [comment]
Well, it's pretty surprising that something like that can happen... Only explanation would be, that somehow you got a super old Makie version together with a new CairoMakie version or so, where then the drawing didn't fit the plot description..But I find it hard to believe that such an old version would even work with a new backend...So, no idea 🤷
