### ISSUE TITLE
SIMD capacity not detected by ScanByte, using scalar fallback

### ISSUE THREAD

**Issue by oniehuis** [JuliaPlots/Makie.jl#2104]
I consistently receive a warning when loading the package CairoMakie in Julia 1.8.0-rc1 (2022-05-27) (experimental 64-bit installer for macOS ARM (M-series Processor)) on a MacBook Pro with Apple M1 Max processor and Mac OS 12.4:

julia> using CairoMakie
┌ Warning: SIMD capacity not detected by ScanByte, using scalar fallback
└ @ ScanByte ~/.julia/packages/ScanByte/cr4PT/src/ScanByte.jl:11

Any idea how to address the problem?

**Comment by jkrumbiegel** [comment]
Please repost this issue at the ScanByte repository, looks like the problem is there.
