### ISSUE TITLE
Travelling wave example seems broken

### ISSUE THREAD

**Issue by MaximeRivest** [JuliaPlots/Makie.jl#212]
The traveling wave example does not work for me. It produces a video but there is no bleu line. Note that I have tweaked `time()` to `mytime()` and `linspace()` to `range()` and changed the file path. Does anybody have an idea of what is wrong? 

```Julia
using Makie

scene = Scene()
mytime = Node(0.0)
f(v, t) = sin(v + t)
scene = lines!(
    scene,
    lift(t -> f.(0:50:2pi, t), mytime),
    color = :blue)
p1 = scene[end];
N = 100
record(scene, "travelling_wave.mp4", range(0, stop = 4pi, length = N)) do i
    mytime[] = i
end
```

Thanks!

**Comment by SimonDanisch** [comment]
```julia
julia> 0:50:2pi |> length
1
```
You should use something like `(0:0.01:2pi)` - like in the example :P

**Comment by MaximeRivest** [comment]
Yep, that would do it! Thanks!
