### ISSUE TITLE
Molecular Dynamics Example

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#214]
Hi

In the molecular dynamics recipe provided in the examples, I was wondering which function actually call the 

`function default_theme(scene::SceneLike, ::Type{<: Plot(Simulation)})
    Theme(
        advance = 0,
        molecule_sizes = [0.08, 0.04, 0.04],
        molecule_colors = [:maroon, :deepskyblue2, :deepskyblue2]
    )
end`

Best,

**Comment by SimonDanisch** [comment]
It's called when creating the plot object: https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/interfaces.jl#L387
