### ISSUE TITLE
Is CairoMakie still works to plot 3D?

### ISSUE THREAD

**Issue by glanzkaiser** [JuliaPlots/Makie.jl#2140]
Hi all, I want to know how to plot this (get the code from an old thread and want to test it). 

I read that CairoMakie is deprecated, I want to try to plot function in 3-D `f(x,y) = cos(x)*cos(y)*sqrt(x^2 + y^2)`, if Cairo is unable then how to plot this with GLMakie?
```
using CairoMakie

f(x,y) = cos(x)*cos(y)*sqrt(x^2 + y^2)

x = range(-5, length = 100, stop = 5)
y = range(-5, length = 100, stop = 5)
z = f.(x, y')

```

**Comment by jkrumbiegel** [comment]
`surface(x, y, z)` works in CairoMakie
