### ISSUE TITLE
How to rotate GLMakie.mesh

### ISSUE THREAD

**Issue by samuelkim314** [JuliaPlots/Makie.jl#2141]
How do I rotate the view for `GLMakie.mesh`? Specifically, I want to have the x- and y-axes increasing going away from the camera, not towards.

I saw in the documentation that there is an attribute `model::Makie.Mat4f` but I haven’t been able to find anywhere how to use this.

**Comment by jkrumbiegel** [comment]
Well that depends on your camera position right? How did you create your plot? The model matrix can be used for rotation but so can the camera.

**Comment by samuelkim314** [comment]
I wasn't able to figure out how to use the camera and wasn't sure if it was compatible with `mesh`. My plotting is pretty simple, and for the sake of illustration is similar to the example:

```julia
using FileIO
using GLMakie

brain = load(assetpath("brain.stl"))

mesh(
    brain,
    color = [tri[1][2] for tri in brain for i in 1:3],
    colormap = Reverse(:Spectral),
    figure = (resolution = (1000, 1000),)
)
```
![example_4580049485859152347](https://user-images.githubusercontent.com/4128439/179419567-770ba0ea-db94-4445-aa2a-7e92a5c35b22.png)

**Comment by samuelkim314** [comment]
I figured out how to rotate my figure using `Scene` and `cam3d!`:

```julia
scene = Scene(resolution = (500, 500))
cam3d!(scene)
f = GLMakie.mesh!(scene, verts, faces, color=verts′[:, 1])
rotate_cam!(scene, (0, -pi/2, 0))
zoom!(scene, 0.5)
```

However, the axes have now disappeared, how do I get these back? For example, below are two images that correspond to before and after using `Scene`/`cam3d!`:
![pcmesh-899](https://user-images.githubusercontent.com/4128439/179439972-6735a31b-e54d-4583-935f-b4ac19bb8fd8.png)![pcmesh-cam3d-view2-899](https://user-images.githubusercontent.com/4128439/179439975-065ab8a2-3f5b-45ad-9753-5b9ff9a8cec9.png)

**Comment by ffreyer** [comment]
If you're going through `Scene` you also need to create the axis manually with `axis3d!(scene[, limits])`. 

> ```julia
> mesh(
>     brain,
>     color = [tri[1][2] for tri in brain for i in 1:3],
>     colormap = Reverse(:Spectral),
>     figure = (resolution = (1000, 1000),)
> )
> ```

This expands to something like

```julia
fig = Figure()
ax = LScene(fig[1, 1])
mesh!(ax, ...)
```

which is the preferred way of doing things now I think

**Comment by samuelkim314** [comment]
This seems incompatible with rotating the cam now, as the axes themselves rotate.

```julia
fig = Figure()
lscene = LScene(fig[1, 1])
scene = lscene.scene
cam3d!(scene)
f = GLMakie.mesh!(lscene, verts′, faces′, color=verts′[:, 1])
rotate_cam!(scene, (0, -pi/2, 0))
GLMakie.save(joinpath(out_dir_full, "pcmesh-cam3d-view3-$id.png"), scene)
```
![pcmesh-cam3d-view3-899](https://user-images.githubusercontent.com/4128439/179560100-09110efb-04dc-4bb8-8f38-530ec32c3b7c.png)

Similar happens with the `axis3d!` approach.

**Comment by ffreyer** [comment]
You can also do `rotate!(plot, axis, angle)` to rotate just a plot. That doesn't rotate the axis, which means that the x direction in your mesh data won't match the x-direction the axis shows. If you want to keep those in sync and just want to keep the grids behind the mesh while rotating you should try `Axis3` instead of `LScene`. https://makie.juliaplots.org/v0.17.10/examples/blocks/axis3/index.html
