### ISSUE TITLE
mesh, nan_color, lowclip, highclip not working?

### ISSUE THREAD

**Issue by lazarusA** [JuliaPlots/Makie.jl#2143]
Not sure if this should be supported, but since currently is possible to pass a list of values for a bunch of meshes I naively was expecting something like this to work.

```julia
mesh([meshes...]; color = mcolors, shading=false, nan_color = :transparent,
    colorrange = (-2.3, 20), lowclip = :black, colormap = :CMRmap)
```

**Comment by SimonDanisch** [comment]
https://github.com/JuliaPlots/Makie.jl/pull/2183
