### ISSUE TITLE
Cannot pass keyword to custom recipe

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#215]
Hello,

I think I sort of get the basic gist of how to create my own custom recipe as suggested in the new tutorial. However, I cannot seem to pass the keyword arguments down. That is

Let says I have
```julia
function plot!(p::Plot(MDSimulation); markersize = 1)
         simulation = to_value(p[1])
        scatter!(simulation.positions, color = :blue, markersize = markersize )
#more stuff
end
```
I seem that the value of markersize is always set to 1 eventhough I change value of the keyword. Now if I naively implement

```julia
function visualize(simulation::MDSimulation; markersize = 1)
   scatter!(simulation.positions, color = :blue, markersize = markersize )
   #more stuff
end
```
everything works fine. I have two questions

1. How can I make the kwarg pass down to the function body?
2. Is it necessary to use the syntax suggested in the tutorial? Can I just use the naive version?

**Comment by SimonDanisch** [comment]
> 2 Is it necessary to use the syntax suggested in the tutorial? Can I just use the naive version?

Yes, you need to follow the syntax in the tutorial!
