### ISSUE TITLE
CairoMakie 0.8.11 blocks/freezes/hangs in Pluto

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaPlots/Makie.jl#2168]
For some reason, CairoMakie hangs with version 0.8.11 whereas it doesn't with version 0.8.10. The following code will block inside a Pluto notebook (Pluto version 0.19.9):

```julia
begin
    using Pkg
    Pkg.activate(; temp=true)
    Pkg.add(; name="CairoMakie", version="0.8.11")
    using CairoMakie
end
```
```julia
lines(1:10, 1:10)
```
If I open a notebook with version to 0.8.10, then it will show the figure. This issue exist in Julia 1.7.3 and Julia 1.8.0-rc3.

**Comment by SimonDanisch** [comment]
Duplicate: https://github.com/JuliaPlots/Makie.jl/issues/2166
