### ISSUE TITLE
GLMakie not plotting lines correctly

### ISSUE THREAD

**Issue by tomchor** [JuliaPlots/Makie.jl#2186]
When I plot lines with GLMakie things don't appear to plot correctly. For example, this snippet from [the basic tutorial](https://makie.juliaplots.org/stable/tutorials/basic-tutorial/#adding_a_plot_to_an_axis):

```julia
using GLMakie

f = Figure()
ax = Axis(f[1, 1])
x = range(0, 10, length=100)
y = sin.(x)
lines!(ax, x, y)
f
```
produces this:

![image](https://user-images.githubusercontent.com/13205162/181419968-dd2f7f2f-bd4d-48ae-84dd-888d2147118e.png)

Any ideas of what's happening?

I'm using:
```
  [e9467ef8] GLMakie v0.5.5
  [ee78f7c6] Makie v0.16.6
```
on Julia 1.6.7.

PS: I tried using CairoMakie to check if this happened too but I'm using it from the REPL and I haven't figured out how to make cairo plots show up yet

**Comment by ffreyer** [comment]
Another case of #1460?

**Comment by tomchor** [comment]
Ah, yeah, good catch. I'm also using AMD on Linux so it's gotta be it...

I'm closing this
