### ISSUE TITLE
RecordEvents missing

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaPlots/Makie.jl#219]
running example http://makie.juliaplots.org/v1.0/examples-heatmap.html#Mouse-Picking-1 leads to error:

```julia
julia> RecordEvents(scene, "./docs/media/add_and_change_points")
ERROR: UndefVarError: RecordEvents not defined
Stacktrace:
 [1] top-level scope at none:0
```
(on master)

**Comment by AshtonSBradley** [comment]
ok, I see that the intention was not to supply that function. I just point out that in this example:
http://makie.juliaplots.org/stable/examples-slider.html#sliders-1

one has to extract the relevant code from `RecordEvents`, i.e. a runnable example would instead end with
```julia
hbox(p, vbox(s1, s2), parent = Scene(resolution = (500, 500)))
```

**Comment by SimonDanisch** [comment]
I added an overload for display to `RecordEvents` and exported it, so this should work now
