### ISSUE TITLE
Permission denied when loading Makie in macOS

### ISSUE THREAD

**Issue by michaelschwob** [JuliaPlots/Makie.jl#2199]
I installed Makie, GLMakie, and CairoMakie. When I have `using Makie, CairoMakie`, I get the following error: 

```
ERROR: LoadError: InitError: IOError: stat("/Users/schwob/.config/makie/theme.jl"): permission denied (EACCES)
Stacktrace:
 [1] uv_error
   @ ./libuv.jl:97 [inlined]
 [2] stat(path::String)
   @ Base.Filesystem ./stat.jl:152
 [3] isfile
   @ ./stat.jl:456 [inlined]
 [4] __init__()
   @ Makie ~/.julia/packages/Makie/Ppzqh/src/Makie.jl:302
 [5] _include_from_serialized(path::String, depmods::Vector{Any})
   @ Base ./loading.jl:768
 [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
   @ Base ./loading.jl:854
 [7] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1097
 [8] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1013
 [9] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:997
during initialization of module Makie
in expression starting at /Users/schwob/Desktop/GitHub/folder/file.jl:10
```

I thought I gave Julia complete permission to my full disk, but I am still getting this error. Thank you.

**Comment by SimonDanisch** [comment]
If you're sure, it's not the fault of OSX, I'd open an issue with https://github.com/JuliaLang/julia...
It's pretty weird, that comes from `themes.jl` though, since we only check if that file exists and do nothing else with it...See: https://github.com/JuliaPlots/Makie.jl/blob/master/src/Makie.jl#L301

**Comment by michaelschwob** [comment]
I think it may be the fault of OSX. Is there a way I can check for this?

**Comment by SimonDanisch** [comment]
Can you try to make a minimal working example (MWE), with something like:
```julia
cfg_path = joinpath(homedir(), ".config", "makie", "theme.jl")
isfile(cfg_path)
```
And see if that also doesn't work? You may need to wrap it into a module, with an `__init__` function for an MWE.

**Comment by michaelschwob** [comment]
MWE w/ suggested improvement:
`###
### Set-up
###

function __init__()
    cfg_path = joinpath(homedir(), ".config", "makie", "theme.jl")
    isfile(cfg_path)
end

using Makie`

This gives me the same error, unfortunately.

**Comment by SimonDanisch** [comment]
uhm... In the using Makie, or in the __init__ function? The init needs to be wrapped in a module...
If that reproduces the issue, you should open an issue with the julia repository...

**Comment by mgkuhn** [comment]
> `drwx------   3 root    staff   96 Aug  3 19:22 /Users/schwob/.config`

Local problem with incorrect `root` file ownership, not related to Julia. See https://github.com/JuliaLang/julia/issues/46254
