### ISSUE TITLE
weird issue with xpra

### ISSUE THREAD

**Issue by gdkrmr** [JuliaPlots/Makie.jl#2207]
I am using GLMakie on a remote machine. On the remote machine I launch an xpra server. If I don't connect to the xpra server, Julia will hang indefinitely on 100% CPU until I connect to the server from my local machine. Any idea what is happening here? Is GLMakie waiting for some signal from X?

**Comment by SimonDanisch** [comment]
I think that's a [GLFW](https://github.com/glfw/glfw) question, since the Julia part doesn't really interact with any display server / windowing system...
I don't even know what xpra is, so I guess I can't really help here ;)
