### ISSUE TITLE
Convert `Attributes` to `NamedTuple`

### ISSUE THREAD

**Issue by filchristou** [JuliaPlots/Makie.jl#2208]
In order to pass arguments around recipes I convert attributes to namedtuples with the following function:

```julia
Base.NamedTuple(attrs::Makie.Attributes) = NamedTuple([pattr.first => pattr.second isa Attributes ? pattr.second : pattr.second[] for pattr in attrs])
```

Now, when I do this locally that's type piracy.
Would it hurt if the function was defined in Makie.jl ?
I could do a PR in case.

coming from #1019

**Comment by filchristou** [comment]
scratch that. `Base.NamedTuple(::Attributes)` seems to work fine already. sorry for the noise.

**Comment by SimonDanisch** [comment]
Btw, I wouldn't actually do that, because it creates lots of type information to just then discard it again! How do you use that anyway?
you can either do `plot!(...; attributes...)` or `plot!(recipe_plot, attributes, args...)`, to pass through attributes to a plot.

**Comment by filchristou** [comment]
I don't quite remember why I ended up getting this road.. Probably I hit some kind of error and it came naturally to convert to `NamedTuple`, which is used for all julia functions. But I see now that it can work directly with passing attributes. Thanks!
