### ISSUE TITLE
Scatter/scatterlines does not co-vary color and marker

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#2215]
I am following the [themeing documentation](https://makie.juliaplots.org/v0.15/documentation/theming/index.html#covarying_cycles), which tells me to do:
```julia
COLORSCHEME = [
    "#6D44D0",
    "#2CB3BF",
    "#1B1B1B",
    "#DA5210",
    "#03502A",
    "#866373",
]

MARKERS = ["circle", "dtriangle", "rect", "pentagon", "xcross"]

default_theme = Theme(
    palette = (
        color = COLORSCHEME,
        marker = MARKERS,
    ),
    # This command makes the cycle of color and marker
    # co-vary at the same time in plots that use markers
    cycle = Cycle([:color, :marker], covary = true)
)

set_theme!(default_theme)

fig = Figure()
ax = Axis(fig[1,1])
for i in 1:5; scatterlines!(ax, rand(3), rand(3)); end 
display(fig)
```
however the resulting plot only varies color, not marker.
![image](https://user-images.githubusercontent.com/19669089/184494956-3c543fa0-73f3-49e7-baf0-dee02d6dbbac.png)

**Comment by lazarusA** [comment]
you'd need to pass also `ScatterLines=(cycle=cycle,)` to your theme. But, it looks like there is a recent bug. This used to work. 

```Julia
using GLMakie
COLORSCHEME = [
    "#6D44D0",
    "#2CB3BF",
    "#1B1B1B",
    "#DA5210",
    "#03502A",
    "#866373",
]
MARKERS = ["circle", "dtriangle", "rect", "pentagon", "xcross"]
cycle = Cycle([:color, :marker], covary = true)
default_theme = Theme(
    palette = (
        color = COLORSCHEME,
        marker = MARKERS,
    ),
    ScatterLines = (cycle=cycle,),
)

set_theme!(default_theme)

fig = Figure()
ax = Axis(fig[1,1])
for i in 1:5; scatterlines!(ax, rand(3), rand(3)); end 
fig
```

The error I'm getting now:

```
ERROR: Buffer quad_offset does not have the same length as the other buffers.
        position has length 3
        quad_offset has length 6
        uv_offset_width has length 6
        scale has length 6
Stacktrace:
  [1] error(s::String)
```

**Comment by SimonDanisch** [comment]
Jeez, that's a terrible error... The issue here: marker allows strings for multiple characters for multiple positions... So "xcross" gets interpreted as 6 different marker symbols.
You have to change those to symbols..
I think we should disallow strings to be used that way and instead use an array of Chars, and then throw a better error if lengths don't match...

**Comment by Datseris** [comment]
> I think we should disallow strings to be used that way and instead use an array of Chars, and then throw a better error if lengths don't match...

Yes please, that makes sense!

> you'd need to pass also ScatterLines=(cycle=cycle,) to your theme. 

Thank you, but I must admit this is not clear from the docs. The way I read them, they seem to imply that `cycle` is given as a global attribute to the `Theme`.

**Comment by jkrumbiegel** [comment]
Yeah that could be worded better. There's this line `set_theme!(Density = (cycle = [],))` but it's not visible enough

**Comment by Datseris** [comment]
But, however, shouldn't it make sense to allow `cycle` to be a `Theme` argument, meaning that all plot types inherit it?

**Comment by jkrumbiegel** [comment]
Not really, as all plot types can have different attributes.
