### ISSUE TITLE
PackageCompile do not show the print

### ISSUE THREAD

**Issue by rveltz** [JuliaPlots/Makie.jl#222]
Hi,

After running `PackageCompiler.compile_package("Makie", force = false) # can take around ~20 minutes
`,

I get the following

```julia
julia> data = rand(50, 50);

julia> scene = heatmap(data)
Scene (960px, 540px):
events:
    window_area: GeometryTypes.HyperRectangle{2,Int64}([0, 0], [0, 0])
    window_dpi: 100.0
    window_open: false
    mousebuttons: Set(AbstractPlotting.Mouse.Button[])
    mouseposition: (0.0, 0.0)
    mousedrag: notpressed
    scroll: (0.0, 0.0)
    keyboardbuttons: Set(AbstractPlotting.Keyboard.Button[])
    unicode_input: Char[]
    dropped_files: String[]
    hasfocus: false
    entered_window: false
plots:
   *Axis2D{...}
   *Heatmap{...}
subscenes:
   *scene(960px, 540px)
```

and no window with the result is opened whereas it is if I run Julia without the `-J` option. Is it to be expected?

Thank you for your amazing work, btw.

**Comment by rveltz** [comment]
the backend gets lost when compiling?

**Comment by Evizero** [comment]
I do not know. I am just saying something in that corner of the code must get twisted in the process

**Comment by SimonDanisch** [comment]
You could try `display(AbstractPlotting.PlotDisplay(), scene)` ! I guess the `__init__` behaves different under static compilation, so likely the plots display doesn't get pushed

**Comment by rveltz** [comment]
it works !

**Comment by rveltz** [comment]
Up to scene : yes
