### ISSUE TITLE
[DOCS] Explain what the "interaction" page does

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#224]
I saw the updated http://makie.juliaplots.org/stable/examples-interaction.html which is awesome.

There is just one thing that needs improvement in my eyes: There is no "human text" (e.g. English) of what the example aims to do. Since in none of the examples the mouse cursor is shown, there are some where it is not clear what is happening.

Surely for someone well versed in the underlining Makie code this is trivial, but for a new user that is definitely not the case. A 2-sentece description of each section would be very helpful for newbies!

**Comment by Datseris** [comment]
(e.g. I got no clue what is the "interaction" in the travelling wave example)

**Comment by SimonDanisch** [comment]
Ah yeah, that one is kind of wrongly tagged (or better: the interaction tag went through a bit of an evolution)

**Comment by SimonDanisch** [comment]
e.g. the surface example was tagged as `interactive`, since it was supposed to show how you can interactively change all the attributes
