### ISSUE TITLE
Building GLMakie Fails 

### ISSUE THREAD

**Issue by JuanVargas** [JuliaPlots/Makie.jl#2241]
I was working with GLMakie one hour ago. Went for dinner, came gack and all of the sudden GLMakie fails to work.
Pkg.add("GLMakie")    failed so I tried

Pkg.build("GLMakie") and get the following errors:

 Building FFTW ────→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/8fda0934cb99db617171f7296dc361f4d6fa5424/build.log`
 Building ModernGL → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/326957556e9cc9253615114c04bb0096a2a69bb8/build.log`    Building GLMakie ─→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/1b2b9f939cbdcfa64e4f9a03601581a337c805b2/build.log`
Precompiling project...  ✓ FFTW
 ✓ FFTViews  ✓ KernelDensity
 ✓ ImageFiltering  ✗ AbstractPlotting
 ✗ MakieGallery 4 dependencies successfully precompiled in 27 seconds. 141 already precompiled. 5 skipped during auto due to previous errors. 2 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packagesERROR: LoadError: AssertionError: precompile(f, (Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(load), String)) Stacktrace: [1] _precompile_() @ FileIO ~/.julia/packages/FileIO/TyKdX/src/precompile.jl:46 [2] top-level scope @ ~/.julia/packages/FileIO/TyKdX/src/FileIO.jl:67 [3] include @ ./Base.jl:419 [inlined] [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String) @ Base ./loading.jl:1554 [5] top-level scope @ stdin:1 in expression starting at /home/juan/.julia/packages/FileIO/TyKdX/src/FileIO.jl:1 in expression starting at stdin:1ERROR: LoadError: Failed to precompile FileIO [5789e2e9-d7fb-5bc7-8068-2c6fae9b9549] to /home/juan/.julia/compiled/v1.8/FileIO/jl_i2AqBe. Stacktrace: [1] error(s::String) @ Base ./error.jl:35 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool) @ Base ./loading.jl:1705 [3] compilecache @ ./loading.jl:1649 [inlined] [4] _require(pkg::Base.PkgId) @ Base ./loading.jl:1337 [5] _require_prelocked(uuidkey::Base.PkgId) @ Base ./loading.jl:1200 [6] macro expansion @ ./loading.jl:1180 [inlined] [7] macro expansion @ ./lock.jl:223 [inlined] [8] require(into::Module, mod::Symbol) @ Base ./loading.jl:1144 [9] include @ ./Base.jl:419 [inlined] [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String) @ Base ./loading.jl:1554 [11] top-level scope @ stdin:1 in expression starting at /home/juan/.julia/packages/ImageIO/bBdyA/src/ImageIO.jl:1 in expression starting at stdin:1ERROR: LoadError: Failed to precompile ImageIO [82e4d734-157c-48bb-816b-45c225c6df19] to /home/juan/.julia/compiled/v1.8/ImageIO/jl_N1MHwr. Stacktrace: [1] error(s::String) @ Base ./error.jl:35 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool) @ Base ./loading.jl:1705 [3] compilecache @ ./loading.jl:1649 [inlined] [4] _require(pkg::Base.PkgId) @ Base ./loading.jl:1337 [5] _require_prelocked(uuidkey::Base.PkgId) @ Base ./loading.jl:1200 [6] macro expansion @ ./loading.jl:1180 [inlined] [7] macro expansion @ ./lock.jl:223 [inlined] [8] require(into::Module, mod::Symbol) @ Base ./loading.jl:1144 [9] include @ ./Base.jl:419 [inlined] [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String) @ Base ./loading.jl:1554 [11] top-level scope @ stdin:1 in expression starting at /home/juan/.julia/packages/AbstractPlotting/JCbJs/src/AbstractPlotting.jl:1 in expression starting at stdin:1ERROR: LoadError: Failed to precompile AbstractPlotting [537997a7-5e4e-5d89-9595-2241ea00577e] to /home/juan/.julia/compiled/v1.8/AbstractPlotting/jl_0jRvMx. Stacktrace: [1] error(s::String) @ Base ./error.jl:35 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool) @ Base ./loading.jl:1705 [3] compilecache @ ./loading.jl:1649 [inlined] [4] _require(pkg::Base.PkgId) @ Base ./loading.jl:1337 [5] _require_prelocked(uuidkey::Base.PkgId) @ Base ./loading.jl:1200 [6] macro expansion @ ./loading.jl:1180 [inlined] [7] macro expansion @ ./lock.jl:223 [inlined] [8] require(into::Module, mod::Symbol) @ Base ./loading.jl:1144 [9] include @ ./Base.jl:419 [inlined] [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String) @ Base ./loading.jl:1554 [11] top-level scope @ stdin:1 in expression starting at /home/juan/.julia/packages/GLMakie/Pway1/src/GLMakie.jl:1 in expression starting at stdin:1
Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to /home/juan/.julia/compiled/v1.8/GLMakie/jl_h0Ju0P.

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1705
  [3] compilecache
    @ ./loading.jl:1649 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] eval
    @ ./boot.jl:368 [inlined]
 [10] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1428
 [11] #invokelatest#2
    @ ./essentials.jl:729 [inlined]
 [12] invokelatest
    @ ./essentials.jl:726 [inlined]
 [13] (::VSCodeServer.var"#198#199"{VSCodeServer.NotebookRunCellArguments, String})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.7.6/scripts/packages/VSCodeServer/src/serve_notebook.jl:19
 [14] withpath(f::VSCodeServer.var"#198#199"{VSCodeServer.NotebookRunCellArguments, String}, path::String)

**Comment by SimonDanisch** [comment]
Not sure what's happening, but I see `AbstractPlotting, MakieGallery` in there, which have been deprecated for years now, and they may also break new versions of Makie, because of tangled and out of date version bounds.
Try to clean up your package environment and make sure you're installing the newest version of Makie + GLMakie
