### ISSUE TITLE
Broken labelling on CairoMakie master

### ISSUE THREAD

**Issue by VarLad** [JuliaPlots/Makie.jl#2246]
I recently installed CairoMakie with 
`Pkg.add(name = "CairoMakie", rev = "master")`
My custom recipes had some weird labelling issues. Further, pre-defined recipes in Makie had the same issues:

![image](https://user-images.githubusercontent.com/51269425/187668049-a6464574-987d-4f46-afb9-1ece80576e93.png)

**Comment by SimonDanisch** [comment]
Ah, version resolve doesn't work as expected if you add a backends master version...
Try:
`] add MakieCore#master Makie#master CairoMakie#master`

**Comment by VarLad** [comment]
Precompilations fail with
```julia 
ERROR: LoadError: UndefVarError: @precompile_calls not defined
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [2] include(x::String)
   @ CairoMakie ~/.julia/packages/CairoMakie/keP4X/src/CairoMakie.jl:1
 [3] top-level scope
   @ ~/.julia/packages/CairoMakie/keP4X/src/CairoMakie.jl:69
 [4] include
   @ ./Base.jl:419 [inlined]
 [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [6] top-level scope
   @ stdin:1
in expression starting at /var/home/varlad/.julia/packages/CairoMakie/keP4X/src/precompiles.jl:10
in expression starting at /var/home/varlad/.julia/packages/CairoMakie/keP4X/src/precompiles.jl:9
in expression starting at /var/home/varlad/.julia/packages/CairoMakie/keP4X/src/CairoMakie.jl:1
in expression starting at stdin:1
```

**Comment by jkrumbiegel** [comment]
Generally such issues are on your end, if master doesn't even precompile. Probably something wasn't installed quite correctly when deving the packages. Because such basic things should always work on master unless we really screw up

**Comment by VarLad** [comment]
Ah, thats correct, had some issues on my end! 
Thanks a lot for the help @SimonDanisch ! :D
