### ISSUE TITLE
Set DPI for all figures?

### ISSUE THREAD

**Issue by tpoisot** [JuliaPlots/Makie.jl#2257]
I'm working on a series of vignettes using *Literate*, and I'd ideally like to have high-dpi figures, using *CairoMakie*.

I know how to change the DPI when saving the figures, but in this specific use case, I do not save them myself (*Literate* handles this). Is there a way I can get nice crispy figures without calling `save` myself?

**Comment by jkrumbiegel** [comment]
You can change the default dpi using `CairoMakie.activate!(px_per_unit = 2)` or whatever your desired scale factor is.

**Comment by tpoisot** [comment]
Thank you so much!
