### ISSUE TITLE
WGLMakie: `MethodError: no method matching pick(::Makie.Scene, ::WGLMakie.WebDisplay, ::GeometryBasics.Vec2{Float64}) `

### ISSUE THREAD

**Issue by lassepe** [JuliaPlots/Makie.jl#2258]
I built a little GUI with a few buttons and sliders which works great in GLMakie and also renders in "open-loop" in WGLMakie so long as I don't try to interact with it. As soon as I hover over the figure, however, I the following error crashing the visualization:

```julia
MethodError: no method matching pick(::Makie.Scene, ::WGLMakie.WebDisplay, ::GeometryBasics.Vec2{Float64})

Closest candidates are:
  pick(::Makie.Scene, ::GLMakie.Screen, ::GeometryBasics.Vec2{Float64})
   @ GLMakie ~/.julia/packages/GLMakie/K6iJk/src/picking.jl:44
  pick(::Makie.Scene, ::WGLMakie.ThreeDisplay, ::GeometryBasics.Vec2{Float64})
   @ WGLMakie ~/.julia/packages/WGLMakie/NQvbl/src/events.jl:109
  pick(::Makie.Scene, ::Number, ::Number)
   @ Makie ~/.julia/packages/Makie/Ppzqh/src/interaction/interactive_api.jl:83
  ...

**Comment by jkrumbiegel** [comment]
Picking is not yet implemented in WGLMakie. Picking refers to determining which object belongs to a pixel in the buffer.

**Comment by lassepe** [comment]
I don't recall explicitly utilizing this feature. Is this something that happens implicitly in a `Slider` or `Menu` widget?

**Comment by jkrumbiegel** [comment]
Yes in order to determine what you click on Makie needs picking. (Unless it can be decided purely by which rectangle the mouse is positioned in.)

**Comment by lassepe** [comment]
I see, thanks for the quick response! I'll close this then.

**Comment by bjarthur** [comment]
picking is a really nice feature, and i'd love to have it in WGLMakie.  is this on the roadmap?

@jkrumbiegel above refers to picking being "not **yet**" implemented for WGLMakie, so i'm hoping it is.  @ffreyer [here](https://github.com/MakieOrg/Makie.jl/issues/1337) also says "WGLMakie doesn't have [it] **yet**".

i'm a beginner here, but could help.  just point me in the right direction.

**Comment by SimonDanisch** [comment]
Should be implemented these days!
