### ISSUE TITLE
axvline/axhline

### ISSUE THREAD

**Issue by grero** [JuliaPlots/Makie.jl#228]
In PyPlot, I often make use of the axvline/axhline to draw lines that span the vertical/horizontal range of the plot. I typically use these lines to e.g. mark the time span of some event, to highlight certain portions of a line plot. The attached figure hopefully illustrates what I mean. What is the best way to achieve this in Makie? I know I can manually draw lines, but then I'd have to figure out the vertical/horizontal limits of the axis. The great thing about axvhline/axhline is that I only have to specify the x/y coordinate at which the line is to be drawn.

```julia
using PyPlot
x = range(0.0, stop=3*pi, length=100)
y = sin.(x)
plot(x,y)
plt[:gca]()[:axvline](2.0,linestyle=:dotted)
plt[:gca]()[:axvline](2.5,linestyle=:dotted)

```
![axspan_test](https://user-images.githubusercontent.com/1245900/48385063-ff6eea80-e727-11e8-9ab4-e77fafecefa8.png)

**Comment by ffreyer** [comment]
Added in https://github.com/JuliaPlots/AbstractPlotting.jl/pull/494
