### ISSUE TITLE
FileIO.save strips theming

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Makie.jl#230]
If I do
```julia
using Makie, MakieThemes
scene = show_ggthemr(:fresh)
```
I get (screenshot)
<img width="477" alt="fresh" src="https://user-images.githubusercontent.com/8429802/48518577-5c72b980-e86a-11e8-97f0-d7d1e155504b.png">
but
```julia
using FileIO
save("test.png", scene)
```
 gives
![default](https://user-images.githubusercontent.com/8429802/48518608-701e2000-e86a-11e8-80f3-3ef4d4355d49.png)

**Comment by SimonDanisch** [comment]
Hm, I can't reproduce this... are these the exact step under AbstractPlotting & Makie master?

**Comment by mkborregaard** [comment]
Just repeated on current master of both and it works. I have no idea what happened (I tried both three times yesterday), but most likely something to do with versions as I'm juggling several Pkg3-projects 🤔
