### ISSUE TITLE
ERROR: UndefVarError: hbox not defined

### ISSUE THREAD

**Issue by gstavrinos** [JuliaPlots/Makie.jl#233]
I get the `ERROR: UndefVarError: hbox not defined` message when I am making a call to `hbox`. The same happens for `vbox` too. For example, I am trying to run the sample code provided [here](http://makie.juliaplots.org/stable/examples-lines.html#Layouting-1), without success.

I tried testing Makie (using Pkg.test) and I got 20 failed tests, from which 11 of them had the tag `Axis theming`.

Just to clarify, I am running Julia-1.0.2 under Kubuntu 18.04. I have also tried inserting `AbstractPlotting.hbox` instead of just `hbox`, with the same results.

The example provided in the link above is this one:

```
using Makie

 p1 = scatter(rand(10), markersize = 1)
 p2 = lines(rand(10), rand(10))
 p3 = surface(0..1, 0..1, rand(100, 100))
 p4 = heatmap(rand(100, 100))
 x = 0:0.1:10
 p5 = lines(0:0.1:10, sin.(x))
 pscene = vbox(
     hbox(p1, p2),
     p3,
     hbox(p4, p5, sizes = [0.7, 0.3]),
     sizes = [0.2, 0.6, 0.2]
 )
```

**Comment by SimonDanisch** [comment]
Yeah, it's only exported on master

**Comment by gstavrinos** [comment]
I used the (deprecated) command `Pkg.clone()` to install the two packages, and now everything seems fine. Do you guys know if there are any plans for a release of the latest master branch?

Thanks for your help!

**Comment by mkborregaard** [comment]
Just `]add Makie#master AbstractPlotting#master` should work.

**Comment by gstavrinos** [comment]
Oh, nice, thanks!
