### ISSUE TITLE
Moving plot undoes zoom

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#236]
When moving a zoomed in plot (using right button) the zoom in is undone.

**Comment by SimonDanisch** [comment]
I either can't reproduce this or you mean something else:
![zoom](https://user-images.githubusercontent.com/1010467/48712065-238d6880-ec0d-11e8-9ee9-c22f67fb0b53.gif)
This is using scroll wheel for zooming + right click for pan

**Comment by SimonDanisch** [comment]
Why don't you just push to a `Node{<: Vector{Point}}`, like in the mouse picking example?

**Comment by Datseris** [comment]
Because my true code looks like this:
```
    # Create the first trajectory on the section:
    scene = Makie.Scene(resolution = (750, 750))
    Makie.scatter!(scene, data; makiekwargs..., color = color(u0))

    # Interactive part:
    on(scene.events.mousebuttons) do buttons
        if ispressed(scene, Mouse.left) && !ispressed(scene, Keyboard.space)
            pos = to_world(scene, Point2f0(scene.events.mouseposition[]))

            x, y = pos; z = plane[2] # third variable comes from plane

            newstate = try
               complete(x, y, z)
            catch err
               @error "Could not set state, got error:" exception=err
               return
            end

            reinit!(integ, newstate)

            data = ChaosTools._initialize_output(integ.u, i)
            @time ChaosTools.poincare_cross!(
                data, integ, f, planecrossing, tf, Ttr, i, rootkw
            )

            Makie.scatter!(scene, data; makiekwargs..., color = color(newstate))
        end
        display(scene)
        return scene
    end
    display(scene)
    return scene
end
```
i.e. after someone clicks on the screen I take this point as a initial condition and do other stuff with it which I then plot.

**Comment by SimonDanisch** [comment]
I don't really see the problem with e.g. using:
```Julia
positions = Node(data)
colors = Node(color(u0))
```
And then pushing to that... What am I missing?

**Comment by Datseris** [comment]
I am sorry, but I really don't understand what you are instructing me to do. Could you be a bit more explicit? I am not super familiar with Makie's inner workings.

`data` is a vector of `SVectors`.

**Comment by SimonDanisch** [comment]
```Julia
positions_node = Node(data)
colors_node = Node(color(u0))
scatter(positions_node, color = colors_node)
on(blah) do x
   positions = position_node[]; colors = colors_node[] # extract current values
   ... # do your thing
   append!(positions, newpos); append!(colors, new_colors);
   position_node[] = positions; colors_node[] = colors # notify the signals, which will update the plot
end
```

**Comment by Datseris** [comment]
Thanks, I haven't really understood this road. Will try it and report!

**Comment by SimonDanisch** [comment]
>EDIT: But doesn't this replot everything? The amount of points can get very high

No, this is the fast path, since it only updates the attributes that change ;)
Your solution might actually be more memory efficient, but currently it does rebuilds the scen because of `display` ... I will think about a solution for that case to just add a single plot without recalculating the whole scene

**Comment by Datseris** [comment]
@SimonDanisch I am trying your approach. I am running into a "problem". You see, in my setup `data` has a bunch of points, typically 100s to 1000s. To _all_ of them I want to attach a single color. 

I have made it work for now by simply repeating the color I want for as long as possible, e.g.:
```
            positions = positions_node[]; colors = colors_node[]
            append!(positions, data)
            append!(colors, (c = color(newstate); [c for i in 1:length(data)]))
```

Would it be possible to define a data structure such that it takes tuples of color and integer. e.g. color `x` for `X` times and color `y` for `Y` times, and then it does the repeat automatically?

I am only asking in case this will be more efficient. If when passing to the plotting backend you _must_ make a full vector of colors then disregard what I say.

**Comment by Datseris** [comment]
Thanks Simon, your advice worked very nicely :)
