### ISSUE TITLE
using `hbox` and interactive point selection has a bug

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#238]
If one uses the pipeline that selects points on mouseclick **with** `hbox` there is a problem. The points I click and the points I get are different. See the following MWE, where you click somewhere but the point is plotted more up than where you click:

```julia
using Makie, StaticArrays

data = [rand(SVector{2, Float32}) for i in 1:1000]
ui, ms = AbstractPlotting.textslider(range(0.0001, stop=0.1, length=1000),
"markersize", start=0.01)
scene = Makie.Scene(resolution = (750, 750))

positions_node = Node(data)
scplot = Makie.scatter(positions_node,  markersize = ms)

hbox(ui, scplot, parent=scene)
display(scene)

on(scplot.events.mousebuttons) do buttons
    if (ispressed(scplot, Mouse.left) && !ispressed(scplot, Keyboard.space) &&
        AbstractPlotting.is_mouseinside(scplot))

        pos = to_world(scplot, Point2f0(scplot.events.mouseposition[]))
        positions = positions_node[];
        push!(positions, pos)
        positions_node[] = positions;
    end
end
```

**Comment by Datseris** [comment]
@SebastianM-C how did you do it in your application?

**Comment by SimonDanisch** [comment]
I currently serve mouseposition as `global` coordinates, so you need to subtract the minimum of the screen rect from it...
Maybe I should implement the function `mouseposition` like here:
```Julia
using Makie, StaticArrays, GLMakie

data = [rand(SVector{2, Float32}) for i in 1:1000]
ui, ms = AbstractPlotting.textslider(range(0.0001, stop=0.1, length=1000),
"markersize", start=0.01)
scene = Makie.Scene(resolution = (750, 750))

positions_node = Node(data)
scplot = Makie.scatter(positions_node,  markersize = ms)

hbox(ui, scplot, parent=scene)
display(scene)
to_screen(scene, mpos) = Point2f0(mpos) .- Point2f0(minimum(pixelarea(scene)[]))
mouseposition(scene) = to_world(scene, to_screen(scene, events(scene).mouseposition[]))

on(scplot.events.mousebuttons) do buttons
    if (ispressed(scplot, Mouse.left) && !ispressed(scplot, Keyboard.space) &&
        AbstractPlotting.is_mouseinside(scplot))
        pos = mouseposition(scplot)
        positions = positions_node[];
        push!(positions, pos)
        positions_node[] = positions;
    end
end
```

**Comment by Datseris** [comment]
Alright, this seems like it needs a convenience function `to_subplot` or something like that :) I assume the same happens for `vbox` where one has to subtract the left-side of the scene's frame.

In general a convenience function that automatically detects whether you clicked a specific subplot and gives you the area you clicked would be nice. If you don't click the specific subplot then the function does not trigger at all.

**Comment by SimonDanisch** [comment]
Feel free to sketch out an API and even make a PR :)

**Comment by Datseris** [comment]
I will do that! Is there any documentation somewhere on the available `to_mouse, to_scene, to_world` and _all_ these functions? Or just which ones _exist_.

I only know them by example, but I don't even know how many they are!!!

**Comment by SimonDanisch** [comment]
There is only `to_world` so far ;) The others I just came up with in the example above
