### ISSUE TITLE
How to install fftmpeg on Windows?

### ISSUE THREAD

**Issue by sairus7** [JuliaPlots/Makie.jl#243]
Should I download fftmpeg library with static/shared/dev linking?
https://ffmpeg.zeranoe.com/builds/
Аnd what should be added to PATH, if there is no `*/bin` directory in dev build? `*/lib`?

**Comment by skanskan** [comment]
I have the same problem.
I have downloaded ffmpeg and installed its executables on c:\windows\system32  (on the path) but when 
I have also copied the executable in julia1.0.2\bin folder.
I try to run the example

```
using Makie

 N = 10
 r = [(rand(7, 2) .- 0.5) .* 25 for i = 1:N]
 scene = scatter(r[1][:, 1], r[1][:, 2], markersize = 1, limits = FRect(-25/2, -25/2, 25, 25))
 s = scene[end] # last plot in scene
 record(scene, "./docs/media/animated_scatter.mp4", r) do m
     s[1] = m[:, 1]
     s[2] = m[:, 2]
end
```
I get this error:
`ERROR: failed process: Process(`ffmpeg -loglevel quiet -i 'c:\Temp\jl_46C3.tmp\##video#959.mkv' -c:v libx264 -preset slow -crf 24 -pix_fmt yuv420p -c:a libvo_aacenc -b:a 128k -y ./docs/media/animated_scatter.mp4`, ProcessExited(1)) [1]
`

**Comment by SimonDanisch** [comment]
Ideally we get: https://github.com/kmsquire/VideoIO.jl/issues/120 - until then, people sadly have to install it manually. 
Since I can't give much help on how to install ffmpeg on windows besides googling it for you, I'm closing this issue ;)

**Comment by SimonDanisch** [comment]
@skanskan  , that seems to be a different issue... can you tell what `ffmpeg --version` tells you?
Best after using Makie in Julia, to be sure you catch the ffmpeg version that Makie is using!
```Julia
using Makie
run(`ffmpeg -version`)
```

**Comment by skanskan** [comment]
@SimonDanisch  here you go:
```
julia> run(`ffmpeg -version`)
ffmpeg version N-92560-gba71ebbbfa Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 24.101 / 56. 24.101
libavcodec     58. 40.100 / 58. 40.100
libavformat    58. 23.101 / 58. 23.101
libavdevice    58.  6.100 / 58.  6.100
libavfilter     7. 46.101 /  7. 46.101
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100
Process(`ffmpeg -version`, ProcessExited(0))
```


And running 
```run(`where ffmpeg`)```

I get this:
```
C:\Windows\System32\ffmpeg.exe
C:\Program Files\ImageMagick-7.0.8-Q16\ffmpeg.exe
C:\Program Files\Julia-1.0.2\bin\ffmpeg.exe
Process(`where ffmpeg`, ProcessExited(0))`
```

**Comment by SimonDanisch** [comment]
hm, so I know that there is a problem with the ffmpeg coming with ImageMagick...
Maybe you implicitly loaded ImageMagick first and that changed your ffmpeg?
Can you try:
```Julia
using ImageMagick
run(`ffmpeg -version`)
```
Although, I think ImageMagick shouldn't tamper with your PATH anymore in the newest version

**Comment by skanskan** [comment]
> using ImageMagick run(`ffmpeg -version`)

Then the output is:
```
ffmpeg version N-92560-gba71ebbbfa Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
```

It seems no matter matter if I load ImageMagick Julia still uses the its own ffmpeg.exe
