### ISSUE TITLE
Out-of-place markers with the "Mouse Picking" example

### ISSUE THREAD

**Issue by tshort** [JuliaPlots/Makie.jl#249]
The markers don't align with the mouse clicks. The skew is most apparent on the Y axis. 

Here is an example:

https://i.imgur.com/Nbu8uhD.gifv

This is on a Windows 10 machine with Julia 1.0.0 with master of Makie and AbstractPlotting.

**Comment by tshort** [comment]
I've got a second Windows computer, and on that machine, the "Mouse Picking" example works perfectly. Markers align exactly right all over the scene. I don't know what the difference is between the machines.

**Comment by SimonDanisch** [comment]
Did you do something like resizing the window/ zooming in or something like that on one PC?

**Comment by tshort** [comment]
No zooming or moving. It's repeatable multiple times, too. On the machine where things work well, it works fine even after resizing.

**Comment by SimonDanisch** [comment]
Ok, that's indeed pretty odd... Let me see if I can come up with a list of things you could check to see what's actually different

**Comment by tshort** [comment]
`show_axis = false` doesn't help, either.

**Comment by tshort** [comment]
My best guess is that on the computer where it doesn't work, `scatter!` is plotting relative to the outside of the entire window (including the window title bar). It should plot relative to the inside dimensions. In the following code, the second `scatter` produces a point right near the top. Any larger than about 475, and it doesn't show (it's under the title bar).

```julia
scene = Scene(resolution = (500, 500))
scatter!([0,250,500], [0,250,500], color = :blue, show_axis = false, markersize = 5, scale_plot = false)
scatter!([250], [470], color = :blue, show_axis = false, markersize = 5, scale_plot = false)
```

**Comment by tshort** [comment]
On my problematic computer, even the basic `scatter` example comes out wrong. The top of the plot is cut off as you can see [here](https://i.imgur.com/p48Sp1W.png).

**Comment by tshort** [comment]
I jumped the gun on that one. It's okay. I just happened to get a `rand()` that fit a pattern.

**Comment by SimonDanisch** [comment]
can you try 
```
Scene(resolution = (500, 500), camera = campixel!)
scatter!([0, 0, 500, 500], [0, 500, 0, 500], color = :blue, raw = true, markersize = 5)
```
This gives me:
![image](https://user-images.githubusercontent.com/1010467/49084478-d97d3600-f24f-11e8-9cf9-efd7b72333f4.png)

**Comment by tshort** [comment]
My window is completely blank for that. There are no markers in the corners. I ran the following with an extra marker in the middle just to make sure it was doing something. With this, the marker in the middle appears, but none of the others.

```julia
scatter!([0, 0, 250, 500, 500], [0, 500, 250, 0, 500], color = :blue, raw = true, markersize = 5)
```

**Comment by SimonDanisch** [comment]
fascinating... can you report size(scene)? 
best like this:
```julia
scene = Scene(resolution = (500, 500), camera = campixel!)
scatter!(scene, [0, 0, 500, 500], [0, 500, 0, 500], color = :blue, raw = true, markersize = 5)
size(scene)
```

**Comment by tshort** [comment]
`size(scene)` is `(500, 500)`.

**Comment by tshort** [comment]
It's fixed after I updated Intel display drivers based on this [hint](https://github.com/Openarl/PathOfBuilding/issues/411). The `scatter!` example and the Mouse Picking example work perfectly, now.
