### ISSUE TITLE
Text input

### ISSUE THREAD

**Issue by grero** [JuliaPlots/Makie.jl#250]
Is there currently a way to get text input from something like a TextEdit box under Makie? I would like to have this for a GUI that pans through data in various way. In particular, I might want to pan through the columns of a matrix, say, plotting each of them as a line plot. Currently, I'm using a slider for this, which works beautifully. However, sometimes panning to a particular column is a bit troublesome, especially if there is a large number of columns, as this requires some precision work with he mouse pointer. It would be great if, in addition to the slider itself, there could be a textfield that allowed a precise value for the slider to be set.

**Comment by ffreyer** [comment]
An editable text box has been added in https://github.com/JuliaPlots/AbstractPlotting.jl/pull/474
