### ISSUE TITLE
hbox not so intuitive

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Makie.jl#252]
It's a little complicated to use hbox because it layers from the right. I was trying to emulate this plot:
```
 ________
| p1 | p2 |
| p3 | p4 |
 ________
```
And had to do
```
vbox(hbox(p2, p1), hbox(p4, p3))
```

**Comment by Evizero** [comment]
Just to be more explicit. The non-inuitive aspect here is the order of the positional parameter in `hbox`, right? Because aside from that this line would exactly be what I would have assumed (even though i never used it in makie)

**Comment by mkborregaard** [comment]
Yes exactly (although it does extend to the question of whether hbox and vbox are the best when trying to accomplish more advanced layouts, see #183)

**Comment by JonasIsensee** [comment]
Your line does not give me the plot you described above. These two do:
```
julia> vbox(hbox(p2, p1), hbox(p4, p3))

julia> vbox(hbox(p3, p1), hbox(p4, p2))
```

Another thing that confuses me each time: Why are they named `hbox` and `vbox`?
To me `hbox` is something _horinzontal_ but here it actually places two plots vertically.
`vbox` (_vertical_) on the other hand places two plots side by side.
I would have intuitively defined this the other way around.
Can someone explain this to me?

**Comment by SimonDanisch** [comment]
As I see it, you're putting the boxes on the horizontal/vertical plane.
So hbox:
```
[box]
_____ horizontal plane 
[box]
```

**Comment by JonasIsensee** [comment]
Thank you.
I must say, my intuition is still not convinced but I'll surely get used to it.

**Comment by yha** [comment]
I agree with @JonasIsensee that the current behavior of `hbox` and `vbox` seems the wrong way around.
(I observe the same behavior described by @JonasIsensee, I think: `vbox` stacks left-to-right, `hbox` stacks bottom-to-top. This is different than what @mkborregaard describes in the first post).
It is also the reverse of CSSUtils.jl (and therefore Interact.jl), and of anything I could find by googling "hbox vbox" and "hbox layout".
I think `hbox` `vbox` should be deprecated in favor of something like `hstack` and `vstack` which are "the right way around" (i.e., respectively the same as `vbox` and `hbox`).

**Comment by asinghvi17** [comment]
It will be interesting to consider how this will play out with constrained layouting...maybe that would be the time for an API change!

**Comment by ffreyer** [comment]
vbox and hbox don't exist anymore
