### ISSUE TITLE
Colormap docs example has render errors

### ISSUE THREAD

**Issue by ianshmean** [JuliaPlots/Makie.jl#255]
The colormaps example [here](https://makie.juliaplots.org/stable/examples-image.html#colormaps-1) seems to have rendering issues that make it hard to read & understand. 

I updated the code and image, but can't find the docs git, so here it is:

![image](https://user-images.githubusercontent.com/1694067/49484493-3dca6780-f805-11e8-9393-276240c70ec6.png)

```
using Makie

 h = 0.0
 offset = 0.1
 scene = Scene()
 cam2d!(scene)
 plot = map(AbstractPlotting.colorbrewer_names) do cmap
     global h
     c = to_colormap(cmap)
     cbar = image!(
         scene,
         range(0, stop = 10, length = length(c)),
         range(0, stop = 1, length = length(c)),
         reshape(c, (length(c),1)),
         show_axis = false
     )[end]
     text!(
         scene,
         string(cmap, ":"),
         position = Point2f0(-0.1, 0.5 + h),
         align = (:right, :center),
         show_axis = false,
         textsize = 1
     )
     translate!(cbar, 0, h, 0)
     h -= (1 + offset)
 end
 scene
```

**Comment by mkborregaard** [comment]
The example has moved here: https://github.com/JuliaPlots/MakieGallery.jl/blob/af942ad15fe3e1bc2ec00fdc3ad2c2a305b0255b/examples/documentation.jl#L92-L119

**Comment by SimonDanisch** [comment]
Great! Thanks a lot :) would you mind moving it to MakieGallery? WOuld probably be the easiest to preserve git authorship!
