### ISSUE TITLE
High dpi output

### ISSUE THREAD

**Issue by natschil** [JuliaPlots/Makie.jl#256]
Is there a way to get higher definition output?  I have a 3000x3000 heatmap which I'd like to save in high definition. Doing `Makie.save("/tmp/output.pdf",scene)` gives me an output, but it is quite blurry. Is there some way to force a higher resolution for the output?

**Comment by SimonDanisch** [comment]
one could add an option to save, which resizes the scene before saving...of course, you could also do that manually befor saving ;)

**Comment by natschil** [comment]
Thanks, calling `resize!` did the trick :)

**Comment by dehann** [comment]
Hi, thanks for working on Makie.jl it looks great!  I have a related question on exporting vectorized graphics (pdf, eps, svg) beyond png/jpg.  I tried saving vector types, but alas... I would like to use Makie to generate figures for papers etc., but these certainly require vectorized plots -- is there perhaps a way to do so?

**Comment by SimonDanisch** [comment]
You can use the experimental [Cairo backend](https://github.com/JuliaPlots/CairoMakie.jl): 
```Julia
using AbstractPlotting, CairoMakie, FileIO
scene = scatter(rand(10))
# save is broken, since it somehow defaults to png without checking the extension -.-
# but the below works to save a svg:
open("test.svg", "w") do io
    show(io, MIME"image/svg+xml"(), scene)
end
```

**Comment by dehann** [comment]
Hi Simon, thanks -- sorry for the slow reply.  I tried the svg export and ran into a second issue on Cairo vs GL Backend.  Can you use them interchangeably?
```julia
julia> open("/tmp/test.svg","w") do io
       show(io, MIME"image/svg+xml"(), scene)
       end
ERROR: MethodError: no method matching backend_show(::GLMakie.GLBackend, ::IOStream, ::MIME{Symbol("image/svg+xml")}, ::Scene)
Closest candidates are:
  backend_show(::Any, ::IO, ::MIME{Symbol("text/plain")}, ::Scene) at /home/dehann/.julia/packages/AbstractPlotting/gwRgD/src/display.jl:72
  backend_show(::GLMakie.GLBackend, ::IO, ::MIME{Symbol("image/png")}, ::Scene) at /home/dehann/.julia/packages/GLMakie/rAuGK/src/gl_backend.jl:69
  backend_show(::CairoMakie.CairoBackend, ::IO, ::MIME{Symbol("image/svg+xml")}, ::Scene) at /home/dehann/.julia/packages/CairoMakie/O5aBi/src/CairoMakie.jl:469
  ...
Stacktrace:
 [1] show(::IOStream, ::MIME{Symbol("image/svg+xml")}, ::Scene) at /home/dehann/.julia/packages/AbstractPlotting/gwRgD/src/display.jl:62
 [2] (::getfield(Main, Symbol("##5#6")))(::IOStream) at ./REPL[10]:2
 [3] #open#294(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(Main, Symbol("##5#6")), ::String, ::Vararg{String,N} where N) at ./iostream.jl:369
 [4] open(::Function, ::String, ::String) at ./iostream.jl:367
 [5] top-level scope at none:0
```

I'm trying to export this figure from the Makie docs, using `scene = hbox(...`):
http://makie.juliaplots.org/stable/examples-image.html#Comparing-contours,-image,-surfaces-and-heatmaps-1

**Comment by SimonDanisch** [comment]
you need to make cairomakie the backend before saving - glmakie doesn't support svg. could be done automatically, i guess, but isn't right now^^ 
It's something like:
AbstractPlotting.current_backend[] = CairoMakie.CairoBackend("path/to/svg")

**Comment by dehann** [comment]
Got it, thanks -- looks like that worked.

**Comment by kskyten** [comment]
I found this [library](http://geuz.org/gl2ps/) for rendering OpenGL to vector formats. Might be useful.
