### ISSUE TITLE
Cropping images

### ISSUE THREAD

**Issue by natschil** [JuliaPlots/Makie.jl#257]
It seems like setting `limits` for an image is broken in the sense that the axes are rescaled, but things outside of them are still part of the scene. Am I using `limits` wrong?

Below is an example where the axes include the part I want to be part of the plot, but the background image is not cropped to these axes.

![output](https://user-images.githubusercontent.com/3118879/49543233-efd26400-f8d7-11e8-9061-6f1a68c08516.jpg)

**Comment by asinghvi17** [comment]
Yeah, this is still an issue unfortunately...see JuliaPlots/AbstractPlotting.jl#97.  Should be fixed by next release if the timeline works out in #336

**Comment by asinghvi17** [comment]
If your surface is rectangular, you could use subscenes with a defined area to simulate clipping.

**Comment by SimonDanisch** [comment]
Or use MakieLayout ;)
