### ISSUE TITLE
Precompilation Error due to AbstractPlotting

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#258]
Hi,

I am got Makie to work a while ago but now I today I try to reinstall everything. I encountered the problem that I have never seen before

`WARNING: Method definition contour() in module AbstractPlotting at /Users/wsrinin/.julia/packages/AbstractPlotting/7QqXZ/src/recipes.jl:127 overwritten in module Makie at /Users/wsrinin/.julia/packages/AbstractPlotting/7QqXZ/src/recipes.jl:127.
ERROR: LoadError: LoadError: cannot assign variable AbstractPlotting.Contour from module Makie
Stacktrace:`

How can I fix this issue? Is it because of Makie and AbstractPlotting are not in sync? If so, how can I go about fixing such a things?

Best

**Comment by natschil** [comment]
I also get this

**Comment by wsrinin** [comment]
Just a follow up. How do I add master with julia package manager?

**Comment by natschil** [comment]
In the Julia REPL, type `]` then type `add Makie#master AbstractPlotting#master GLMakie#master"`

**Comment by wsrinin** [comment]
That works, Thank You.

**Comment by wsrinin** [comment]
I am sad to report that the earlier solution does not work. It seems to me that the problem now lies with GLMakie, which I just open an issue. I spend quite a bit of time trying to figure out the error but I think I am giving up for now.  I am quite sad since Makie works perfectly well for me just a month ago. :(

**Comment by wsrinin** [comment]
This is rather curious since I got everything to work in version sd-recipes. What are the main differences?

**Comment by SimonDanisch** [comment]
Yeah sorry, there has been a large refactor and I upgraded most involved packages to Pkg3 using a project toml, which obviously wasn't a 100% smooth... But it should work by now as pointed out here:
https://nextjournal.com/sdanisch/makie-pkg3
That installs everything from scratch and works fine!
