### ISSUE TITLE
Makie.jl/REQUIRE should include AbstractNumbers

### ISSUE THREAD

**Issue by CrashBurnRepeat** [JuliaPlots/Makie.jl#26]
Just went to use `Makie` and got an error about an uninstalled package `AbstractNumbers`. The dependency should be included in the `REQUIRE` list.

**Comment by mschauer** [comment]
Makie requires manual installation, see https://github.com/SimonDanisch/Makie.jl#installation . AbstractNumbers is not yet registered and "If unregistered packages contain a REQUIRE file at the top of their source tree, that file will be used to determine which registered packages the unregistered package depends on"

**Comment by SimonDanisch** [comment]
I'm working on registering a working, tagged version to integrate it into the REQUIRE :)

**Comment by CrashBurnRepeat** [comment]
Ok, I think I was mislead about it being registered already when `Pkg.add("AbstractNumbers")` worked without complaint. I was looking into some other errors (in other packages) at the time, so I may not have been the most patient. Should this be kept open until it's registered, or closed since the `README` covers this?
