### ISSUE TITLE
Practical Advice on How to Make Color Bars and Legends

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#262]
Hello,

I would love to be able to create the following example with Makie

How can I create the scale bar to the right of the plot? I found an ad-hoc solution which is to use heatmap and reposition the heat map next to the graph. Is this the way to do it?

![image](https://user-images.githubusercontent.com/24701859/49882994-c6499900-fdff-11e8-9a96-3f06883a080b.png)

**Comment by SimonDanisch** [comment]
You can use colorlegend: 
http://htmlpreview.github.io/?https://github.com/SimonDanisch/ReferenceImages/blob/master/gallery/color_legend/index.html
Will be soon more tightly integrated!

**Comment by wsrinin** [comment]
Oh, this is really neat. I really like the fact that I can compose anything I want in Makie. In my ad-hoc solution, I can't figure out what attribute I need to access in order to turn off the axis label ( may be only on the x-axis) and grid behind the heat map since I want to convert it to the scale bar.

<img width="259" alt="screen shot 2018-12-12 at 12 02 14 pm" src="https://user-images.githubusercontent.com/24701859/49885818-3529f080-fe06-11e8-8ac8-22fc5f8f708d.png">

**Comment by SimonDanisch** [comment]
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/basic_recipes/axis.jl#L68
There you see, you need:
```
heatmap(..., axis = (names = (axisnames = ("", ""),),))
```
I admit this is a bit ugly, which is why we need to have some magic arguments ;)

**Comment by wsrinin** [comment]
I can't wait for the magic arguments :).
