### ISSUE TITLE
Interactive sample in jupyter (IJulia)

### ISSUE THREAD

**Issue by utotch** [JuliaPlots/Makie.jl#266]
I want to make interactive 3D visualization with Makie in jupyter.
I found a sample of this image:

https://user-images.githubusercontent.com/1010467/43538067-4a12b232-95c1-11e8-9783-0b55c9ddde54.gif

but I can't remake it since Visualizer class doesn't exist.

Does anyone know how to write interactive Makie visualization by using a mouse in jupyter?

**Comment by SimonDanisch** [comment]
Sorry, this will need to wait for the WebGL backend - which will come at some point ;)

**Comment by tamasgal** [comment]
That would be awesome ;)

**Comment by SimonDanisch** [comment]
Actually, the webgl backend is pretty far at this point:
https://nextjournal.com/sdanisch/wglmakie
https://github.com/JuliaPlots/WGLMakie.jl/issues/6

**Comment by tamasgal** [comment]
Oh wow, I have to try that! Currently I am struggling to get Makei work on my macOS though. I'd like to use it for live 3D neutrino event displays :)
