### ISSUE TITLE
SVG in Makie Window

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#268]
Hello,

Is there a way to render SVG file in Makie window?

Best,

**Comment by SimonDanisch** [comment]
No, only by converting it to png...
But actually, it shouldn't be tooo hard to implement a function svg -> Makie.Scene, since svg doesn't have that many drawing operations and they should be all supported by Makie.
I actually tried that some time ago, but admittedly failed at parsing the xml and getting any meaningful paths + attributes out of it... Someone with more xml experience could probably do this quite a bit faster!

**Comment by wsrinin** [comment]
That is what I figure out as well. The infrastructure is there but it is gonna quite a bit of work to make it work because I was thinking about rendering the math equation as SVG or PNG use it as a texture to plot on Makie scene. I can't remember why precisely I don't want to use PNG format. 

Isn't Cairo capable of doing SVG?

**Comment by SimonDanisch** [comment]
I guess if you stay with the cairo backend, there could be a simpler way ;) 
Png is resolution dependent, so if you zoom you will see ugly pixels + edges - so yeah, perfect solution would be to directly turn an svg into a makie plot!

**Comment by lobingera** [comment]
@wsrinin Cairo is able to output SVG and librsvg can render SVG to Cairo surfaces (https://github.com/lobingera/Rsvg.jl)  Do you think of 'just' putting this as background picture?

**Comment by dehann** [comment]
Moving SVG export discussion to from #256

Unfortunately I'm having another issue with the svg export.

The issue I'm having is that the backend call:
```julia
AbstractPlotting.current_backend[] = CairoMakie.CairoBackend("/tmp/test.svg")

#intention is to get here
#open("/tmp/test.svg","w") do io
#   show(io, MIME"image/svg+xml"(), scene)
#end
```

Changes the behavior of plotting, resulting in incorrect plots.  The best way to describe is looks like canvas sizing error where the original plot becomes tiled with repetition inside the original axes.  For example, the correct image looks something like this (a png):

![test](https://user-images.githubusercontent.com/6412556/52523656-b87a8d80-2c61-11e9-88c4-4cd896b4ccb9.png)

But ends up looking like this (screen grab of svg opened via `eog` on Ubuntu 16.04):

![screenshot from 2019-02-09 11-59-46](https://user-images.githubusercontent.com/6412556/52523709-38a0f300-2c62-11e9-8ff5-e3558ef633b9.png)

Note, the Makie Window no longer shows the plots (as per this issue), but working through Juno the plot pane shows the same funky canvas version.  I'm pretty sure it is related to changing to the Cairo backend.

**Comment by kskyten** [comment]
[Manim](https://github.com/3b1b/manim) implements an [SVG parser](https://github.com/3b1b/manim/blob/master/manimlib/mobject/svg/svg_mobject.py) that does pretty much this in Python. What are the primitive plotting commands that should be used to make the Makie scene?

**Comment by asinghvi17** [comment]
That's interesting, I will definitely give it a look!  

We currently decompose all plotting commands into several 'atomic' drawing operations within AbstractPlotting - for 2d plotting, all you really need is `linesegments`, `lines`, `mesh`, `heatmap`/`image`, and `text`.

**Comment by asinghvi17** [comment]
Also, @dehann, the issue with Cairo is being investigated in JuliaPlots/CairoMakie.jl#11.

**Comment by kskyten** [comment]
There are probably better parsers to look at as well. [This](https://github.com/memononen/nanosvg) looks promising, although it parses everything into bezier curves, so semantic information is lost. Shouldn't matter just for plotting, though.

**Comment by kskyten** [comment]
I wonder if we can use [resvg](https://github.com/RazrFalcon/resvg) directly? If not, [usvg](https://github.com/RazrFalcon/resvg/tree/master/usvg) should at least make parsing easier.

**Comment by asinghvi17** [comment]
Looking at the resvg repo, it seems that it statically links `harfbuzz` at runtime.  That, and figuring out the C API, would be the only hiccups in getting it wrapped in Julia.

**Comment by behinger** [comment]
Because I found this via google - you can render SVG/Latex/Typst via [MakieTex](https://github.com/JuliaPlots/MakieTeX.jl)
