### ISSUE TITLE
Updating scene within a function

### ISSUE THREAD

**Issue by lstagner** [JuliaPlots/Makie.jl#269]
I have a problem where it would be useful to regularly update a scene from within a function call. The body of function works but as soon as I wrap it in a function the scene no longer updates.
```
function f()
     scene = Scene()
     display(scene)
     x = Node(rand(50,50))
     heatmap!(scene,lift(a->a,x))
     for i=1:10
           push!(x,rand(50,50))
           sleep(1)
     end;
end
```

**Comment by SebastianM-C** [comment]
you can display the scene in the global scope and then have a function that
updates it.

**Comment by lstagner** [comment]
I tried that. The effect is the same.
```
function f(scene)
     x = Node(rand(50,50))
     heatmap!(scene,lift(a->a,x))
     for i=1:10
           push!(x,rand(50,50))
           sleep(1)
     end
end
```

**Comment by SebastianM-C** [comment]
You have to have some observables / nodes in the scene so that when they update, the scene also updates. For example:
```julia
a = Node(rand(10,10))
scene = heatmap(a)

function update(a)
    for i=1:100
        a[] = rand(10,10)
        sleep(1/60)
    end
end

update(a)
```

**Comment by lstagner** [comment]
Ok, so the scene has to contain observables before it is displayed. Is there a way to add observables to an already displayed scene?

**Comment by lstagner** [comment]
I just have an iterative optimization that I want to monitor from within the optimization function. From your comments I was able to get my original example to work by displaying the scene after the first heatmap. 
```
function f() 
     scene = Scene()
     # display(scene) # display here doesn't work
     x = Node(rand(50,50))
     heatmap!(scene,lift(a->a,x))
     display(scene) # display has to be after first call to heatmap
     for i=1:100
           x[] = rand(50,50)
           sleep(1/60)
     end
end
```
My intuition was that the placement of the `display` command shouldn't be important since I thought that the `heatmap!` call would modify the scene/display to include the observable but apparently the placement matters when you're not in global scope.

**Comment by SebastianM-C** [comment]
Glad I could help.
