### ISSUE TITLE
Plotting filled-in polygons

### ISSUE THREAD

**Issue by natschil** [JuliaPlots/Makie.jl#274]
I have about 500 closed curves in 2D where I would like to plot the inside filled-in. The curves are given by a list of points. Does Makie have any functions for plotting something like this? I saw the poly() function, but I'm not sure it does what I want. I'm guessing something like what I need may already be implemented in some form of contour function, but I'm not sure where I should look exactly.

**Comment by SimonDanisch** [comment]
`Makie.poly(points::Vector{Point})` should give you a filled shape...
I haven't implemented `Vector{Vector{Point}}` yet, but the way to go is to create a list of points + list of triangles with [EarCut.jl](https://github.com/JuliaGeometry/EarCut.jl) and display it as a mesh... If I decide to take on that dependency, we could have a recipe for this.
```Julia
using EarCut, Makie
using GeometryTypes
triangle_faces = triangulate(polygon::Vector{Vector{Point2f0}})
points = vcat(polygon...)
Makie.mesh(points, triangle_faces)
```

**Comment by natschil** [comment]
Thanks!

**Comment by natschil** [comment]
I'm not sure I quite understand your code... this is just for one polygon, right? How would I combine triangle_faces from multiple polygons? I tried just concatenating the arrays, but this doesn't seem to work.

**Comment by natschil** [comment]
Ok, I figured it out, writing here so that if anyone stumbles upon this with a similar question, they will know what to do: Basically `triangle_faces` is a list of indices of the points list. So if you concatentate lists of points, you can't simply concatentate lists of faces but you need to add an appropriate offset so that the index is the index in the new list.

**Comment by SimonDanisch** [comment]
That sounds wrong... I thought triangle_list would already point to the vcat'ed list! Isn't that the case?

**Comment by SimonDanisch** [comment]
![image](https://user-images.githubusercontent.com/1010467/50986614-962d0d00-1507-11e9-9d91-babd16e000be.png)
Seems to work just fine?

**Comment by natschil** [comment]
Say I have a vector of  points representing polygons, then what I currently do is the following:
```
res_points = Points2f0[]
res_tris =  GeometryTypes.Face{3,GeometryTypes.OffsetInteger{-1,UInt32}}[]
offset = 0
for poly in polygons
    append!(res_points,poly)
   tris = triangulate([poly])
   append!(res_tris,[tri .+ offset for tri in tris])
   offset += length(poly)
end

**Comment by natschil** [comment]
This seems to work. However, I now have the problem that calling Makie.mesh!(scene,...) paints things *behind* the scene = Makie.heatmap() I would like to paint on top of. Is there some way I can move things into the foreground/background?

**Comment by SimonDanisch** [comment]
why don't you do `triangulate(polygons)`?

**Comment by SimonDanisch** [comment]
can you give a screenshot?

**Comment by natschil** [comment]
My assumption was that triangulate(polygons) works like https://github.com/mapbox/earcut.hpp in that the first polygon in the list gives the outer polygon, and the next ones define holes. I haven't tried passing the whole list so far.

**Comment by SimonDanisch** [comment]
You could be right ;) I actually haven't tested it much yet!

**Comment by SimonDanisch** [comment]
Well, then you might as well just use:
```Julia
for poly in polygons
    Makie.poly!(poly)
end
```
The algorithm I use for that may, or may not be, worse than earcut ;) I think it was definitely faster, so if it produces the right polygons, you should definitely just use `poly!`.
You may still want to use mesh! + earcut, if you have lots of small polygons... But I think the ratio of points per polygon vs total polygons must be really bad to give you any performance benefit!

**Comment by natschil** [comment]
Yeah I have a ton of polygons. Previously when I was just plotting the lines I ran into problems past about 200 calls to Makie.lines (or whatever the function is called), so I had to modify what I was doing to use Makie.linesegments. I suspect that with the number of (very small) polygons I have, using mesh is better (and it seems to work).

As for a screenshot with the foreground/background issue: there sould be a whole bunch of red polygons on the blue area (and they are there if I replace blue with transparency)
![output](https://user-images.githubusercontent.com/3118879/50987381-caa1c880-1509-11e9-92e2-19e1ac1a0837.jpg)

**Comment by SimonDanisch** [comment]
a quick hack could be to do:
```julia
polyplot = poly!(bla)[end]
translate!(polyplot, 0, 0, 10)
```
Hope that works for you! make sure you plot the image first!

**Comment by natschil** [comment]
Thanks! Is there a way  I translate! a mesh?

**Comment by natschil** [comment]
If I use poly! it seems to run, but I then get an error on Makie.FileIO.save("/tmp/output.png",scene); As I'm running on a remote machine I can't actually look at the screen at the moment to see whether or not the polygons were drawn. The error I get is:
``ERROR: KeyError: key :faces not found
Stacktrace:
 [1] pop!(::Dict{Symbol,Any}, ::Symbol) at ./dict.jl:581
 [2] GLMakie.GLAbstraction.NativeMesh{GLPlainMesh}(::Observables.Observable{GLPlainMesh}) at /home/nate/.julia/packages/GLMakie/lv9dg/src/GLAbstraction/GL
Utils.jl:94
 ```

**Comment by mkborregaard** [comment]
That looks amazing btw

**Comment by SimonDanisch** [comment]
> Thanks! Is there a way I can translate! a mesh?

```Julia
translate!(plot, 0, 0, 10)
```
Well, that's the way to translate any plot (or scene as well) ;)

**Comment by SimonDanisch** [comment]
>The error I get is:

That's weird - not much I can do without a minimal working example to reproduce the error

**Comment by natschil** [comment]
>Well, that's the way to translate any plot (or scene as well) ;)

When I tried it earlier, I got some weird errors :D But now it works. I think I must have used Float64s for the arguments instead of Int64s or something like that previously.

**Comment by SimonDanisch** [comment]
Ah yeah, I implemented it only for the same number type ... If you want to contribute a super low hanging fruit, a PR to improve this would be super appreciated :)
