### ISSUE TITLE
Is there a way to clear a scene without creating a new one

### ISSUE THREAD

**Issue by gzhang8** [JuliaPlots/Makie.jl#277]
Thanks for making this great package. It helps me a lot on visualizing 3D data. Recently, I came across the need to clear a scene and re-draw everything. I looked into examples and docs but don't find a way to do it. More specifically, I use `Scene()` to create a scene and then draw on it using functions like `scatter!`. Creating a new scene whenever I want to clear kinda works, but it reset viewpoint. Is there a way to clear a scene so that I can reuse it to redraw?

**Comment by SimonDanisch** [comment]
What exactly do you want to clear? Can't you just mutate in place the plots you have?

**Comment by gzhang8** [comment]
@SimonDanisch Thanks for your reply. I think that is what I want. But I cannot find the `mutate` related docs or source code. Can you give a pointer? Thanks

**Comment by SimonDanisch** [comment]
Is this what you're looking for: http://juliaplots.org/MakieGallery.jl/stable/interaction.html ?

**Comment by gzhang8** [comment]
Great! It is. I should have gone further than just reading functions. Many thanks.
