### ISSUE TITLE
Computing and ploting at the same time

### ISSUE THREAD

**Issue by squarefk** [JuliaPlots/Makie.jl#279]
Basically, what I am trying to do is computing a sequence of number and interactively ploting them with Makie
However, I found that window created by Makie could automatically exit when I try to do anything after RecordEvents()
A quick example is like:
```
using Makie

 x = rand(10)
 y = rand(10)
 colors = rand(10)

 scene = scatter(x, y, color = colors)

 println("Makie is awesome")
```

**Comment by SimonDanisch** [comment]
You can achieve this like this:
```Julia
using Makie, AbstractPlotting

xy = rand(Point2f0, 10)
colors = rand(10)
points_node = Node(xy)
scene = scatter(points_node, color = colors)

display(scene)
for i in LinRange(0, 2pi, 20)
    push!(xy, Point2f0(sin(i), cos(i)))
    # update the signal of the points
    points_node[] = xy 
    # optional if you want to zoom in + update limits:
    AbstractPlotting.update_limits!(scene)
    AbstractPlotting.update!(scene)
    yield()
end

```

For your other questions you need to be more specific. I don't see any RecordEvents in the code, so I have no idea how you're using it, or how you execute the code for the window to close!
