### ISSUE TITLE
[DOCS] Basics/Interaction is outdated

### ISSUE THREAD

**Issue by cserteGT3** [JuliaPlots/Makie.jl#281]
The documentation still mentions `Reactive.jl` for interactivity, but (as I understand) it uses `Observables.jl`. Also #134 suggests that is final by now. If so, I'm happy to correct that part of the docs, but did not find where to do it.

**Comment by asinghvi17** [comment]
Check out http://juliaplots.org/MakieGallery.jl/stable/ which is where the latest documentation is hosted - what's on `README.md` right now is an older build.  Also check out https://github.com/JuliaPlots/MakieGallery.jl if you'd like to contribute :)
