### ISSUE TITLE
How to contribute to documentation?

### ISSUE THREAD

**Issue by pbouffard** [JuliaPlots/Makie.jl#283]
I'm guessing that the docs that are served at http://makie.juliaplots.org/v1.0/ are generated from something other than the master branch which doesn't seem to have a docs directory. How does one make a PR to the documentation?

**Comment by asinghvi17** [comment]
Have a look at JuliaPlots/MakieGallery.jl - that's where the new docs are located, as well as http://juliaplots.org/MakieGallery.jl/stable/ which is where they are hosted.




Sincerely,


Anshul Singhvi







On Sun, Feb 10, 2019 at 10:59 AM -0500, "Patrick Bouffard" <notifications@github.com> wrote:












I'm guessing that the docs that are served at http://makie.juliaplots.org/v1.0/ are generated from something other than the master branch which doesn't seem to have a docs directory. How does one make a PR to the documentation?

**Comment by pbouffard** [comment]
Thanks @asinghvi17. Would it make sense then to have the master branch's README point there instead?

**Comment by asinghvi17** [comment]
I just added a PR #284 to add a `docs | latest` badge to the README next to the 'current' docs.
