### ISSUE TITLE
Request: Implement more of the color schemes from the Viridis color palettes 

### ISSUE THREAD

**Issue by xtalax** [JuliaPlots/Makie.jl#285]
I adore makie, but I  feel that the available deafult colormaps are quite limited. In particular the [viridis](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html#the-color-scales) colormaps all look fantastic, and while the default has found its way in to makie, some others like magma and inferno would be much appreciated. Could someone direct me as to how I might do this or better yet add these to the default symbols?

**Comment by lnacquaroli** [comment]
You can check [ColorSchemes.jl](https://juliagraphics.github.io/ColorSchemes.jl/stable/index.html). Provides a collection of colorschemes and colormaps and is compatible with most plotting libraries.

**Comment by mkborregaard** [comment]
Makie depends on PlotUtils, which has a very large range of good color schemes defined: https://docs.juliaplots.org/latest/colors/#colorschemes
Would be an easy PR to have Makie use those color schemes.

**Comment by asinghvi17** [comment]
Resolved by JuliaPlots/AbstractPlotting.jl#96!
