### ISSUE TITLE
Visual `Slider` representation does not react to changes of its `Observable` field `value`.

### ISSUE THREAD

**Issue by dafred94** [JuliaPlots/Makie.jl#2852]
# MWE
```
fig = Figure()

# .. add a slider with text
sg = SliderGrid(
    fig[1, 1],
    (startvalue = 5, range=0:1:10, format="{:d}"),
    width = 250,
    tellheight = false
)

sl = sg.sliders[1]

# add a button..
bt = Button(
    fig[1, 2],
    label="Set slider to 2!"
)

on(bt.clicks) do val
    sl.value[] = 2
end

# add a Label to monitor the slider... again
Label(
    fig[0, :],
    lift(sl.value) do val
        "slider value: "*string(val)
    end,
    fontsize = 20
)

display(fig)
```

# my issue
Sliding the slider manually works, no problem. The text next to it and the label update as intended. Now I want to set the slider value to a specific value. For that I created `Button` `bt`. Once clicked, both texts update as intended. However, the slider does not visually move to that position.

How to address this issue? Is there another thing to do so that the visual representation of the slider updates?

The documentation says that you can even double-click the slider to reset it to close to the `startvalue`. Where can I even see the function that is called on double-click on the slider? The relevant snippets of code to solve my issue should be included there. I feel like I am having trouble navigating the docs here...

**Comment by SimonDanisch** [comment]
https://github.com/MakieOrg/Makie.jl/blob/master/src/makielayout/blocks/slider.jl#L196-L200
