### ISSUE TITLE
Allow argument `framerate` to record

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#287]
Record should be able to get a `framerate` argument to control the framerate of the resulting animation. If such an option is already possible then please leave this issue open until it is documented ;)

**Comment by asinghvi17** [comment]
See [AbstractPlotting.jl/#79](https://github.com/JuliaPlots/AbstractPlotting.jl/pull/79)

**Comment by asinghvi17** [comment]
Merged and released!
