### ISSUE TITLE
Set axis limits ONCE and ensure they are left untouched by automatic behavior.

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#288]
MWE:

```julia
scplot = scatter(rand(5), rand(5), markersize = 0.1, limits = IRect(0, 0, 1, 1))
text!(scplot, "InteractiveChaos",
     position = (0.05, 0.05),
     align = (:left,  :lower),
     textsize = 0.12,
     font = "Source Code Pro"
 )
```

Calling `text!` resets axis limits to be NOT (0, 1). If I add `limits = IRect(0,0,1,1)` to the `text!` command, then the axis limits are again set to (0, 1). 

Generally however, If I set the axis limits once, I want them to stay like this regardless of what else I put into my plot. This option should be supported somehow (and if it is already supported it should be documented)

**Comment by asinghvi17** [comment]
I expect you could pass `limits` again, it is kind of a hack though.
