### ISSUE TITLE
add :showgrid to 2D axis

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#289]
mwe:
```
scplot = scatter(rand(5), rand(5), markersize = 0.1, limits = IRect(0, 0, 1, 1))
scplot[Axis][:showgrid]
```
```
KeyError: key :showgrid not found
```

**Comment by Benoit9** [comment]
Also` :showticks` and `:showaxis` seem defined for Axis3D but not for Axis2D.

`scene[Axis][:visible]=false` does not seem to hide the axes.

I have been setting linewidth and textsize to 0 instead.

**Comment by SimonDanisch** [comment]
on master, this works:
```julia
julia> scatter(rand(10), axis = (showgrid = false,))

julia> scatter(rand(10), axis = (showgrid = (false,true),))

julia> scatter(rand(10), axis = (showticks = (false,true),))

julia> scatter(rand(10), axis = (showticks = false,))

julia> xx[Axis].showticks = (false, false)
(false, false)
```

**Comment by SimonDanisch** [comment]
(AbstractPlotting#master)

**Comment by ani-yadav** [comment]
Hi there. Just tried these suggestions, but the gridlines don't get removed.

```
using CairoMakie
scatter(rand(10), axis = (showgrid = false,)) #grid lines remain visible...
```

Any suggestions?

**Comment by jkrumbiegel** [comment]
It's `xgridvisible` and `ygridvisible`

**Comment by ani-yadav** [comment]
Thanks! sorry if this is the wrong place to ask this, but could you point me to where I can find a list of axis attributes in the docs? Searching the documentation for "xgridvisible" returned no results...

**Comment by jkrumbiegel** [comment]
`?Axis` or here http://makie.juliaplots.org/stable/documentation/api_reference/#Axis
