### ISSUE TITLE
Reduce text displayed on display(scene)

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#290]
`display(scene)` is a very natural thing to type in the console or repl or inline juno evaluation.

However if one does this without `;` at the end, they are in big, BIG trouble. Because an infinite amount of text is starting to render (which encodes the result of `display(scene)`):
```

julia> display(scplot)
GLMakie.Screen(GLFW.Window(Ptr{Nothing} @0x0000000029444220), GLMakie.GLFramebuffer(Observable{Tuple{Int64,Int64}} with 1 listeners. Value:
(1280, 540), (0x00000001, 0x00000002), Texture2D:
                  ID: 1
                Size: Dimensions: x1280x540
    Julia pixel type: RGBA{FixedPointNumbers.Normed{UInt8,8}}
   OpenGL pixel type: GL_UNSIGNED_BYTE
              Format: GL_RGBA
     Internal format: GL_RGBA8
          Parameters: GLMakie.GLAbstraction.TextureParameters{2}(:nearest, :nearest, (:clamp_to_edge, :clamp_to_edge), 1.0f0, UInt32[])
, Texture2D:
                  ID: 2
                Size: Dimensions: x1280x540
    Julia pixel type: Vec{2,UInt16}
   OpenGL pixel type: GL_UNSIGNED_SHORT
              Format: GL_RG_INTEGER
```

It has been **literally minutes** since I've submitted the command and the wall of text is keep going. This should be definitely changed. You could return `nothing` on `display` or if the return value is important the definitely overwrite the default `Base.show`.

**Comment by asinghvi17** [comment]
Would it be easier to make `display(::Scene)` pass the Scene to `display(::AbstractPlotting.PlotDisplay, ::Scene)` instead?   From what I've seen so far `display` does have GUI associations in other packages.

**Comment by SimonDanisch** [comment]
This just needs a show overload for `GLMakie.Screen` - could be a very simple one, since it's encapsulates "internal" state
