### ISSUE TITLE
glTexImage 3D: width too large

### ISSUE THREAD

**Issue by gdkrmr** [JuliaPlots/Makie.jl#291]
Julia 1.1 with Makie 0.9.
```julia
julia> using Makie

julia> volume(rand(506, 720, 1440))
Error showing value of type Scene:
ERROR: glTexImage 3D: width too large. Width: 506
```

**Comment by SimonDanisch** [comment]
yeah, seems like your gpu isn't supporting 3D textures of that size...
You can check the maximum texture size with:
```Julia
using Makie, GLMakie, ModernGL
# simple plot to open a window (needs to be open for opengl)
display(scatter(rand(10)))
glGetIntegerv(GL_MAX_3D_TEXTURE_SIZE)
```
And then just split the volume:
```Julia
vol = rand(506, 720, 1440)
ranges = (1:256, 1:256, 1:256)
scene = volume(ranges..., vol[ranges...])
for i in 1:3
    global ranges
    ranges = ntuple(3) do j
        s = j == i ? last(ranges[j]) : 1
        e = j == i ? size(vol, j) : last(ranges[j])
        s:e
    end
    volume!(ranges..., vol[ranges...])
end

scene
```
Although, my gpu is returning a ridicilous high number here (16384) - and it indeed works for me... Not sure if you have an old gpu, or maybe using your onboard gpu instead of the dedicated one!

**Comment by gdkrmr** [comment]
Is this limited by the amount of video memory?

**Comment by SimonDanisch** [comment]
Not necessarily

**Comment by gdkrmr** [comment]
`glGetIntegerv(GL_MAX_3D_TEXTURE_SIZE)` gives 2048, it's the integrated GPU of an Intel i7 5xxxU processor.

**Comment by SimonDanisch** [comment]
Hm sadly OpenGL isn't really great with this:
```Julia
data returns one value, a rough estimate of the largest 3D texture that the GL can handle. The value must be at least 64. Use GL_PROXY_TEXTURE_3D to determine if a texture is too large. See glTexImage3D. 
```
I'm using `GL_PROXY_TEXTURE_3D` to throw the error, so it's definitely too big^^
