### ISSUE TITLE
Incorrect Bounding boxes?

### ISSUE THREAD

**Issue by tkonolige** [JuliaPlots/Makie.jl#294]
Something is a little wrong with how points in the 3d scatter are handled.

With this test program:
```julia
using Makie
scatter([(1.0,1.0,1.0),(0.9,1.0,1.0), (0.0,0.0,0.0)])
```

I get this plot.
<img width="646" alt="screen shot 2019-02-20 at 3 57 34 pm" src="https://user-images.githubusercontent.com/1501680/53130766-5e62ad80-3528-11e9-8ada-7900a7fb1fde.png">
Notice the weird corner cut out of the point on the right.

I have no clue why this is happening, but it gets to be a big problem when lots of points are close together. It also appears with `linesegments` in 3D.

**Comment by SimonDanisch** [comment]
i'm just about to merge an improvement for this. meanwhile, you can use transparency=true to improve the situation

**Comment by tkonolige** [comment]
`transparency=true` works great. Thanks!
