### ISSUE TITLE
Line not displayed

### ISSUE THREAD

**Issue by mschauer** [JuliaPlots/Makie.jl#30]
The line `z` is not displayed. Uncommenting the third point in z makes the line visible.
```
using Makie, Colors, GeometryTypes
scene = Scene(resolution = (200, 200))
x = [Point3f0(0,1,l) for l in [0., 1., 2., 3.]]
z = [Point3f0(0,0,l) for l in [-0.5, #=0.0,=# 0.5]]
lines(x, linewidth=3.5, color=colorant"black")
lines(z, linewidth=3.5, color=:darkred)

center!(scene)
```

**Comment by mschauer** [comment]
Maybe related, I cannot plot lines with repeating points, e.g. 
```
using Makie, Colors, GeometryTypes
scene = Scene(resolution = (200, 200))
z = [rand(SVector{3,Float64}) for i in 1:10]
lines(z, linewidth=0.5, color=:darkred)
lines([z[1],z[1],z[2],z[3],z[3],z[3],z[4],z[5],z[6],z[7], z[7],z[8],z[9],z[10]], linewidth=3.5, color=:darkred)
center!(scene)
```

**Comment by SimonDanisch** [comment]
sorry, the first one is actually a known problem :( the second one is new :D let me check it out

**Comment by SimonDanisch** [comment]
The first one is fixed by checking for lines with N < 4 and then padding it :P I had some code in Plots.jl which i just haven't ported to Makie yet.

**Comment by mschauer** [comment]
Again thanks for your work. Given that Makie is not even released yet, I am getting good mileage out of it. Check out https://github.com/mschauer/Bridge.jl/blob/master/example/3DExamples.ipynb

**Comment by SimonDanisch** [comment]
Nice notebook! I should make that part of the examples ;)

I think the line generation rendering shader is simply not robust to repeating points. I should just insert a `unique` into the pipeline. Although that will be quite expensive for animated lines without repeating points.

**Comment by mschauer** [comment]
I solved it by adding visually invisible noise. That is a very "Erlang" thing to do.

**Comment by mschauer** [comment]
> should make that part of the examples ;)

Please do! In any case, Bridge and Makie have uncanny interoperability because of the joint `FixedSizeArrays` heritage. See for example https://gist.github.com/mschauer/351ef5af3458192172cfb785443b47e1 . Let's evolve that, endgame being particles moving in Makie following Ordinary or Stochastic Differential equations :-)

**Comment by ffreyer** [comment]
Both of these look fine to me now
