### ISSUE TITLE
Cannot compile GLMakie

### ISSUE THREAD

**Issue by OmarAshkar** [JuliaPlots/Makie.jl#3007]
Hello,

I am trying to use GLMakie. But I am getting error when compiling it. This my traceback
```
julia> using GLMakie
[ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]
â Warning:     GLFW couldn't create an OpenGL window.
â     This likely means, you don't have an OpenGL capable Graphic Card,
â     or you don't have an OpenGL 3.3 capable video driver installed.
â     Have a look at the troubleshooting section in the GLMakie readme:
â     https://github.com/MakieOrg/Makie.jl/tree/master/GLMakie#troubleshooting-opengl.
â @ GLMakie /blue/ufiiseed21kim/omar.elashkar/.julia/packages/GLMakie/OVxAi/src/screen.jl:228
ERROR: LoadError: GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: GLXBadFBConfig
```

Additional Information:
- OpenGL version string: 2.1 Mesa 18.3.4
- julia version 1.8.2
- Redhat 7
- Nvidia GPU

Please guide me through this.

Thank you!

**Comment by SimonDanisch** [comment]
Opengl 2.0 is not enough to run glmakie... If your gpu isnt older than 12 years or so, a discrete nvidia gpu should give you at least opengl 3.3 so i suspect that the drivers arent setup correctly!
