### ISSUE TITLE
[question/documentation/roadmap] macOS OpenGL deprecation: documents on switching backends

### ISSUE THREAD

**Issue by daviehh** [JuliaPlots/Makie.jl#303]
For macos, OpenGL is scheduled to be deprecated (see, e.g. [here](https://arstechnica.com/gadgets/2018/06/the-end-of-opengl-support-other-updates-apple-didnt-share-at-the-keynote/)). Looks like there's currently work on

https://github.com/JuliaPlots/GRMakie.jl
https://github.com/JuliaPlots/CairoMakie.jl

but documentation for these seems to be missing, e.g. 

```
using CairoMakie, AbstractPlotting
x = LinRange(0,3pi,200)
y = sin.(x)
c=lines(x,y)
```
does not return anything, `typeof(c)` gives `Scene`, and `display(AbstractPlotting.PlotDisplay(),c)` gives

> (CairoMakie.CairoBackend(SVG::RenderType = 0, "/var/folders/d8/hcnrglbn5ts52xx1hp_wx4480000gn/T/tmpcOPoFU/cairo.svg"), Scene(nothing, Events(Observable{GeometryTypes.HyperRectangle{2,Int64}} with 1 listeners. Value:
> GeometryTypes.HyperRectangle{2,Int64}([0, 0], [0, 0]), Observable{Float64} with 0 listeners. Value:
> 100.0, Observable{Bool} with 0 listeners. Value:
> ......(long text output)

looks like the plot is saved to a temporary svg file `cairo.svg` but no gui is displayed.

**Comment by c42f** [comment]
I'm not sure what the larger plan is for the various backends, but it might make sense to support hardware accelerated plotting on macOS via the WebGL backend when it's eventually written. The reason being that there exist third party OpenGL ES middleware layers for macOS and OpenGL ES is almost the same as WebGL.

Whether such a stack of middleware would actually work out is unknown though. It would presumably look something like `AbstractPlotting->GLESMakie->GLOVE->MoltenVK->Metal`... which doesn't exactly inspire confidence!

**Comment by SimonDanisch** [comment]
There will be multiple backends for Makie (there arlready are), so by the time this happens, it will likely not threaten Makie. It mainly depends on how well Makie matures ;) If we are at a state in ~2 years, were Makie is widely used with a solid group of open source developers, I'm pretty sure we'll be well equipped to still offer a performant backend for Makie on OSX without OpenGL.
If not, well, then Makie probably kind of failed, and the question isn't relevant anymore ;)

**Comment by jlewis91** [comment]
@SimonDanisch Just wanted to post a note here as someone with an Apple Silicon Mac as this will probably come up increasingly in the future:

1) glfw seems to fail on Apple Silicon: https://github.com/glfw/glfw/issues/1809; haven't tested Makie plots explicitly, but the error comes up on installation of Makie
2) OpenGL is deprecated  (but available) on Apple Silicon https://developer.apple.com/documentation/xcode/porting_your_macos_apps_to_apple_silicon
3) WGLMakie works brilliantly in Safari with Pluto.jl on Apple Silicon as long as the WebGL 2.0 experimental feature is turned on

**Comment by SimonDanisch** [comment]
Thanks, that's really useful to know :)
