### ISSUE TITLE
Toggle visibility of plot elements

### ISSUE THREAD

**Issue by tkonolige** [JuliaPlots/Makie.jl#305]
Is there a way to toggle visibility of plot elements? I'd like to have a key toggle line or points in my plot.

**Comment by asinghvi17** [comment]
I believe @Datseris has done that for JuliaDynamics/InteractiveChaos.jl but I'm not sure how.  I believe it is tied into the `transparency` keyword argument in the plotting command, though - if you can make a button trigger that, then it should work.  (I believe that the argument should be Boolean.)

**Comment by Datseris** [comment]
Yeap. We make the transparency (i.e. fourth entry of the color `RGBA`) an observable and upon click set the transparency to 0. :)

**Comment by tkonolige** [comment]
I hadn't thought of using an observable. That works great. It's easier if I use the `visible` keyword instead of the `transparency` one.

**Comment by SimonDanisch** [comment]
`plot.visible = false` is the way to go ;)
