### ISSUE TITLE
Makie 0.9.3 Hanging on new install 

### ISSUE THREAD

**Issue by perrinmeyer** [JuliaPlots/Makie.jl#315]
I just tried to install Makie on both my Desktop and Laptop, both recently upgraded to Ubuntu 18.10 (Makie 0.9.3). I build julia v1.1 from git sources and all the tests pass. 

On Both, Makie seems to build fine, and even pass all the tests, but when I try to even start a simple example, it hangs on both my computers -- Ubuntu gives me the "Makie not responding Dialog - Force Quit?" which then does not work, and the graphics hang and I have to hard reboot. 

Any thoughts?

**Comment by perrinmeyer** [comment]
I compiled GLFW3 from source https://github.com/glfw/glfw and I removed the ubuntu libglfw, and now after a LONG wait (I still get the Ubuntu "Makie Not responding" dialog), but eventually I get a plot...  Subsequent plots are a lot faster...

**Comment by asinghvi17** [comment]
About the long time to first plot - try static compiling a binary for Makie, it basically eliminates precompilation time!  There are instructions at the bottom of the README, and you can check out the documentation of PackageCompiler.jl to find out more!

**Comment by perrinmeyer** [comment]
Yes, I was able to get PackageCompiler to work, now when i load the sys.so image, The time to first plot is under 10 seconds.

I get this warning, which I assume is harmless...

``perrin@pop-os:~/MakieGallery.jl/examples$ jm
┌ Warning: QuartzImageIO.jl can only be used on Apple macOS. Suggested usage is
│     @static if Sys.isapple()
│         using QuartzImageIO
│         # QuartzImageIO specific code goes here
│     end
└ @ QuartzImageIO ~/.julia/packages/QuartzImageIO/9DhKg/src/QuartzImageIO.jl:723

**Comment by SimonDanisch** [comment]
I greatly improved this on GLMakie#master & AbstractPlotting#master! It now shows a load screen, and also I inserted lots of polling events inbetween function calls, so it has a chance to refresh the window while compiling the julia functions ;)
