### ISSUE TITLE
Video resolution

### ISSUE THREAD

**Issue by zsoerenm** [JuliaPlots/Makie.jl#316]
How do I set the video resolution when recording with the `record` function? I know that there is an optional parameter `resolution`  for the scene, but it does not have an effect on the video resolution.

For example:

```julia
using Makie

 scene = Scene(resolution = (1000,1000)) # Does not effect the video resolution
 f(t, v, s) = (sin(v + t) * s, cos(v + t) * s)
 time_node = Node(0.0)
 p1 = scatter!(scene, lift(t-> f.(t, range(0, stop = 2pi, length = 50), 1), time_node))[end]
 p2 = scatter!(scene, lift(t-> f.(t * 2.0, range(0, stop = 2pi, length = 50), 1.5), time_node))[end]
 points = lift(p1[1], p2[1]) do pos1, pos2
     map((a, b)-> (a, b), pos1, pos2)
 end
 linesegments!(scene, points)
 N = 150
 record(scene, "interaction.mp4", range(0, stop = 10, length = N)) do i
     push!(time_node, i)
end
```
Resizing the window during the recording gives weird artefacts.

**Comment by SimonDanisch** [comment]
Can you give some additional details on how you run this? If I execute this (and also if I change the resolution), it does get reflected in the output!

**Comment by zsoerenm** [comment]
Ah okay, if I run it through a normal terminal the set resolution does indeed make a difference.
I was running in in Atom and the same plot was shown in the plot pane as well as in a seperate window. I guess the plot pane restricted the size to whatever is the maximal size of the plot pane.
