### ISSUE TITLE
PackageCompiler error missing deps.jl

### ISSUE THREAD

**Issue by sdewaele** [JuliaPlots/Makie.jl#322]
As described in the latest docs, I am using the latest version of Makie, installed using:
```
add Makie#master AbstractPlotting#master GLMakie#master
```
I also added `MakieGallery#master`. However, when I attempt the [package compilation](https://github.com/JuliaPlots/Makie.jl#precompilation), I get an error indicating a missing `deps.jl` file:
```
...
[ Info: used 273 out of 273 precompile statements
┌ Info: new environment will be placed at /home/myusername/.julia/packages/PackageCompiler/oT98U/packages/Project.toml
└ @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:575
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: LoadError: LoadError: LoadError: LoadError: could not open file /home/myusername/.julia/packages/GLMakie/nDrlO/deps/deps.jl
```
I am using Julia 1.1.0 (I've seen the same error also in 1.0.0). GLMakie indeed does not appear to contain the `deps.jl` file. Any ideas? By the way, I suspect that the following comment in this [post](https://github.com/JuliaPlots/Makie.jl/issues/311#issuecomment-469883867) may be correct:

> Is it possible that `PackageCompiler.compile_incremental(:Makie, :AbstractPlotting, force = false)` uses the latest tagged versions (and not `#master` specified in the default environment) in it's own internal environment? If so, how should one precompile after updating packages?

**Comment by sdewaele** [comment]
Okay, this may be related to the fact that `GLMakie` may not build correctly on my system. Interestingly, when I call `]build GLMakie` in the REPL it appears to work, but when I execute GLMakie's `deps/build.jl`, I get an error.

**Comment by SimonDanisch** [comment]
Did you look closely at any warnings or looked into the build log? What is the error?

**Comment by asinghvi17** [comment]
Is this still an issue now?
