### ISSUE TITLE
white borders around some objects

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#327]
I'm trying to draw 3D stick/lollipop plots with a combination of `linesegments` and `scatter`. I have some visual glitches where it looks like the lines are being drawn over the scatter dots, and they have a white line around them.

![image](https://user-images.githubusercontent.com/734386/55089401-b9d20f00-5083-11e9-83c9-16846f3335e0.png)

Here's how i made the plot:

```julia
julia> t = range(0, 10, length=40)
0.0:0.2564102564102564:10.0

julia> sig = exp.(im*t) + exp.(2im*t);

julia> function sticks(x, y, z)
           origy = zeros(length(y))
           origz = zeros(length(z))
           linesegments(
               reshape(permutedims([x x]), :),
               reshape(permutedims([origy y]), :),
               reshape(permutedims([origz z]), :))
       end
sticks (generic function with 1 method)

julia> sticks(t, real(sig), imag(sig))

julia> scatter!(t, real(sig), imag(sig))
```

**Comment by SimonDanisch** [comment]
Yeah, that's a problematic artifact right now... You can try to set `transparency = true` for the lineplot.

**Comment by ssfrr** [comment]
yeah, that looks much nicer. thanks!
