### ISSUE TITLE
mouse sensitivity too high when rotating 3D scene

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#33]
MWE:

```julia
using Makie, GeometryTypes, Colors

scene = Scene()
dots = scatter(rand(10), rand(10), rand(10))
center!(scene)
```

When I click and drag on the scene window, it rotates very quickly (about 1cm is a full rotation). I have a relatively high DPI screen, so if it's measuring mouse movement in pixels that would make it more sensitive.

**Comment by SimonDanisch** [comment]
Good point! I need to test this on my high dpi laptop, and likely should use screen `millimeter` as the unit ;)

**Comment by pfitzseb** [comment]
Mouse sensitivity also feels strange (too low) when panning -- I'd kinda expect the cursor to stay fixed to the scene instead of moving much faster.

**Comment by SimonDanisch** [comment]
Are you by any chance on macos? I think in a 2d scene, the mouse should always move with the scene when panning.

**Comment by pfitzseb** [comment]
No, Manjaro. I'm using a flat mouse profile though, so that might be a cause?

**Comment by cdsousa** [comment]
Is there any available workaround for this?

**Comment by asinghvi17** [comment]
You can decrease rotation speed by setting `scene.camera.rotationspeed[]`

**Comment by cdsousa** [comment]
@asinghvi17, I cannot find any `rotationspeed`...

**Comment by asinghvi17** [comment]
Ah, you need `cameracontrols(scene).rotationspeed[]` @cdsousa

**Comment by pauljurczak** [comment]
The default value of `cameracontrols(scene).rotationspeed[]` was 0.3. Even if I set it to 0.0001, it still rotates very, very fast.

**Comment by asinghvi17** [comment]
Could you try something like:
```julia
cameracontrols(scene).rotationspeed[] = 0.01f0
```
to make sure that the provided value is Float32?

btw, this looks like a pretty good default to me.  @SimonDanisch could you test this out on your machine?  If it makes sense, I'll PR the change.

**Comment by pauljurczak** [comment]
@asinghvi17 
My error. I was redefining `scene` object. It works just fine now. BTW, `0.01f0` is not necessary - `0.01` works just fine.

Agree with 0.01 being much better default than 0.3.

**Comment by sdewaele** [comment]
+1 for less sensitivity by default
