### ISSUE TITLE
What does campixel do?

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#330]
Hello,

I would like to understand what does campixel do. In particular, why in some case we wrap it around a scene and in some case we don't?

Best,

**Comment by asinghvi17** [comment]
I believe that `campixel!` is generally used when you want something not to be displayed on an axis, and it communicates the correct bounding box information (i.e., of the actual thing, not the axes) to `vbox` or `hbox`.

**Comment by SimonDanisch** [comment]
`campixel` is a "fixed" camera, that interprets your data in pixel units. Because its fixed, it also has a fixed boundingbox (you can't zoom in), so that's why I can use the boundinbox more easily in vbox/hbox.
