### ISSUE TITLE
How to rotate 2D scene?

### ISSUE THREAD

**Issue by wsrinin** [JuliaPlots/Makie.jl#333]
Hi, 

I have a hard time figuring out how to rotate 2D plot such as scatter or barplot. The things is that when I use rotate!  I can figure out the right quarternion to use. It seems that my plot essentially slanted in the 3D space. What is the correct way to do this?

**Comment by asinghvi17** [comment]
Try passing a 2-tuple of angles?

**Comment by wsrinin** [comment]
Hi,

I did put it does not seem to work

`s = barplot(ones(10), color =cl, rotations = (\theta1, \theta2) )`

does not seem to do anything.

**Comment by wsrinin** [comment]
If I do this it give incorrect result

`rotate!(s, qrotation(SVector{3}(1.0, 0.0, 0.0), π/2))`

**Comment by asinghvi17** [comment]
As I understand it, you're looking to transpose the graph - swap the x and y axes, right?

**Comment by wsrinin** [comment]
In this case yes, but I would love to know how to do rotation of 2d scene
in general. The problem I think is that the camera field does not get
update correctly. It treat the 2D as if it is a 3D object,

**Comment by asinghvi17** [comment]
I suppose you could try to pull off just using a `cam3d!` in the `camera` argument and rotating it that way, but it's hardly elegant...

**Comment by wsrinin** [comment]
Yep, that is what I attempt to do put it is really complicated.

**Comment by asinghvi17** [comment]
Maybe put `camera = cam3d!` and then `rotate_cam!` instead?

**Comment by SimonDanisch** [comment]
Do you want to rotate the whole scene or just a single plot object?

**Comment by asinghvi17** [comment]
ping @wsrinin

**Comment by goretkin** [comment]
I put some code in https://github.com/JuliaPlots/Makie.jl/issues/1298 that rotates a node in the scene graph. Note that there is an issue with CairoMakie, however. 

I also asked a related question here: https://discourse.julialang.org/t/permute-x-and-y-axes-of-a-makie-axis/67826
