### ISSUE TITLE
Error plotting a *large* matrix

### ISSUE THREAD

**Issue by giordano** [JuliaPlots/Makie.jl#335]
While trying to reproduce [this issue](https://github.com/JuliaAstro/AstroImages.jl/issues/10), I gave Makie.jl a try, however it fails to plot, with `heatmap`, a matrix with size 24900 x 26620 (but also 170000 x 17000):

```julia
julia> using AbstractPlotting, GLMakie, Makie

julia> heatmap(rand(Float32, 24900, 26620))
Error showing value of type Scene:
ERROR: glTexImage 2D: width too large. Width: 24900
[...]
```

Images this large are relatively common in astronomy and currently I don't see any tool in Julia able to visualise them.

**Comment by asinghvi17** [comment]
https://github.com/JuliaPlots/Makie.jl/issues/291#issuecomment-464798807 may have a solution to this

**Comment by giordano** [comment]
I'm talking about a 2D image, not a 3D one, thus I guess that `glGetIntegerv(GL_MAX_3D_TEXTURE_SIZE)` is unrelated.  BTW:
```
julia> glGetIntegerv(GL_MAX_3D_TEXTURE_SIZE)
-1
```

**Comment by asinghvi17** [comment]
That's weird, the heatmap command 'works' on my machine (although its output is suspect).  Are you plotting on a headless system or something?  `glGetIntegerv(GL_MAX_3D_TEXTURE_SIZE)` should return a number >= 64...

**Comment by asinghvi17** [comment]
Also, what I meant to show when linking to that was 
```julia
vol = rand(506, 720, 1440)
ranges = (1:256, 1:256, 1:256)
scene = volume(ranges..., vol[ranges...])
for i in 1:3
    global ranges
    ranges = ntuple(3) do j
        s = j == i ? last(ranges[j]) : 1
        e = j == i ? size(vol, j) : last(ranges[j])
        s:e
    end
    volume!(ranges..., vol[ranges...])
end

scene
```

for which you could do the same in 2 dimensions with heatmaps.

**Comment by giordano** [comment]
> Are you plotting on a headless system or something?

Not sure what you mean by "headless system", it's a MacBook running Arch Linux.

**Comment by asinghvi17** [comment]
Hmm...does Makie work otherwise?

(What I meant by a headless system is one with no display, like an SSH-only server or something).

If your Macbook Air is old enough, it may not support OpenGL, meaning Makie might not work there..

**Comment by giordano** [comment]
```julia
julia> using Makie, GLMakie, ModernGL

julia> heatmap(rand(Float32, 10_000, 10_000))
```

![image](https://user-images.githubusercontent.com/765740/55676207-b03c7880-58c7-11e9-960b-3cdf56c75cfa.png)

**Comment by asinghvi17** [comment]
Perhaps this approach might work?

```julia
using Makie
heatmap(rand(Float32, 10_000, 10_000))
heatmap!(10000:20000, 10000:20000, rand(Float32, 10000, 10000))
heatmap!(10000:20000, 0:10000, rand(Float32, 10000, 10000))
heatmap!(00000:10000, 10000:20000, rand(Float32, 10000, 10000))
```
which yields

<img width="480" alt="Screen Shot 2019-04-06 at 8 11 01  08200PM" src="https://user-images.githubusercontent.com/32143268/55676722-2cbf5f00-58a8-11e9-955d-9939b5d7bac1.png">

**Comment by asinghvi17** [comment]
Essentially, assemble the whole plot from slices of data, thereby making the texture non continuous and circumventing the OpenGL error.  It fails on mine too (although silently).  Perhaps this is something we should add to the docs!

**Comment by SimonDanisch** [comment]
yeah this is too big for the gpu and needs tiling!

**Comment by asinghvi17** [comment]
Is there a value that can be accessed which gives the max 2d texture size (similar to `glGetIntegerv(GL_MAX_3D_TEXTURE_SIZE)`)?

**Comment by giordano** [comment]
> yeah this is too big for the gpu and needs tiling!

I guess it uses a different way to plot figures, but matplotlib has no problem to deal with matrices this large and is also relatively fast.

These large matrices are not rare in astronomy and it would be great if it were possible to handle them more easily.

**Comment by asinghvi17** [comment]
I suspect that could be written into a recipe (something like `bigheatmap`)?

**Comment by asinghvi17** [comment]
Since heatmap is a primitive, would we have to build this into every backend?

**Comment by asinghvi17** [comment]
We _could_ recursively break up too-large heatmaps.  Not sure if that's doable, though - might need some massaging on the AbstractPlotting end

**Comment by SimonDanisch** [comment]
I think something like that should be handled by another package creating a recipe to view very large arrays

**Comment by tecosaur** [comment]
I just ran into this issue when trying to run `heatmap` on a large matrix of mine (30k x 30k). Is the current suggestion that somebody creates a `GLMakieLargeHeatmapTilingWorkaround.jl` package?

**Comment by asinghvi17** [comment]
Yes, I would go with that for now.
