### ISSUE TITLE
pan/zoom on 2D graphs

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#34]
When plotting high-density data I often use the pan/zoom functions in PlotlyJS. It would be super useful to be able to navigate similiarly in a 2D Makie scene.

PlotlyJS's box zoom behavior is also very nice, where it lets you either define a rectangle to zoom or zoom just along the x or y axes, depending on how you drag. That seems lower-priority than basic pan/zoom though.

**Comment by SimonDanisch** [comment]
This is actually implemented in a branch and will be part of the first release :)

**Comment by ssfrr** [comment]
great!

BTW I'm really enjoying playing around with Makie so far. It's soooo fast!

**Comment by timholy** [comment]
One of my episodic needs for plotting has come up. Any updates on this? Is there a branch I could play with/help with?

**Comment by grero** [comment]
The ability to zoom on 2d plots would indeed be useful to me, too. Any updates on this?

**Comment by SimonDanisch** [comment]
This should be long implemented ;) Maybe we want it to behave a bit different - but that should go into another issue!

**Comment by grero** [comment]
oh, cool! Just to clarify, though, the current way this zooming works is to zoom the entire plot, right, basically like a 2D image of sorts? That's what I see when scroll the mouse on a 2D plot. I guess what I had in mind was something where the axis limits are updated as the user zooms in/out. Is there a separate issue for this somewhere?
