### ISSUE TITLE
Improving precompilation using SnoopCompile for Makie

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Makie.jl#343]
I was poking around some packages today, and thought of something - we could bundle a 'cache' generated by SnoopCompile into Makie, as described by their README.  We could generate it like this:

```julia
using SnoopCompile

### Log the compiles
# This only needs to be run once (to generate "/tmp/colortypes_compiles.log")

SnoopCompile.@snoopc "/tmp/colortypes_compiles.log" begin
    using Makie, Pkg
    include(joinpath(dirname(dirname(pathof(Makie))), "test", "runtests.jl"))
end

### Parse the compiles and generate precompilation scripts
# This can be run repeatedly to tweak the scripts

data = SnoopCompile.read("./tmp/makie_compiles.log")

pc = SnoopCompile.parcel(reverse!(data[2]))

SnoopCompile.write("./precompile", pc)
```
I'll run some performance tests on my machine and post those.  It seems like an interesting idea, but it probably would be a pain for package development, and would *definitely* increase precompile time - but precompile time is a small thing to give up in exchange for time-to-first-plot. 

This is just an idea I felt like throwing out there - it may not work, but if it does it would be lovely.

**Comment by SimonDanisch** [comment]
thats exactly what package compiler does ;)

**Comment by SimonDanisch** [comment]
Not 100% like that, but PackageCompiler is pretty much the only option ;) precompile isn't caching any output of `precompile` calls (ironic, i know)

**Comment by asinghvi17** [comment]
Dang...I'd thought that there might be a way to form a cache which would at least alleviate the inference burden, but sadly no :(

Well, we still have PackageCompiler at least :P

**Comment by timholy** [comment]
Yep, the caching is not as extensive as it needs to be. Potential fix in https://github.com/JuliaLang/julia/pull/31466, whenever I get time to finish it. Until then, PackageCompiler seems to be the only viable approach. (And even then PackageCompiler will be needed if you want cut down on the LLVM time.)
