### ISSUE TITLE
Animation interface

### ISSUE THREAD

**Issue by kskyten** [JuliaPlots/Makie.jl#346]
I'm interested in making mathematical animations similar to [Manim](https://github.com/3b1b/manim). I believe [`Observables`](http://juliaplots.org/MakieGallery.jl/stable/interaction.html#) make this a lot easier, but it would be nice to have some additional tools on top of this (e.g. interpolation, keyframes). I would like to brainstorm some ideas for what the interface should look like. I was looking at https://animejs.com/, https://popmotion.io/pure/ and https://acko.net/blog/mathbox2/ for inspiration.

**Comment by kskyten** [comment]
I decided to model the API after [Popmotion Pure](https://popmotion.io/pure/).

How do I run the animations in the background? I will need to run something like the following without blocking the REPL and control the animation with `play()`, `pause()`, etc.
```julia
mutable struct Ticker
    t0
    elapsed
end

Ticker() = Ticker(time(), 0.0)
tick!(t) = t.elapsed = time() - t.t0

function loop(t, s)
    while t.elapsed < s
        tick!(t)
    end
end
```

**Comment by SimonDanisch** [comment]
That looks like what I tried at some point.
Have a look at the code from thise line to the bottom:
https://github.com/SimonDanisch/Visualize.jl/blob/master/src/events.jl#L298
I'm not sure how this API can work anymore in Makie, but since Makie's design was heavily inspired by Visualize, most things should port fine ;)

**Comment by kskyten** [comment]
Thanks, that looks like a good place to start. I also found [this code](https://github.com/JuliaPlots/AbstractPlotting.jl/blob/b8dbc7d95b6c5a45b1e995903675a7f07fc71e28/src/interaction/gui.jl#L218) for a play button, which seems relevant. Can you explain it?

**Comment by dpsanders** [comment]
I have also been thinking exactly along these lines and am very interested!

**Comment by kskyten** [comment]
[Animations.jl](https://github.com/jkrumbiegel/Animations.jl) was established after this issue was opened. This is currently the best option for animations in Makie.
