### ISSUE TITLE
Picking a line is too difficult

### ISSUE THREAD

**Issue by dpsanders** [JuliaPlots/Makie.jl#349]
Is it possible to increase the tolerance for picking a line?

**Comment by asinghvi17** [comment]
If you mean increasing the bounding box, then I think so; but are you trying to select a line using the mouse?  If so, how are you selecting it?

**Comment by dpsanders** [comment]
Yes, selecting using mouse -- in the "standard" way from https://simondanisch.github.io/ReferenceImages/gallery//edit_polygon/index.html, i.e. 
```
plot, _idx = mouse_selection(scene)
                 if plot == pplot
```

**Comment by SimonDanisch** [comment]
you could draw a thicker transparent line underneath... or implement your own is point close to line ;) That'd be nice to have as a fallback anyways

**Comment by ffreyer** [comment]
https://github.com/JuliaPlots/AbstractPlotting.jl/pull/696 + https://github.com/JuliaPlots/GLMakie.jl/pull/177 make `pick(scene, pos, range)` more available (it picks the closest point within range to the given position) and it adds a `pick_sorted(scene, pos, range)` for when you want to filter out plots yourself (which is very useful with Axis drawing a background rectangle).

https://github.com/JuliaPlots/AbstractPlotting.jl/pull/677 also adds some magic for finding the closest point on a line in both 2D and 3D.

I think this can be closed with those pr's merged

**Comment by ffreyer** [comment]
Minor update on this - all these pr's have been merged now. If you want to pick a line with tolerance you can use something like
```julia
for (plot, idx) in pick_sorted(fig.scene, mouseposition_px(fig.scene), 10)
    if plot == my_line_plot
        do_something(plot, idx)
        break
    end
end
```

Note that for 2d `Axis` there is a mesh in the background which will take priority with `pick`. So you need to sort through selections like in the example. In 3d you can probably get by with `pick(scene, pos, range)`.

There also a `mouse_selection(scene, range)` which calls `pick(scene, pos, range)`.
