### ISSUE TITLE
How to detect mouse drag on axis?

### ISSUE THREAD

**Issue by bryaan** [JuliaPlots/Makie.jl#351]
Can someone please post a quick snippet of how one would detect mouse drags on a 2D axis.

I'm interested in then updating the bounds to create an interactive axis.  Seems like it shouldn't be much effort.

**Comment by asinghvi17** [comment]
I believe there might be an implementation in JuliaDynamics/InteractiveChaos

**Comment by ffreyer** [comment]
MakieLayout has dragging in its mouse state machine. Some relevant functions are:

```julia
mouseevents = addmouseevents!(scene[, plots_or_bbox])

onmouseleftdrag(mouseevents) do event
    px_delta = event.px - event.prev_px
    data_delta = event.data - event.prev_data
    ...
end

onmouseleftdragstart(callback, mouseevents)
onmouseleftdragstop(callback, mouseevents)
```

You can also do this through the normal events:

```julia
dragging = Ref(false)
last_mpos = Ref(Point2f0(NaN))
on(events(fig).mousebutton) do event
    dragging[] = event.button == Mouse.left && event.action == Mouse.press
end
on(events(fig).mouseposition) do px_pos
    if dragging[]
        # do stuff ...
        last_mpos[] = px_pos
    end
end
```

I'll close this since its is just a question and at this point quite old.
