### ISSUE TITLE
Video resolution decreased when frame rate is 60.

### ISSUE THREAD

**Issue by Volcano2333** [JuliaPlots/Makie.jl#352]
If the frame rate is 24, it works and the resolution is good,
but if I set the frame rate at 60, the resolution of video sharply decreased.
How can I get a high resolution video with 60 frames.

```
scene = Scene(resolution = (1000, 1000))
mytime = Node(1.0)
f1(n) = xyzLog[:,Int(3n-2)],xyzLog[:,Int(3n-1)],xyzLog[:,Int(3n)]
meshscatter!(lift(a -> f1(a), mytime),limits = FRect3D(Vec3f0(-20, -20, -20), Vec3f0(40, 40, 40)),markersize=0.5)
record(scene, "E:/test.mp4", 1:1000; framerate = 24) do i
    mytime[] = i
end
```

**Comment by asinghvi17** [comment]
Are you on AbstractPlotting master?

**Comment by Volcano2333** [comment]
> Are you on AbstractPlotting master?

Thank you. I know what went wrong. After I installed AbstractPlotting master, it works.
