### ISSUE TITLE
would be nice to plot Cone

### ISSUE THREAD

**Issue by Jinwei1987** [JuliaPlots/Makie.jl#353]
I can plot a cone by 

n = 200
θ = [0;(0.5:n-0.5)/n;1]
φ = [(0:2n-2)*2/(2n-1);2]
x = [cospi(φ)*sinpi(θ) for θ in θ, φ in φ]
y = [sinpi(φ)*sinpi(θ) for θ in θ, φ in φ]
z = @. sqrt(x^2 + y^2)
surface(x, y, z)

But it does not looks nice enough. I would be good there is some thing similar like Sphere

**Comment by SimonDanisch** [comment]
You mean something like:
```Julia
mesh(Sphere(Point3f0(0), 1f0), color = rand(10, 10))
```
?

**Comment by Jinwei1987** [comment]
No, I mean Cone.

<img width="635" alt="Screen Shot 2019-05-15 at 7 12 25 PM" src="https://user-images.githubusercontent.com/28111060/57798819-8176b500-7745-11e9-9cea-71a690ff1049.png">

**Comment by edljk** [comment]
`Cylinder` type may be easily adapted to create a cone type.

**Comment by SimonDanisch** [comment]
Sorry for the slow answer, but this works:
```julia
n = 200
θ = LinRange(0, 0.5, 100)
φ = LinRange(0, 2, 100)
x = [cospi(φ)*sinpi(θ) for θ in θ, φ in φ]
y = [sinpi(φ)*sinpi(θ) for θ in θ, φ in φ]
z = sqrt.(x.^2 + y.^2)
surface(x, y, z, shading = false)
```
Somehow the normals get really messed up in that version, so i had to set shading=false, which is probably a good thing to do anyways.

**Comment by Jinwei1987** [comment]
thanks!
