### ISSUE TITLE
What layouting capabilities are planned for Makie?

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/Makie.jl#354]
I really like the idea of makie as a platform that allows fast gpu rendered plots to be updated in real time. I come from matplotlib and there it's not possible to do anything close to that.

I haven't really taken a deep dive into this package because early on I noticed that many smaller aspects I'd need for standard plots are not implemented yet, such as font or marker size in display instead of data coordinates, which is of course understandable for a one man show package :) 

But one thing I'm curious about is the hbox vbox system that seems to be used for layouting. In the examples I've seen layouts where everything is kind of just placed in a rough grid but axes are not placed with spines aligned to each other.

I think for what this package aims to be (the default julia plotting package) it's vitally important to have a good layouting mechanism. I really like the idea of matplotlibs constrained layout that was introduced relatively recently. Ideally, to fine tune plots I would like to be able to align any objects with anything else in the scene of I so choose. Like aligning the title of one plot with the spine of another, or something like "this text is always supposed to be 6pt below the midpoint of these two subplot corners" (a little bit like constraints are set up for example in iOS development). In matplotlib's case you can see that if this capability is not built into the foundations it can be very hard to add later. What is the plan for Makie in this regard, are you planning to add constrained layouts and a solver for that?

In the end I believe that "publication ready" is a phrase that a lot of plotting packages use once they offer a certain subset of capabilities, but in my experience it's exactly the small stuff that's super important. Like making precise layouts, having good font support and so on. So I'm rooting for Makie to become the best at these things as well, not just speed.

**Comment by mkborregaard** [comment]
See also https://github.com/JuliaPlots/Makie.jl/issues/183

**Comment by SimonDanisch** [comment]
You can already move/scale/rotate any plot or scene completely freely in 2D and 3D.
So any kind of layouting API should be possible on top of that.
It's just a matter of implementing the nice APIs and implementing the solvers.
Since anyone could implement a solver outside of Makie, I just hope someone else will create a layout constraint solver, and I can just use it in Makie ;) That I write one myself isn't very likely at the moment, since there is a long list of other priorities that come first.

**Comment by jkrumbiegel** [comment]
Matplotlib is using this one: https://pypi.org/project/kiwisolver/

And about the font sizes, how are transforms handled exactly in Makie? In Matplotlib e.g. I sometimes have to place text in axis coordinates in the x component, but in figure coordinates in the y component. For this I can access the different transforms and pick the parts that I need. I think this system and a constraint solver would have to go hand in hand so that constraints can be specified in multiple reference frames, depending on what is needed.

**Comment by asinghvi17** [comment]
Another problem is how font sizes are handled - there doesn't seem to be a consensus on whether to use pixels, typographical points, device-independent pixels, et cetera...

**Comment by grero** [comment]
My vote is for using typographical points for text since most people are familiar with those units. Pixels could also work, but it would entail, at least for me, a mental calculation every time I use them, where as I know intuitively what a 12pt font looks like. Anyway, just my two cents : )

**Comment by SimonDanisch** [comment]
There doesn't need to ne any consesus ;) We'll just offer the different units :)

**Comment by jkrumbiegel** [comment]
I also think pt are a good unit for text and therefore also for line thickness etc to make them match visually, but ideally with unit support you could just specify whatever unit you want for whatever element and it would be resolved depending on the output mode. I thought that was especially convenient to do in Julia syntax wise?

When I prepare figures for a paper, I mostly want to make sure font sizes in figure and text match, so the export to PDF for example would need to honor pt measurements. For all screen based visualizations I think it doesn't matter what the units are as long as you can easily scale everything up and down with one setting. That means retina screens, projectors, lower resolution displays, etc. should be easy to accommodate by tweaking one parameter.

**Comment by jkrumbiegel** [comment]
> You can already move/scale/rotate any plot or scene completely freely in 2D and 3D.
> So any kind of layouting API should be possible on top of that.
> It's just a matter of implementing the nice APIs and implementing the solvers.
> Since anyone could implement a solver outside of Makie, I just hope someone else will create a layout constraint solver, and I can just use it in Makie ;) That I write one myself isn't very likely at the moment, since there is a long list of other priorities that come first.

I have tried to port the Rhea constraint solver to Julia [,](https://github.com/jkrumbiegel/Rhea.jl) mostly to see if I could do it. But now I've implemented most of it I think, so maybe you want to take a look at it, if it could be useful for Makie. As I said earlier, I do think that having this functionality for subplot layouts would be great.

**Comment by SimonDanisch** [comment]
Woah, that's awesome :) Can you give a simple example how I would use it to calculate a layout?

**Comment by jkrumbiegel** [comment]
You specify variables and create constraints with these variables using ==, <= or >=. There's this part in the tests where I tried something like a rectangle inside another rectangle with spacers:

```julia
cont_w = variable()
cont_h = variable()
inner_w = variable()
inner_h = variable()
inner_t = variable()
inner_b = variable()
inner_l = variable()
inner_r = variable()
solver = simplex_solver()

add_constraints(solver, [
    cont_w == 1000,
    cont_h == 800,
    inner_w == 2 * inner_h,
    inner_t == inner_b,
    inner_t >= 60,
    inner_l >= 30,
    cont_w == inner_l + inner_r + inner_w,
    cont_h == inner_t + inner_b + inner_h,
    inner_l == inner_r
])
```
Everytime you put in a new constraint the solver updates and the variables change their values accordingly. So here I want the container to have size 1000x800, the inner rectangle should have aspect ratio 2 to 1, the spacings on the left and the right are the same, as are the ones on the top and the bottom. You can also make required constraints that can't be broken, or strong, medium or weak ones that will be broken if necessary.

**Comment by SimonDanisch** [comment]
This sounds like we need some high-level language for this. 
Incidentally, I was contemplating to write a Makie renderer for: https://github.com/yurivish/Hyperscript.jl ... I'm guessing that Rhea is exactly the kind of solver I'd need for this - and looks like Hyperscript is exactly the kind of language we'd want to use to lay down such constraints.

**Comment by jkrumbiegel** [comment]
Yes I think something more high-level like that would make sense, it would get tedious to spell out all of these constraints manually. Just want to say, though, that I don't completely understand the math or logic behind the solver, I mostly tried to translate the c++ source to julia :) And I did encounter some bugs along the way because it wasn't always clear to me whether some action in c++ created a new object or referenced an old one across multiple function calls. There are a lot of mutable structs and dictionaries going around that allow all this updating, but I found that can make it hard to track down where exactly something went wrong

**Comment by SimonDanisch** [comment]
Fair enough ;) Guess that'd even more reason to start using it to find all those nasty bugs^^ Although that sounds really annoying to debug, because you likely always just know "something looks wrong" but no error or nothing. Ah well...

**Comment by jkrumbiegel** [comment]
Yes, I learned some time ago that having immutability and pure functions is great, but at least here it wasn't possible (for me) ;) And it is annoying to debug, so hopefully in a first piloting phase it will become clearer if this is a good way to go or not

**Comment by timholy** [comment]
This is really cool @jkrumbiegel. FYI, [Gadfly](https://github.com/GiovineItalia/Gadfly.jl) has long had a nice layout engine, and last I checked (about 3 years ago :smile:) it was based on linear programming. While there are something things about Gadfly that I would avoid emulating, I suspect the layout engine might be relatively self-contained and a good inspiration here. It has an MIT license so it's fine to study and copy/paste.

**Comment by SimonDanisch** [comment]
> FYI, Gadfly has long had a nice layout engine

Oh crazy I didn't realize! Maybe worth checking out indeed!

**Comment by SimonDanisch** [comment]
@jkrumbiegel, how would I update the solver? 
In your example I did: 
```Julia
set_value(cont_w, 1500)
Rhea.autoupdate(solver)
```
Or do I need to construct the problem from scratch everytime a variable changes?

**Comment by SimonDanisch** [comment]
Would that be the right way?
```Julia
solver = simplex_solver()
wconstr = cont_w == 1000
add_constraints(solver, [
    wconstr,
    cont_h == 800,
    inner_w == 2 * inner_h,
    inner_t == inner_b,
    inner_t >= 60,
    inner_l >= 30,
    cont_w == inner_l + inner_r + inner_w,
    cont_h == inner_t + inner_b + inner_h,
    inner_l == inner_r
])
Rhea.remove_constraint(solver, wconstr)
Rhea.add_constraint(solver, cont_w == 1500)
```

**Comment by timholy** [comment]
FYI [Parametron](https://github.com/tkoolen/Parametron.jl) allows on-the-fly updates of parameter values.

**Comment by jkrumbiegel** [comment]
> @jkrumbiegel, how would I update the solver?
> In your example I did:

I think you would use set_constant for that in Rhea to change the constraint, not set the value of the variable directly:

```julia
@testset "set constant 4 test" begin
    x = variable(0)
    solver = simplex_solver()
    cn = add_constraint(solver, x <= 100)
    @test value(x) == 100
    set_constant(solver, cn, 50)
    @test value(x) == 50

    set_constant(solver, cn, 150)
    @test value(x) == 150

    set_constant(solver, cn, -25)
    @test value(x) == -25
end
```

The solver is always resolving when you change something, I think it was designed that way to work faster for GUI purposes than standard solvers, because most parameters usually don't change. Although something like Parametron sounds like it does something similar.

You can also use edit variables and do `suggest(solver, variable, value)` which makes the solver resolve trying to start with that value, but it's not a constraint per se. That's why it's called suggest, but for underdefined situations it works.

**Comment by SimonDanisch** [comment]
Pretty cool! :) I guess, I'll see what I can do with Rhea, and then maybe, if interested, @tkoolen could help setting up something similar in Parametron? To be fair, from the documentation, I'm not entirely sure what solver I need and how to set things up ;)

**Comment by tkoolen** [comment]
I'm pretty short on time right now, but just two comments:

* it looks like Rhea is setting up an LP. You can see [here](http://www.juliaopt.org/JuMP.jl/v0.19.1/installation/) which solvers you can use for LPs. A free one is Clp (though I haven't used it recently)
* with Parametron you can change parameter values, but problem size (number of variables and constraints) should stay fixed between solves.

**Comment by jkrumbiegel** [comment]
I've cobbled together a small prototype with hbox and vbox functionality and a constraint layout (in Plots.jl because this is only about the constraints for now) . Right now it just creates arbitrary "label" sizes on all four sides of each axis to test whether alignment works but these would have to be calculated from actual labels of course. And there are no gaps between subplots, but that wouldn't be hard to add.

[Here's a gist with the code.](https://gist.github.com/jkrumbiegel/781dfde0d793d5c4ef49b8359755cfe1)

The code just to create the actual example is:
```julia
function test_constraint_layout()
    # [1, 2, 1] are the relative widths of the axes without labels in this box
    h1 = Hbox(3, [1, 2, 1])
    v1 = Vbox(2)
    h2 = Hbox([h1, v1], [2, 1])
    v2 = Vbox(2)
    v3 = Vbox([h2, v2])
    v4 = Vbox(3, [2, 3, 4])
    h3 = Hbox([v3, v4], [3, 2])

    s = simplex_solver()
    # recursively add all constraints of objects in the top box
    add_constraints(s, h3)

    # add specific constraints for plot size and position
    add_constraints(s, [
        width(h3) == 800,
        height(h3) == 400,
        leftedge(h3) == 0,
        bottomedge(h3) == 0
    ])

    p = plot(legend = false)
    plot!(h3)
    p
end

test_constraint_layout()
```

All axes within boxes are sensibly aligned, it looks like this:

![constraint example](https://i.imgur.com/QAcdcei.png)

**Comment by SimonDanisch** [comment]
Amazing :) I quickly tried it out with Makie and it looks like expected:
![image](https://user-images.githubusercontent.com/1010467/58960310-3b8e9900-87a7-11e9-8815-e6796b3371fe.png)

Now, the real question is, how to integrate this nicely..I will give it some thought!

**Comment by asinghvi17** [comment]
@SimonDanisch, if we go through with this, then I think axes may need to be special-cased...it would make customizing them a lot easier as well, I think.

**Comment by jkrumbiegel** [comment]
Just to keep this going a little bit.. I extended the approach from above a little bit. Now, containers in the layout are called Alignables. So far that means that they need to have an outer and an inner bounding box, where the inner is supposed to be what aligns to others in a grid layout. Vbox and Hbox fall away because they are just grids with one dim == 1. A grid is an Alignable, and an Axis also. If an Alignable contains others, like the grid does, it creates the constraints that aligns them relative to each other. They can be nested, too. Here's an example where the plot has two main parts, the upper contains 9 "plots" and their "colorbar", the lower 1 colorbar and 2 plots. There are two grids nested in the main grid, and the upper colorbar spans two rows as an example of that. A grid usually keeps all column gaps and row gaps equal, respectively. Code for the example:

```julia
function test6()
    g = Grid(2, 1, relheights = [3, 2])
    gtop = Grid(3, 4, relwidths = [3/11, 3/11, 3/11, 1/11])
    gbottom = Grid(1, 3, relwidths = [1/11, 5/11, 5/11])
    g[1] = gtop
    g[2] = gbottom

    topaxes = [Axis() for i in 1:9]
    toplegend = Axis()
    bottomaxes = [Axis() for i in 1:2]
    bottomlegend = Axis()

    for (i, a) in enumerate(topaxes)
        gtop[i, :down] = a
    end
    for (i, a) in enumerate(bottomaxes)
        gbottom[i+1] = a
    end
    gtop[:, 4] = toplegend
    gbottom[1] = bottomlegend

    s = simplex_solver()
    add_constraints(s,[
        (width(g) == 1000) | strong(),
        (height(g) == 1000) | strong(),
        (g.edges.bottom == 0) | strong(),
        (g.edges.left == 0) | strong()
    ])

    add_constraints(s, g)

    p = plot(legend = false)
    plot!.(topaxes)
    plot!.(bottomaxes)
    plot!(toplegend)
    plot!(bottomlegend)
    plot!(g)
    plot!(gtop)
    plot!(gbottom)
    p
end
```

looks like:

<img width="889" alt="grafik" src="https://user-images.githubusercontent.com/22495855/59450628-e6d3c980-8e09-11e9-82cd-c152ff16f090.png">

The red outlines are the edges of the grids, the blue lines show column and row boundaries. The axes have random edge sizes to make the alignment more apparent. Light gray are the edges and darker gray the align boundaries.

The whole thing is still a little bit buggy, though :) 1 out of 10 times or so the solver says there are required constraints that can't be resolved..

**Comment by SimonDanisch** [comment]
I think we can close this legendary issue :) 
Thanks a ton to @jkrumbiegel, to revolutionize layouting, axes and making Makie 10x more usable!
