### ISSUE TITLE
Quiver with variable arrow size

### ISSUE THREAD

**Issue by LaurentPlagne** [JuliaPlots/Makie.jl#356]
It would be nice if the quiver arrow head sizes could be made relative to their sizes. So there are just dots when the velocity is very small

**Comment by SimonDanisch** [comment]
You mean something like:
```Julia
using AbstractPlotting, Makie
using ImageFiltering, LinearAlgebra

x = range(-2, stop = 2, length = 21)
y = x
z = x .* exp.(-x .^ 2 .- (y') .^ 2)
scene = contour(x, y, z, levels = 10, linewidth = 3)
u, v = ImageFiltering.imgradients(z, KernelFactors.ando3)
n = vec(norm.(Vec2f0.(u,v)))
arrows!(x, y, u, v, arrowsize = n, arrowcolor = n)
```
![grafik](https://user-images.githubusercontent.com/1010467/57984300-c9098380-7a5a-11e9-974d-407834edceca.png)

**Comment by LaurentPlagne** [comment]
Simply great !
I wonder it could be included in the examples because it is the default behavior in matlab or matplotlib and It is not that easy to figure out (at least for me).
Thanks a lot

**Comment by asinghvi17** [comment]
Perhaps, for the basic (atomic) plotting functions at least, we could add attribute descriptions to docstrings?
