### ISSUE TITLE
`hbox` and `vbox` result in inconsistent font size

### ISSUE THREAD

**Issue by haberdashPI** [JuliaPlots/Makie.jl#358]
In a grid of plots I would expect the axis font sizes to remain the same. Below is a figure showing how, when the scale is quite different, the fonts of the axis are quite different.

![image](https://user-images.githubusercontent.com/7861592/58264881-a1613680-7d4c-11e9-9783-98e5fe52269c.png)

The y-axis on the lower figure is basically illegible.

Possibly related to the bigger issues raised in #183, but I thought it might be worth addressing this specific, smaller problem separately.

**Comment by asinghvi17** [comment]
This is a symptom of font sizes being in rescaled data coordinates, not in pixel coordinates.  Should be alleviated by JuliaPlots/AbstractPlotting.jl#88 (adding support for different units via Unitful).

**Comment by ffreyer** [comment]
vbox and hbox are gone and fontsizes are in pixel coordinates now
