### ISSUE TITLE
High Level interface to title, axis-labels

### ISSUE THREAD

**Issue by heitorPB** [JuliaPlots/Makie.jl#365]
It should be easy to set the plot/scene title, x-label, y-label. z-label, etc.

in MatPlotlib:
```
ax.set_title("Bla")
ax.set_xlabel("ble")
```
In Plots.jl:
```
plot!(title = "The Title")
plot!(xlabel = "t (s)")
```
In Makie:
```
# how to set the title?
axis = scene[Axis]
axis[:names, :axisnames] = ("t (s)", "||<↓|Ψ(t)>||²")
```

The way I found to set a plot title in Makie is with [a lot of code](https://discourse.julialang.org/t/makie-add-title-to-plot/22340/2). The Plots.jl is very simple and convenient.

Is this in the roadmap somewhere?

**Comment by asinghvi17** [comment]
`title(scene, "text")` should do it

**Comment by mschauer** [comment]
Is there a similar interface for the axis labels, maybe like `axis(scene, ...)`?

**Comment by SimonDanisch** [comment]
If you hammer out the API, we can make it happen :)

**Comment by mschauer** [comment]
Deal.

**Comment by asinghvi17** [comment]
For Plots compatibility, we could define convenience constructs?  Like `xlabel, ylabel, ...`

**Comment by asinghvi17** [comment]
Will tackle this today.

**Comment by asinghvi17** [comment]
I've implemented the axis label and limit mutating functions, but (a) they don't take Observables and (b) they are a convenience layer, so we should strongly recommend you mutate the axis directly if you want to do anything more than simple on-the-fly plotting.

**Comment by mschauer** [comment]
Do you have a link for me?

**Comment by asinghvi17** [comment]
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/shorthands.jl

**Comment by asinghvi17** [comment]
Resolved by JuliaPlots/AbstractPlotting.jl#283
