### ISSUE TITLE
axis labels too small for large axes

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#37]
this example from the docs is fine:
```julia
using Makie
scene = Scene(resolution = (500, 500))
aviz = axis(linspace(0, 2, 4), linspace(0, 2, 4))
center!(scene)
```

but if you make the axis larger the labels get very small, e.g. `aviz = axis(linspace(0, 20, 4), linspace(0, 20, 4))`

**Comment by SimonDanisch** [comment]
yes i'm working on that! I'll soon introduce units to make those things independant of scale
