### ISSUE TITLE
Make.rotate!() does not rotate everything in the scene

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/Makie.jl#375]
When I plot an image, append lines to it, and then call `Make.rotate!()`, only the image rotates so my lines are not correctly aligned.

**Comment by SimonDanisch** [comment]
Can you post a full example to make it easier to work on it?

**Comment by logankilpatrick** [comment]
Yes. I will paste one later today.

**Comment by logankilpatrick** [comment]
Thinking this isn't actually an issue.

**Comment by logankilpatrick** [comment]
Will close if that ends up being the case.

**Comment by logankilpatrick** [comment]
I will post a full example tomorrow, I am still having this issue.
