### ISSUE TITLE
Use Makie for text rendering

### ISSUE THREAD

**Issue by philoez98** [JuliaPlots/Makie.jl#377]
Hi, I was wondering if currently is possible to use Makie to render text only (and how?).
I know that text can be added to a plot, but what about a blank scene with text only (no axis, no grids...) that can maybe allow interaction (rotations, animations...)?
I'm sorry if the question might sound silly, but I haven't found an answer to this problem yet.

Thanks.

**Comment by asinghvi17** [comment]
Plot with show_axis=false, which should give you text with no axis.

**Comment by philoez98** [comment]
Thanks, but how can I specify a position in the window? Without the axis the `position` parameter does nothing. I can only justify the text right now.
