### ISSUE TITLE
Error when building GLMakie 

### ISSUE THREAD

**Issue by mikibene** [JuliaPlots/Makie.jl#381]
I get a segmentation fault when running `]build GLMakie` with the following message that I was not able to find in the issues.

> Error: Error building `GLMakie`: 
> │ 
> │ signal (11): Segmentation fault
> │ in expression starting at /scratch/beneitez/numerical_codes/julia/.julia/packages/GLMakie/tmubz/deps/build.jl:31
> │ _ZN4llvm2cl16AddLiteralOptionERNS0_6OptionENS_9StringRefE at /scratch/beneitez/numerical_codes/julia/usr/bin/../lib/libLLVM-6.0.so (unknown line)
> │ _ZN4llvm18RegisterPassParserINS_20MachineSchedRegistryEE9NotifyAddENS_9StringRefEPFPvvES3_ at /scratch/beneitez/numerical_codes/julia/usr/bin/../lib/libLLVM-6.0.so (unknown line)
> │ unknown function (ip: 0x2b0770f7230b)
> │ unknown function (ip: 0x2b0728a52be9)
> │ unknown function (ip: 0x2b0728a52cd2)
> │ unknown function (ip: 0x2b0728a56e37)
> │ unknown function (ip: 0x2b0728a52aa3)
> │ unknown function (ip: 0x2b0728a5662a)
> │ dlopen_doit at /build/glibc-6V9RKT/glibc-2.19/dlfcn/dlopen.c:66
> │ unknown function (ip: 0x2b0728a52aa3)
> │ _dlerror_run at /build/glibc-6V9RKT/glibc-2.19/dlfcn/dlerror.c:163
> │ __dlopen at /build/glibc-6V9RKT/glibc-2.19/dlfcn/dlopen.c:87
> │ unknown function (ip: 0x2b07520480b5)
> │ unknown function (ip: 0x2b075204bb9b)
> │ unknown function (ip: 0x2b0752020993)
> │ glXQueryVersion at /usr/lib/x86_64-linux-gnu/libGL.so.1 (unknown line)
> │ _glfwInitGLX at /scratch/beneitez/numerical_codes/julia/.julia/packages/GLFW/e257h/deps/usr/lib/libglfw.so (unknown line)
> │ _glfwPlatformCreateWindow at /scratch/beneitez/numerical_codes/julia/.julia/packages/GLFW/e257h/deps/usr/lib/libglfw.so (unknown line)
> │ glfwCreateWindow at /scratch/beneitez/numerical_codes/julia/.julia/packages/GLFW/e257h/deps/usr/lib/libglfw.so (unknown line)
> │ CreateWindow at /scratch/beneitez/numerical_codes/julia/.julia/packages/GLFW/e257h/src/glfw3.jl:487
> │ #Window#15 at /scratch/beneitez/numerical_codes/julia/.julia/packages/GLFW/e257h/src/glfw3.jl:338
> │ unknown function (ip: 0x2b073ac5575a)
> │ jl_fptr_trampoline at /scratch/beneitez/numerical_codes/julia/src/gf.c:1831
> │ jl_apply_generic at /scratch/beneitez/numerical_codes/julia/src/gf.c:2184
> │ Type at ./tuple.jl:0
> │ unknown function (ip: 0x2b073ac539c3)
> │ jl_fptr_trampoline at /scratch/beneitez/numerical_codes/julia/src/gf.c:1831
> │ jl_apply_generic at /scratch/beneitez/numerical_codes/julia/src/gf.c:2184
> │ do_call at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:324
> │ eval_value at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:430
> │ eval_body at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:553
> │ eval_body at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:613
> │ jl_interpret_toplevel_thunk_callback at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:806
> │ unknown function (ip: 0xfffffffffffffffe)
> │ unknown function (ip: 0x2b0737b7972f)
> │ unknown function (ip: 0x14)
> │ jl_interpret_toplevel_thunk at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:815
> │ jl_toplevel_eval_flex at /scratch/beneitez/numerical_codes/julia/src/toplevel.c:805
> │ jl_parse_eval_all at /scratch/beneitez/numerical_codes/julia/src/ast.c:838
> │ jl_load at /scratch/beneitez/numerical_codes/julia/src/toplevel.c:839
> │ include at ./boot.jl:317 [inlined]
> │ include_relative at ./loading.jl:1044
> │ include at ./sysimg.jl:29
> │ jl_apply_generic at /scratch/beneitez/numerical_codes/julia/src/gf.c:2184
> │ include at ./client.jl:392
> │ jl_fptr_trampoline at /scratch/beneitez/numerical_codes/julia/src/gf.c:1831
> │ jl_apply_generic at /scratch/beneitez/numerical_codes/julia/src/gf.c:2184
> │ do_call at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:324
> │ eval_value at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:430
> │ eval_stmt_value at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:363 [inlined]
> │ eval_body at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:678
> │ jl_interpret_toplevel_thunk_callback at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:806
> │ unknown function (ip: 0xfffffffffffffffe)
> │ unknown function (ip: 0x2b07357bcbef)
> │ unknown function (ip: 0xffffffffffffffff)
> │ jl_interpret_toplevel_thunk at /scratch/beneitez/numerical_codes/julia/src/interpreter.c:815
> │ jl_toplevel_eval_flex at /scratch/beneitez/numerical_codes/julia/src/toplevel.c:805
> │ jl_toplevel_eval_flex at /scratch/beneitez/numerical_codes/julia/src/toplevel.c:754
> │ jl_toplevel_eval_in at /scratch/beneitez/numerical_codes/julia/src/builtins.c:622
> │ eval at ./boot.jl:319
> │ jl_apply_generic at /scratch/beneitez/numerical_codes/julia/src/gf.c:2184
> │ exec_options at ./client.jl:243
> │ _start at ./client.jl:425
> │ jl_apply_generic at /scratch/beneitez/numerical_codes/julia/src/gf.c:2184
> │ jl_apply at /scratch/beneitez/numerical_codes/julia/ui/../src/julia.h:1537 [inlined]
> │ true_main at /scratch/beneitez/numerical_codes/julia/ui/repl.c:112
> │ main at /scratch/beneitez/numerical_codes/julia/ui/repl.c:233
> │ __libc_start_main at /build/glibc-6V9RKT/glibc-2.19/csu/libc-start.c:287
> │ _start at /scratch/beneitez/numerical_codes/julia/usr/bin/julia (unknown line)
> │ Allocations: 2603870 (Pool: 2603012; Big: 858); GC: 4
>

**Comment by mschauer** [comment]
References https://github.com/JuliaPlots/GLMakie.jl/blob/645805c8c9b078dcf5fad76a8056b5ac749da330/deps/build.jl#L31

**Comment by mikibene** [comment]
Yes, I checked and it is that part where the problem seems to be.

**Comment by asinghvi17** [comment]
Is this reproducible?
