### ISSUE TITLE
mesh() errors when given colors are all equal

### ISSUE THREAD

**Issue by augustt198** [JuliaPlots/Makie.jl#385]
If a vector of colors with all values equal is given using `color` attribute for `mesh`, rendering [errors here](https://github.com/JuliaPlots/AbstractPlotting.jl/blob/ae6aa3de1787f3de380549ce6b56d90a4fbeecf3/src/utilities/utilities.jl#L10) because `cmin` = `cmax`.

**Comment by ffreyer** [comment]
```julia
mesh(Rect3D(Point3f0(0), Vec3f0(1)), color = [:red for _ in 1:24])
mesh(Rect3D(Point3f0(0), Vec3f0(1)), color = [1 for _ in 1:24], colormap=(:red, :red))
```
Both work so I don't think this is an issue anymore
