### ISSUE TITLE
Does not zoom towards mouse pointer with hbox/wbox

### ISSUE THREAD

**Issue by jonalm** [JuliaPlots/Makie.jl#399]
Hi, I stumbled upon some weird zooming behavior which might be a bug. Consider

```
using Makie
Nx, Ny = 10, 15
X = LinRange(-1,1, Nx)
Y = LinRange(-1,1, Ny)

s1 = surface(X, Y, X .+ Y')
s2 = surface(X, Y, X .* Y')
hbox(s1,s2) |> display
```

When I use the mouse to zoom on the lower pane (s1), it zooms towards the mouse pointer, but in the upper pane (s2), it zooms towards a point lying above the plot window. Likewise, using vbox instead, the rightmost plot (s2) zooms towards a point right of the plot window.

I’m on a mac if that makes a difference.

**Comment by logankilpatrick** [comment]
I see what you are saying. The zooms are distinctly different. It's worth noting that the zoom of the top figure does seem to be affected by where the mouse is, just not to the same extent as the bottom figure.

**Comment by SimonDanisch** [comment]
Ah, I guess I'm missing to normalize the mouse position to the window rectangle somewhere^^

**Comment by ffreyer** [comment]
Seems to be fixed
