### ISSUE TITLE
A place to discuss architecture.

### ISSUE THREAD

**Issue by lobingera** [JuliaPlots/Makie.jl#4]
In plotting and especially in interactive plotting, sooner or later the generalized problem end up in providing a means of a scene graph that is rendered and displayed. Have you thought about splitting into a OpenGL compositor and the plotting part? I'm asking this after reading: https://hacks.mozilla.org/2017/10/the-whole-web-at-maximum-fps-how-webrender-gets-rid-of-jank/

**Comment by SimonDanisch** [comment]
A lot I do in GLVisualize already works like webrender! The scene graph is still very simple though and we could put much more time into making it nice and efficient.
I tried my best to decouple things, so once we have some time for such optimizations, it should be relatively simple to do so :)
