### ISSUE TITLE
Axes origin/direction in 3d plots, advice?

### ISSUE THREAD

**Issue by norru** [JuliaPlots/Makie.jl#408]
Hi, all, looking for some advice.

In all examples I've seen, origin is top right, y grows "down" and "x" grows left, as shown here:

![image](https://user-images.githubusercontent.com/889291/69272314-5b3b4180-0bce-11ea-8a08-7cfbd2e9419f.png)

I am looking of an example that shows how to configure the x and y axes in a 3d plot so that:

- (0,0) is at bottom left of the diagram
- z axis grows "towards the observer" (this is already correct)
- y axis grows "up"
- x axis grows "right"

Thanks,
Nico

**Comment by mkborregaard** [comment]
Oh yeah, that seems like it should be the default?

**Comment by asinghvi17** [comment]
You can move the camera using `rotate_cam!` and `translate_cam!`

**Comment by norru** [comment]
Huh? Does camera movement flip the axes?

**Comment by asinghvi17** [comment]
Ah, my bad - I think I misinterpreted what you were asking for.  In 3D axes, without fiddling with the code, I don't think this is possible because of some scaling issues we have with negative scale - but you could try `scale!(scene, -1, -1, 1)`...otherwise you could change your input data to the desired orientation, and assign ticks manually.

**Comment by norru** [comment]
Uhm, fiddling with the data is a no go. Guess this is kind of a showstopper for now if scaling does not work.

What is the rationale behind the nonstandard axis direction?

**Comment by mkborregaard** [comment]
@asinghvi17 is this just some kind of oversight, or am I thinking wrongly about this? I don't ever believe I've seen flipped axes by default for 3d in other plotting packages.

**Comment by ffreyer** [comment]
This is very old now so I'll close this.

The coordinate system as it is (and was) is right handed as it should be. You can get to
 
>     * (0,0) is at bottom left of the diagram
>     * z axis grows "towards the observer" (this is already correct)
>     * y axis grows "up"
>     * x axis grows "right"

through rotations/explicitly setting `update_cam!(scene, cameracontrols(scene), eyeposition, lookat, up)`. The axes are not made for this though.
![Screenshot from 2021-06-04 22-03-26](https://user-images.githubusercontent.com/10947937/120856970-e39af080-c580-11eb-91d7-f0faef1d034d.png)

Also `scale!(scene, -1, -1, 1)` doesn't really mess with your data. It sets a transformation that applies to everything in the scene, meaning every piece of data and the coordinate system. It's no different that the transformation the camera applies at that point.
