### ISSUE TITLE
problem with show_axis?

### ISSUE THREAD

**Issue by edljk** [JuliaPlots/Makie.jl#410]
the following instruction do not erase axis..
```julia
using Makie
scene = plot(rand(10))
axis = scene[Axis]
axis[:show_axis] = false
```
it is perhaps not the right way to disable axis plot?

**Comment by SimonDanisch** [comment]
Uh... that might be half a bug - The show_axis attribute needs to be set before plotting anything, and then it won't be added... But after it's added, it doesn't hide it ... Could/should be implemented though.

**Comment by edljk** [comment]
Ah ok, thanks.
