### ISSUE TITLE
Animation after click

### ISSUE THREAD

**Issue by JaRoSchm** [JuliaPlots/Makie.jl#411]
Hi,

I want to start an animation after clicking on the plot.
My code looks like that:

```julia
using Makie

function start_anim(scene, pos)
    node = Node(rand(60, 60))
    heatmap!(scene, lift(matrix -> matrix, node))[end]
    display(scene)

    for i in 1:20
        println(i)
        node[] = rand(60, 60)
        println(size(to_value(node)))
        sleep(0.1)
    end
end

scene = heatmap(rand(60, 60))

on(scene.events.mousebuttons) do buttons
    if ispressed(scene, Mouse.left)
        pos = to_world(scene, Point2f0(scene.events.mouseposition[]))
        start_anim(scene, pos)
    end
    return
end

scene
```

If I start the animation by `start_anim(scene, 0)` everything works fine. But after clicking on the plot the only thing shown is a loading symbol.
![Bildschirmfoto 2019-12-07 um 09 19 20](https://user-images.githubusercontent.com/6123821/70371393-c2493d80-18d2-11ea-877a-f85c76ea7661.png)
Then the last image of the animation is shown.
OS: MacOS 10.15.1
Julia 1.3
Makie 0.9.5

Is this an error in my code?

Thanks,
Jan

**Comment by SimonDanisch** [comment]
May I ask why you create a new heatmap ontop of the existing one?
Also, `display` shouldn't be required on the recently tagged abstractplotting + glmakie version!

**Comment by SimonDanisch** [comment]
This works:
```julia
using Makie

function start_anim(scene, pos)
    heatmap = scene[end] # last plotted plot
    for i in 1:20
        # update arg 1 of heatmap call
        heatmap[1] = rand(60, 60)
        sleep(0.1)
    end
end

scene = heatmap(rand(60, 60))
on(scene.events.mousebuttons) do buttons
    if ispressed(scene, Mouse.left)
        pos = mouseposition(scene)
        # You need the async here, otherwise, you will block glfw
        # which sent the mouse event, which in turn blocks opengl rendering!
        @async start_anim(scene, pos)
    end
    return
end

scene
```

**Comment by SimonDanisch** [comment]
Btw, feel free to ping me after a day or so of not answering.. I had this on my stack but then totally forgot to answer ;)

**Comment by JaRoSchm** [comment]
Thank you very much!
