### ISSUE TITLE
Make mouse scroll change FOV (zoom) instead of moving camera "lookat"

### ISSUE THREAD

**Issue by cdsousa** [JuliaPlots/Makie.jl#413]
It would be nice to have a setting to make mouse scroll events change the FOV (what "zoom" actually should mean) instead of moving camera "lookat" point along the camera axis.
My major issue with current behavior is that the camera "lookat" point is used as a pivot point around which camera rotations are made, thus moving it makes rotations decenter the camera making looking around a plot harder.

**Comment by SimonDanisch** [comment]
That's a good point! Maybe we should just change that ;) 
If you want to get your hands dirty, it should be very easy to change from setting the position, to setting cam.fov in here: https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/camera/camera3d.jl#L235

**Comment by cdsousa** [comment]
Thanks @SimonDanisch , actually by looking into what you pointed me I discovered I could use `AbstractPlotting.cam3d_cad!(scene)` to get an effect that can be used instead of FOV change: move the camera closer or farther to the "lookat", but keeping that "lookat".

**Comment by NHDaly** [comment]
To follow up on @cdsousa's point, you can currently make this work by updating the type of camera used in the scene by calling `AbstractPlotting.cam3d_cad!(scene)` after creating the scene.

Reading a bit more, it looks like there's some way to specify the camera type when constructing the scene? I couldn't quite figure it out though.

(For what it's worth, i also found the current "turntable" style camera quite surprising for `mesh()`. Would it make sense to just change the default camera type for `mesh()`, specifically?)
