### ISSUE TITLE
z-scale in surface plots

### ISSUE THREAD

**Issue by joa-quim** [JuliaPlots/Makie.jl#418]
If I've not missed it there is no way to set a different scale for the z-axis. All 3D examples use isometric units so this problem does not arise, but if one wants to make a surface of a DTM with x,y in degrees (or even meters) and z in meters one have to scale *z* by ~0.001, but this implies creating a copy of the *z* array. Instead of doing this, it would be nice to have a way to set a different scale for the *z* axis. Matlab has the DataAspectRatio property that controls it.

**Comment by asinghvi17** [comment]
You could probably use `scale!(scene, 1, 1, 0.001)`, or use `scale_plot = true`?

**Comment by mschauer** [comment]
Exactly
