### ISSUE TITLE
Specifying rotation in image scene fails.

### ISSUE THREAD

**Issue by lassepe** [JuliaPlots/Makie.jl#421]
When using `image` to instantiate a scene object, it seems like currently one can not use the `rotation` keyword ([as could be done for other plots](https://makie.juliaplots.org/stable/plot-attributes.html#List-of-attributes-1)). Currently, something like `image(img, rotation=pi)` fails with

```
Error showing value of type Scene:
ERROR: MethodError: no method matching gl_convert(::Quaternion{Float32})
```

**Comment by SimonDanisch** [comment]
Hm... You could try:
```julia
s = image(rand(100, 200))
rotate!(s[end], 1.0*pi)
```

**Comment by lassepe** [comment]
Yes, I am aware that this is an option. However, with `rotate!` I run into similar scaling issues as discussed in #397 which is why I was looking for an alternative. For now I decided to rotate the image before handing it over to Makie (e.g. using `ImageTransformations.jl`)

**Comment by SimonDanisch** [comment]
Yeah, so the rotate argument ~~is~~ was a shorthand for `rotate!(plot, ...)`, so wouldn't have been an alternative anyways ;)
Hopefully we get more solid image plotting soon!
