### ISSUE TITLE
y axis label overlaps with ticks in default settings

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#424]
On a currently clean install of latest stable Makie I do the very first doc example
```
using Makie
 x = rand(10)
 y = rand(10)
 colors = rand(10)
 scene = scatter(x, y, color = colors)
```
which results in
![image](https://user-images.githubusercontent.com/19669089/72384078-0b37b180-371d-11ea-9fd9-1a5535538ae4.png)

As you can see the y axis label is missplaced.

**Comment by SimonDanisch** [comment]
The old 2d axis is deprecated
