### ISSUE TITLE
image scatter doesn't work on images with different size

### ISSUE THREAD

**Issue by babaq** [JuliaPlots/Makie.jl#431]
Hi,

I tried to reproduce the image scatter example, but failed on images with different size. the example commented that same size images give best performance, but did not mention it doesn't support images with different size.

```Julia
using Makie
Makie.scatter(1:2,1:2,marker=[rand(RGB,10,10),rand(RGB,15,15)],markersize=0.2)
```

I am testing it in Julia v1.3.1 and on Makie master. I am wandering if I had missed something, or Makie doesn't support different size images yet?

Best,

Alex

**Comment by mschauer** [comment]
Ad hoc: You can vary the marker size instead of the image size:
```
Makie.scatter(1:2,1:2,marker=[rand(RGB{Float32},4,4),rand(RGB{Float32},4,4)],markersize=[0.2, 0.8])
```

**Comment by babaq** [comment]
Hi,

I just tried the latest Makie v0.11.2, and GLMakie v0.1.20 on julia 1.5.3 on window10.

it works on a single image:
```julia
using Makie
Makie.scatter(1:2,1:2,marker=rand(RGB,10,10),markersize=100)
```

but not working with multiple images, even with the same size:
```julia
Makie.scatter(1:2,1:2,marker=[rand(RGB,10,10), rand(RGB,10,10)],markersize=100)
```
