### ISSUE TITLE
3D-axis 

### ISSUE THREAD

**Issue by AlexisRenchon** [JuliaPlots/Makie.jl#433]
3D-axis label behavior and appearance is sometimes out of control, e.g.
![image](https://user-images.githubusercontent.com/22160257/74303948-24824c80-4d21-11ea-9e4f-3718bd2d6145.png)

Rotating a 3D-axis hide the plot behind grid (of course, if you display grid), and axis ticks and labels. 
![image](https://user-images.githubusercontent.com/22160257/74304043-775c0400-4d21-11ea-8624-1794e07c4f71.png)
A suggestion to improve this would be to have axis labels and axis ticks always facing the camera, and having the grid and box always in the background when rotating, and axis label and ticks on the foreground axes. (or maybe add this as an option)

**Comment by ffreyer** [comment]
I vaguely remember seeing this get fixed... I'll close this for now, feel free to open a new issue or comment here if it's still a problem
