### ISSUE TITLE
Common attributes

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Makie.jl#44]
The key feature of Plots.jl is that every command is just `plot`, and every `plot` has a common set of attributes.

http://docs.juliaplots.org/latest/attributes/

Can that page be replicated in Makie?

**Comment by SimonDanisch** [comment]
Yes! I actually want to even go a step further, by making it mandatory even for recipes to document their attributes. Right now, the list of attributes gets created automatically with the `@default` macro.

**Comment by ChrisRackauckas** [comment]
Awesome! Can the docs page be auto-generated from all of this?

**Comment by SimonDanisch** [comment]
That's the idea ;)

**Comment by SimonDanisch** [comment]
This all is already auto generated: http://www.glvisualize.com/Makie.jl/stable/functions.html#Makie.lines
