### ISSUE TITLE
High resolution scenes get cropped when saving to PNG

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaPlots/Makie.jl#440]
I'm not sure if this is a bug, but it's something I need to find a workaround for. I posted to discourse [here](https://discourse.julialang.org/t/can-makie-render-a-scene-at-resolutions-larger-than-the-display/34772) but so far no responses.

Slight modification of the line demo in the docs to save to a high resolution PNG:
```
using Makie

x = range(0, stop = 2pi, length = 40)
f(x) = sin.(x)
y = f(x)
scene = lines(x, y, color = :blue; resolution=(5000,3000));
Makie.save("out.png", scene)
```

The resulting PNG is cropped to 3844x2124 (roughly my screen resolution) and shows just the lower left of the full scene. If I display the scene in a window I get the full scene rescaled to my screen resolution. Same result in 0.9.5 and master.

If this is a bug, can you suggest a workaround for how I can save scenes (actually produced using GeoMakie) to an image at very high resolution?

**Comment by SimonDanisch** [comment]
On what os is this?

**Comment by niclasmattsson** [comment]
Forgot to mention, sorry. Windows 10, Julia 1.3.1.

**Comment by SimonDanisch** [comment]
![image](https://user-images.githubusercontent.com/1010467/74732617-ed44fb80-524a-11ea-81f9-f4a01ab18f39.png)
Can't reproduce on linux + REPL...Where are you executing this?

**Comment by niclasmattsson** [comment]
I've tried this example in the REPL and similar GeoMakie code inside a project of mine, same result.

**Comment by SimonDanisch** [comment]
Hm, I can test later on windows

**Comment by niclasmattsson** [comment]
OK, thanks. I just confirmed that saving large PNGs using Images.jl works fine, so the problem does appear to be in the Makie/Plotting ecosystem somewhere.

```
using Images
img = Gray.(rand(5000,3000))
save("gray.png", img)
```

**Comment by SimonDanisch** [comment]
can reproduce this on windows... Will try to take a look later!

**Comment by SimonDanisch** [comment]
https://discourse.glfw.org/t/can-i-create-a-window-larger-than-the-monitor-resolution/951/2

Hm, seems like the window manager is allowed to overwrite this... I'll need to figure out how the answer can be applied in Makie...

**Comment by SimonDanisch** [comment]
Try: https://github.com/JuliaPlots/GLMakie.jl/pull/70

**Comment by niclasmattsson** [comment]
Thanks for the quick bugfix work! To use it, do I just add GLMakie#master and sit back or are other steps needed?

**Comment by asinghvi17** [comment]
Yep, that's all you have to do.

**Comment by SimonDanisch** [comment]
Let me know if that fixes it

**Comment by niclasmattsson** [comment]
It did, thank you again!
