### ISSUE TITLE
Stroke for barplot 

### ISSUE THREAD

**Issue by AlexisRenchon** [JuliaPlots/Makie.jl#441]
As in the title. 
It would be nice to add a stroke attribute to barplot

**Comment by mkborregaard** [comment]
What's it supposed to be doing?

**Comment by SimonDanisch** [comment]
This issue is known...sadly we had to take away stroke from rectangle scatter, which barplot uses under the hood :D Maybe we should just use `poly!` for the [barplot recipe](https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/basic_recipes/basic_recipes.jl#L535)

**Comment by SimonDanisch** [comment]
Should be fixed in: https://github.com/JuliaPlots/AbstractPlotting.jl/pull/331
