### ISSUE TITLE
zoom causes camera to rotate

### ISSUE THREAD

**Issue by colinxs** [JuliaPlots/Makie.jl#446]
Sorry for the second issue in a row here! I ran into this peculiar behaviour as well:
```julia
sc = scatter(rand(10, 3))
cam3d_cad!(sc,
    eyeposition = [0, 0.1, -1],
    lookat = [0, 0, 1]
)
display(sc)
```
using the mouse zoom will both zoom AND rotate the camera about the zoom axis. This is with Makie@v0.9.5 and AbstractPlotting@v0.9.26.

**Comment by ffreyer** [comment]
I believe that's intended for the cad camera. You should be using the default `cam3d!` if you don't want the rotation.

```julia
help?> cam3d_cad!
search: cam3d_cad!

  cam3d_cad!(scene; kw_args...)

  Creates a 3D camera for scene which rotates around the viewer's "up" axis - similarly to how it's
  done in CAD software cameras.
```
