### ISSUE TITLE
colormap does not respect order

### ISSUE THREAD

**Issue by affans** [JuliaPlots/Makie.jl#447]
I have a matrix `x` that I am trying to create a heatmap of. This matrix could contain values from 1 to 9, but dosn't always contain all of them. For example, the matrix could just be all 1s, or a combination of 1s, 2s, or possibly all 9 numbers. I basically want that when `x[i, j] = 1`, pick color green, when `x[i, j] = 2`, pick color red, and so on... This can be achieved somewhat by using a `colormap`. See the following
```
x= rand(1:3, 10, 10)
hp = heatmap(x, scale_plot = true, show_axis = false, 
    colormap=[colorant"green", colorant"red", colorant"blue", colorant"azure", 
    colorant"red", colorant"lightsalmon", colorant"magenta", colorant"magenta", colorant"grey60", colorant"black"])
```
here `x` is  matrix that only has values from 1 to 3 (but in my application, could theoretically have 9 unique values).  So when `x[i, j]= 1`, it picks color green, when the `x[i, j] = 2` it picks the color red, but when `x[i, j] = 3` it picks the color black... i.e. the function uses the first two colors and then jumps to the end of colormap array. 

Similarly, if you have `x = rand(1:4, 10, 10)`, it will pick the first three colors (green, red, blue) and then the last one black. 

Is there a way to always make it pick the first `n` colors corresponding to the unique numbers in the matrix?

**Comment by affans** [comment]
Actually I just realize that it's not a one to one mapping anyways. If i have 3 unique numbers in a matrix, it will just pick three different colors rather than looking at the order of those numbers and picking the proper color

**Comment by SimonDanisch** [comment]
Try setting colorrange=(1,8) or whatever your desired range is !

**Comment by affans** [comment]
Ah yes, this fixed it... missed this keyword argument.
