### ISSUE TITLE
New window takes away focus from REPL

### ISSUE THREAD

**Issue by EricForgy** [JuliaPlots/Makie.jl#452]
It would be great if focus could stay in the REPL when plotting.

**Comment by mschauer** [comment]
In Atom, putting a semicolon after all but one plotting command alleviates the problem a bit

**Comment by asinghvi17** [comment]
Copying what I said on Slack: you can try `GLFW.WindowHint(GLFW.FOCUS_ON_SHOW, 0)`, which should force GLFW not to cause the window to be focused when opened.

**Comment by mkborregaard** [comment]
it'd be a nice thing to add as an option though

**Comment by EricForgy** [comment]
Out of curiosity, any reason why this shouldn't be the default behavior?

**Comment by EricForgy** [comment]
Oops.

```julia
julia> using Makie
julia> Makie.GLMakie.GLFW.WindowHint(Makie.GLMakie.GLFW.FOCUS_ON_SHOW, 0)
ERROR: UndefVarError: FOCUS_ON_SHOW not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\Base.jl:13
 [2] top-level scope at REPL[2]:1
```

**Comment by MariusDrulea** [comment]
In GLMakie 0.4.0 the focus is left to REPL, and now I want to have it back to the window. 
I do open an window in a for-loop and everytime the window opens without focus. How can I open the window with focus?

**Comment by SimonDanisch** [comment]
Have a look at: https://github.com/JuliaPlots/Makie.jl/blob/master/GLMakie/src/rendering.jl#L69
