### ISSUE TITLE
option to flip heatmap

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#46]
currently `heatmap` puts cell (1,1) in the top-left corner. This is often what you want (like when visualizing an image), but other times you want it on the bottom-left (e.g. in an audio spectrogram).

for [reference](https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.imshow) PyPlot's `imshow` function takes the `origin="upper"` or `origin="lower"` options.

**Comment by mkborregaard** [comment]
The Plots syntax is yflip = true

**Comment by ssfrr** [comment]
I find that less clear - you have to know what the default is to understand what `yflip` will do

**Comment by mkborregaard** [comment]
It's also a lot more general - it's not restricted to heatmaps, which is just another seriestype, not some specific plotting function with bespoke arguments to learn. The y axis has the lowest value in the bottom on all plots, so there's nothing to remember. If you want the y axis to have the lowest value on top, you use yflip = true. It's also not restricted to the y axis, you can xflip and zflip as well. 

That's the key point of Plots and I believe a central component of its success: generality.

**Comment by ssfrr** [comment]
Yeah, if the convention is that the origin is in the lower-left for everything than I can see how `yflip` is good and consistent. In that case the default for `heatmap` should be flipped from what it is now (the origin is currently in the top-left), and `yflip=true would flip it back, right?

**Comment by mkborregaard** [comment]
Yes 👍

**Comment by SimonDanisch** [comment]
I'm planning to have each visual be accompanied by a rich transformation attribute - which will support padding, placement, flipping and maybe even arbitrary transformation functions, if I figure opengl transpilation out fast enough.
This will get implemented for all plotting types and it will be possible to inherit those from the parent scene (so that you can transform the whole scene).

**Comment by mkborregaard** [comment]
That sounds awesome.

**Comment by asinghvi17** [comment]
`scale!` should do this.

**Comment by xaviergonzalez** [comment]
Wait so how do we actually flip the y-axis for a heatmap in Makie?

**Comment by jkrumbiegel** [comment]
ax.yreversed = true

**Comment by xaviergonzalez** [comment]
> ax.yreversed = true

But what if I'm not using an `ax` atttribute, i.e. I'm just doing something like 

```
CairoMakie.heatmap(mat, yflip=true)
```

This code produces the heatmap, just not with the y-axis flipped.

**Comment by asinghvi17** [comment]
You would have to do `CairoMakie.heatmap(mat, axis = (yflip=true,))`.

**Comment by jkrumbiegel** [comment]
It's `yreversed` if I'm not wrong
