### ISSUE TITLE
CairoMakie sometimes doesn't draw the last bin in stephist

### ISSUE THREAD

**Issue by aplavin** [JuliaPlots/Makie.jl#4627]
Same code, `stephist(1:10, bins=[0,5,10], axis=(;limits=(0..10, nothing)))`, with GLMakie (correct):
![Image](https://github.com/user-attachments/assets/774cf1eb-99e2-4563-91a3-6c1787eef9a1)
and CairoMakie (last bin is missing):
![Image](https://github.com/user-attachments/assets/3aeac297-47bb-4077-adc8-7a989f45d689)

Changing the right limit to something above 10, even to 10.001, plots the histogram correctly.

- [x] what version of Makie are you running? (`]st -m Makie`) latest
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on? macbook m2

**Comment by jkrumbiegel** [comment]
@ffreyer maybe some of your clipping code?

**Comment by ffreyer** [comment]
Yup, fixed in #4631.
