### ISSUE TITLE
Cannot Display Anything

### ISSUE THREAD

**Issue by duncanam** [JuliaPlots/Makie.jl#465]
Hello,

Makie works fine on my desktop with a GPU, but I'm really just trying to plot isosurfaces in Julie. Makie seems to be able to do this. My laptop can't utilize GLMakie, so I have added CairoMakie and WGLMakie but when I import either of those in the REPL along with AbstractPlotting I have issues. 

Example:
[http://juliaplots.org/MakieReferenceImages/gallery//isorange,_isovalue/index.html](http://juliaplots.org/MakieReferenceImages/gallery//isorange,_isovalue/index.html)

In REPL, returns:
```
julia> AbstractPlotting.volume(matr .* (matr .> 1.4), algorithm = :iso, isorange = 0.05, isovalue = 1.7)
┌ Warning: Showing scene as text. This happens because `AbstractPlotting.inline!(true)` is set.
│ This needs to be false to show a plot in a window when in the REPL.
└ @ AbstractPlotting ~/.julia/packages/AbstractPlotting/S71fs/src/display.jl:117
Scene (960px, 540px):
events:
    window_area: GeometryTypes.HyperRectangle{2,Int64}([0, 0], [0, 0])
    window_dpi: 100.0
    window_open: false
    mousebuttons: Set(AbstractPlotting.Mouse.Button[])
    mouseposition: (0.0, 0.0)
    mousedrag: notpressed
    scroll: (0.0, 0.0)
    keyboardbuttons: Set(AbstractPlotting.Keyboard.Button[])
    unicode_input: Char[]
    dropped_files: String[]
    hasfocus: false
    entered_window: false
plots:
   *Axis3D{...}
   *Volume{...}
subscenes:
```
So, I set this parameter to false, and nothing changes. Is there a better way to be doing this on a GPU-less laptop, or do I need to be looking at a different package or back to MATLAB for my isosurfaces?

**Comment by asinghvi17** [comment]
If you're using WGLMakie, you need an external display like ElectronDisplay.jl.

**Comment by duncanam** [comment]
Closing this as this was due to an issue with `mesa` on Arch Linux.
