### ISSUE TITLE
test failures on my machine

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#47]
I'm not sure if the expectation is that other folks can run the test suite at the moment, but if so I'm having some trouble.

My test output is [here](https://gist.github.com/ssfrr/25270f5693c98d6093f7d1bc4c03910a). The first couple failures seem to be where the images don't match, but without much of a useful error message. Then some shaders aren't linking, with errors like:

```
program 84 not linked. Error in: 
  /home/sfr/.julia/v0.6/GLVisualize/src/../assets/shader/fragment_output.frag or /home/sfr/.julia/v0.6/GLVisualize/src/../assets/shader/util.vert or /home/sfr/.julia/v0.6/GLVisualize/src/../assets/shader/uv_normal.vert or /home/sfr/.julia/v0.6/GLVisualize/src/../assets/shader/standard.frag
  error: fragment shader input `o_color' has no matching output in the previous stage
```

**Comment by SimonDanisch** [comment]
oh let me look that up, that might be easy to fix!

**Comment by SimonDanisch** [comment]
It's really silly, how much undefined behavior opengl has :D
