### ISSUE TITLE
rename linesegment -> linesegments

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#48]
continuous lines are plotted with `lines`, it seems more consistent to plot a collection of segments with `linesegments` rather than the current `linesegment`. One weirdness is that GLVisualize seems to use `:linesegment` for its style description, so I'm not sure if you want to leave GLVis as it is and translate, or make the change to both packages. (or leave everything as it is and close the issue) :)

**Comment by SimonDanisch** [comment]
Yes, I 100% agree! I also generally tried to make names consistent and ignore names in GLVisualize if they collide!
