### ISSUE TITLE
SSAO (Screen Space Ambient Occlusion)

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPlots/Makie.jl#487]
This could be fairly easy to integrate:

https://learnopengl.com/Advanced-Lighting/SSAO

I already create a few shaders + render targets in: https://github.com/JuliaPlots/GLMakie.jl/blob/master/src/glwindow.jl#L52
And we could add the ones required for SSAO!

**Comment by ffreyer** [comment]
I started working on this (the learnopengl version). I think the occlusion calculation is now working correctly. Here's what I get:

![SSAO2](https://user-images.githubusercontent.com/10947937/80430354-a92b4280-88ee-11ea-9690-177479feb26f.png)

which should be similar to

![SSAO_learn_opengl](https://learnopengl.com/img/advanced-lighting/ssao_without_blur.png)

I still need to implement the blur and combine this with colors. After that it's a question of integrating it nicely with Makie. 

Btw I noticed a couple of issues with the shaders:
* The transformation of normals is incorrect for some model matrices. According to learnopengl it should use `transpose(inv(model)) * normal`, but it's just using `model * normal`. I guess that's what `normalmatrix` is in there for, but it's not defined. For SSAO we'd need `transpose(inv(view * model))` as well. (In `standard.vert`)
* Some places have `if(color.a <= 0.0) discard;`. To my understanding `discard` stops opengl from skipping obstructed geometry, so it's bad for performance. Are these really needed? (For example in `fragment_output.frag`)
* There's a `Light` struct in `util.vert` that's never used (or is it?).

**Comment by SimonDanisch** [comment]
Oh wow, amazing :) 

>The transformation of normals is incorrect for some model matrices. According to learnopengl it should use transpose(inv(model)) * normal, but it's just using model * normal. I guess that's what normalmatrix is in there for, but it's not defined. For SSAO we'd need transpose(inv(view * model)) as well. (In standard.vert)

Good point, I noticed that as well, but never (fully?) fixed it! We should fix that!

>Some places have if(color.a <= 0.0) discard;. To my understanding discard stops opengl from skipping obstructed geometry, so it's bad for performance. Are these really needed? (For example in fragment_output.frag)

Yeahh... This is an annoying situation. We have quite a few shaders, that mix opaque & transparent outputs. I decided its the least worse evil, And all the other approaches I tried to implement mixed transparencies didn't really work out as well...

>There's a Light struct in util.vert that's never used (or is it?).

Yeah should remove it!

**Comment by ffreyer** [comment]
> > Some places have if(color.a <= 0.0) discard;. To my understanding discard stops opengl from skipping obstructed geometry, so it's bad for performance. Are these really needed? (For example in fragment_output.frag)
> 
> Yeahh... This is an annoying situation. We have quite a few shaders, that mix opaque & transparent outputs. I decided its the least worse evil, And all the other approaches I tried to implement mixed transparencies didn't really work out as well...

Is it really about transparent vs opaque? This is checking `alpha <= 0`, so it would only throw away completely invisible pixels.
Or does this act as an alternative to using opengl blending?

**Comment by SimonDanisch** [comment]
Well, I rather meant cut-out with half transparent (anti aliased) edges...Most prominently, we use that in the scatter/text shader, to cut out the bilboards with the markershape ;)

**Comment by SimonDanisch** [comment]
That's also why we have: https://github.com/jkrumbiegel/MakieLayout.jl/issues/66
The outer cut out get's discarded which works correctly, but the aa edge still writes to the depthbuffer, so it doesn't alpha blend...

**Comment by ffreyer** [comment]
Turns out "some places" means `fragment_output.frag`, `fxaa.frag` (kinda) and `postprocess.frag`.

I disabled the one in `fragment_output.frag`, Doesn't look like anything changes...

mesh + surface + text, no transparency:
![Screenshot from 2020-04-28 23-49-50](https://user-images.githubusercontent.com/10947937/80542490-5a90ad80-89ad-11ea-9d87-e62dc1a4207a.png)

mesh + text w/ transparency
![Screenshot from 2020-04-28 23-51-34](https://user-images.githubusercontent.com/10947937/80542493-5bc1da80-89ad-11ea-92f7-66f035b9236b.png)

transparent text, transparent scatter, opaque line:
![Screenshot from 2020-04-29 00-22-05](https://user-images.githubusercontent.com/10947937/80543638-a3e1fc80-89af-11ea-91eb-43ed27aa1757.png)

**Comment by ffreyer** [comment]
I'll close this since SSAO has been merged
