### ISSUE TITLE
use `:z` for heatmap data property?

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#49]
I generally think of `heatmap` and `surface` as being closely-related, so I figured I could update the data of a `heatmap` with `hm[:z] = newdata`, but apparently it wants `hm[:heatmap] = newdata`. Do you think `:z` might be a better property name for that, to match `surface`?

**Comment by SimonDanisch** [comment]
I just went with the names that make the most sense to me - `:z` is absurd to me :D  But I can also see, how it makes more sense in a data oriented (plotting) world, were x,y,z just enumerates dimensions, and not THE 3 spatial dimensions. 
I don't have any strong preferences for the name and will just go with what most people feel comfortable with in the final version :)

**Comment by mkborregaard** [comment]
To me @ssfrr 's idea is completely intuitive as well :-)

**Comment by ssfrr** [comment]
AFAICT heatmap property is now `:color`, which seems good to me, as that's the property being mapped to.
