### ISSUE TITLE
What's missing

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPlots/Makie.jl#490]
There is actually not that much to do anymore until this is fully functioning:

- [x] fully hook up interactivity (easy)
- [x] hook up buffer updates
- [x] images, heatmaps (very easy)
- [x] decent lines (harder) ... Not really decent yet, they're still not super nice, but its at least usable now
- [x] volumes (easy)
- [x] maximum intensity projection
- [x] export to png/jpeg (not sure?)

**Comment by yijiangh** [comment]
I'm trying the `Blink` option [above ](https://github.com/JuliaPlots/Makie.jl/issues/490#issuecomment-504019038), but `body!(w, WGLMakie.three_scene(scene));` tells me that `WGLMakie.three_scene` is undefined. Would you mind pointing me to the latest way to do this? Thanks!

**Comment by Ouam74** [comment]
Hi,
i have the same problem, i cannot render a Makie plot into Blink using : **_body!(w, WGLMakie.three_scene(scene))_**.
I get following message : **_### **_LoadError: UndefVarError: three_scene not defined.__****

**Comment by schneiderfelipe** [comment]
> I'm trying the `Blink` option [above ](https://github.com/JuliaPlots/Makie.jl/issues/490#issuecomment-504019038), but `body!(w, WGLMakie.three_scene(scene));` tells me that `WGLMakie.three_scene` is undefined. Would you mind pointing me to the latest way to do this? Thanks!

I am also having this issue:

```julia
julia> body!(w, WGLMakie.three_scene(scene))
ERROR: UndefVarError: three_scene not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
 [2] top-level scope at REPL[103]:1
```

**Comment by SimonDanisch** [comment]
This works pretty well by now:
```julia
using Blink
s = scatter(1:4)
w = Window()
body!(w, s)
```
Only problem: the resolution isn't really synced, so it comes out as too big!

**Comment by yijiangh** [comment]
@SimonDanisch Thanks! Just complementing your code snippet to make it an MWE:

```julia
using Blink, AbstractPlotting, WGLMakie
s = scatter(1:4)
w = Window()
body!(w, s)
```

Package info:

```julia
(@v1.5) pkg> st Makie
Status `C:\Users\yijiangh\.julia\environments\v1.5\Project.toml`
  [ee78f7c6] Makie v0.11.1

(@v1.5) pkg> st WGLMakie
Status `C:\Users\yijiangh\.julia\environments\v1.5\Project.toml`
  [276b4fcb] WGLMakie v0.2.9

(@v1.5) pkg> st Blink
Status `C:\Users\yijiangh\.julia\environments\v1.5\Project.toml`
  [ad839575] Blink v0.12.3

(@v1.5) pkg> st AbstractPlotting
Status `C:\Users\yijiangh\.julia\environments\v1.5\Project.toml`
  [537997a7] AbstractPlotting v0.12.15
```
