### ISSUE TITLE
Display to IJulia fails

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Makie.jl#493]
<img width="1104" alt="Screen Shot 2019-05-31 at 3 39 23  74100PM" src="https://user-images.githubusercontent.com/32143268/58699230-9f395080-83ba-11e9-96ee-97e9bd13efb6.png">

**Comment by JuliDi** [comment]
This still does not seem to work: there is no output (and no error) from the above commands.
Is there a way to force WGLMakie (or GLMakie) to open a gui window instead of trying to make an inline plot? (like `gui()` in `Plots.jl`)

**Comment by SimonDanisch** [comment]
Well for GLMakie you can use `inline!(false)` to have a window open in IJulia...

**Comment by JuliDi** [comment]
Thanks for the hint. However, this unfortunately does not work as expected.
A new julia icon opens in the dock – using Makie from the REPL this also pops up and after some time shows the plot window – but then the plot still gets displayed inline.

![Makie_inline](https://user-images.githubusercontent.com/20155974/121000302-588d4680-c78a-11eb-857f-843457893c21.png)

**Comment by SimonDanisch** [comment]
That may be because of how IJulia works - i think it tries every mime to display it and calls the show methods directly, so it may be hard to avoid.
I guess you can do `display(scatter(rand(10)));` to not show anything inline

**Comment by JuliDi** [comment]
Thank you! Combining both worked, and the window is interactive as expected

So
```julia
using GLMakie
AbstractPlotting.inline!(false)
display(lines(vec(rand(1,200))))
```
shows the plot in an external window and allows for interaction.

**Comment by diegozea** [comment]
Could it be a problem with the size of the cell output on IJulia? The plot is there, but the `iframe` size is just too small.

![Screenshot from 2021-09-16 13-05-55](https://user-images.githubusercontent.com/2822757/133601478-a0d97d57-bf31-4769-bc8f-13a6eca3aa12.png)


This is using Julia 1.6.2, WGLMakie 0.4, and IJulia 1.23.2
