### ISSUE TITLE
documentation is down

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#51]
The readme points to http://www.glvisualize.com/Makie.jl/stable/, but that appears to be down.

**Comment by ChrisRackauckas** [comment]
It's because of the change to JuliaPlots.

**Comment by ChrisRackauckas** [comment]
I set this up with a CNAME and after the zone edits on my server, the docs should be pointed to `makie.juliaplots.org`.

**Comment by SimonDanisch** [comment]
Thanks Chris! I actually started solving this by creating https://github.com/SimonDanisch/MakieDocs, but I didn't change the link just yet, since that version has a few problems....

**Comment by ChrisRackauckas** [comment]
We might as well put the CNAME there then.

**Comment by ChrisRackauckas** [comment]
Docs are up. We should think about getting a MakieDocs in JuliaPlots though, and I'll swap the CNAME over to that when it's available.
