### ISSUE TITLE
Should there be a title! function?

### ISSUE THREAD

**Issue by jagot** [JuliaPlots/Makie.jl#513]
With the help of @asinghvi17 I got this working, which allows me to do simple subplots:
```julia
using Makie

function mfigure(f::Function, args...; kwargs...)
    scene = Scene(args...; kwargs...)
    f(scene)
    scene # This prevents `title` from showing up, but without it, subplots don't work
end

function msubplot(f::Function, scene::Scene, m, n, i; kwargs...)
    ir = lift(scene.px_area) do parent
        x,y = parent.origin
        w,h = parent.widths
        sw = max(1, floor(Int, w/n))
        sh = max(1, floor(Int, h/m))
        I = (2i - 1) >> 2
        J = rem(i-1,2)
        IRect(x+J*sw, y+I*sh, sw, sh)
    end
    subscene = Scene(AbstractPlotting.root(scene), ir)
    f(subscene)
    subscene
end
```
However, I can't get titles to show up, since they don't modify the `scene` (?):
```julia
mfigure() do scene
    lines!(scene, rand(100), rand(100))
    title(scene, "My title")
end
```
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/117947/66807056-0b12f480-ef29-11e9-826a-1a7dbdd111a8.png">

Furthermore, if I try to add titles to subplots, things go really bananas:
```julia
mfigure() do scene
    msubplot(scene, 1,2,1) do subscene
        lines!(subscene, rand(100), rand(100))
        title(subscene, "My title")
    end
    msubplot(scene, 1,2,2) do subscene
        lines!(subscene, rand(100), rand(100), color=:red)
        title(subscene, "My next title")
    end
end
```
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/117947/66807339-33025800-ef29-11e9-8c0a-393816898b61.png">

Without titles, at least the subplots show up fine:
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/117947/66807485-5decac00-ef29-11e9-8418-17692840e069.png">

**Comment by ffreyer** [comment]
`Axis` and `Axis3` have titles now, and in general you can add a `Label` above an axis or `LScene` in a figure.
