### ISSUE TITLE
Trouble with to_world

### ISSUE THREAD

**Issue by tshort** [JuliaPlots/Makie.jl#52]
I'm trying to run the following example. The highlighted line is causing an error. `to_world` doesn't like the symbol `:auto` for the camera argument ("ERROR: type Symbol has no field view"). 

https://github.com/JuliaPlots/Makie.jl/blob/master/docs/src/examples/scattermouse.jl#L13

**Comment by SimonDanisch** [comment]
Oh, that has changed... And will change again :-D Sorry about that...

**Comment by tshort** [comment]
Wow. That was fast. Thanks, @SimonDanisch. Fun stuff.
