### ISSUE TITLE
handling vectors with `Missing` in type signature (even if there are no missing values)

### ISSUE THREAD

**Issue by kescobo** [JuliaPlots/Makie.jl#532]
```julia
julia> using Makie

julia> x = rand(10); y=rand(10);

julia> scene = Scene();

julia> scatter!(scene, x, y, markersize=0.5);

julia> scatter!(scene, x, Union{Missing, Float64}[y...], color=:red, markersize=0.5);

julia> scene
```

<img width="913" alt="Screen Shot 2020-01-23 at 11 18 54 AM" src="https://user-images.githubusercontent.com/3502975/73002578-4a779980-3dd2-11ea-864a-78e3419ee21f.png">

@jkrumbiegel noted on slack:

> it turns the yvalues into ascending integers

![image](https://user-images.githubusercontent.com/3502975/73002513-2f0c8e80-3dd2-11ea-9e5b-7b8b62f296f5.png)

**Comment by briochemc** [comment]
This just bit me today. Here is a MWE with the current syntax:

```julia
using GLMakie

y = rand(10)
x = rand(10)
y2 = convert(Vector{Union{Missing, Float64}}, y)

fig = Figure()
ax1 = fig[1,1] = Axis(fig)
scatter!(ax1, x, y)
scatter!(ax1, x, y2, color=:red)

fig
```

gives

<img width="390" alt="Screen Shot 2021-05-06 at 9 58 55 am" src="https://user-images.githubusercontent.com/4486578/117223747-ad6b3380-ae51-11eb-8c6e-d87ae79d7fe1.png">

I'm probably *missing* something (no pun intended) but, until this is resolved, shouldn't it throw (instead of failing silently)?

**Comment by kescobo** [comment]
Ha! I forgot about this issue. It's even weirder if the missing is in a `color` argument, since it doesn't error until you try to display it. Here's a MWE I posted to slack yesterday:

```
julia> fig = Figure()
julia> a = fig[1,1] = Axis(fig)
Axis with 0 plots:
julia> b = fig[1,2] = Axis(fig)
Axis with 0 plots:
julia> x = rand(10); y = rand(10); c = rand(10);
julia> scatter!(a, x, y, color=c)
Scatter{Tuple{Vector{Point{2, Float32}}}}
julia> fig
julia> scatter!(b, x, y, color=Union{Missing,Float64}[c...])
Scatter{Tuple{Vector{Point{2, Float32}}}}
julia> fig
Error showing value of type Figure:
ERROR: TypeError: in <:, expected Type, got a value of type Float64
```

**Comment by SimonDanisch** [comment]
This is fixed
