### ISSUE TITLE
One-off error in either heatmap or image?

### ISSUE THREAD

**Issue by mschauer** [JuliaPlots/Makie.jl#54]
Steps to reproduce on a hopefully not too old master (around christmas)
```
scene = Scene(resolution = (500, 500))
heatmap(rand(32, 32))
image(map(x->RGB(x,0.5, 0.5), rand(32,32)))
```

<img width="500" alt="makiebug" src="https://user-images.githubusercontent.com/1923437/35280524-c75abdea-0050-11e8-86a0-f093cdf24df7.png">

**Comment by SimonDanisch** [comment]
I have an idea about this ;) Let me push a fix!

**Comment by SimonDanisch** [comment]
This line:
https://github.com/JuliaPlots/Makie.jl/blob/master/src/plotsbase/atomics.jl#L404
 needs to become:
`$func(scene, 0.0 => n, 0.0 => m, data, attributes)`

Sorry, master has some problems right now, I will push this change when I fixed those!
