### ISSUE TITLE
problems with select_rectangle

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/Makie.jl#547]
The function `select_rectangle` has problems which I do not know where they come from.

First of all, using `select_rectangle(scene)` seems to wrongly stretch the scene axis. For example:
```
using Makie
scene = lines(rand(100), rand(100), color = :red)
display(scene)
```
![image](https://user-images.githubusercontent.com/19669089/51276722-cbd56880-19d5-11e9-8451-8545566e94b9.png)

However
```
scene = lines(rand(100), rand(100), color = :red)
rect = select_rectangle(scene)
display(scene)
```
![image](https://user-images.githubusercontent.com/19669089/51276744-dee83880-19d5-11e9-8a1b-d8f0cc863a21.png)

and immediatelly when I press right click to move the picture, the display instantly becomes:
![image](https://user-images.githubusercontent.com/19669089/51276783-00e1bb00-19d6-11e9-8799-03201981caa6.png)

(the axis are hidden)

---

There is also a second problem with `select_rectangle`. It doesn't seem to propagate keywords correctly and instead messes the plot. For example
```
scene = lines(rand(100), rand(100), color = :red)
rect = select_rectangle(scene; color = :red)
display(scene)
```

doesn't make a red rectangle to select but a filled black one. Even though `select_rectangle` propagate keywords to `lines!`.

**Comment by Datseris** [comment]
I no longer have any of the issues described here, `select_rectangle` works for me (on 2D axis only).

**Comment by yha** [comment]
I tried again on master, and I still see the issue as originally described here, when running
```
using Makie
scene = lines(rand(100), rand(100), color = :red)
rect = select_rectangle(scene)
scene
```
as a Juno cell, or in the REPL surrounded by `begin... end` (to suppress the first display). The scene is stretched and sometimes (seemingly randomly) also completely non-responsive.
Version info:
```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
```

**Comment by SimonDanisch** [comment]
I think this function should be deprecated, and we should make sure that https://makie.juliaplots.org/stable/examples/layoutables/axis/index.html#rectangle_selection_zoom can replace it fully!

**Comment by Datseris** [comment]
No, the rectangle selection zoom does something different. It doesn't select a rectangle, it zooms into one. That is very different. I want a _selection_ of a rectangle, so that I can get the coordinates of the rectangle selected and do something other than just zooming in on the existing plot.

**Comment by Datseris** [comment]
so please don't remove it because you will literally break down half of InteractiveDynamics.jl. We certainly need to make it appropriate for the new interaction pipeline. I never did that.

**Comment by SimonDanisch** [comment]
>But it is certainly not just "zooming into a selection".

Yeah, you can actually do this these days with the Axis interactions as well... Probably needs to have some more docs about how to do it!
