### ISSUE TITLE
Text sizes are inflated arbitarily in the colorbuffer

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Makie.jl#574]
`save("scene.png", scene)`
![scene](https://user-images.githubusercontent.com/32143268/79826452-654db000-83b9-11ea-9340-aea767001fc3.png)

`AbstractPlotting.colorbuffer(CairoMakie.CairoScreen(scene)) |> save("image.png")`
![image](https://user-images.githubusercontent.com/32143268/79826449-62eb5600-83b9-11ea-8941-f2461f0da0e2.png)

**Comment by jkrumbiegel** [comment]
fixed by https://github.com/JuliaPlots/AbstractPlotting.jl/pull/401 and respective cairomakie changes
