### ISSUE TITLE
support `delete!(::Scene, ::Scene)`

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#58]
Suppose I have some heatmaps added like so:

```julia
s = Scene()
hm1 = heatmap(s, rand(32, 32))
hm2 = heatmap(s, rand(32, 32), offset=(0, 40))
```

My first thought as to how to remove that heatmap would be something like `delete!(s, hm1)`, but that doesn't work. It seems that I can delete one of them with `delete!(s, :heatmap)`, but it's not obvious to me how that would extend to multiple heatmaps.

**Comment by SimonDanisch** [comment]
Yes, let's support this :)

**Comment by JeremyBYU** [comment]
So I couldn't get the delete! syntax shown to work, not even for one heatmap. But just by looking at the scene data structure and playing around I got this to work:

```julia
data1 = randn(10, 3);
data2 = randn(10,3);
scene = Scene();
scatter!(scene, data1[:,1], data1[:,2], data1[:,3])
scatter!(scene, data2[:,1], data2[:,2], data2[:,3])
# All the data is showing
# Make data 1 invisible
scene.plots[2].attributes[:visible]= true
# Make data 2 invisible
scene.plots[3].attributes[:visible]= true
```
Suppeerrrr hacky. But for right now seems to be working. Not sure about performance issues. Hopefully all the points don't have to be drawn by the GPU if they are marked invisible.

**Comment by SimonDanisch** [comment]
>scene.plots[2].attributes[:visible]= false

There is a non hacky version:
```julia
scene[2].visible = false
```

Also, delete is implemented now:
```julia
s = Scene()
hm1 = heatmap(s, rand(32, 32))[end]
delete!(s, hm1)
```
