### ISSUE TITLE
transparency issue?

### ISSUE THREAD

**Issue by edljk** [JuliaPlots/Makie.jl#591]
When I try to reproduce the transparency illustration 
[transparent sphere](https://discourse.julialang.org/t/transparent-surfaces-in-makie-jl/15775)
I obtain an opaque sphere. Can someone reproduce this issue? Perhaps it is a problem in my installation..

**Comment by asinghvi17** [comment]
Did setting `transparency = 0.4` or `transparency = true` in `surface` help?

**Comment by edljk** [comment]
Yes, `transparency = true`  in `surface` solves the problem. Thanks a lot.

**Comment by SimonDanisch** [comment]
>transparency = 0.4

Transparency is a boolean ;)

**Comment by lazarusA** [comment]
is there a way to control the degree of transparency ?, sometimes it shows too much.

**Comment by ffreyer** [comment]
You can add an alpha value to a colormap (or any color) by doing something like `colormap=(:viridis, 0.4)`

**Comment by lazarusA** [comment]
Yes, I know. But that doesn't affect the transparency strength, one just gets a more diffusive color.

**Comment by ffreyer** [comment]
I don't know what you're asking for then. `transparency` enables or disables transparency and the alpha component of a color controls how transparent something is. We don't have different transparency methods at this point.

This is `(:viridis, 0.8)` vs `(:viridis, 0.2)`
![Screenshot from 2021-02-23 12-06-42](https://user-images.githubusercontent.com/10947937/108835463-cc3a8780-75cf-11eb-801a-59f499fd054e.png)
