### ISSUE TITLE
generic highclip / lowclip and nonlinear color transforms 

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/Makie.jl#596]
We should replace every instance of `colormap`, `colorrange`, `highclip` and `lowclip` attributes with one object that supports all of these properties as well as a nonlinear transform to pick from the chosen color map. Basically all objects that use color maps should work the same.

**Comment by SimonDanisch** [comment]
That's the plan :)

**Comment by jkrumbiegel** [comment]
Yeah I figured, but was there an issue for discussion?

**Comment by SimonDanisch** [comment]
No, just wanted to assure, that this is indeed the way forward! :)

**Comment by asinghvi17** [comment]
@jkrumbiegel there's a prototype interface in src/sampler.jl

**Comment by jkrumbiegel** [comment]
it seems like the colorsampler code is only for continuous values? It would make sense to bake continuous vs. categorical deep into the code so we don't have to struggle with fake categorical maps later. Basically, having explicitly categorical color samplers would allow to use any iterable as the `colors` attribute, you would just group and sort the items and then assign them sequentially to the categorical color values.

For a categorical color map it does not make any sense to allow interpolation, so I would try to make it hard to use this incorrectly.

It would also be great if the color maps were categorical for colorbars that either show the steps with interpolation, or without.

Something like
```julia
scatter!(rand(1:3, 100), color = rand('a':'c', 100), colormap = categorical(:some_map))
```

What do you think?

**Comment by jkrumbiegel** [comment]
We could correctly classify the existing colormaps so if you only specify the symbol, you'd automatically get categorical, or continuous. This would have to be specifically overridden.

```julia
color = :viridis # would be be automatically like continuous(:viridis)
color = :seaborn_deep6 # would be automatically like categorical(:seaborn_deep6)
```

**Comment by asinghvi17** [comment]
They already support categorical natively - the interpolation has "nearest" (categorical) or "linear" (continuous) modes.

**Comment by jkrumbiegel** [comment]
> They already support categorical natively

I'm not sure that this is the same thing I mean. Categorical color maps shouldn't work with interpolation at all, it should just be about indexing into the color map. So I think it would be confusing to supply a continuous value, then round that and look up via nearest neighbor. Basically, if you choose a categorical color map, there should not even be a color range.

**Comment by asinghvi17** [comment]
I don't think I get what you're saying.  Surely, offering the flexibility of having a color range is better than not offering it?  You can always supply `Int64` colors and a color range if you want to replicate the effect of "indexing" into the colormap anyway.  I use categorical colormaps quite a bit in research to see what the segmentation of a heatmap looks like, and it's a good substitute for filled contours as well.

**Comment by jkrumbiegel** [comment]
what would the color range of three values 'a', 'b' and 'c' look like? I'm saying categorical color ranges make the step via some continuous value unnecessary, or rather it's convoluted to use the nearest neighbor approach with categorical variables.

**Comment by jkrumbiegel** [comment]
What your describing with heatmaps is not categorical, it's a continuous color map with super low resolution, or large bins

**Comment by asinghvi17** [comment]
Oh, so by a categorical colormap you mean `[:a => :red, :b => :blue,...]` instead of `[:red, :blue, ...]` - I see now.  My conception of a categorical colormap is just one which interpolates by nearest neighbour instead of linearly.  That said, PlotUtils seems to subscribe to this approach, so it might make sense to have a "discrete" colormap instead with no interpolation, but more like a Dict or a Vector of Pairs.

**Comment by jkrumbiegel** [comment]
From a user's perspective, you might have a scatter plot and you want three different colors in there. The color vector has an arbitrary kind of data in it, but always with three groups. So if you assign that as color, ideally the backend would complain if you didn't choose a categorical color map, but if you did (and I think this should be as easy as just choosing one of the obviously categorical map symbols) then this should just work. The problem with your approach is that you need bins on a continuous number line that you map the categories to, instead of just sorting the values and assigning colors sequentially to each group.

**Comment by mkborregaard** [comment]
@jkrumbiegel check the docs here describing how it is in PlotUtils https://docs.juliaplots.org/latest/generated/colorschemes/
We distinguish between colorgradients and palettes. Colorgradients can be continuous or categorical. What you are talking about is a palette. In that parlance. IMHO the problem you are describing is well understood and already solved.

**Comment by jkrumbiegel** [comment]
sure it's solved, just not in Makie ;) I'll check out your link

**Comment by jkrumbiegel** [comment]
So what would the user interface for something like a scatter plot in Makie be, `color = palette(xyz)` and `color = cgrad(xyz)` or something else?

**Comment by asinghvi17** [comment]
I think it would be `colormap` not `color`, but otherwise yes?  We also have `palette` as a scene-wide color controller for series coloring.

**Comment by jkrumbiegel** [comment]
so what would `palette` return in our case, a `Palette` object of some kind that we can dispatch on?

**Comment by asinghvi17** [comment]
Yeah, we already have one of those I think
