### ISSUE TITLE
Zooming without entering shape

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [JuliaPlots/Makie.jl#602]
Is there a way to change the zooming behaviour so it does not case the viewer to "enter the shape". See the below animation. I would like to be able to zoom in on a particular triangle or vertex as much as I want. It should keep magnifying rather than flying into the shape. 

![Peek 2020-05-12 22-11](https://user-images.githubusercontent.com/8392709/81746978-406fc880-949f-11ea-8617-fa24192e0cc5.gif)

**Comment by ffreyer** [comment]
There are two things you want to mess with in this case. First, the `lookat` vector, which controls the point where you zoom towards. Second the `near` clip, which controls how close you can get before geometry is clipped. For the cat mesh, try something like

```julia
scene.camera_controls[].lookat[] = Vec3f0(0, 0.5, 1)
scene.camera_controls[].near[] = 1f-5
```

**Comment by fedario** [comment]
Are these attributes still available today?
I cannot seem to find them in the object that gets returned by a plotting function like `scatter`.

**Comment by ffreyer** [comment]
They are in `ax.scene`. (`fig, ax, p = scatter(...)`) There is also a `camera_controls()` function but it probably hasn't been ported yet.

**Comment by ffreyer** [comment]
I'll close this since it's not really an issue, it's just a result of how cameras work.
