### ISSUE TITLE
Configuring tests using environment variables

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Makie.jl#609]
I think we should have a central function in MakieGallery, which checks some env variables and loads a database.  My initial thoughts are:
- `MAKIE_MINIMAL`: if true, load short tests; else, load database.
- `MAKIE_3D_TESTING`: if true, load all tests, else load only 2D tests.
- `MAKIE_RECORD_DIR`: directory to record refimages to.  Defaults to `test/test_recordings`.
- `MAKIE_DIFF_DIR`: directory to record diffs to.  Defaults to `test/tested_different`.

**Comment by SimonDanisch** [comment]
I think those should be functions in MakieGallery, which one can then quite easily call ;)
