### ISSUE TITLE
scale! has no effect on an image scene

### ISSUE THREAD

**Issue by IanButterworth** [JuliaPlots/Makie.jl#610]
This used to work for flipping the y axis for an image, but now `scale!` has no effect on the scene

```
img = image([1 0; 0 0])
scale!(img, 1, -1, 1)
```

Makie 0.10.0
Julia 1.4.1

**Comment by asinghvi17** [comment]
Works for me on master.

<img width="832" alt="Screen Shot 2020-05-21 at 9 32 42  61700PM" src="https://user-images.githubusercontent.com/32143268/82578882-a3054a80-9baa-11ea-934b-0c992b2f4430.png">

**Comment by ffreyer** [comment]
Yea seems fine to me
