### ISSUE TITLE
center! discards transformation

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Makie.jl#611]
`sc = image([1 0; 0 0])`
<img width="788" alt="Screen Shot 2020-05-21 at 9 34 20  96000PM" src="https://user-images.githubusercontent.com/32143268/82579089-efe92100-9baa-11ea-8c8c-1c602438523b.png">
`scale!(sc, 1, -1, 1)`
<img width="788" alt="Screen Shot 2020-05-21 at 9 34 39  39900PM" src="https://user-images.githubusercontent.com/32143268/82579109-f7102f00-9baa-11ea-8fca-feeabf46531a.png">
`center!(sc)`
<img width="788" alt="Screen Shot 2020-05-21 at 9 34 44  83700PM" src="https://user-images.githubusercontent.com/32143268/82579119-fb3c4c80-9baa-11ea-9167-26688e343371.png">

**Comment by ffreyer** [comment]
Doesn't seem to be an issue anymore, not in a 2d Scene, nor a 3d `LScene`. I don't think this is relevant to `Axis` and `Axis3`.
