### ISSUE TITLE
GLMakie package won't load

### ISSUE THREAD

**Issue by mattderstine** [JuliaPlots/Makie.jl#613]
This file seems to be missing when I attempt "using Make" after adding the Makie package to a fresh install of JuliaPro 

> could not open file /Users/matt/.juliapro/JuliaPro_v1.4.1-1/packages/GLMakie/S9Zib/deps/deps.jl

I had been just adding GLMakie#master to make it work, but now a version mismatch prevents even that.

**Comment by asinghvi17** [comment]
Could you try `]build GLMakie`?

**Comment by mattderstine** [comment]
Works great! Thanks. I'm new to all of this (Julia, Git, ...) so I appreciate the exceedingly responsive help!

**Comment by asinghvi17** [comment]
For what it's worth, I made a PR to improve the error message (https://github.com/JuliaPlots/GLMakie.jl/pull/106).  Is there any other helpful information I can add?
