### ISSUE TITLE
CairoMakie still needs to implement `transform_func`

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Makie.jl#615]

**Comment by lobingera** [comment]
If you plan with the 'help wanted' label, a little bit more description would be helpful

**Comment by SimonDanisch** [comment]
This is about transforming the positions for e.g. specififying log transform!
This is the PR for GLMakie: https://github.com/JuliaPlots/GLMakie.jl/commit/7cc5be95d7cdda36416e56975000a8340a193f2f

**Comment by jkrumbiegel** [comment]
done https://github.com/JuliaPlots/CairoMakie.jl/pull/153
