### ISSUE TITLE
Error when using Makie on Windows 10

### ISSUE THREAD

**Issue by sbacelar** [JuliaPlots/Makie.jl#616]
When I try to `using Makie` on `Windows 10` I receive the following error message. I tried also to add the master version without success.

```
julia> using Makie
[ Info: Precompiling Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a]
WARNING: Method definition (::Type{GeometryTypes.HyperRectangle{3, Float32}})(Tuple{Tuple{#s15, #s14} where #s14<:Number where #s15<:Number, Tuple{#s13, #s12} where #s12<:Number where #s13<:Number}) in module GeometryTypes at C:\Users\sbac\.julia\packages\GeometryTypes\gpBFp\src\hyperrectangles.jl:164 overwritten in module AbstractPlotting at C:\Users\sbac\.julia\packages\AbstractPlotting\B5nOF\src\types.jl:141.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{GeometryTypes.HyperRectangle{3, Float32}})(Tuple{Tuple{#s15, #s14, #s13} where #s13<:Number where #s14<:Number where #s15<:Number, Tuple{#s12, #s26, #s27} where #s27<:Number where #s26<:Number where #s12<:Number}) in module GeometryTypes at C:\Users\sbac\.julia\packages\GeometryTypes\gpBFp\src\hyperrectangles.jl:167 overwritten in module AbstractPlotting at C:\Users\sbac\.julia\packages\AbstractPlotting\B5nOF\src\types.jl:144.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{GeometryTypes.HyperRectangle{3, Float32}})(GeometryTypes.HyperRectangle{2, T} where T) in module GeometryTypes at C:\Users\sbac\.julia\packages\GeometryTypes\gpBFp\src\hyperrectangles.jl:129 overwritten in module AbstractPlotting at C:\Users\sbac\.julia\packages\AbstractPlotting\B5nOF\src\types.jl:148.
  ** incremental compilation may be fatally broken for this module **

ERROR: LoadError: LoadError: UndefVarError: clibraries not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\Base.jl:26
 [2] top-level scope at C:\Users\sbac\.julia\packages\AbstractPlotting\B5nOF\src\conversions.jl:606
 [3] include(::Module, ::String) at .\Base.jl:377
 [4] include(::String) at C:\Users\sbac\.julia\packages\AbstractPlotting\B5nOF\src\AbstractPlotting.jl:1
 [5] top-level scope at C:\Users\sbac\.julia\packages\AbstractPlotting\B5nOF\src\AbstractPlotting.jl:40
 [6] include(::Module, ::String) at .\Base.jl:377
 [7] top-level scope at none:2
 [8] eval at .\boot.jl:331 [inlined]
 [9] eval(::Expr) at .\client.jl:449
 [10] top-level scope at .\none:3
in expression starting at C:\Users\sbac\.julia\packages\AbstractPlotting\B5nOF\src\conversions.jl:606
in expression starting at C:\Users\sbac\.julia\packages\AbstractPlotting\B5nOF\src\AbstractPlotting.jl:40
ERROR: LoadError: Failed to precompile AbstractPlotting [537997a7-5e4e-5d89-9595-2241ea00577e] to C:\Users\sbac\.julia\compiled\v1.4\AbstractPlotting\6fydZ_3loi6.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
 [6] include(::Module, ::String) at .\Base.jl:377
 [7] top-level scope at none:2
 [8] eval at .\boot.jl:331 [inlined]
 [9] eval(::Expr) at .\client.jl:449
 [10] top-level scope at .\none:3
in expression starting at C:\Users\sbac\.julia\packages\Makie\3CKlT\src\Makie.jl:3
ERROR: Failed to precompile Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a] to C:\Users\sbac\.julia\compiled\v1.4\Makie\iZ1Bl_3loi6.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
```

**Comment by asinghvi17** [comment]
Looks like you got an old version.  Could you try `]add Makie@0.11`?

**Comment by sbacelar** [comment]
Not working also:
```
(@v1.4) pkg> add Makie@0.11
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Colors [5ae59095]:
 Colors [5ae59095] log:
 ├─possible versions are: [0.9.0, 0.9.2-0.9.6, 0.10.0-0.10.2, 0.11.0-0.11.2, 0.12.0-0.12.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.9.0, 0.9.2-0.9.6, 0.10.0-0.10.2, 0.11.0-0.11.2, 0.12.0-0.12.1]
 ├─restricted by compatibility requirements with FreeTypeAbstraction [663a7486] to versions: [0.11.0-0.11.2, 0.12.0-0.12.1]
 │ └─FreeTypeAbstraction [663a7486] log:
 │   ├─possible versions are: [0.4.0-0.4.2, 0.5.0, 0.6.0-0.6.5, 0.7.0, 0.8.0] or uninstalled
 │   └─restricted by compatibility requirements with AbstractPlotting [537997a7] to versions: 0.8.0
 │     └─AbstractPlotting [537997a7] log:
 │       ├─possible versions are: [0.9.0-0.9.27, 0.10.0-0.10.11, 0.11.0-0.11.1] or uninstalled
 │       ├─restricted to versions * by an explicit requirement, leaving only versions [0.9.0-0.9.27, 0.10.0-0.10.11, 0.11.0-0.11.1]
 │       ├─restricted by compatibility requirements with Makie [ee78f7c6] to versions: 0.11.0-0.11.1
 │       │ └─Makie [ee78f7c6] log:
 │       │   ├─possible versions are: [0.9.0-0.9.6, 0.10.0, 0.11.0] or uninstalled
 │       │   └─restricted to versions 0.11 by an explicit requirement, leaving only versions 0.11.0
 │       └─restricted by compatibility requirements with GLMakie [e9467ef8] to versions: 0.11.1
 │         └─GLMakie [e9467ef8] log:
 │           ├─possible versions are: [0.0.1-0.0.18, 0.1.0-0.1.5] or uninstalled
 │           ├─restricted by compatibility requirements with Makie [ee78f7c6] to versions: 0.1.0-0.1.5
 │           │ └─Makie [ee78f7c6] log: see above
 │           └─restricted by compatibility requirements with AbstractPlotting [537997a7] to versions: [0.0.1-0.0.8, 0.1.5] or uninstalled, leaving only versions: 0.1.5
 │             └─AbstractPlotting [537997a7] log: see above
 ├─restricted by compatibility requirements with InteractBase [d3863d7c] to versions: [0.10.0-0.10.2, 0.11.0-0.11.2], leaving only versions: 0.11.0-0.11.2
 │ └─InteractBase [d3863d7c] log:
 │   ├─possible versions are: [0.6.0-0.6.1, 0.7.0-0.7.1, 0.8.0-0.8.3, 0.9.0-0.9.3, 0.10.0-0.10.4] or uninstalled
 │   ├─restricted by compatibility requirements with Interact [c601a237] to versions: [0.6.0-0.6.1, 0.7.0-0.7.1, 0.8.0-0.8.3, 0.9.0-0.9.3, 0.10.0-0.10.4]
 │   │ └─Interact [c601a237] log:
 │   │   ├─possible versions are: [0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.3] or uninstalled
 │   │   └─restricted to versions * by an explicit requirement, leaving only versions [0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.3]
 │   └─restricted by compatibility requirements with Observables [510215fc] to versions: 0.10.4 or uninstalled, leaving only versions: 0.10.4
 │     └─Observables [510215fc] log:
 │       ├─possible versions are: [0.2.0-0.2.3, 0.3.0-0.3.1] or uninstalled
 │       └─restricted by compatibility requirements with AbstractPlotting [537997a7] to versions: 0.3.1
 │         └─AbstractPlotting [537997a7] log: see above
 └─restricted by compatibility requirements with PlotUtils [995b91a9] to versions: 0.12.0-0.12.1 — no versions left
   └─PlotUtils [995b91a9] log:
     ├─possible versions are: [0.5.0-0.5.8, 0.6.0-0.6.5, 1.0.0-1.0.4] or uninstalled
     ├─restricted by compatibility requirements with GraphRecipes [bd48cda9] to versions: [0.6.2-0.6.5, 1.0.0-1.0.4]
     │ └─GraphRecipes [bd48cda9] log:
     │   ├─possible versions are: [0.4.0, 0.5.0-0.5.4] or uninstalled
     │   └─restricted to versions 0.5 by AgentsPlots [7820620d], leaving only versions 0.5.0-0.5.4
     │     └─AgentsPlots [7820620d] log:
     │       ├─possible versions are: 0.3.0 or uninstalled
     │       └─AgentsPlots [7820620d] is fixed to version 0.3.0
     └─restricted by compatibility requirements with AbstractPlotting [537997a7] to versions: 1.0.0-1.0.4
       └─AbstractPlotting [537997a7] log: see above
```

**Comment by asinghvi17** [comment]
Looks like InteractBase is holding Colors back, nothing to do with Makie

**Comment by sbacelar** [comment]
Thank you. After removing `Interact` and building `GLMakie` now `Makie` is precompiling.

**Comment by sbacelar** [comment]
But I keep getting a warning in `Jupyter lab`:
```
┌ Info: Precompiling Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a]
└ @ Base loading.jl:1260
┌ Warning: Package AbstractPlotting does not have ImageIO in its dependencies:
│ - If you have AbstractPlotting checked out for development and have
│   added ImageIO as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with AbstractPlotting
└ Loading ImageIO into AbstractPlotting from project dependency, future warnings for AbstractPlotting are suppressed.
```

**Comment by SimonDanisch** [comment]
Maybe call `]resolve` in Jupyter?

**Comment by sbacelar** [comment]
Thank you. I called `]resolve]` and now it works.

**Comment by hafez-ahmad** [comment]
Precompiling Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a]
WARNING: Method definition (::Type{GeometryTypes.HyperRectangle{3, Float32}})(Tuple{Tuple{#s15, #s14} where #s14<:Number where #s15<:Number, Tuple{#s13, #s12} where #s12<:Number where #s13<:Number}) in module GeometryTypes at C:\Users\hafez\.julia\packages\GeometryTypes\gpBFp\src\hyperrectangles.jl:164 overwritten in module AbstractPlotting at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\types.jl:141.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{GeometryTypes.HyperRectangle{3, Float32}})(Tuple{Tuple{#s15, #s14, #s13} where #s13<:Number where #s14<:Number where #s15<:Number, Tuple{#s12, #s26, #s27} where #s27<:Number where #s26<:Number where #s12<:Number}) in module GeometryTypes at C:\Users\hafez\.julia\packages\GeometryTypes\gpBFp\src\hyperrectangles.jl:167 overwritten in module AbstractPlotting at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\types.jl:144.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{GeometryTypes.HyperRectangle{3, Float32}})(GeometryTypes.HyperRectangle{2, T} where T) in module GeometryTypes at C:\Users\hafez\.julia\packages\GeometryTypes\gpBFp\src\hyperrectangles.jl:129 overwritten in module AbstractPlotting at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\types.jl:148.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition convert(Type{#s59} where #s59<:(Observables.Observable{T} where T), Any) in module Observables at C:\Users\hafez\.julia\packages\Observables\0wrF6\src\Observables.jl:52 overwritten in module AbstractPlotting at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\types.jl:288.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition copy(Observables.Observable{T}) where {T} in module Observables at C:\Users\hafez\.julia\packages\Observables\0wrF6\src\Observables.jl:30 overwritten in module AbstractPlotting at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\interaction\nodes.jl:15.
  ** incremental compilation may be fatally broken for this module **

ERROR: LoadError: LoadError: MethodError: convert(::Type{Observables.Observable}, ::Observables.Observable{Any}) is ambiguous. Candidates:
  convert(::Type{Observables.Observable}, x::Observables.AbstractObservable) in Observables at C:\Users\hafez\.julia\packages\Observables\0wrF6\src\Observables.jl:41
  convert(::Type{T}, x::T) where T<:Observables.Observable in AbstractPlotting at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\types.jl:289
Possible fix, define
  convert(::Type{Observables.Observable}, ::Observables.Observable)
Stacktrace:
 [1] setindex!(::Dict{Symbol,Observables.Observable}, ::Observables.Observable{Any}, ::Symbol) at .\dict.jl:380
 [2] Dict{Symbol,Observables.Observable}(::Base.Generator{Base.Iterators.Pairs{Symbol,Array{T,1} where T,NTuple{4,Symbol},NamedTuple{(:color, :marker, :linestyle, :side),Tuple{Array{ColorTypes.RGB{Float64},1},Array{Symbol,1},Array{Union{Nothing, Symbol},1},Array{Symbol,1}}}},typeof(AbstractPlotting.node_pairs)}) at .\dict.jl:103
 [3] #Attributes#4 at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\types.jl:292 [inlined]
 [4] top-level scope at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\theming.jl:16
 [5] include(::Module, ::String) at .\Base.jl:377
 [6] include(::String) at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\AbstractPlotting.jl:1
 [7] top-level scope at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\AbstractPlotting.jl:37
 [8] include(::Module, ::String) at .\Base.jl:377
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:331 [inlined]
 [11] eval(::Expr) at .\client.jl:449
 [12] top-level scope at .\none:3
in expression starting at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\theming.jl:16
in expression starting at C:\Users\hafez\.julia\packages\AbstractPlotting\B5nOF\src\AbstractPlotting.jl:37
ERROR: LoadError: Failed to precompile AbstractPlotting [537997a7-5e4e-5d89-9595-2241ea00577e] to C:\Users\hafez\.julia\compiled\v1.4\AbstractPlotting\6fydZ_uXjNk.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
 [6] include(::Module, ::String) at .\Base.jl:377
 [7] top-level scope at none:2
 [8] eval at .\boot.jl:331 [inlined]
 [9] eval(::Expr) at .\client.jl:449
 [10] top-level scope at .\none:3
in expression starting at C:\Users\hafez\.julia\packages\Makie\3CKlT\src\Makie.jl:3

**Comment by SimonDanisch** [comment]
Make sure, you don't have any package holding back your update!
Try:
```julia
]add AbstractPlotting@0.11.2
```
And see what packages disallow you upgrading to that version
