### ISSUE TITLE
Resizing TextureBuffer 

### ISSUE THREAD

**Issue by skleinbo** [JuliaPlots/Makie.jl#628]
Concerning GLMakie. Dynamically changing the number of particles in a meshscatter does not work, because resizing of `TextureBuffer`s is not implemented. E.g

```julia
using Makie

pos = Node(rand(Point3f0, 10))
meshscatter(pos)

pos[] = rand(Point3f0, 5)
```
fails. This is a bit disappointing, because I frequently want to visualize simulations with an ever-changing number of agents, and sprites often don't look good enough for my taste.

So, with great naivete, I went ahead and digged through the source of GLMakie, and made the following trivial amendment https://github.com/JuliaPlots/GLMakie.jl/pull/109
which makes the above example work.

Could it really be this simple? Or rather, what still needs to be done?

Happy about any input!

**Comment by SimonDanisch** [comment]
Hm, it might just work :D But I'm not 100% sure anymore, why I implemented it and disabled it later on... -.-

**Comment by ffreyer** [comment]
This can be closed now that https://github.com/JuliaPlots/GLMakie.jl/pull/110 has been merged.
