### ISSUE TITLE
save png compression regression

### ISSUE THREAD

**Issue by jaakkor2** [JuliaPlots/Makie.jl#629]
Compare AbstractPlotting v0.9.27 vs v0.11.2
```
using GLMakie, AbstractPlotting
m = GLMakie.loadasset("cat.obj")
scene = mesh(m)
save("cat.png", scene)
```
file sizes are 44 kB (v0.9.27) vs 2706 kB (v0.11.2).

PNGFiles does have the option for `compression_level`
```
using PNGFiles
PNGFiles.save("debug0.png", fill(UInt8.(0), 720, 1280), compression_level=0)
PNGFiles.save("debug1.png", fill(UInt8.(0), 720, 1280), compression_level=1)
```
`debug0.png` is 903 kB, `debug1.png` is 3 kB`.

**Comment by asinghvi17** [comment]
Here are the relevant lines:
https://github.com/JuliaPlots/GLMakie.jl/blob/9dec4a4b761f092d709ea8f46f2130a5f42f788b/src/gl_backend.jl#L77-L85
If we take a dependency on PNGFiles, we could easily do this.  cc @SimonDanisch

**Comment by jaakkor2** [comment]
Already now AbstractPlotting.jl takes a dependency on ImageIO.jl that depends on PNGFiles.jl.

I proposed that PNGFiles.jl would default to `Z_BEST_SPEED`, let's see the response on that.

Otherwise we could write in `GLMakie.jl/src/gl_backend.jl` something like
```
function AbstractPlotting.backend_show(::GLBackend, io::IO, m::MIME"image/png", scene::Scene)
    img = scene2image(scene)
    PNGFiles.save(raw_io(io), img, compression_level = PNGFiles.Z_BEST_SPEED)
end
```

**Comment by jaakkor2** [comment]
PNGFiles.jl v0.3.0 and IOImage.jl v0.3.0 have been tagged, and https://github.com/JuliaPlots/AbstractPlotting.jl/pull/475 has been merged. Now only a tag on AbstractPlotting.jl is needed to close this issue.  cc @SimonDanisch

**Comment by jaakkor2** [comment]
Size of `cat.png` with AbstractPlotting v0.11.4 is 103 kB, that is 3x compared to 44 kB when using v0.9.27.  Reason is that now the image is 24 bpp vs 8 bpp.  As compression is fine, I close the issue.
