### ISSUE TITLE
Thickness Scaling

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPlots/Makie.jl#63]
@ma-laforge might want to take an early look at Makie.jl and see whether the arguments in https://github.com/JuliaPlots/Plots.jl/issues/891 hold.

**Comment by ChrisRackauckas** [comment]
Related (@Datseris) https://github.com/JuliaPlots/Plots.jl/issues/778

**Comment by Datseris** [comment]
Scale free arrows are important!

**Comment by ChrisRackauckas** [comment]
Related as well: https://github.com/JuliaPlots/Plots.jl/issues/653

**Comment by mkborregaard** [comment]
If scale-free stuff is deemed a priority, more people tend to be concerned about lines and bars with infinite lengths (that don't affect the axes limits)

**Comment by mkborregaard** [comment]
Oh there are a lot of related issues on Plots to this. @daschw had a list (so did I but I lost it in slack). I don't think scale-free stuff necessarily is related though.

**Comment by daschw** [comment]
https://github.com/JuliaPlots/Plots.jl/issues/653
https://github.com/JuliaPlots/Plots.jl/issues/733
https://github.com/JuliaPlots/Plots.jl/issues/740
https://github.com/JuliaPlots/Plots.jl/issues/742
https://github.com/JuliaPlots/Plots.jl/issues/778
https://github.com/JuliaPlots/Plots.jl/issues/891
https://github.com/JuliaPlots/Plots.jl/issues/897
https://github.com/JuliaPlots/Plots.jl/issues/960
Not sure, if that's complete, I also lost the slack conversation.

**Comment by SimonDanisch** [comment]
As a side note, what is on master doesn't do much about this, while `sd/units`, which contains some changes, isn't complete yet...

**Comment by ma-laforge** [comment]
The arguments should still hold:

 - `dpi` should simply change how many pixels make up the image (pixel density).  It should not affect how thick lines look relative to the total image dimensions.
 - I also get the impression users ***probably*** still want an easy way to easily scale up line thickness (`thicknessscaling`?) & font sizes (`scalefontsizes`/`fontscaling`?) using by setting a high-level plot attribute.

@ChrisRackauckas: I am guessing your question is more about whether this is done well in the current implementation of Makie.jl?

--> If this is the question, I cannot really answer yet.  I tried installing Makie.jl on my Ubuntu 14.04LTS distribution - but I cannot get it to work.

I even installed the newest version of Julia v6.2 & cleared the entire `~/.julia/v0.6` directory.  It still does not work for me.

**Comment by SimonDanisch** [comment]
A few things have been addressed, and the remaining issue need some better specs to be actionable
