### ISSUE TITLE
Precompile error

### ISSUE THREAD

**Issue by dnabanita7** [JuliaPlots/Makie.jl#634]
I have been getting [this error](https://gist.github.com/dnabanita7/2fcf2e5da2a38be13489098e64803811) and I am unable to resolve it. I use Ubuntu 19.10. It is a [Makie Gallery](https://github.com/JuliaPlots/MakieGallery.jl) precompile error i.e. when I use ``using MakieGallery``.

**Comment by SimonDanisch** [comment]
You need to make sure, that you're on the newest version of AbstractPlotting.
You probably have some packages installed, that hold back an upgrade.
Try:
```julia
]up; add AbstractPlotting@0.11.2
```
This will likely give you some package resolver errors, which you will need to resolve by removing/freeing/upgrading the named dependencies.
