### ISSUE TITLE
Dismantling StatsMakie

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Makie.jl#636]
My current understanding is that StatsMakie has a bit of a usability problem, because:
- the separation from Makie is not super-clear, and it has a little bit of everything,
- it takes a long time to precompile / load.

This is really not ideal and (justifiably) encourages AbstractPlotting to take the most basic stuff ([histograms](https://github.com/JuliaPlots/AbstractPlotting.jl/pull/434), [errorbars](https://github.com/JuliaPlots/AbstractPlotting.jl/pull/464)), so that one doesn't have to load StatsMakie for basic things.

I wanted to discuss here possible fixes, basically how to dismantle StatsMakie into separate packages.

## Grouping

So, the grouping part should basically be superseded by AlgebraOfGraphics. The syntax in AlgebraOfGraphics is slightly more verbose (though not so much in many scenarios if we make `scatter` the default plot instead of `lines` in AbstractPlotting). Other than that, it should almost have feature parity, provided one moves the analyses, that is, [this folder](https://github.com/JuliaPlots/StatsMakie.jl/tree/master/src/typerecipes), to AlgebraOfGraphics. I'd be curious if somebody has examples of things that they do with StatsMakie grouping that are impossible / clumsy in AlgebraOfGraphics.

Maybe dodging / stacking could also go here? I am not completely sure. I also wonder whether it would just be simpler to take care of stacking and doding on a recipe by recipe base.

## Recipes

That is to say [this folder](https://github.com/JuliaPlots/StatsMakie.jl/tree/master/src/recipes):

- `ribbon`,
- `violin`,
- `boxplot`,
- `crossbar`
- `errorbar`

These require StatsBase, which loads surprisingly fast (0.28 secs on my machine), so I think it is an OK dependency (and we could also use it to have full histogram support in AbstractPlotting directly).

The main issue is KernelDensity, which on my laptop takes around 6 seconds to load. It is needed for `violin`, and for smooth density plots (the continuous counter-part of 1D and 2D histograms), which we should also have, if we want `histogram`. The package itself is small and, once you know the bandwidth, computing the kernel density is very easy, but the package uses `Optim` for optimal automatic bandwidth selection, which is a bit on the heavy side.

I see 3 possible ways to move forward:

1. accept the extra loading time (not ideal)
2. have a simpler KernelDensity in AbstractPlotting, where manual bandwidth selection is required
3. "lobby" on KernelDensity to remove their Optim dependency (see [this issue](https://github.com/JuliaStats/KernelDensity.jl/issues/83)), then it should be an OK dependency as well.

I can start with 3. by making a PR to KernelDensity.

**Comment by piever** [comment]
TODO list:

- [x] porting recipes to Abstract Plotting (https://github.com/JuliaPlots/AbstractPlotting.jl/pull/478)
- [ ] making scatter the default plot for real vectors (https://github.com/JuliaPlots/AbstractPlotting.jl/pull/487)
- [x] add missing analyses to AlgebraOfGraphics (https://github.com/JuliaPlots/AlgebraOfGraphics.jl/pull/70, https://github.com/JuliaPlots/AlgebraOfGraphics.jl/pull/71)
- [x] Add `dodge` to AlgebraOfGraphics (https://github.com/JuliaPlots/AlgebraOfGraphics.jl/pull/67)
- [ ] Adding `stack` to AlgebraOfGraphics

When all the ticks are checked, I think we should just tag both AlgebraOfGraphics and AbstractPlotting and add a deprecation notice to StatsMakie.

**Comment by jtrakk** [comment]
Is this done?

**Comment by SimonDanisch** [comment]
Yes I think so...
