### ISSUE TITLE
kwarg sliderlength doesn't work for textslider

### ISSUE THREAD

**Issue by photor** [JuliaPlots/Makie.jl#637]
I tried the following code:
```
sϕ,ϕ = textslider(0:2π/32:2π, "ϕ", start=π/4, sliderheight=100, sliderlength=800)
sθ,θ = textslider(-π/2:2π/32:π/2, "θ", start=5π/16, sliderheight=100, sliderlength=800)
scene=hbox(sϕ,sθ)
display(scene)
```
The result is:
<img width="832" alt="Screen Shot 2020-07-03 at 5 10 28 PM" src="https://user-images.githubusercontent.com/50810677/86497692-9ef34d80-bd50-11ea-9adf-9dc729b36c94.png">
The length of the sliders remains the same whatever values I set in the sliderlength kwarg for the textslider.

**Comment by photor** [comment]
BTW, this kwarg works well for slider().

**Comment by ffreyer** [comment]
`textslider` is gone now and has been fully replaced by MakieLayout sliders. I'll close this since it's not relevant anymore
