### ISSUE TITLE
Textslider problems in Makie

### ISSUE THREAD

**Issue by erlebach** [JuliaPlots/Makie.jl#639]
Here is an MWE that draws three points on a 2D graph. I would like to control the x-value of the 1st point via a text slider.
```
using Makie
s1, v1 = textslider(0.00f0:.1f0:1.0f0, "Variable", start = 0.5f0)

# Draw three points. 
scene = Scene()
x = 1
scatter!(scene, [x, 2., 3.], [2., 5., 3.], markersize=.1)
parent = vbox(s1, scene)
```
How can I use the slider to control the `x2 position of the first point draw `(x,2,3)`.

This will go a very long way towards helping me understand these concepts more deeply. Thanks.

**Comment by ffreyer** [comment]
`textslider` is gone now and has been fully replaced by MakieLayout sliders. I'll close this since it's not relevant anymore
