### ISSUE TITLE
Scaling a hypersphere

### ISSUE THREAD

**Issue by erlebach** [JuliaPlots/Makie.jl#640]
Could somebody please provide me with a simple example of how to scale a 3D Hypersphere. I am trying to use textsliders. Here is my code. Needless to say, I am very frustrated :-( I also posted to discourse.julialang.org.  I am posting this message after several fruitless hours. :-(  Thanks for any suggestions that will allow me to move forward. 
```
using Makie, GeometryTypes, AbstractPlotting
using LightGraphs, MetaGraphs

# For some reason, `using Makie` does not import its functions.
const AP = Makie

function setupCamera!(scene)
    cam = cam3d!(scene)
    #cam.projectiontype[] = AbstractPlotting.Orthographic
    #cam.
    eyepos = Makie.Vec3f0(5, 1.5, 0.5);
    lookat = Makie.Vec3f0(0., 0., 0.);
end

function makePlot()
    marker_size = 0.0002
    scene = Scene();
    sradius, s_marker_radius = textslider(2f0.^(0.5f0:0.25f0:20f0), "light pos r", start=2f0)
    sphere = Makie.Sphere(Makie.Point3f0(0), 1f0)
    s_sphere = Scene(scene)
    mesh(s_sphere, sphere, color=:red, scale=s_marker_radius)   # HOW TO CHANGE SPHERE RADIUS?
    scale!(s_sphere, 4., 8., .2)
    parent_scene = Scene()
    hbox(sradius, scene, parent=parent_scene)
    setupCamera!(scene);
    display(parent_scene)
end

# Execute the function
makePlot()
```

**Comment by ffreyer** [comment]
Huh, I thought something like this would work. Another way to do this is to pass a model matrix. (You also need to use `mesh!` since you're passing a scene)

```julia
model = map(s -> Makie.AbstractPlotting.scalematrix(Vec3f0(s)), s_marker_radius)
mesh!(s_sphere, sphere, color=:red, model=model)
```

**Comment by erlebach** [comment]
Thank you. Good try, but no, does not work. Here is the code I tried with your suggested approach. 
There are very few examples, if any, of how to translate, rotate, scale one sphere in a field of 3 spheres. That would go a long way towards the adaption of Makie for more complex tasks. I am sure people have done this, but they have not posted their solutions anywhere that I could find. If somebody could actually try this out, it would be great!
```
using Makie, GeometryBasics, AbstractPlotting
using LightGraphs, MetaGraphs

# For some reason, `using Makie` does not import its functions.
const AP = Makie

function setupCamera!(scene)
    cam = cam3d!(scene)
   eyepos = Makie.Vec3f0(5, 1.5, 0.5);
    lookat = Makie.Vec3f0(0., 0., 0.);
    update_cam!(scene, cam, eyepos, lookat)
end

function makePlot()
    marker_size = 0.0002
    sradius, s_marker_radius = textslider((0.5f0:0.25f0:10f0), "Radius", start=2.f0)

    s_sphere = Scene()
    sphere = Sphere(Point3f0(0), 1f0)

    model = map(s -> Makie.AbstractPlotting.scalematrix(Vec3f0(s)), s_marker_radius)
    mesh!(s_sphere, sphere, color=:red, model=model)
    hbox(sradius, s_sphere) #, parent=parenkjt_scene)
    setupCamera!(s_sphere);
end

# Execute the function
makePlot()
```

**Comment by ffreyer** [comment]
With

```julia
function makePlot()
    marker_size = 0.0002
    sradius, s_marker_radius = textslider((0.5f0:0.25f0:10f0), "Radius", start=2.f0)

    s_sphere = Scene()
    sphere = Sphere(Point3f0(0), 1f0)

    model = map(s -> Makie.AbstractPlotting.scalematrix(Vec3f0(s)), s_marker_radius)
    mesh!(s_sphere, sphere, color=:red, model=model)
    parent = hbox(sradius, s_sphere) #, parent=parenkjt_scene)
    setupCamera!(s_sphere);
    return parent
end
```

This works for me.

If you want to use multiple spheres anyway, you should look at `meshscatter`. That has `markersize` implemented to scale individual objects and `rotation` implemented to rotate them. Iirc `rotation` assumes the meshes are pointing in `(0, 0, 1)` direction and rotates them to point in whatever direction you pass. For example:

```julia
meshscatter(
    rand(Point3f0, 10), 
    marker=Rect3D(Vec3f0(-0.5), Vec3f0(1)), 
    markersize=[Vec3f0(0.02i) for i in 1:10], 
    rotation=[Vec3f0(sin(i/5), cos(i/5), 0) for i in 1:10]
)
```

If you want to mess around with model matrices more there are a bunch of matrices defined in https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/camera/projection_math.jl.

**Comment by erlebach** [comment]
This worked!!! Thank you! Now I must study it because I really do not understand why what I did did not work. What is different about your solution. Whatever the rules are, I think some better examples are needed in the documentation. I come from an OpenGL background and this is not intuitive for me. Perhaps I am missing something. 

Thanks again! I'll be in touch. Are you the Makie developer?

**Comment by ffreyer** [comment]
In order for a scene to get displayed `display(scene)` needs to be called. That (usually) happens automatically when the scene is output of you code (like in  `makePlot()`) or if you do `julia> scene`.

`hbox` always returns the parent scene, but you can also pass one if you want to. It's useful for these kind of functions to return the scene so it gets displayed. I guess you can also do some setup on the parent scene beforehand when passing it, like for example the window size. 

You can get some hints on the available keyword arguments with `?meshscatter`, for example. I'm not sure how complete/accurate those are though. Lighting attributes (lightposition, ambient, diffuse, specular, shininess) are everywhere for example, but only apply to 3D plots afaik.

**Comment by erlebach** [comment]
I identified what prevent my code from running. I simply did not return the parent scene. 
So could you please explain to me why the parent scene must be returned from the function? I do not need to call `display(parent_scene)` for the code to work. I really do not understand the logic.

**Comment by erlebach** [comment]
One last question. Compare the two lines: 
```
model = map(s -> Makie.AbstractPlotting.scalematrix(Vec3f0(s)), s_marker_radius)
 model = Makie.AbstractPlotting.scalematrix(Vec3f0(s_marker_radius))
```
The first is the one you wrote, which works. The second is mine, which does not work because `s_marker_radius` is an `Observable`, and `Vec3f0` does not apply to Observables. So why does your version work? You wrote an anonynous function, with an argument of type Observable`which is maps the `Observable` to a function within which one must evaluation `Vec3f0(s_marker_radius)`,  which works, but according to me should not work. There is something I obviously do not understand. Thanks again!

   Gordon

**Comment by erlebach** [comment]
I am trying to create a shortcut to your `map` command. The following does not work, and yet the `model` output is identical. Why would that be? 

```
sscale_matrix(s) = :(map(s ->Makie.AbstractPlotting.scalematrix(Vec3f0(s)), s_marker_radius))

function makePlot()
     ...
         #model = map(s -> Makie.AbstractPlotting.scalematrix(Vec3f0(s)), s_marker_radius)
         model = eval(sscale_matrix(s_marker_radius))
    ...
end
```
Surely there is has to be a way to come up with a simpler notation than what you proposed! Your solution worked, but does not seem to be elegant.

**Comment by SimonDanisch** [comment]
Passing scaling to plots has been bit-trotting a bit.
I'd always rather do:
```julia
meshplot = mesh!(s_sphere, sphere, color=:red)[end]
on(s_marker_radius) do x
    scale!(meshplot, x, x, x)
end
```
Also, yeah, maybe one should use meshscatter

**Comment by erlebach** [comment]
I like your approach, Simon. I had read about this, but there were no examples. If there are many sliders, say 10, and a function to execute with 10 arguments varied through sliders, would I code up 10 `on` statements, or is there a more elegant approach?

**Comment by erlebach** [comment]
Does anybody know where the method `!mesh` is defined? `methods()` in Juno does not provide a path. I search `Makie` and other libraries to no avail. I can also not see where `mesh` is defined, except indirectly through a recipe. Thank you.

**Comment by SimonDanisch** [comment]
I'd do a loop like this:
```julia
sliders = map(1:10) do i
    slider = s_marker_radius = slider(..)
    meshplot = mesh!(...)[end]
    on(s_marker_radius) do x
        scale!(meshplot, x, x, x)
    end
    return slider
end
```
Add some point it might also make more sense to use meshscatter:
```julia
sliders = map(1:10) do i
    slider, radius = slider(...)
end
radius_observables = last.(sliders)
markersize = lift(vcat, radius_observables...)
meshscatter!(..., markersize=markersize)
```
