### ISSUE TITLE
slider with multiple handles

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Makie.jl#650]
I find it really useful, especially to select a subrange of a range, to have a slider with multiple handles (and potentially allowing to customize which "segment" is highlighted). I imagine it should be feasible with `LSlider` as it already has an initial highlighted segment. For an example see for instance https://refreshless.com/nouislider/.

The API in Interact is that you pass an array, instead of a scalar, as starting value, and it would make an handle for each of them. As a consequence the `:value` would give an `Observable{Vector}`

**Comment by jkrumbiegel** [comment]
good idea, I can try it when I have time. By multiple you mean exactly two right? I don't see what you would do with more and the logic would be much more complicated I guess

**Comment by piever** [comment]
I confess I've never needed it with more than two (highlighting the chunk in the middle rather than the one in the beginning), so yeah, if the code is cleaner with just two, I think that's the way to go.

**Comment by ffreyer** [comment]
> good idea, I can try it when I have time.

And so he did. https://makie.juliaplots.org/stable/makielayout/intervalslider.html
