### ISSUE TITLE
`to_offset` is overly-strict on types

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#66]
```julia
sn = Scene()
lines(rand(10), rand(10), offset=(0.0, 2))
center!(sn)
```

This gives the error
`MethodError: no method matching to_offset(::Makie.Scene{:makie}, ::Tuple{Float64,Int64})`

If the offset is given as a tuple where both are Ints or both are Floats it's OK.

**Comment by SimonDanisch** [comment]
Yes, I'll need to go through these!
