### ISSUE TITLE
heatmap ticks are "off"

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Makie.jl#661]
Sorry for the uninformative title! I find that the `x` and `y` values should be at the center of the bins.

For example, for `heatmap(1:3, 1:4, rand(3, 4))` Makie gives (note the ticks placement)

![makie_heatmap](https://user-images.githubusercontent.com/6333339/88392461-f4e96d00-cdb3-11ea-853b-3d41f89a5108.png)

But I believe that the correct `x, y` values are those given by Plots (with the same command):

![plots_heatmap](https://user-images.githubusercontent.com/6333339/88392535-0fbbe180-cdb4-11ea-8002-25d49a258197.png)

**Comment by kool7d** [comment]
Shifting the indices like this works for me.
```
heatmap(1:3, 1:4, rand(3, 4))

indexshift(idxs,shift=1.0) = try
	float.(idxs).+=shift .|> Int
catch
	float.(idxs).+=shift
end

xs = 1:3; ys = 1:4; data = rand(3, 4)
xs = indexshift([xs...,xs[end]+1], -0.5)
ys = indexshift([ys...,ys[end]+1], -0.5)

heatmap(xs, ys, data)
```

**Comment by mschauer** [comment]
I could see that the makie default would be the one you want when putting a heat map as background of a figure.

**Comment by kool7d** [comment]
Maybe there could be a kwarg like 
```heatmap(xs, ys, data; centerindex = true) = heatmap(float.([xs...,xs[end]+1]).-=0.5, float.([xs...,xs[end]+1]).-=0.5, data)```

**Comment by piever** [comment]
Fixed on master by https://github.com/JuliaPlots/AbstractPlotting.jl/pull/727
