### ISSUE TITLE
GLMakie window dies

### ISSUE THREAD

**Issue by emiwar** [JuliaPlots/Makie.jl#668]
This looks like a very cool and useful package!

When I open any windows with GLMakie they work properly at first but die after ~10s. This might be similar to #304 , but happens for non-interactive plots as well, for example for
```
using Makie
scene = scatter(rand(10), rand(10))
screen = display(scene)
```
Inspecting `screen.rendertask[]` gives
```
Task (failed) @0x000000004b0d1cd0
GLFWError (PLATFORM_ERROR): WGL: Failed to make context current: The handle is invalid. 
_ErrorCallbackWrapper(::Int32, ::Cstring) at C:\Users\Emil\.julia\packages\GLFW\g1nX6\src\callback.jl:43
MakeContextCurrent at C:\Users\Emil\.julia\packages\GLFW\g1nX6\src\glfw3.jl:659 [inlined]
make_context_current at C:\Users\Emil\.julia\packages\GLMakie\Y3YHT\src\drawing_primitives.jl:46 [inlined]
vsynced_renderloop(::GLMakie.Screen) at C:\Users\Emil\.julia\packages\GLMakie\Y3YHT\src\rendering.jl:9
renderloop(::GLMakie.Screen; framerate::Float64) at C:\Users\Emil\.julia\packages\GLMakie\Y3YHT\src\rendering.jl:44
renderloop(::GLMakie.Screen) at C:\Users\Emil\.julia\packages\GLMakie\Y3YHT\src\rendering.jl:41
(::GLMakie.var"#47#49"{GLMakie.Screen})() at .\task.jl:356
```

Makie v0.11.1, Julia 1.5.0-rc2.0, Windows 10, NVidia driver 451.67

Thanks!

**Comment by jkrumbiegel** [comment]
I've experienced closing windows since the recent changes to the renderloop, but only on my relatively weak windows laptop. My macbook seems to be fine. It also seems to be less frequent if I set `set_window_config!(vsync = false)`.

**Comment by jaakkor2** [comment]
I see this as well on Windows 10 with integrated Intel graphics.  Problem started with GLMakie v0.1.6, and was fine with GLMakie v0.1.5.

`set_window_config!(vsync = false)` works as a workaround for me as well, I did not see window to have closed with this setting.
