### ISSUE TITLE
:mouseposition signal is in pixels

### ISSUE THREAD

**Issue by ssfrr** [JuliaPlots/Makie.jl#67]
It seems like providing the mouse position in pixels is not usually what one wants. If you're doing a UI thing like triggering rotation then you get issues with different DPI screens, and if you're placing an object you need to use `to_world`. Here are some other options I can think of:

1. normalize to 0-1 where (0, 0) is the lower-left and (1, 1) is the upper-right
2. normalize to 0-1 based on the longest dimension of the window (so (0,0)-(1,1) is a square)
3. normalize to 0-1 based on the shortest dimension of the window (so (0,0)-(1,1) is a square)
4. detect the DPI of the display and use real-world units like cm.

I think I'm partial to no. 4 but I'm not sure if that's workable reliably.

**Comment by mkborregaard** [comment]
What about the option of providing it in the plot coordinate system, if within the plot area?

**Comment by ssfrr** [comment]
I think that intersects with the camera discussion - if there are multiple cameras in a scene, it's not clear which of them should drive the transformation from screen to world coordinates. Currently the `to_world` function takes a camera argument so it's unambiguous.

**Comment by SimonDanisch** [comment]
I think it should be clear what camera drives the plot in future versions! 
So I'd prefer to have it in pixels or normalized coordinates, and if needed transform it with `to_world(scene, mouse_px)`. I'm a bit against making world coordinates the default - I'd need figure out a way to not calculate this relatively expensive calculation for every mouse move, even if it's not actually used ;)

**Comment by ssfrr** [comment]
you prefer pixels to cm, or is it hard to reliably get the screen DPI?

**Comment by SimonDanisch** [comment]
Are you referring to the camera issue? I just like pixel as the default, since it's plain and nicely maps to a fixed pixel camera ;) And you could just convert it to mm/cm if needed! I'll need to think about how to do that nicely in the unit aware Makie, without doing something like `convert(Millimeter, scene, mousepos)` since we'll need information from the scene for this :(

**Comment by ssfrr** [comment]
No, I mean cm on the actual user's screen, not in world coordinates, so that issues like are #33 less likely.

e.g. if I'm doing something like:

```julia
lastpos = Vector2f0(0, 0)
x = lift_node(scene, :mouseposition) do pos
    diff = pos - lastpos
    lastpos = pos
    # do something with diff
end
```

than `diff` will represent a given physical distance of mouse motion independent of the user's DPI.

**Comment by SimonDanisch** [comment]
Issue #33 was what I wanted to reference here ;)

**Comment by SimonDanisch** [comment]
We should use mm in that case anyways!

**Comment by ssfrr** [comment]
ah, i see. Yeah, mm/cm/inches/furlongs, whatever, just real-world units. :)

**Comment by SimonDanisch** [comment]
`mouseposition(scene)` now, that returns the mouseposition in data units
