### ISSUE TITLE
LMenu default value selection - MakieLayout.jl

### ISSUE THREAD

**Issue by errearanhas** [JuliaPlots/Makie.jl#670]
When setting a `menu=LMenu(...)` object, there is this `menu.i_selected = 1` method to set a starting default value for the menu.

Maybe a better option would be the object already setting the first available option as default, without the need of manually setting it. Would it be possible?

**Comment by jkrumbiegel** [comment]
This is possible, it's just a matter of good defaults. I thought there is no harm in not preselecting something unexpected. But it could be made easier to preselect one of the options

**Comment by garrekstemo** [comment]
I think this is implemented now. #2074

**Comment by jkrumbiegel** [comment]
Yes one can now set defaults
