### ISSUE TITLE
bug: "squiggly" renders (axes + plot)

### ISSUE THREAD

**Issue by behinger** [JuliaPlots/Makie.jl#676]
I am not sure what happened, but recently Makie Plots started to look like this:
```scatter(1:10,ones(10),marker="cdefghijlk")```
![grafik](https://user-images.githubusercontent.com/10183650/89291898-a06baa80-d65b-11ea-90e5-37a7ad97e5a6.png) 

I tried updating to Julia 1.5 and rebuilding Makie but that didn't work.
I only loaded Revise, OhMyREPL and Makie (0.11.1)

**Comment by SimonDanisch** [comment]
What's the abstractplotting and GLMakie version?

**Comment by behinger** [comment]
[e9467ef8] GLMakie v0.1.8
  [537997a7] AbstractPlotting v0.12.6

**Comment by SimonDanisch** [comment]
What OS?
Can you remove the font cache? The path is in AbstractPlotting/sec/texture_atlas.jl
Something like AbstractPlotting.cache_path or so ;)

**Comment by behinger** [comment]
Windows 10

Fontcache deletion worked partially:
![grafik](https://user-images.githubusercontent.com/10183650/89295387-335b1380-d661-11ea-8533-a2d66b2f2b14.png)
Besides the stretching (#677) the stencil-like glyphs in the plot were not there before.

Potentially related: Zooming/Moving the window makes the Makie-Window crash without outputting any error (secret verbose flag somewhere?)

**Comment by SimonDanisch** [comment]
Try updating to `GLMakie@0.1.9`

**Comment by SimonDanisch** [comment]
Oh, and the stencil like glyphs are actually, because the scatter defaults have changed... This will give you the old behaviour:
```
scatter(1:10,ones(10),marker="cdefghijlk", strokewidth=0, color=:black, markerspace=AbstractPlotting.SceneSpace, markersize=0.3)
```
This will still leave you with stretched glyphs, but if I'm not forgetting a change, this is actually by design... Even, if it's probably not the best design^^
You should use text/annotations for actual text.

**Comment by behinger** [comment]
Seems to work for now. Thanks!

Why I use scatter: I don't have text on a line, but text around curved paths. And I have ~60.000 characters to plot. My intution was to use scatter, but I can also try text/annotation 

PS: I restarted julia repl everytime - is that necessary?

**Comment by SimonDanisch** [comment]
>PS: I restarted julia repl everytime - is that necessary?

Every time after what?
For the text cache it kinda is, although, you can also just re-evaluate `texture_atlas.jl`.

> And I have ~60.000 characters to plot

Hm, so text should have similar rendering performance as scatter, although, it does a bit more work during setup (e.g. layouting).
You can also size the glyphs correctly quite easily:

```julia
font = to_font("Deja vue")
lotsoftext = randstring(60_000)
positions = rand(Point2f0, 60_000) .* 1000
sizes = widths.(AbstractPlotting.glyph_boundingbox.(collect(lotsoftext), font, 16))
scatter(positions, marker=lotsoftext, markersize=sizes)
```

Looks pretty cool :D And with pixelspace, the glyphs are always readable: 
![image](https://user-images.githubusercontent.com/1010467/89338310-b2217200-d69c-11ea-8b87-9638e3b44b69.png)

**Comment by behinger** [comment]
- restart repl after installing a package update was my Question
- It is definitely not normal that you can just plot 60.000 characters like that. Other software I tried in the past (i.e. matlab, ggplot) really doe not like it. Great job!

I ran @time with annotation (0.6s) and scatter (0.2s-0.3s), so maybe there is a benefit of scatter.

Ok this ticket extends over and beyond what I initially asked. Thanks a ton for the fast help!

PS: I noticed you cant use color=[1,2,1,2,2,3, ...] in annotations while you can in scatter. Should I open a ticket for it?

**Comment by SimonDanisch** [comment]
Hehe, great :) 
Pfew, I dunno, we need to rework the annotation api anyways, and doesn't seem a high priority atm to support `color=Vector{Number}`...
