### ISSUE TITLE
Stretched Glyphs when plotting (GLMakie, CairoMakie is fine)

### ISSUE THREAD

**Issue by behinger** [JuliaPlots/Makie.jl#677]
If I run:
``` julia> scatter(1:10,ones(10),marker="cdefghijlk") ```
I get this plot:
![grafik](https://user-images.githubusercontent.com/10183650/89229860-8fcb1e00-d5e2-11ea-91a2-f1b42127cffd.png)
With clearly stretched/distorted glyphs. 

 If I export it to a svg using cairo:
``` 
using AbstractPlotting,CairoMakie
AbstractPlotting.current_backend[] = CairoMakie.CairoBackend("test.svg")
open("test.svg","w") do io
       show(io, MIME"image/svg+xml"(), p)
end
``` 
I get the correct "undistorted" SVG glyphs

**Comment by SimonDanisch** [comment]
That is somewhat by design - although may be a bad design!
Can workaround by supplying the sizes:
```julia
font = to_font("Deja vue")
lotsoftext = randstring(60_000)
positions = rand(Point2f0, 60_000) .* 1000
sizes = widths.(AbstractPlotting.glyph_boundingbox.(collect(lotsoftext), font, 16))
scatter(positions, marker=lotsoftext, markersize=sizes)
```

**Comment by behinger** [comment]
Thanks, but isn't it a bug then in CairoMakie to not stretch them?

**Comment by jkrumbiegel** [comment]
As the person who implemented some of the CairoMakie backend I think I assumed normal glyphs were the desired output and treated GLMakies stretchy behavior as an unfixed bug
