### ISSUE TITLE
Arrowheads have a zoom-dependent outline

### ISSUE THREAD

**Issue by vilim** [JuliaPlots/Makie.jl#688]
When setting e.g. the attributes
```julia
linecolor=:red,
arrowcolor=:red,
```
in quiver or arrows, I get arows which look like this:
![image](https://user-images.githubusercontent.com/3041236/90664170-e96e5200-e24a-11ea-857e-0e6fda540e19.png)

when zoomed out, and like this:
![image](https://user-images.githubusercontent.com/3041236/90664217-f723d780-e24a-11ea-897a-e63049aba842.png)
when zoomed in.

Is there another attribute I need to set, or is this a bug in GLMakie?

I am using GLMakie v0.1.10 and AbstractPlotting v0.12.6 on Julia 1.5 on Windows.

**Comment by SimonDanisch** [comment]
Oooh... I think that changed when the defaults for scatter changed to include a stroke - and we dont actually set/forward any stroke colors to the scatter function...
If you want to fix this, it would be an easy PR:
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/basic_recipes/basic_recipes.jl#L237

**Comment by vilim** [comment]
Thank you, that was a quick fix!
