### ISSUE TITLE
Arrowheads in Makie are misaligned and do not point exactly to the specified endpoint.

### ISSUE THREAD

**Issue by ghralima** [JuliaPlots/Makie.jl#689]
The arrowheads are always slightly misaligned with the arrow body, unless both axis share the same scale, which sometimes is not the desired option. Also, the arrowheads should end exactly at the endpoints specified by the function, but instead the triangle (or any other marker) is centered at the specified end point.

**Comment by ffreyer** [comment]
I think we fixed this in https://github.com/JuliaPlots/AbstractPlotting.jl/pull/720
