### ISSUE TITLE
VScode lacks the dropdown trees like Juno

### ISSUE THREAD

**Issue by kool7d** [JuliaPlots/Makie.jl#697]
I find the dropdown things of whatever is returned from code execution to be super useful. I don't think there is such a thing in VScode. It doesn't seem very complicated. Is anyone working on filling that gap? What do you think? It is useful enough to me that I still am using Juno for a lot of stuff.

**Comment by mschauer** [comment]
Slightly miss-placed issue ;-)

**Comment by mkborregaard** [comment]
And VSCode has them.

**Comment by kool7d** [comment]
Sorry for the misplaced issue! I was thinking of a Makie solution to it.
How do I get them working in VScode?
