### ISSUE TITLE
Multiple lines and alpha blending in CairoMakie vs. GLMakie

### ISSUE THREAD

**Issue by dgleich** [JuliaPlots/Makie.jl#707]
There is a difference with how CairoMakie and GLMakie show multiple lines in terms of alpha blending and stroking.
In GLMakie it doesn't matter if you give multiple lines at once, or individual lines in terms of the blending behavior. So the following two plots are identical. 

```
##
using GLMakie, Colors
scene = lines([0.25,0.75],[0.25,0.75],color=RGBA(0,0,0,0.5),linewidth=30)
lines!([0.75,0.25],[0.25,0.75],color=RGBA(0,0,0,0.5),linewidth=30)
scene # or save scene... 
## This shows the same thing... 
scene = lines([0.25,0.75,NaN,0.75,0.25],[0.25,0.75,NaN,0.25,0.75],color=RGBA(0,0,0,0.5),linewidth=30)
scene # or save scene... 
```

In CairoMakie, this makes a difference. 

```
##
using CairoMakie, AbstractPlotting, Colors
scene = lines([0.25,0.75],[0.25,0.75],color=RGBA(0,0,0,0.5),linewidth=30)
lines!([0.75,0.25],[0.25,0.75],color=RGBA(0,0,0,0.5),linewidth=30)
scene # or save scene... 
##
scene = lines([0.25,0.75,NaN,0.75,0.25],[0.25,0.75,NaN,0.25,0.75],color=RGBA(0,0,0,0.5),linewidth=30)
scene
```

The first one does show blending on the lines. The second does not.

This occurs because Cairo will assemble the full path and then stroke it before blending it.

In terms of the Cairo calls the first case is represented by 

```
using Cairo
c = CairoARGBSurface(256,256)
cr = CairoContext(c)

set_source_rgba(cr,0.0,0.0,0.0,0.5)
set_line_width(cr, 30.0);
move_to(cr, 32,32)
line_to(cr, 256-32,256-32)
stroke(cr)
move_to(cr, 256-32,32)
line_to(cr, 32,256-32)
stroke(cr)

write_to_png(c,"test.png")
```

whereas the second case is represented by

```
using Cairo
c = CairoARGBSurface(256,256)
cr = CairoContext(c)

set_source_rgba(cr,0.0,0.0,0.0,0.5)
set_line_width(cr, 30.0);
move_to(cr, 32,32)
line_to(cr, 256-32,256-32)
move_to(cr, 256-32,32)
line_to(cr, 32,256-32)
stroke(cr)

write_to_png(c,"test.png")
```

which shows the same difference. 

In terms of being self-consistent, I think the 'blended' behavior is consistent with both GLMakie, and also variations on calls to lines. The following call also shows the blended behavior.

```
using CairoMakie, AbstractPlotting, Colors
scene = lines([0.25,0.75,NaN,0.75,0.25],[0.25,0.75,NaN,0.25,0.75],color=[RGBA(0,0,0,0.5) for i in 1:5],linewidth=30)
scene
```

A fix is fairly simple if that is desired as one simply has to insert 

```
function draw_single(primitive::Lines, ctx, positions)
    Cairo.move_to(ctx, positions[1]...)
    for i in 2:length(positions)
        if isnan(positions[i])
            i == length(positions) && break
            Cairo.move_to(ctx, positions[i+1]...)
        else
            Cairo.stroke(ctx) # NEW:  insert complete new segment
            Cairo.line_to(ctx, positions[i]...)
        end
    end
    Cairo.stroke(ctx)
end

function draw_single(primitive::LineSegments, ctx, positions)
    @assert iseven(length(positions))
    Cairo.move_to(ctx, positions[1]...)
    for i in 2:length(positions)
        if iseven(i)
            Cairo.line_to(ctx, positions[i]...)
        else
            Cairo.stroke(ctx) # NEW:  insert complete new segment
            Cairo.move_to(ctx, positions[i]...)
        end
    end
    Cairo.stroke(ctx)
end

**Comment by jkrumbiegel** [comment]
The drawback of drawing every single line segment separately is that you lose the line joins. I personally don't like the look when there are small gaps between separate angled segments. But I assume in your case this is about many lines where you want to see overlapping areas darker as a form of density visualization?

**Comment by dgleich** [comment]
Oh, I think I fat-fingered a copy-and-paste edit to the NaN case that resulted in a misunderstanding here. My apologies. What I think is that all of the three following calls should be treated identically. There should be a proper line-join in the first line, but then alpha blending between NaN separated lines. 

Put simply: NaN separated lines and multiple calls to lines should be equivalent. 

````
using CairoMakie, AbstractPlotting, Colors
scene = lines([0.25,0.50,0.75,NaN,0.75,0.25],[0.25,0.0,0.75,NaN,0.25,0.75],color=RGBA(0,0,0,0.5),linewidth=30)
scene
##
scene = lines([0.25,0.5,0.75,NaN,0.75,0.25],[0.25,0.0,0.75,NaN,0.25,0.75],color=[RGBA(0,0,0,0.5) for i in 1:6],linewidth=30)
scene
##
scene = lines([0.25,0.5,0.75],[0.25,0.0,0.75],color=RGBA(0,0,0,0.5),linewidth=30)
lines!([0.75,0.25],[0.25,0.75],
  color=RGBA(0,0,0,0.5),linewidth=30)
````

I think the code should have been... [I guess not so simple...] 

````
function draw_single(primitive::Lines, ctx, positions)
    Cairo.move_to(ctx, positions[1]...)
    for i in 2:length(positions)
        if isnan(positions[I])
            i == length(positions) && break
            Cairo.stroke(ctx) # NEW:  insert and stroke complete new segment
            Cairo.move_to(ctx, positions[i+1]...)
        else
            Cairo.line_to(ctx, positions[i]...)
        end
    end
    Cairo.stroke(ctx)
end
````

Yes -- the idea to use this as a simple density visualization. (networks with ~100M edges/lines).

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaPlots/CairoMakie.jl/pull/150.

**Comment by dgleich** [comment]
Thanks all! Appreciate it!
