### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by MartinOtter** [JuliaPlots/Makie.jl#719]
Is there a possibility to generate multiple windows with Makie, e.g. scene1=Scene(); scene2=Scene() and then have two windows. When I do this on my Windows 10 machine, only **one** window is shown (either scene1 or scene2, depending on the last command).

**Comment by SimonDanisch** [comment]
Duplicate of: https://github.com/JuliaPlots/Makie.jl/issues/188
