### ISSUE TITLE
Useful for visualizing on a sphere?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPlots/Makie.jl#72]
I'm looking for a "good" method to do visualizations on the sphere, including heat maps and vector fields.

Is this possible in Makie?

**Comment by SimonDanisch** [comment]
Can you give an example? how i imagine it, mapping something to the surface of a sphere, it should be possible ;)

**Comment by dlfivefifty** [comment]
For the density plot, @MikaelSlevinsky has some nice examples he did using PlotlyJS (https://arxiv.org/pdf/1801.04902.pdf)

<img width="175" alt="untitled" src="https://user-images.githubusercontent.com/1229737/36921293-b929b040-1e5b-11e8-95ad-1b0b518f321f.png">

For vector fields on a sphere, the simplest is just to plot a lot of arrows, a bit nicer would be a [stream plot](http://reference.wolfram.com/language/ref/StreamPlot.html) but where the stream lines are on the sphere, with colour used to indicate magnitude.

**Comment by SimonDanisch** [comment]
Is the code somewhere, so I can get an idea of the interface?

**Comment by dlfivefifty** [comment]
Yes: https://github.com/JuliaApproximation/SpectralTimeStepping.jl/blob/master/NonlocalSphere/plot_Allen_Cahn.jl
The key line is
```julia
  s = surface(x=x, y=y, z=z, colorscale = "Viridis", surfacecolor = F, cmin = -1.0, cmax = 1.0, showscale = false)
```
where `F` is the heights of the function.

**Comment by dlfivefifty** [comment]
For the arrow plot case, the interface should match `quiver`: something like
```julia
quiver(pts, quiver=df)
```
where `pts` is a `Vector{<:Point}` or `Vector{<:Tuple}` and `df` is also a `Vector{<:Point}` or `Vector{<:Tuple}`.

**Comment by SimonDanisch** [comment]
Do you expect the arrows do bend according to the surface of the sphere?

**Comment by SimonDanisch** [comment]
and will the points / vectors be 2d, and you will indicate with a keyword argument, that they should be on a sphere?

**Comment by dlfivefifty** [comment]
> Do you expect the arrows do bend according to the surface of the sphere?

I "expect" them to not because that's hard to implement, but I wish they would.

**Comment by dlfivefifty** [comment]
No, 3D

**Comment by SimonDanisch** [comment]
Surface works!
![grafik](https://user-images.githubusercontent.com/1010467/36975158-8727e34e-2079-11e8-87a7-24104e0372a8.png)

I will make a pr to make it a bit more user friendly, since right now, you need to map F to an array of colors yourself... But that actually fits well with implementing `image(x::Matrix{Float64}, colormap = ..., color_norm = (-1, 1))` to also work as intended ;)

I just recently added a prototype for quiver, I'll take a look how far it is ;)

**Comment by SimonDanisch** [comment]
Do you also have a piece of code that gives me `pts` and `df`?

**Comment by dlfivefifty** [comment]
For `quiver`, probably something like:
```julia
f    = (x,y,z) -> x*exp(cos(y)*z)
∇f  = (x,y,z) -> SVector(exp(cos(y)*z), -sin(y)*z*x*exp(cos(y)*z), x*cos(y)*exp(cos(y)*z))
∇ˢf = (x,y,z) -> ∇f(x,y,z) - SVector(x,y,z)*dot(SVector(x,y,z), ∇f(x,y,z))

θ = [0;(0.5:n-0.5)/n;1]
φ = [(0:2n-2)*2/(2n-1);2]
x = [cospi(φ)*sinpi(θ) for θ in θ, φ in φ]
y = [sinpi(φ)*sinpi(θ) for θ in θ, φ in φ]
z = [cospi(θ) for θ in θ, φ in φ]

pts = vec(SVector.(x, y, z))
∇ˢF = vec(∇ˢf.(x, y, z))

quiver(pts, df=∇ˢF)
```

**Comment by SimonDanisch** [comment]
Something like this?
![grafik](https://user-images.githubusercontent.com/1010467/36984358-ff05f264-2094-11e8-9a59-bd1f764c83f8.png)

**Comment by dlfivefifty** [comment]
Perfect!   (I assume all the arrows are tangential to the sphere... hard to tell without being able to rotate and zoom.)


If the arrows could wrap around the sphere it would be even nicer... but I guess that will take some work (and may be too slow in practice)...

**Comment by SimonDanisch** [comment]
Slowness shouldn't be a problem, but someone will need to put some time into emiting the correct line paths... I'm guessing one would need to project the 3D vectors on the surface of the sphere?

They're not really tangential, since `pts .+ ∇ˢF` doesn't result on the points being on the sphere. Maybe I'm interpreting `∇ˢF` wrong? I'm using `pts[i] => pts[i] + ∇ˢF[i]` to generate line segments

**Comment by dlfivefifty** [comment]
It should be true that `dot(∇ˢF[i], pts[i]) ≈ 0` for all `i` by construction (since `norm(SVector(x,y,z)) == 1`). In other words, `∇ˢF[i]` is tangential to the normal at `pts[i]`. 

This means the arrow connecting `pts[i]` and `∇ˢF[i]` should line in the tangent plane (that is if you draw a plane tangential to the sphere at `pts[i]`)

**Comment by dlfivefifty** [comment]
> They're not really tangential, since `pts .+ ∇ˢF` doesn't result on the points being on the sphere

To clarify further: `pts .+ ∇ˢF` should not be on the sphere.

**Comment by dlfivefifty** [comment]
Cool! That's good enough for me.

**Comment by dlfivefifty** [comment]
PS Is it easy to create animated GIFs like on the README? 

I'll send you some nice movies of evolving functions / vector fields on the sphere once we get it working.

**Comment by MikaelSlevinsky** [comment]
This is really cool! Care to give ballpark timings? (PlotlyJS worked great up to about 512 x 1024 grids)

More of a transforms-related issue, but the grids probably shouldn't cluster at the poles for a quiver plot.

**Comment by dlfivefifty** [comment]
Is there Julia code for generating uniformly distributed points on the sphere?

**Comment by MikaelSlevinsky** [comment]
There's Matlab code for minimum energy or maximum determinant nodes https://github.com/gradywright/spherepts/blob/master/docs/NodesGridsMeshesOnSphere.pdf

but perhaps HEALPix would be better transforms-wise.

**Comment by MikaelSlevinsky** [comment]
Oh wait, the min energy and max det use huge look-up tables. https://github.com/gradywright/spherepts/tree/master/nodes

**Comment by dlfivefifty** [comment]
It’s MIT license so we can just copy the tables

**Comment by SebastianM-C** [comment]
You can generate uniformly distributed points oh the unit sphere with something like this:
```
function SphericalToCartesian(r::T,θ::T,ϕ::T) where T<:AbstractArray
    x = @.r*sin(θ)*cos(ϕ)
    y = @.r*sin(θ)*sin(ϕ)
    z = @.r*cos(θ)
    
    x,y,z
end

n = 1000 # number of points to generate

r = ones(n);
θ = acos.(1 .- 2 .* rand(n));
ϕ = 2π * rand(n);

x,y,z = SphericalToCartesian(r,θ,ϕ);
```

**Comment by dlfivefifty** [comment]
I think random points are not a good idea since the arrows will be hard to read. Also you’ll have clustering of points.

PS here’s another random points on the sphere which is coordinate independent:
```julia
qr(randn(3,3))[1][:,1]
```

**Comment by SimonDanisch** [comment]
So this works now on master:
```Julia
using GeometryTypes, Colors, Makie
# the surface
scene = Scene()
s = Makie.surface(x, y, z, image = F, colormap = :viridis, colornorm = (-1.0, 1.0))
s[:image] = F .+ 0.1 # update image

# the quiver

n = 20
f   = (x,y,z) -> x*exp(cos(y)*z)
∇f  = (x,y,z) -> Point3f0(exp(cos(y)*z), -sin(y)*z*x*exp(cos(y)*z), x*cos(y)*exp(cos(y)*z))
∇ˢf = (x,y,z) -> ∇f(x,y,z) - Point3f0(x,y,z)*dot(Point3f0(x,y,z), ∇f(x,y,z))

θ = [0;(0.5:n-0.5)/n;1]
φ = [(0:2n-2)*2/(2n-1);2]
x = [cospi(φ)*sinpi(θ) for θ in θ, φ in φ]
y = [sinpi(φ)*sinpi(θ) for θ in θ, φ in φ]
z = [cospi(θ) for θ in θ, φ in φ]

pts = vec(Point3f0.(x, y, z))
∇ˢF = vec(∇ˢf.(x, y, z))
scene = Scene();

surface(x, y, z)
arr = Makie.arrows(
    scene,
    pts, ∇ˢF,
    arrowsize = 0.03, linecolor = (:gray, 0.7), linewidth = 3
)
arr[:lengthscale] = 0.3

center!(scene)
# record a video
io = VideoStream(scene, joinpath(homedir(), "Desktop"), "test")
arr[:directions] = ∇ˢF
for i = 1:100
    arr[:directions] = (to_value(arr, :directions) .+ (rand(Float32, length(∇ˢF)) * 0.05))
    recordframe!(io)
    sleep(1/30)
end
finish(io, "mp4") # could also be gif, webm or mkv

```

**Comment by SimonDanisch** [comment]
Please let me know about any problems in a new issue ;)

**Comment by dlfivefifty** [comment]
The code work, and I checked and all the arrows are in the tangent plane, yay! It's a bit clearer when we normalize and scale:
```julia
scene = Scene(); surface(scene , x, y, z); arr = Makie.arrows(
                  scene,
                  pts, normalize.(∇ˢF)./15,
                  arrowsize = 0.03, linecolor = (:gray, 0.7), linewidth = 3
              )
```

Some questions:
1. You never gave the code for the density map plot
2. For the arrows on the sphere, does the fact that they are (circular) arcs help? I.e., is there an `arc` analogue to `linesegment` (used to make the arrows)?

**Comment by SimonDanisch** [comment]
The code for the density map is above:
```Julia
using GeometryTypes, Colors, Makie
# the surface
scene = Scene()
s = Makie.surface(x, y, z, image = F, colormap = :viridis, colornorm = (-1.0, 1.0))
s[:image] = F .+ 0.1 # update image
```

**Comment by dlfivefifty** [comment]
Forgot one question:

\3. How do you clear the scene?

**Comment by SimonDanisch** [comment]
3)
I usually just make a new scene! In the future, I plan to offer a more Plots.jl like api, where plot (without !) will just create a new scene!

**Comment by SimonDanisch** [comment]
Btw, there are arguments for normalization and scaling: 
https://github.com/JuliaPlots/Makie.jl/blob/master/src/plotsbase/basic_recipes.jl#L14
Not sure if `lengthscale` is a particularly nice name^^

**Comment by SimonDanisch** [comment]
2.) For the arrows on the sphere, does the fact that they are (circular) arcs help? I.e., is there an arc analogue to linesegment (used to make the arrows)?

We can definitely just draw lines with a high enough granularity, to look like they're bend along the sphere ;) Could you supply me with an example code, using `lines(arc::Vector{Point3f0})`, to show how to translate `∇ˢF` into a vector field of arcs?

**Comment by dlfivefifty** [comment]
At that point we might as well do streamlines. Here's a first attempt (it works but is dreadfully slow, and needs a better point distribution to look good):
```julia
function sphere_streamline(∇ˢf, pt, h=0.01f0, n=5)    
    ret = [pt]
    df = normalize(∇ˢf(pt...))
    push!(ret, normalize(pt .+ h*df))
    for k=2:n
        cur_pt = last(ret)
        push!(ret, cur_pt)
        df = normalize(∇ˢf(cur_pt...))
        push!(ret, normalize(cur_pt .+ h*df))
    end
    ret
end

function plotstreamline(scene, ret)
    linecolor = :gray
    linewidth = 3
    scale = Vec3f0(1)
    linesegment(scene, ret, color = linecolor, linewidth = linewidth, linestyle = nothing, scale = scale)
    Makie.arrows(scene, [ret[end-1]], [ret[end]-ret[end-1]], arrowsize = 0.01, linecolor = (:gray, 0.7), linewidth = 3)
end

lns = sphere_streamline.(∇ˢf, pts, 0.03f0)

scene = Scene();
    for ln in lns
        plotstreamline(scene, ln)
    end  
```

**Comment by SimonDanisch** [comment]
ok, let's make it fast :)

**Comment by SimonDanisch** [comment]
Wow, it's slower than I imagined ;) Good news is, it should be easy to fix!

**Comment by SimonDanisch** [comment]
I didn't expect it to be fast, but there must also be a performance bug, since it seems to become at least quadratically slower

**Comment by SimonDanisch** [comment]
This seems to be reasonably fast:
```Julia
using Makie, GeometryTypes
function sphere_streamline(linebuffer, ∇ˢf, pt, h=0.01f0, n=5)
    push!(linebuffer, pt)
    df = normalize(∇ˢf(pt[1], pt[2], pt[3]))
    push!(linebuffer, normalize(pt .+ h*df))
    for k=2:n
        cur_pt = last(linebuffer)
        push!(linebuffer, cur_pt)
        df = normalize(∇ˢf(cur_pt...))
        push!(linebuffer, normalize(cur_pt .+ h*df))
    end
    return
end

function streamlines(
        scene, ∇ˢf, pts::AbstractVector{T};
        h=0.01f0, n=5, color = :black, linewidth = 1
    ) where T
    linebuffer = T[]
    sub = Scene(
        scene,
        h = h, n = 5, color = :black, linewidth = 1
    )
    lines = lift_node(to_node(∇ˢf), to_node(pts), sub[:h], sub[:n]) do ∇ˢf, pts, h, n
        empty!(linebuffer)
        for point in pts
            sphere_streamline(linebuffer, ∇ˢf, point, h, n)
        end
        linebuffer
    end
    linesegment(sub, lines, color = sub[:color], linewidth = sub[:linewidth])
    sub
end

# needs to be in a function for ∇ˢf to be fast and inferable
function test()
    n = 20
    f   = (x,y,z) -> x*exp(cos(y)*z)
    ∇f  = (x,y,z) -> Point3f0(exp(cos(y)*z), -sin(y)*z*x*exp(cos(y)*z), x*cos(y)*exp(cos(y)*z))
    ∇ˢf = (x,y,z) -> ∇f(x,y,z) - Point3f0(x,y,z)*dot(Point3f0(x,y,z), ∇f(x,y,z))
    θ = [0;(0.5:n-0.5)/n;1]
    φ = [(0:2n-2)*2/(2n-1);2]
    x = [cospi(φ)*sinpi(θ) for θ in θ, φ in φ]
    y = [sinpi(φ)*sinpi(θ) for θ in θ, φ in φ]
    z = [cospi(θ) for θ in θ, φ in φ]

    pts = vec(Point3f0.(x, y, z))
    scene = Scene()
    lns = streamlines(scene, ∇ˢf, pts)
    # those can be changed interactively:
    lns[:color] = :black
    lns[:h] = 0.06
    lns[:linewidth] = 1.0
    for i = linspace(0.01, 0.1, 100)
        lns[:h] = i
        yield()
    end
end
test()
```

**Comment by loicspace** [comment]
Hi Hi,

I'm trying to play some with the arrows, and I'm using the code Simon put in there, 

```
using GeometryTypes, Colors, Makie 
# the quiver
n = 20
f   = (x,y,z) -> x*exp(cos(y)*z)
∇f  = (x,y,z) -> Point3f0(exp(cos(y)*z), -sin(y)*z*x*exp(cos(y)*z), x*cos(y)*exp(cos(y)*z))
∇ˢf = (x,y,z) -> ∇f(x,y,z) - Point3f0(x,y,z)*dot(Point3f0(x,y,z), ∇f(x,y,z))

θ = [0;(0.5:n-0.5)/n;1]
φ = [(0:2n-2)*2/(2n-1);2]
x = [cospi(φ)*sinpi(θ) for θ in θ, φ in φ]
y = [sinpi(φ)*sinpi(θ) for θ in θ, φ in φ]
z = [cospi(θ) for θ in θ, φ in φ]

pts = vec(Point3f0.(x, y, z))
∇ˢF = vec(∇ˢf.(x, y, z))
scene = Scene();

surface(x, y, z)
arr = Makie.arrows(scene,pts, ∇ˢF)

```
But I am getting the following error:

```
DimensionMismatch("tuples could not be broadcast to a common size")
Arrows{...}(::AbstractPlotting.Scene, ::AbstractPlotting.Attributes, ::Tuple{AbstractPlotting.Scene,Array{GeometryTypes.Point{3,Float32},1},Array{GeometryTypes.Point{3,Float32},1}}) at interfaces.jl:288
plot!(::AbstractPlotting.Scene, ::Type{Arrows{...}}, ::AbstractPlotting.Attributes, ::AbstractPlotting.Scene, ::Vararg{Any,N} where N) at interfaces.jl:382
#plot!#175(::Array{Any,1}, ::Function, ::AbstractPlotting.Scene, ::Type{T} where T, ::AbstractPlotting.Scene, ::Vararg{Any,N} where N) at interfaces.jl:364
plot!(::AbstractPlotting.Scene, ::Type{T} where T, ::AbstractPlotting.Scene, ::Array{GeometryTypes.Point{3,Float32},1}, ::Vararg{Array{GeometryTypes.Point{3,Float32},1},N} where N) at interfaces.jl:364
#plot#169(::Array{Any,1}, ::Function, ::Type{T} where T, ::AbstractPlotting.Scene, ::Vararg{Any,N} where N) at interfaces.jl:351
plot(::Type{T} where T, ::AbstractPlotting.Scene, ::Array{GeometryTypes.Point{3,Float32},1}, ::Vararg{Array{GeometryTypes.Point{3,Float32},1},N} where N) at interfaces.jl:351
#arrows#258(::Array{Any,1}, ::Function, ::AbstractPlotting.Scene, ::Vararg{Any,N} where N) at recipes.jl:77
arrows(::AbstractPlotting.Scene, ::Array{GeometryTypes.Point{3,Float32},1}, ::Vararg{Array{GeometryTypes.Point{3,Float32},1},N} where N) at recipes.jl:77
include_string(::String, ::String) at loading.jl:522
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##102#107{String,Int64,String})() at eval.jl:82
withpath(::Atom.##102#107{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
hideprompt(::Atom.##101#106{String,Int64,String}) at repl.jl:62
macro expansion at eval.jl:80 [inlined]
(::Atom.##100#105{Dict{String,Any}})() at task.jl:80
```
I have both Makie and AbstractPlotting checked out. What am I missing?
Cheers,

Loic

**Comment by mateuszbaran** [comment]
In case someone needs an updates version:
```julia
using GLMakie, Makie, LinearAlgebra

n = 10

θ = [0;(0.5:n-0.5)/n;1]
φ = [(0:2n-2)*2/(2n-1);2]
x = [cospi(φ)*sinpi(θ) for θ in θ, φ in φ]
y = [sinpi(φ)*sinpi(θ) for θ in θ, φ in φ]
z = [cospi(θ) for θ in θ, φ in φ]

f2(x, y, z) = cross([x, y, z], [1.0, 0.0, 0.0])
tans = f2.(vec(x), vec(y), vec(z))
u = [a[1] for a in tans]
v = [a[2] for a in tans]
w = [a[3] for a in tans]

scene = Scene();

surface(x, y, z)
arr = Makie.arrows!(
    vec(x), vec(y), vec(z), u, v, w;
    arrowsize = 0.1, linecolor = (:gray, 0.7), linewidth = 0.02, lengthscale = 0.1
)
```
