### ISSUE TITLE
meta: logo

### ISSUE THREAD

**Issue by LeMinaw** [JuliaPlots/Makie.jl#73]
As we just discussed (https://github.com/JuliaGL/GLVisualize.jl/issues/71), I tried to make a logo for Makie.

![](http://image.noelshack.com/fichiers/2018/10/1/1520259745-g4715.png)

The icon being only the color stripes.

It's drawn from a maki-e, matches Julia colors, and is intended to remind how fast is GPU plotting. :)

**Comment by SimonDanisch** [comment]
Wow, that was quick :) Great start, thank you! Do you have this in an editable format? I'd love to adjust the colors a bit more to my taste ;)

**Comment by LeMinaw** [comment]
I had to zip it, sorry -because GitHub doesn't allow svg uploading.
[makie.zip](https://github.com/JuliaPlots/Makie.jl/files/1781493/makie.zip)

**Comment by SimonDanisch** [comment]
Haha thanks! I might be able to unzip it! :)

**Comment by diegozea** [comment]
What about using the Maki-e word in Japanese and the Julia colors? I think is まきえ but I don't know Japanese.

**Comment by LeMinaw** [comment]
Hey @SimonDanisch,
Any news on this? Can I help in any way?
Cheers :)

**Comment by SimonDanisch** [comment]
Sorry! I wanted to tweak it a bit, got stuck since I didn't like my own tweaks - and then run out of time ;)
Also, the GLFW icon PR is still not merged^^

**Comment by SimonDanisch** [comment]
Thank you!
