### ISSUE TITLE
Let LAxis title be ""

### ISSUE THREAD

**Issue by grahamas** [JuliaPlots/Makie.jl#731]
When you give an empty string to the `title` kwarg of `LAxis`, you can get a couple different inscrutable errors.  When you try to put that LAxis into a layout, somewhere inside `setindex!` you'll get `ERROR: LoadError: InexactError: trunc(Int64, NaN)`.  If you get rid of all calls to `setindex` by making the `LAxis` the top level of the layout, then you'll get the marginally more sensible `ERROR: LoadError: ArgumentError: reducing over an empty collection is not allowed` which comes from the call to `map` in `glyph_positions` in `layouting.jl:110`.

Makie v0.11.1
AbstractPlotting v0.12.6 (also tried v0.12.16)
Julia v1.5.2

to-be-edited: sorry for the lack of both MWE and error messages.  It's late, the fix is simply `title = "fixme"` and my session is in tmux on a new OS install and I cannot for the life of me make it copy text.  If I don't have at *least* the full stack traces by Oct 25, please feel free to ping me as aggressively as you'd like. Though the MWE should be straightforward so hopefully I'll have that then, too.

**Comment by jkrumbiegel** [comment]
The axis title is " " by default because AbstractPlotting errors with empty strings for Text objects. That's the whole reason and until it's fixed, LAxis can't take empty strings

**Comment by timholy** [comment]
Same issue as https://github.com/jkrumbiegel/GridLayoutBase.jl/issues/5. Until that's fixed, how about having the `LAxis` constructor throw an informative error if the user supplies an empty string? Currently it's a pretty inscrutible bug, I spent quite a long time debugging this before realizing it was just due to an empty string.

**Comment by jkrumbiegel** [comment]
fixed in https://github.com/JuliaPlots/AbstractPlotting.jl/pull/530
