### ISSUE TITLE
"3D Contour with 2D contour slices" draw ordering issue

### ISSUE THREAD

**Issue by staticfloat** [JuliaPlots/Makie.jl#733]
From a clean install on a current `master` on MacOS, it appears there's a draw ordering issue.  I ran [this example](http://juliaplots.org/MakieReferenceImages/gallery/3d_contour_with_2d_contour_slices/index.html), and got the following:

<img width="640" alt="Screen Shot 2020-10-20 at 2 18 28 PM" src="https://user-images.githubusercontent.com/130920/96645402-5bacf280-12df-11eb-82f1-2f915aec36f6.png">

```
Julia Version 1.6.0-DEV.1278
Commit c760957469 (2020-10-19 16:42 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
```

**Comment by SimonDanisch** [comment]
Oh that's weird :-O
I get:
![image](https://user-images.githubusercontent.com/1010467/96646946-33e47b80-132d-11eb-8955-2dac10da72ce.png)
```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.1285
Commit 7efae4b2f3 (2020-10-20 07:17 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```
With newest version of GLMakie & AbstractPlotting.
Can you tell me the output from:
```
glxinfo | grep OpenGL
```

**Comment by ffreyer** [comment]
Works for me as well. Your result looks like `scene.plots[:] = scene.plots[[1, 3, 4, 5, 2]]; scene` didn't run

**Comment by staticfloat** [comment]
Oh dear, how embarassing.  It must have been a copy-paste error.  Sorry for the noise!
