### ISSUE TITLE
using mapslices to contruct vector of Points2f0

### ISSUE THREAD

**Issue by f-t-s** [JuliaPlots/Makie.jl#734]
Hi all,

I started to give Makie another try and ran into the following issue. 
When using mapslices to turn a 2xn array into an array of n Points2f0, it instead returns the original array.
`mapslices(Makie.Point2f0, rand(2,3), dims=1)` should be returning an array of Point2f0, but instead it is returning a 2 times 3 array.

**Comment by jkrumbiegel** [comment]
Try `Point2f0.(eachcol(rand(2, 3)))`

**Comment by SimonDanisch** [comment]
This is more of a general Julia issue any ways ;) 
If it helps: `Point2f0 <: AbstractArray`!
