### ISSUE TITLE
Restrict horizontal/vertical zoom for selection rectangle?

### ISSUE THREAD

**Issue by grero** [JuliaPlots/Makie.jl#738]
I often plot long time series, where I'm interested both in getting an overall view of trends, but also in zooming in to look at detail. This mostly involves zooming in and out on the time axis, leaving the y-axis alone. I noticed in the `add_zoom!` function for `LAxis` that this functionality exists when zooming using scrolling, but not when using the selection rectangle. I was able to achieve what I wanted by just copying the code checking whether `yzoomlock`/`xzoomlock` was set to true to the `on(selection_rectangle)` part of the `add_zoom` function. I was wondering, though if there is an interest in adding this functionality to the `selection_retangle` code? Perhaps something along the lines of, if `yzoomlock` is true, a horinztal line is drawn, and if `xzoomlock` is true, a vertical line is drawn, instead of the full rectangle? I believe this is how Matlab does it, for instance.

**Comment by grero** [comment]
See https://github.com/JuliaPlots/AbstractPlotting.jl/pull/533 for my quick attempt at addressing this.

**Comment by jkrumbiegel** [comment]
fixed by the latest release :)
