### ISSUE TITLE
EGL support for GLMakie on Wayland systems?

### ISSUE THREAD

**Issue by clad26** [JuliaPlots/Makie.jl#739]
GLFW already supports EGL.

`julia> scatter(1:4) Error showing value of type Scene: ERROR: GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: GLXBadFBConfig`
 nvidia proprietary drivers don't seem to work with glx on Wayland... although it works with EGL...

**Comment by SimonDanisch** [comment]
This is a bug with the driver or GLFW. Try searching in the issues here or in GLFW to find it.
