### ISSUE TITLE
New release breaks delete! functionnality

### ISSUE THREAD

**Issue by touste** [JuliaPlots/Makie.jl#740]
Hi, I have a code that creates a couple of buttons then deletes them:

```
layout[3, 1] = subl_buttons = GridLayout(tellwidth = false)
axButtonOK = subl_buttons[1, 1] = LButton(scene, label = "Validate")
axButtonCancel = subl_buttons[1, 2] = LButton(scene, label = "Cancel")
```
then later
```
delete!(axButtonOK)
delete!(axButtonCancel)
```
This code was working fine but a recent release broke it, the error is:
```
ERROR: MethodError: no method matching hasfield(::Type{AbstractPlotting.MakieLayout.LButton}, ::Symbol)
You may have intended to import Base.hasfield
Stacktrace:
 [1] delete!(lobject::AbstractPlotting.MakieLayout.LButton)
   @ AbstractPlotting.MakieLayout ~/.julia/packages/AbstractPlotting/JCbJs/src/makielayout/helpers.jl:322
```
I suspect the issue is due to the following commit: https://github.com/JuliaPlots/AbstractPlotting.jl/commit/6ef45c0b574b22cd2746cf45f142b135a485b5be#diff-3920d00b3452f7c605be39dd84181f873d23ce4e079a243eca56597ba42c97c3

and more specifically this line:
`@generated hasfield(x::T, ::Val{key}) where {T<:Layoutable, key} = :($(key in fieldnames(T)))`

Thanks!

**Comment by ericphanson** [comment]
related: https://github.com/JuliaPlots/AbstractPlotting.jl/pull/535 (not sure that PR helps here since it was a different line)

**Comment by touste** [comment]
Yes this solves the issue!
Could you please merge the PR?

Thanks!
