### ISSUE TITLE
Plotting Legends in meshes

### ISSUE THREAD

**Issue by Martijn98** [JuliaPlots/Makie.jl#747]
I am currently struggling to create a good looking mesh for a FEM. Currently, when I create the mesh using:
```
using AbstractPlotting
scene = AbstractPlotting.mesh(vertexArray, cellArray, color=colors)
FileIO.save("assets/results.png", scene)
```
I obtain the following mesh:
<img width="1440" alt="Screenshot 2020-10-27 at 14 03 48" src="https://user-images.githubusercontent.com/29573455/97578815-9d315200-19f1-11eb-80a3-d045a4d0da4b.png">

Unfortunately, I can't get AbstractPlotting to also show a legend, or to show a Colorbar. I can generate a Colorbar using:
```
cb = LColorbar(scene, scene[end], width=30)
```
But I can't seem to add the colorbar to the existing scene. I have attempted to use *MakieLayout* and use something like:
```
using AbstractPlotting.MakieLayout
scene, layout = layoutscene(resolution=(1200,900))
layout[1,1] = LAxis(scene)
AbstractPlotting.mesh!(vertexArray, cellArray, color=colors)
cb = LColorbar(scene, scene[end], width=30)
layout[1,2] = cb
```
Unfortunately, this doesn't seem to work, since it appears like **mesh!(...)** plots the mesh in a new scene, instead of in the already existing scene. 

I have been struggling with this issue for some time now, so I hope someone can help me out!

Using:
- AbstractPlotting 0.13.2
- GLMakie 0.1.14
- Julia 1.4.2

P.S. also, the link to the Slack group [in the docs](https://makie.juliaplots.org/stable/index.html) doesn't seem to work anymore. The link posted there leads to [https://slackinvite.julialang.org/](https://slackinvite.julialang.org/), which doesn't exist.

**Comment by ffreyer** [comment]
You need to do something like

```julia
s = layout[1,1] = LAxis(scene)
AbstractPlotting.mesh!(s, vertexArray, cellArray, color=colors)
```

otherwise `mesh!` will plot to `scene` rather than the layout element.

**Comment by jkrumbiegel** [comment]
If you haven't seen it, I recommend the tutorial to get started with MakieLayout :) It has a particular logic to it that might not be immediately obvious http://makie.juliaplots.org/stable/makielayout/tutorial.html

**Comment by Martijn98** [comment]
> You need to do something like
> 
> ```julia
> s = layout[1,1] = LAxis(scene)
> AbstractPlotting.mesh!(s, vertexArray, cellArray, color=colors)
> ```
> 
> otherwise `mesh!` will plot to `scene` rather than the layout element.

Thanks! This solved the problem.
