### ISSUE TITLE
2D Arrow head rotation looks odd

### ISSUE THREAD

**Issue by Keno** [JuliaPlots/Makie.jl#753]
![Screenshot from 2020-11-14 22-04-21](https://user-images.githubusercontent.com/1291671/99161926-6e8bca80-26c5-11eb-8c56-1098676480bc.png)

arrow heads need to be aligned in the tail->head orientation. These arrow heads just look like they're being drawn horizontally:

```
struct ImplicitSurface{n}
	f::Function
	bb::GeometryBasics.HyperRectangle{n}
end

function draw!(scene, s::ImplicitSurface{1})
	x = range(s.bb.origin[1], s.bb.widths[1]; length=100)
	lines!(scene, x, s.f.(x))
end

scene = Scene()
f(x) = 0.1x^3 + 0.9x^2- x + 5
s = ImplicitSurface(f, Rect(-10, 10))
draw!(scene, s)
bs = 2:0.5:7
xpts = Point2.(bs, 0)
arrows!(scene, xpts, [Vec2(0, 5) for _ in xpts], linecolor=:red, linewidth=3, arrowcolor=:red, arrowsize=4)
```

**Comment by ffreyer** [comment]
My arrows look fine. Maybe this is a related to #754? The arrow head is a scatter plot, which is also text based, I believe.

**Comment by Keno** [comment]
Yup, you're right. I've redone this plot and the arrows look fine now.
