### ISSUE TITLE
Arrow head size should not depend on data scale

### ISSUE THREAD

**Issue by Keno** [JuliaPlots/Makie.jl#755]
Right now it looks like the default arrow head scale depends on the scale of the data being plotted. I think it would be better to default to a constant "visual size". E.g. the following looks ridiculous (yes, I will resize it, but we should pick a sensible default):

![Screenshot from 2020-11-15 02-06-22](https://user-images.githubusercontent.com/1291671/99179005-372e1580-26e7-11eb-89ea-d75683da74a7.png)

```
x = y = -2:0.1:2
g(x, y) = exp(-(x^2+y^2))
scene = Scene()
heatmap!(scene, x, y, g.(x, y'), interpolate = true)
bp = Point(0.5, 0.4)
scatter!(scene, [bp], color=:red)
arrows!(scene, [bp], [Vec(0.2, 0)], linecolor=:red)
scene
```

**Comment by ffreyer** [comment]
The size of arrow heads in 2d is in pixel size now which I think is what you are asking for.
