### ISSUE TITLE
rug plot

### ISSUE THREAD

**Issue by jtrakk** [JuliaPlots/Makie.jl#760]
Helps show where the data is, marginally.

![image](https://user-images.githubusercontent.com/43392409/99860543-42020380-2b48-11eb-8a51-c9c8fd650b51.png)

**Comment by jkrumbiegel** [comment]
You could do this with MakieLayout's `hlines!` or `vlines!`:

```julia
scene, layout = layoutscene(resolution = (600, 400), fontsize = 10)
ax = layout[1, 1] = LAxis(scene)
# hidedecorations!(ax)
xs = randn(200)
ys = randn(200)

scatter!(ax, xs, ys, markersize = 5)
hlines!(ax, ys, xmin = 0, xmax = 0.05)
vlines!(ax, xs, ymin = 0, ymax = 0.05)

scene
```

<img width="676" alt="grafik" src="https://user-images.githubusercontent.com/22495855/101401529-c4255280-38d2-11eb-8e60-a3ef273ea767.png">
