### ISSUE TITLE
Two-argument form of errorbars()

### ISSUE THREAD

**Issue by chec99** [JuliaPlots/Makie.jl#763]
Currently the error bars want a center point, a lower offset, and an upper offset. Sometimes I have the location of the bottom edge and location of the top edge, but not the center point. I could calculate this myself, or Makie could provide a `errorbars(top,bottom)` form that doesn't need the center point. 

One possible downside is that this might risk confusing people about what arguments they're passing.

**Comment by jkrumbiegel** [comment]
Yeah I actually want to change that back to just lower and upper point. I was really thinking about these plots where the bars stick out from scatter markers, but it is weird. Good point

**Comment by jkrumbiegel** [comment]
What held this up was that I couldn't yet make a resizable version work, errorbars still error if their argument lengths are changed interactively

**Comment by ffreyer** [comment]
Maybe we should just have it auto-truncate like I had in https://github.com/JuliaPlots/AbstractPlotting.jl/pull/515? That did work with resizing at least.

**Comment by ffreyer** [comment]
With https://github.com/JuliaPlots/AbstractPlotting.jl/pull/564 (AbstractPlotting v0.14.0+) you now have the following options:
```julia
    errorbars(x, y, error_both; kwargs...)
    errorbars(x, y, error_low, error_high; kwargs...)
    errorbars(x, y, error_low_high; kwargs...)

    errorbars(xy, error_both; kwargs...)
    errorbars(xy, error_low, error_high; kwargs...)
    errorbars(xy, error_low_high; kwargs...)

    errorbars(xy_error_both; kwargs...)
    errorbars(xy_error_low_high; kwargs...)

    rangebars(val, low, high; kwargs...)
    rangebars(val, low_high; kwargs...)
    rangebars(val_low_high; kwargs...)
```
where `errorbars` use offsets from some point and `rangebars` directly specify the bottom and top (or left and right) position of a bar.

**Comment by jkrumbiegel** [comment]
I'll close this as it's implemented now
