### ISSUE TITLE
No legendelements for barplot

### ISSUE THREAD

**Issue by jeremiedb** [JuliaPlots/Makie.jl#765]
The basic legend example is failing when using a barplot.  

```julia
using Makie
using GLMakie
using AbstractPlotting
using AbstractPlotting.MakieLayout

scene, layout = layoutscene(resolution = (1400, 900))
ax = layout[1, 1] = LAxis(scene)
xs = 0:0.5:10
ys = sin.(xs)
lin = lines!(ax, xs, ys, color = :blue)
sca = barplot!(ax, ys, color = :red, markersize = 15px)
# sca = scatter!(ax, xs, ys, color = :red, markersize = 15px)
leg = LLegend(scene, [lin, sca], ["a line", "some dots"])

ERROR: LoadError:     There is no `legendelements` method defined for plot type Combined{AbstractPlotting.barplot,Tuple{Array{Point{2,Float32},1}}}. This means
    that you can't automatically generate a legend entry for this plot type.
    You can overload this method for your plot type that returns a `LegendElement`
    vector, or manually construct a legend entry from those elements.
```

**Comment by MackHarry** [comment]
I also hit on this issue. Is this a bug or by design?

**Comment by jkrumbiegel** [comment]
> Is this a bug or by design?

Bit of both? There are tons of plot objects, and I only defined legendelements for a couple basic ones. The question is, if we don't define legendelements manually for all kinds of plot objects, what could be a good mechanism to build them, maybe just recursively by checking the recipe component plots. In the `barplot` case that would be `poly` I guess, or `scatter` maybe?

If you want a solution for your current problem you can just define `MakieLayout.legendelements(bp::BarPlot)` to return a vector with one `PolyElement` for example.

**Comment by MackHarry** [comment]
thx for the answer. I went down a similar path, by defining a `PolyElement` by hand, but overloading `legendelements` is surely the more elegant way. The below was sufficient for me atm.  

```julia 
x = 1:10
y = rand(10)
scene, layout = layoutscene()
axs = layout[1,1] = [LAxis(scene)]
b = barplot!(axs[1], x, y; color = :red)
le = PolyElement(color=b.color, strokecolor=b.strokecolor)
leg =  layout[1, end+1] = LLegend(scene, [le], ["some label"])
```

![test](https://user-images.githubusercontent.com/39521902/100733520-99b53000-33ce-11eb-9844-c66c68a0de82.png)


I'm not 100% sure how I would go about running recursively over the recipe plot components as you said, my Julia knowledge is of a rather pragmatic nature (read: I know only what I need, and if that works, I'm happy...)

**Comment by jkrumbiegel** [comment]
Every complex plot is made out of simpler ones, stored in `plotobject.plots`. So if some plot doesn't have `legendelements` defined one could look at `.plots` and just layer the legendelements of the children on top of each other. That wouldn't necessarily look good in every case, but at least it could give some results without erroring. One can still define a better method then

**Comment by jkrumbiegel** [comment]
But I'm glad you got it working, I think in many cases people want some "weirder" legend elements than the defaults could give them, so I tried to make sure it's easy enough to assemble them yourself

**Comment by jkrumbiegel** [comment]
cf. https://github.com/JuliaPlots/AbstractPlotting.jl/pull/565

**Comment by MackHarry** [comment]
thx for your effort in answering my question.

**Comment by jeremiedb** [comment]
I second, thanks for you help!
