### ISSUE TITLE
Makie not using hardware driver with VirtualGL

### ISSUE THREAD

**Issue by tbenst** [JuliaPlots/Makie.jl#767]
I'm using VirtualGL for remote hardware acceleration. I've verified that the Nvidia drivers are in path:
```
> vglconnect <server>
$ vglrun -c jpeg julia
julia> out = read(`glxinfo`, String);
julia> for ln in split(out,"\n")
         if occursin("OpenGL", ln)
           println(ln)
         end
       end
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: TITAN RTX/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 450.80.02
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 450.80.02
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 450.80.02
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

And yet Makie uses Mesa instead:
```
julia> using GLMakie, AbstractPlotting

julia> scene = Scene()
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
```

I'm guessing some environmental variable isn't set that Makie is expecting, although will note that the other OpenGL applications I've tried are running on GPU as expected. Any ideas? many thanks!!

**Comment by SimonDanisch** [comment]
Hm, I can't say much about this, but it looks a bit like the load paths are not in order... Maybe VirtualGL hasn't registered it's OpenGL.so with mesa. The output of `glxinfo` looks correct, so it seems mostly in order, though ;) 
Did you set the display variable?
This may be related:
https://github.com/intel-isl/Open3D/issues/17#issuecomment-339391580
For debugging, I'd try this minimal example, which is much faster to run:
```
ENV["DISPLAY"] = ":0"; using GLFW; GLFW.Window()
```

**Comment by tbenst** [comment]
Thanks for the thoughts, @SimonDanisch! On reboot, everything works perfectly and it’s running on my GPU 🤷🏼‍♂️. The only thing I changed that I can think of was setting [‘HardDPMS‘ to false](https://wiki.archlinux.org/index.php/NVIDIA/Troubleshooting#Driver_415:_HardDPMS), dunno if that’s what did it or not! Also, at the moment I’m using a client from another machine using the `-c proxy` setting but I’m pretty sure that doesn’t matter.

For posterity’s sake, even with the Mesa error the window was rendering properly just very slowly. vglconnect sets the DISPLAY variable to eg “localhost:10” since were displaying frames rendered from remote using local X11, so this shouldn’t be changed.

Appreciate the support and great work on this package!
