### ISSUE TITLE
Setting aspect ratio for a surface plot

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaPlots/Makie.jl#768]
The code below shows that some surfaces would be best served by having the ability to scale the aspect ratios. I couldn't find out how to do this for a surface plot by reading the docs or scanning issues.
```julia
using Makie

x = -1:0.005:1
y = -1:0.005:1

f = (x, y) -> exp(sin(50x)) + sin(60exp(y)) + sin(70sin(x)) + sin(sin(80y)) - sin(10*(x+y)) + (x^2 + y^2)/4
scene = Scene(resolution = (2000, 2000))
surface!(scene, x, y, f, colormap = :seismic)
save("plot1.png", scene)
```
![plot1](https://user-images.githubusercontent.com/8176037/100693238-0ccc9100-3352-11eb-93f1-1aa2b4d8d3d2.png)
```
f = (x, y) -> (exp(sin(50x)) + sin(60exp(y)) + sin(70sin(x)) + sin(sin(80y)) - sin(10*(x+y)) + (x^2 + y^2)/4)/15
scene = Scene(resolution = (2000, 2000))
surface!(scene, x, y, f, colormap = :seismic)
save("plot2.png", scene)
```
![plot2](https://user-images.githubusercontent.com/8176037/100693254-16ee8f80-3352-11eb-9f00-6d2d98691881.png)

**Comment by ffreyer** [comment]
You can `scale!(scene, x_scale, y_scale, z_scale)` any scene.

**Comment by MikaelSlevinsky** [comment]
Thanks!
