### ISSUE TITLE
layoutscene not available

### ISSUE THREAD

**Issue by petar** [JuliaPlots/Makie.jl#779]
The tutorial http://makie.juliaplots.org/stable/makielayout/tutorial.html#Scene-and-Layout utilizes a function called "layoutscene" which does not seem to be available in the latest Makie.jl or AbstractPlotting.jl

Pointers appreciated.

**Comment by jkrumbiegel** [comment]
We exported MakieLayout by default in 0.14.1, which we decided shouldn't be a breaking release just because people don't need `using AbstractPlotting.MakieLayout` anymore. So could be that you're on almost the newest version which then doesn't match the tutorial
