### ISSUE TITLE
Supressing axes (decorations) on heatmaps

### ISSUE THREAD

**Issue by DanielRivasMD** [JuliaPlots/Makie.jl#783]
Is there any intuitive/effective way to achieve axes suppression, completely, when plotting heatmaps? I have used AbstractPlotting. Much appreciated

**Comment by ffreyer** [comment]
`Scene(show_axis = false)` should work. (If you call `heatmap()` you can pass it there. If you're using MakieLayout you need to pass it as `scene_kw=(; show_axis = false)` to the `LAxis` or `LScene` iirc)

**Comment by jkrumbiegel** [comment]
For LAxis it would be

```
hidedecorations!(ax)
hidespines!(ax)
```

**Comment by DanielRivasMD** [comment]
Thanks! `show_axis = false` worked smoothly. I tried with LAxis, but that did not work.
