### ISSUE TITLE
MakieLayout: sequence of specifying layouts matters?

### ISSUE THREAD

**Issue by j-fu** [JuliaPlots/Makie.jl#786]
Hi, trying to use makielayout and want to use it in a nested way.

IMHO the following should work, and it would allow to define subscenes  of various kinds and allow to arrange them in an arbitrary fashion:
````
using MakieLayout, GeometryBasics

function should_work()
    scene, layout = layoutscene(resolution=(1000,500))
    layoutL=GridLayout()
    layoutR=GridLayout()
    volmesh=GeometryBasics.Mesh([Point3f0(0,0,0),Point3f0(1,1,1)],Vector{GLTriangleFace}(undef,0))
    function make_scene!(scene,layout,color)
        myscene= layout[1,1] = LScene(scene, camera = cam3d!, raw = false,scenekw = (clear = true,))
        myslider=layout[2,1] = LSlider(scene, range = 4:1:10000, startvalue = 4,width = Auto())
        mesh!(myscene,volmesh)
        node=Node(rand(myslider.value[],3))
        scatter!(myscene,lift(a->a,node),color=color);
        onany(myslider.value) do v
            node[]=rand(v, 3)
        end
    end
    make_scene!(scene,layoutL,:blue)
    make_scene!(scene,layoutR,:red)
    layout[1, 1] = layoutL
    layout[1, 2] = layoutR
    scene
end
````
This gives:
![should](https://user-images.githubusercontent.com/9221937/102000364-fbd33680-3ce6-11eb-80cd-ed3699f42e00.png)

What does work is:
````
function does_work()
    scene, layout = layoutscene(resolution=(1000,500))
    layoutL=GridLayout()
    layoutR=GridLayout()
    volmesh=GeometryBasics.Mesh([Point3f0(0,0,0),Point3f0(1,1,1)],Vector{GLTriangleFace}(undef,0))

    mysceneL= layoutL[1,1] = LScene(scene, camera = cam3d!, raw = false,scenekw = (clear = true,))
    mysceneR= layoutR[1,1] = LScene(scene, camera = cam3d!, raw = false,scenekw = (clear = true,))
    mysliderL=layoutL[2,1] = LSlider(scene, range = 4:1:10000, startvalue = 100,width = Auto())
    mysliderR=layoutR[2,1] = LSlider(scene, range = 4:1:10000, startvalue = 100,width = Auto())

    mesh!(mysceneL,volmesh)
    nodeL=Node(rand(mysliderL.value[],3))
    scatter!(mysceneL,lift(a->a,nodeL),color=:blue);
    onany(mysliderL.value) do v
        nodeL[]=rand(v, 3)
    end
    
    mesh!(mysceneR,volmesh)
    nodeR=Node(rand(mysliderR.value[],3))
    scatter!(mysceneR,lift(a->a,nodeR),color=:red);
    onany(mysliderR.value) do v
        nodeR[]=rand(v, 3)
    end
    
    layout[1, 1] = layoutL
    layout[1, 2] = layoutR
    scene
end
````
It gives:

![does](https://user-images.githubusercontent.com/9221937/102000369-05f53500-3ce7-11eb-9f73-212aa137a833.png)

So in the moment it appears that I am forced to fill the layout grid row by row.

Bug or feature ?

**Comment by jkrumbiegel** [comment]
This

```julia
LScene(scene, camera = cam3d!, raw = false,scenekw = (clear = true,))
```

should be

```julia
LScene(scene,scenekw = (camera = cam3d!, raw = false, clear = true))
```

Does that fix your problem?

**Comment by j-fu** [comment]
Thanks - it looks right now, but at the expense of not being able to rotate the left plot. The sliders work though.

In your layout example from zulip  I can have two 3D scatter plots working.

In fact I would like to get rid of the need to use sliders as they eat up screen real estate.
I'd rather use arrow keys or the mouse (with "mode switching" through some hotkeys) to control things - main purpose is here interactively controlling isolevels or isosurfaces in 3D.  For this purpose there should be a way to distinguish the LScene where they happen.

**Comment by j-fu** [comment]
ok figured  this out so far - just check if mouse position is in pixel area....
working now  to catch up with the big update....
