### ISSUE TITLE
Rectangle zoom on LAxis breaks when spam clicking

### ISSUE THREAD

**Issue by ffreyer** [JuliaPlots/Makie.jl#788]
When spamming rectangle zooms in
```julia
scene, layout = layoutscene()
s = layout[1, 1] = LAxis(scene)
scatter!(s, rand(Point2f0, 10))
display(scene)
```
the RectangleZoom overlay eventually ends up breaking and remaining:
![Screenshot from 2020-12-13 20-03-35](https://user-images.githubusercontent.com/10947937/102021204-6d11f880-3d7e-11eb-834a-6968f37784a7.png)
(This includes the outline, it's just small.)

I have had this happen in scenes with an LMenu over an LAxis as well, without spam clicking. (The menu selection causes some lag in those cases, maybe that changes the timing needed for this to happen)

**Comment by jkrumbiegel** [comment]
I had this happen as well when zooming for the first time, because of the compilation delay it seems. I'll check it out, it seems like the created axis is just not removed correctly.

**Comment by jkrumbiegel** [comment]
I think this should fix it https://github.com/JuliaPlots/AbstractPlotting.jl/pull/575

Even if the order of operations is still somehow messed up due to compilation delays, at least dragging again should get rid of the spurious mesh and wireframe, where they would be inaccessible before

**Comment by ffreyer** [comment]
> Even if the order of operations is still somehow messed up due to compilation delays, at least dragging again should get rid of the spurious mesh and wireframe, where they would be inaccessible before

After some spam clicking, I think I can confirm this. :+1:
