### ISSUE TITLE
Tall images not scaled correctly

### ISSUE THREAD

**Issue by Benoit9** [JuliaPlots/Makie.jl#80]
This only happens for images that are taller than wide. Instead of exactly filling the window, the image is scaled up and cropped.

`
using GLVisualize, Makie

img=loadasset("back_active.png")
Scene(resolution=reverse(size(img)))
image(img)
`

See the difference with this code where the image is displayed correctly:

`
using GLVisualize, Makie

img=loadasset("back_active.png")
Scene(resolution=(128,128) )
image(img)
`

**Comment by SimonDanisch** [comment]
I'm not sure if it's not a real issue, or if I can't reproduce it. Can you sent a screenshot?

I don't scale anything by default, so it just gets displayed weirdly, but looks fine after a call to `center!(scene)`.
What does look weird is, that there seems to be a minimal window size, which blackens out half of the window. Not 100% if that's my fault, or if it's a os / glfw restriction.

**Comment by Benoit9** [comment]
`center!(scene)` does the trick.

It was necessary, since it works without for other aspect ratios.

Thanks!
