### ISSUE TITLE
update_cam! doesn't respect the value of Camera3D.far

### ISSUE THREAD

**Issue by HastingsGreer** [JuliaPlots/Makie.jl#801]
As documented in a comment, https://github.com/JuliaPlots/AbstractPlotting.jl/blob/74097044b55277a9c846c2ebc75741912de8c325/src/camera/camera3d.jl#L284
 , currently update_cam! computes an approximately good value for the far clipping plane instead of respecting the value set in the Camera3D object. What would be the correct behavior here? Since currently the value of Camera3D.far is never used, perhaps it should be initialized to a value that indicates "just compute some reasonable default," which can trigger the current code path in update_cam!, but if it is edited, then the value of Camera3D.far can be passed to frustum() ?

**Comment by ffreyer** [comment]
Should be fixed in v0.14.3+
