### ISSUE TITLE
Layoutable layoutscene?

### ISSUE THREAD

**Issue by j-fu** [JuliaPlots/Makie.jl#806]
After hbox and vbox gone, ist it possible to make the  scene coming out of layoutscene()  a Layoutable ?

This would allow to build up  independent subscenes which can be freely combined in some global layout which the are not aware of a priori.

**Comment by jkrumbiegel** [comment]
Good question, in theory it's quite simple because LScene is only the minimal stuff for layouts plus a scene, so we probably need only a constructor for LScene which takes an existing scene. What I don't know, maybe @SimonDanisch can answer that, is how to add an existing scene into another existing scene as a child, I have never quite understood what the underlying state is

**Comment by j-fu** [comment]
So this is less about LScene - after what I understand, this tends to be deprecated at some point. 
With hbox it was possible to  combine LScene whith text  etc, and have that layouted in a larger layout.

What I mean is more like this:
````
parent, main_layout=layoutscene()

subscene, sub_layout=layoutscene(parent=parent)

main_layout[1,1]=...
main_layout[1,2] =  subscene

sub_layout[1,1]=...
sub_layout[1,2]=...
etc.
````

Combining the subscene would happen some function which is not aware of the existence of the main layout.

But is is as well possible that I still  miss something.

**Comment by gurvesh** [comment]
@j-fu I think hbox can still be implemented as follows (I have replaced it in some code as below):

Previous code (all items are linked to the scene already): 
```julia
controllayout[5, 1] = hbox!(
        item1, item2, item3, item4, width = Auto(false)
    )
```

New code:

```julia
sublayout = GridLayout(width = Auto(false))
controllayout[5, 1] = sublayout
sublayout[:h] = [item1, item2, item3, item4]
```

For vbox, I was able to do the same, but replace the [:h] with [:v].

**Comment by jkrumbiegel** [comment]
The GridLayout versions are called hgrid and vgrid now, because they don't really do anything with "boxes" as the original makie functions of the same name. It could be that I forgot to explicitly document those except in the changelog..

**Comment by j-fu** [comment]
Ah thank you. Unfortunately I have no time to try this out immediately. In a week or so...

**Comment by gurvesh** [comment]
@jkrumbiegel - thanks. I tried using hgrid! just now as a replacement directly - and it gives the following error. However, my solution above still works. 

```julia
ERROR: LoadError: Content array size is length 5 for 1 * 1 cells
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] setindex!(::GridLayout, ::Array{AbstractPlotting.MakieLayout.Layoutable,1}, ::Int64, ::Int64) at C:\Users\Gurvesh Sanghera\.julia\packages\GridLayoutBase\RQA67\src\gridlayout.jl:1176
 [3] #hbox!#128 at C:\Users\Gurvesh Sanghera\.julia\packages\GridLayoutBase\RQA67\src\gridapi.jl:34 [inlined]
 [4] add_controls!(::GridLayout, ::Scene, ::Int64, ::String, ::Int64) at d:\Dropbox\Code\julia\LinAlg\Sparse regularization with the L-1 norm\orbitdiagram.jl:304
 [5] interactive_orbitdiagram(::DiscreteDynamicalSystem{false,StaticArrays.SArray{Tuple{2},Float64,1,2},2,typeof(DynamicalSystemsBase.Systems.hoop),Array{Float64,1},typeof(DynamicalSystemsBase.Systems.hoop_jac),StaticArrays.SArray{Tuple{2,2},Float64,2,4},false}, ::Int64, ::Float64, ::Float64, ::Int64; u0::StaticArrays.SArray{Tuple{2},Float64,1,2}, parname::String, title::String) at d:\Dropbox\Code\julia\LinAlg\Sparse regularization with the L-1 norm\orbitdiagram.jl:57
```

**Comment by jkrumbiegel** [comment]
ah I think it's a vararg function, so probably `hgrid!(item1, item2, item3, item4, width=Auto(false))` should work.

**Comment by gurvesh** [comment]
@jkrumbiegel Yes it works. I should have tried that.. duh.. 

Thanks!

**Comment by j-fu** [comment]
Ok, solved: I used vbox to add title and footer to LScene, with gridlayout I can use the protrusion functionality:
```
scene=LScene(parent)
...
GL=GridLayout(parent=parent)
GL[1,1,Top()]=Label(parent, header)
GL[1,1 ]=scene
GL[1,1,Bottom()]=Label(parent,footer)
```

With Axis3 one can put the header into the title:

```
scene=Axis3(parent,title=header)
...
GL=GridLayout(parent=parent)
GL[1,1 ]=scene
GL[1,1,Bottom()]=Label(parent,footer)
```

So this is much better than vbox, thank you @jkrumbiegel  !
