### ISSUE TITLE
2D Coordinate indicator

### ISSUE THREAD

**Issue by sents** [JuliaPlots/Makie.jl#810]
It would be nice to be able to add a indicator showing what 2D coordinate the cursor is pointing to in a scene/layout.
Maybe this feature exists already but I didn't find any issues related to it.

For plots with LAxis this is not a lot of work:
```julia
using Makie
using AbstractPlotting.MakieLayout
function indicator(ax::LAxis,ob)
    register_interaction!(ax, :indicator) do event::MouseEvent, axis
        if event.type === MouseEventTypes.over
            ob[] = event.data
        end
    end
end
function indicator(grid::GridLayout,ob)
    foreach(LAxis,grid;recursive=true) do ax
        indicator(ax,ob)
    end
end
function indicator(grid::GridLayout)
    ob = Observable(Point2f0(0.,0.))
    indicator(grid,ob)
    ob
end
function indicator(scene::Scene,grid::GridLayout,args...;kwargs...)
        LText(
            scene,
            lift(ind->"x: $(ind[1])  y: $(ind[2])",indicator(grid)),
            args...;kwargs...
        )
end
```

For plots directly on a scene I've found this to work, but it is not as pretty:
```julia
function indicator!(sc::Scene,position=(0,0),size=1)
    lims = sc.data_limits[]
    midpoint = Point2f0((lims.origin + lims.widths/2)[1:2])
    position_string = lift(sc.events.mouseposition) do mp
        x,y = Point2f0(mp) |> x->to_world(sc,x) |> Tuple
        "x: $(x)  y: $(y)"
    end
    display_position = lift(sc.events.mouseposition,sc.events.scroll;init=midpoint) do mp,scroll
            position |> Point2f0 |> x->to_world(sc,x)
    end
    dsize = lift(sc.camera.projection) do pro
        size/√(pro[1,1]^2+pro[2,1]^2)*5e-2
    end
    text!(sc,position_string,position=display_position,textsize=dsize)
end
```

I think this is a convenience feature that is really nice to have already integrated. As far as I know a lot of plotting frameworks have this.

**Comment by sents** [comment]
If you would like to I can open a pull request for this.

**Comment by sents** [comment]
Here is the code for the indicator on a scene:
```julia
plot_range = range(0,10;length=1000)
sc = Scene()
p1 = lines!(sc,plot_range,plot_range .^ 2)
indicator!(sc)
display(sc)
```
![Animation of adding an coordinate indicator to a scene](https://krein.moe/indicator_scene.gif)
One problem with this is that I have not yet found a way to set the size of the text in pixels. The size is still related to the size of the coordinate grid.

Here is how to use the indicator with an LAxis plot:
```julia
plot_range_1 = range(0,1;length=1000)
plot_range_2 = range(0,100;length=1000)
sc, layout = layoutscene()
ax1 = layout[1,1] = LAxis(sc)
ax2 = layout[1,2] = LAxis(sc)
lay2 = layout[1,3] = GridLayout(sc)
ax3 = lay2[1,1] = LAxis(sc)
ax4 = lay2[2,1] = LAxis(sc)
l1 = lines!(ax1,plot_range_1,plot_range_1 .^ 2)
l2 = lines!(ax2,plot_range_1,plot_range_1 .^ 3)
l3 = lines!(ax3,plot_range_1,plot_range_1 .^ 4)
l4 = lines!(ax4,plot_range_2, sqrt.(plot_range_2) .* sin.(plot_range_2))
txt= layout[2,:] = indicator!(sc,layout)
```
![Animation of adding a coordinate indicator to a layout plot](https://krein.moe/indicator_layout.gif)

**Comment by jkrumbiegel** [comment]
I think we could add something like this as an interaction mode that you can toggle on and off. It seems sensible to me to plot the numbers into a corner of the axis on a half-translucent white background maybe. Then the numbers can be deleted again when the mouse interaction (mouseover) stops, and in general the feature can be toggled on and off this way.

You can check out how the selection rectangle works, the logic would be similar:

https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/makielayout/interactions.jl#L140-L181

I think currently the text would have to be plotted into the parent scene because the axis itself doesn't support text that's not in data coordinates right now.

**Comment by doddgray** [comment]
How would the code above need to be modified for use with the Figure/Axis interface rather than GridLayout/LAxis? I can't tell for sure from the docs but the latter interface seems deprecated (they are not used in the linked selection rectangle example). Sorry if this has already been addressed elsewhere.

**Comment by sents** [comment]
The above example with the new interface would look like this:
```julia
function indicator(ax::Axis,ob)
    register_interaction!(ax, :indicator) do event::MouseEvent, axis
    if event.type === MouseEventTypes.over
        ob[] = event.data
    end
    end
end
function indicator(grid::GridLayout,ob)
    foreach(Axis,grid;recursive=true) do ax
    indicator(ax,ob)
    end
end
function indicator(grid::GridLayout)
    ob = Observable(Point2f0(0.,0.))
    indicator(grid,ob)
    ob
end
function indicator(fig,args...; tellwidth=false, kwargs...)
    Label(
        fig,
        lift(ind->"x: $(ind[1])  y: $(ind[2])",indicator(fig.layout)),
        args...; tellwidth=tellwidth, kwargs...
    )
end

plot_range_1 = range(0,1;length=1000)
plot_range_2 = range(0,100;length=1000)
fig = Figure()
ax1 = fig[1,1] = Axis(fig)
ax2 = fig[1,2] = Axis(fig)
lay2 = fig[1,3] = GridLayout()
ax3 = lay2[1,1] = Axis(fig)
ax4 = lay2[2,1] = Axis(fig)
l1 = lines!(ax1,plot_range_1,plot_range_1 .^ 2)
l2 = lines!(ax2,plot_range_1,plot_range_1 .^ 3)
l3 = lines!(ax3,plot_range_1,plot_range_1 .^ 4)
l4 = lines!(ax4,plot_range_2, sqrt.(plot_range_2) .* sin.(plot_range_2))
txt= fig[2,:] = indicator(fig)
display(fig)
```

**Comment by walra356** [comment]
I have difficulties finding the observable for the px_area? of the heatmap under scrollzoom. Do I have to extract it from the 4x4 camera matrix?

**Comment by ffreyer** [comment]
`px_area` is a scene observable, plots don't have it. If you want to find the (full) area of a heatmap or image plot you can use `boundingbox(plot)`. If you want one tile you'll have to calculate that from `mouseposition_px(scene)` and the arguments of the plot (`plot[1]` etc). That calculation will change with the next release though. JuliaPlots/AbstractPlotting.jl#677 is getting merged before the next release as well, so there will be a tool that does that soon.

**Comment by walra356** [comment]
###
```
function indicator(ax::Axis,ob)
    register_interaction!(ax, :indicator) do event::MouseEvent, axis
    if event.type === MouseEventTypes.over
        ob[] = event.data
    end
    end
end
function indicator(grid::GridLayout,ob)
    foreach(Axis,grid;recursive=true) do ax
    indicator(ax,ob)
    end
end
function indicator(grid::GridLayout)
    ob = Observable(Point(512.,512.) .+ 100.)
    indicator(grid,ob)
    ob
end
function indicator(fig,args...; tellwidth=true, kwargs...)
    Label(
        fig,
        lift(ind->"$(ind)",indicator(fig.layout)),
        args...; tellwidth=tellwidth, kwargs...
    )
```
"""

>  @end{3, Float32}(Float32[0.0, 0.0, 0.0], Float32[4.0, 5.0, 0.0])

**Comment by walra356** [comment]
Thank for your comments!
Consider:
"""
```
function indicator(ax::Axis,ob)
    register_interaction!(ax, :indicator) do event::MouseEvent, axis
    if event.type === MouseEventTypes.over
        ob[] = event.data
    end
    end
end
function indicator(grid::GridLayout,ob)
    foreach(Axis,grid;recursive=true) do ax
    indicator(ax,ob)
    end
end
function indicator(grid::GridLayout)
    ob = Observable(Point(512.,512.) .+ 100.)
    indicator(grid,ob)
    ob
end
function indicator(fig,args...; tellwidth=true, kwargs...)
    Label(
        fig,
        lift(ind->"$(ind)",indicator(fig.layout)),
        args...; tellwidth=tellwidth, kwargs...
    )
end
    
data = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
data = reshape(data,(5,4))
f = Figure()
ax = Axis(f[1,1],aspect=4/5)
txt= f[2,1] = indicator(f)
hm = heatmap!(ax, rotr90(data))
display(f)
```
```
plot = f.scene.children[1].plots[1]
boundingbox(plot) 
```
"""
ans = GeometryBasics.HyperRectangle{3, Float32}(Float32[0.0, 0.0, 0.0], Float32[4.0, 5.0, 0.0])

ans is invariant under scrollzoom. Now I want to select part of the heatmap by zooming. How do I get the HyperRectangle of the heatmap clipped to e.g. to Float32[0.0, 0.0, 0.0], Float32[2.0, 2.5, 0.0]. The clipping can be read from the x and y scales but how do I get access the clipping values? It would be sufficient to know the same Rectangle in the coordinates of the scene and do some scaling.

**Comment by ffreyer** [comment]
Maybe it's helpful to check the upcoming code from `DataInspector`. It's gotten a bit messy because it combines `image` and `heatmap`, allows for irregular grids and does different things depending on interpolation, but maybe it's still helpful.
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/7569c3d55c29affb994020124cbde9b20436bb03/src/interaction/inspector.jl#L709
You could also try it out on GLMakie#master and AbstractPlotting#master if you're feeling courageous :)

What it boils down to is:
* on mouse scroll or movement, check if the plot is hovered (`MouseEventTypes.over` probably does that, not 100% sure)
* get the x, y and z/img values from the plot (i.e. `plot[1]` etc)
* figure out the index from the current `mouseposition(parent_scene(plot))` which is in data space and the x and y values
* figure out the boundingbox from that + x and y values

**Comment by walra356** [comment]
Thank you for your patience! I made progress. I now use leftdragstart/leftdragstop to zoom the heatmap and can print the coordinates using println(ob[]) - see the example below. This gives me the numbers but it is a bit clumsey. How to assign these values to a variable that I can use for futher processing? 

"""
```
function indicator(ax::Axis,ob)
    register_interaction!(ax, :indicator) do event::MouseEvent, axis
        if event.type === MouseEventTypes.leftclick
            ob[] = event.data
        end
        if event.type === MouseEventTypes.leftdragstart
            ob[] = event.data
            println(ob.val)
        end
        if event.type === MouseEventTypes.leftdragstop
            ob[] = event.data
            println(ob.val)
        end         
    end
end
function indicator(grid::GridLayout,ob)
    foreach(Axis,grid;recursive=true) do ax
        indicator(ax,ob)
    end
end
function indicator(grid::GridLayout)
    ob = Observable(Point(0.,0.))
    indicator(grid,ob)
    ob
end
function indicator(fig,args...; tellwidth=true, kwargs...)
    Label(
        fig,
        lift(ind->"(x,y) = ($(round(Int,ind[1])),$(round(Int,ind[2])))",indicator(fig.layout)),
        args...; tellwidth=tellwidth, kwargs...
    )
end          
# ................................................................................            
function _set_range(n::Real; center=false)
    return center ? (isodd(n) ? (-n/2:1:n/2) : (0.5-n/2:1:0.5+n/2)) : (0.5:1:0.5+n)  # return range      
end
function _set_ticks(n::Real, step=1; center=false)
    max = (n÷2÷step)step
    return center ? (-max:step:max) : (0:step:n+1)  
end            
n1=7
n2=6    
data = [i for i=1:n1*n2]
data1 = reshape(data,(n1,n2))
data2 = reshape(data,(n2,n1))
f = Figure()
ax1 = Axis(f[1,1],aspect=n1/n2)
ax2 = Axis(f[1,2],aspect=n2/n1)
ax1.xticks = _set_ticks(n2,1)
ax1.yticks = _set_ticks(n1,1)
ax2.xticks = _set_ticks(n2,1;center=true)
ax2.yticks = _set_ticks(n1,1;center=true)
txt= f[2,:] = indicator(f)
hm1 = heatmap!(ax1,_set_range(n2),_set_range(n1), rotr90(data1))
hm2 = heatmap!(ax2,_set_range(n1;center=true),_set_range(n2,center=true), rotr90(data2))
Label(f[0,:], text="select color field", color = (:Black,0.5))
display(f)
```
"""

**Comment by walra356** [comment]
Thank you for your patience! I made progress. I now use leftdragstart/leftdragstop to zoom the heatmap and can print the coordinates using println(ob[]) - see the example below. This prints the view  boundary points of the heatmap which I was asking. Bit it is a bit clumsey. How to assign these values to a variable that I can use for futher processing?

```
GLMakie.activate!()
AbstractPlotting.inline!(false)
function indicator(ax::Axis,ob)
    register_interaction!(ax, :indicator) do event::MouseEvent, axis
        if event.type === MouseEventTypes.leftclick
            ob[] = event.data
        end
        if event.type === MouseEventTypes.leftdragstart
            ob[] = event.data
            println(ob.val)
        end
        if event.type === MouseEventTypes.leftdragstop
            ob[] = event.data
            println(ob.val)
        end         
    end
end
function indicator(grid::GridLayout,ob)
    foreach(Axis,grid;recursive=true) do ax
        indicator(ax,ob)
    end
end
function indicator(grid::GridLayout)
    ob = Observable(Point(0.,0.))
    indicator(grid,ob)
    ob
end
function indicator(fig,args...; tellwidth=true, kwargs...)
    Label(
        fig,
        lift(ind->"(x,y) = ($(round(Int,ind[1])),$(round(Int,ind[2])))",indicator(fig.layout)),
        args...; tellwidth=tellwidth, kwargs...
    )
end          
# ................................................................................  
function _set_range(n::Real; center=false)
    return center ? (isodd(n) ? (-n/2:1:n/2) : (0.5-n/2:1:0.5+n/2)) : (0.5:1:0.5+n)  # return range      
end
function _set_ticks(n::Real, step=1; center=false)
    max = (n÷2÷step)step
    return center ? (-max:step:max) : (0:step:n+1)  
end            
n1=7
n2=6    
data = [i for i=1:n1*n2]
data1 = reshape(data,(n1,n2))
data2 = reshape(data,(n2,n1))
f = Figure()
ax1 = Axis(f[1,1],aspect=n1/n2)
ax2 = Axis(f[1,2],aspect=n2/n1)
ax1.xticks = _set_ticks(n2,1)
ax1.yticks = _set_ticks(n1,1)
ax2.xticks = _set_ticks(n2,1;center=true)
ax2.yticks = _set_ticks(n1,1;center=true)
txt= f[2,:] = indicator(f)
hm1 = heatmap!(ax1,_set_range(n2),_set_range(n1), rotr90(data1))
hm2 = heatmap!(ax2,_set_range(n1;center=true),_set_range(n2;center=true), rotr90(data2))
Label(f[0,:], text="select color field", color = (:Black,0.5))
display(f)
```

**Comment by walra356** [comment]
The world is small. I worked on the quantum gases since 1973 ...

**Comment by jtrakk** [comment]
I like the DataInspector transient highlight on hover. It would be nice to have a permanent highlight on click too, so I can click on some reference points and compare their values to my mouse location as I move around.

**Comment by ffreyer** [comment]
I'll close this since the main issue has been taken care of by `DataInspector` and there is another issue specifically about keeping (semi-)permanent  indicators. See https://github.com/JuliaPlots/Makie.jl/issues/962
