### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by kangpyo** [JuliaPlots/Makie.jl#815]
I install GLMakie package and tried to run the "test GLMakie". 
I get error messages for all the test. 
is there any clue what I did wrong?
I'm using Linux mint and already installed GLFW
 
`Stacktrace:
 [1] macro expansion at /home/kangpyo/.julia/packages/MakieGallery/V0mvg/src/io.jl:309 [inlined]
 [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115 [inlined]
 [3] (::MakieGallery.var"#135#138"{Tuple{Int64,Int64},Bool,String,Array{Any,1}})(::MakieGallery.CellEntry, ::Nothing) at /home/kangpyo/.julia/packages/MakieGallery/V0mvg/src/io.jl:293
Test Summary:                              | Fail  Total
Full Gallery recording                     |  184    184
  Tutorial simple scatter                  |    1      1
  Tutorial markersize                      |    1      1
  Tutorial simple line                     |    1      1
  Tutorial adding to a scene               |    1      1
  Tutorial removing from a scene           |    1      1
  Tutorial adjusting scene limits          |    1      1
  Tutorial basic theming                   |    1      1
  Tutorial heatmap                         |    1      1
  Tutorial linesegments                    |    1      1
  Tutorial barplot                         |    1      1
  Tutorial title                           |    1      1
  Tutorial title function                  |    1      1
  Tutorial plot transformation             |    1      1
  algorithm                                |    1      1
  align                                    |    1      1
  color                                    |    1      1
  colormap                                 |    1      1
  colorrange                               |    1      1
  fillrange                                |    1      1
  font                                     |    1      1
  glowcolor, glowwidth                     |    1      1
  image                                    |    1      1
  interpolate                              |    1      1
  isorange, isovalue                       |    1      1
  levels                                   |    1      1
  linestyle                                |    1      1
  linewidth                                |    1      1
  markersize                               |    1      1
  position                                 |    1      1
  rotation                                 |    1      1
  shading                                  |    1      1
  strokecolor, strokewidth                 |    1      1
  strokecolor, strokewidth                 |    1      1
  textsize                                 |    1      1
  visible                                  |    1      1
  simple line plot                         |    1      1
  multiple functions                       |    1      1
  animations                               |    1      1
  parametric plots                         |    1      1
  colors                                   |    1      1
  attributes                               |    1      1
  build plot in pieces                     |    1      1
  barplot                                  |    1      1
  subplots                                 |    1      1
  text                                     |    1      1
  contours                                 |    1      1
  3D                                       |    1      1
  heatmap                                  |    1      1
  label rotation, title location           |    1      1
  lines with varying colors                |    1      1
  Test heatmap + image overlap             |    1      1
  barplot                                  |    1      1
  poly and colormap                        |    1      1
  quiver                                   |    1      1
  Arrows on hemisphere                     |    1      1
  image                                    |    1      1
  scatter colormap                         |    1      1
  FEM polygon 2D                           |    1      1
  FEM mesh 2D                              |    1      1
  colored triangle                         |    1      1
  heatmap interpolation                    |    1      1
  colored triangle                         |    1      1
  Subscenes                                |    1      1
  scale_plot                               |    1      1
  Polygons                                 |    1      1
  Contour Function                         |    1      1
  Hbox                                     |    1      1
  Customize Axes                           |    1      1
  contour                                  |    1      1
  Heatmap                                  |    1      1
  Animated Scatter                         |    1      1
  Text Annotation                          |    1      1
  Text rotation                            |    1      1
  The famous iris example                  |    1      1
  linesegments + colors                    |    1      1
  Standard deviation band                  |    1      1
  Parallel Prefix Sum                      |    1      1
  Interactive light cone                   |    1      1
  Streamplot animation                     |    1      1
  Line with varying colors                 |    1      1
  Viridis color scheme                     |    1      1
  timeseries                               |    1      1
  Line changing colour with Observables    |    1      1
  streamplot                               |    1      1
  Categorical heatmap                      |    1      1
  Arc                                      |    1      1
  Transforming lines                       |    1      1
  Orthographic Camera                      |    1      1
  Volume Function                          |    1      1
  Textured Mesh                            |    1      1
  Load Mesh                                |    1      1
  Colored Mesh                             |    1      1
  Wireframe of a Mesh                      |    1      1
  Wireframe of Sphere                      |    1      1
  Wireframe of a Surface                   |    1      1
  Surface                                  |    1      1
  Surface with image                       |    1      1
  Line Function                            |    1      1
  Meshscatter Function                     |    1      1
  scatter                                  |    1      1
  Marker sizes                             |    1      1
  3D Contour with 2D contour slices        |    1      1
  Contour3d                                |    1      1
  Arrows 3D                                |    1      1
  Image on Surface Sphere                  |    1      1
  Arrows on Sphere                         |    1      1
  surface + contour3d                      |    1      1
  FEM mesh 3D                              |    1      1
  Axis + Surface                           |    1      1
  Fluctuation 3D                           |    1      1
  Connected Sphere                         |    1      1
  image scatter                            |    1      1
  Simple meshscatter                       |    1      1
  Sphere Mesh                              |    1      1
  Stars                                    |    1      1
  Unicode Marker                           |    1      1
  Merged color Mesh                        |    1      1
  Surface + wireframe + contour            |    1      1
  Streamplot 3D                            |    1      1
  Fractional Brownian surface              |    1      1
  Coloured fractional Brownian noise field |    1      1
  Volume on black background               |    1      1
  Mouse Picking                            |    1      1
  sliders                                  |    1      1
  Mouse Hover                              |    1      1
  Edit Polygon                             |    1      1
  Add and change points                    |    1      1
  Orbit Diagram                            |    1      1
  Robot Arm                                |    1      1
  Animation with slider control            |    1      1
  Volume slider                            |    1      1
  Lighting                                 |    1      1
  Ambient Occlusion                        |    1      1
  Viridis scatter                          |    1      1
  Viridis meshscatter                      |    1      1
  Marker sizes + Marker colors             |    1      1
  Marker offset                            |    1      1
  colormaps                                |    1      1
  Available markers                        |    1      1
  Stepper demo                             |    1      1
  Implicit equation                        |    1      1
  Cube lattice                             |    1      1
  3D cube with sphere cutout, inside       |    1      1
  3D cube with sphere cutout, outside      |    1      1
  Biohazard                                |    1      1
  Twisty cube thing                        |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Test                                     |    1      1
  Type recipe for molecule simulation      |    1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 184 failed, 0 errored, 0 broken.
in expression starting at /home/kangpyo/.julia/packages/Makie/JLzLy/test/runtests.jl:14
ERROR: Package Makie errored during testing`

**Comment by SimonDanisch** [comment]
That looks like an old version of GLMakie
