### ISSUE TITLE
Is it possible to add a secondary y axis?

### ISSUE THREAD

**Issue by wsgreen** [JuliaPlots/Makie.jl#816]
Is there a way to create a plot with a secondary y (or x) axis, similar to Matplotlib twinx() / twiny()?

Thanks!

**Comment by wsgreen** [comment]
I figured out how to overlay two plots with a 'hardcoded' bbox. 
But how do I get the actual bbox of axis 1 so I can plug it into axis 2?

```
using CairoMakie
using AbstractPlotting
using DataFrames

fig = Figure(resolution = (600, 400))
ax1 = Axis(fig, xlabel = "x", ylabel = "", bbox = BBox(50, 500, 50, 350))
ax2 = Axis(fig, xlabel = "x", ylabel = "", bbox = BBox(50, 500, 50, 350))

A = DataFrame([[1,2,3,4,5],rand(5) .* 10])
B = DataFrame([[1,2,3,4,5],rand(5)])

plot1 = lines!(ax1, A.x1, A.x2)
plot2 = lines!(ax2, B.x1, B.x2, color = :blue)

ax2.yaxisposition = :right
ax2.yticklabelalign = (:left, :center)
```
![figure](https://user-images.githubusercontent.com/59248456/104857362-63992480-5918-11eb-810d-e2acf2604017.png)

Naively, I would think something like this:
`ax2 = Axis(fig, xlabel = "x", ylabel = "", bbox = boundingbox(ax1))`

**Comment by jkrumbiegel** [comment]
You can do it, but it's not documented and could change at any time:

```julia
f = Figure(figure_padding = 50)
ax = Axis(f[1, 1])
lines!(ax, 0..8pi, sin)
MakieLayout.LineAxis(f.scene,
    endpoints = @lift(MakieLayout.topline($(ax.scene.px_area))),
    spinecolor = :black,
    labelfont = "Dejavu Sans",
    ticklabelfont = "Dejavu Sans",
    spinevisible = false,
    minorticks = IntervalsBetween(2),
    flipped = true,
    ticklabelalign = (:center, :bottom),
    ticklabelsize = 16,
    limits = @lift((minimum($(ax.finallimits))[1], maximum($(ax.finallimits))[1])),
    ticks = MultiplesTicks(5, pi, "π"),
    label = "",
)
f
```
![grafik](https://user-images.githubusercontent.com/22495855/144040113-70d5262a-6c41-4582-8d3a-e5485ccb77a3.png)

**Comment by thudjx** [comment]
Is the functionality added to documentation?
