### ISSUE TITLE
Explicit `GridLayout` breaks nested indexing

### ISSUE THREAD

**Issue by yha** [JuliaPlots/Makie.jl#817]
There's a confusing inconsistency between the behavior of `layout = fig[i,j] = GridLayout(...)` and `fig[i,j] = GridLayout(...); layout = fig[i,j]`:
```
fig = Figure()

lines(fig[1,1], rand(5))

# This works:
fig[1,2] = GridLayout(tellheight = false)
rightpane = fig[1,2]
# This doesn't: (errors below)
# rightpane = fig[1,2] = GridLayout(tellheight = false)

rightpane[1,1][1,1] = Slider(fig) # Error here

display(fig)
```

**Comment by jkrumbiegel** [comment]
oh yes good catch, that's because I came up with the nested grid creation during the figure rewrite, so it's not in gridlayoutbase. but I should add it there, too for consistency

**Comment by jkrumbiegel** [comment]
I've fixed this in https://github.com/JuliaPlots/AbstractPlotting.jl/commit/4b951344a3bc27975cd00fa73b361524aeb4e9b9 and that will soon be tagged as well
