### ISSUE TITLE
Add stem plots

### ISSUE THREAD

**Issue by Uroc327** [JuliaPlots/Makie.jl#818]
I'd like to create 2D and 3D stem plots similar to [1] or [2].

Are there any plans to provide a function for this?

  [1] https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.stem.html
  [2] https://www.mathworks.com/help/matlab/ref/stem.html

**Comment by ffreyer** [comment]
This is fairly easy to recreate in 2D:

```julia
xs = 1:0.1:10
ys = sin.(xs)

fig = Figure()
fig[1, 1] = Axis(fig)

_lines = [Point2f0(x, (0, y)[i]) for (x, y) in zip(xs, ys) for i in 1:2]
linesegments!(fig[1,1], _lines, color=:red)
scatter!(fig[1,1], xs, ys, color=:red)
```

![Screenshot from 2021-01-20 17-30-57](https://user-images.githubusercontent.com/10947937/105205391-83f9f680-5b45-11eb-9020-a18a97688497.png)

**Comment by ffreyer** [comment]
This can be closed now that it has been implemented in https://github.com/JuliaPlots/AbstractPlotting.jl/pull/643
