### ISSUE TITLE
using Makie - failing at first hurdle

### ISSUE THREAD

**Issue by neuralian** [JuliaPlots/Makie.jl#82]
I installed Makie as per the instructions. It seemed to install OK.
I am using JuliaPro 6.2.2 (latest) under Windows 10.
"using Makie" throws an error ...
(Sorry if I have missed something obvious; long-time MATLAB user trying to switch to Julia, still struggling with it  - but convinced that its worth a struggle). 
Thanks - Mike.

julia> using Makie
INFO: Precompiling module Makie.
ERROR: MethodError: no method matching joinpath(::Array{Any,1}, ::String)
Closest candidates are:
  joinpath(::String, ::String) at path.jl:208
  joinpath(::AbstractString, ::AbstractString) at path.jl:217
  joinpath(::AbstractString, ::AbstractString, ::AbstractString...) at path.jl:205
Stacktrace:
 [1] julia_cmd() at .\util.jl:604
 [2] create_expr_cache(::String, ::String, ::Array{Any,1}) at .\loading.jl:626
 [3] compilecache(::String) at .\loading.jl:709
 [4] _require(::Symbol) at .\loading.jl:497
 [5] require(::Symbol) at .\loading.jl:405
 [6] eval(::Module, ::Any) at .\boot.jl:235
 [7] eval(::Any) at .\boot.jl:234
 [8] macro expansion at C:\Users\paumi69p\AppData\Local\JuliaPro-0.6.2.2\pkgs-0.6.2.2\v0.6\Atom\src\
repl.jl:117 [inlined]
 [9] anonymous at .\<missing>:?

**Comment by SimonDanisch** [comment]
Great :) 
This looks very much like a problem with Atom - or at least it it's hiding the real problem!
Can you try `using Makie` in the REPL? Just open Julia in the command line / terminal ;)

**Comment by neuralian** [comment]
Thanks :-)
In the REPL, "using Makie" generates a long list of warnings, most of which are "redefining constant JULIA_HOME", but terminates without an error.  Twice it warns that FFTW.ji was not created/found.  Otherwise the warnings seem innocuous.

"scatter_lines.jl" from the examples runs OK up to line 10 ( which draws the line plot) then crashes on line 11 (the scatter plot), with the following error message.  The good news is, at least I can understand this error message! But I don't know how to fix it.  BTW, running the script from Atom/JuliaPro now gives the same error.
=========
julia> include("C:/Users/paumi69p/Documents/Julia/noobs/scatter_lines.jl")
ERROR: LoadError: UndefVarError: RGBA not defined
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:576
 [2] include(::String) at .\sysimg.jl:14
while loading C:\Users\paumi69p\Documents\Julia\noobs\scatter_lines.jl, in expression starting on line 11
===========

**Comment by SimonDanisch** [comment]
>include("C:/Users/paumi69p/Documents/Julia/noobs/scatter_lines.jl")

That seems to be your own script? RGBA not defined likeley means, you need to add a `using Colors` to your script.

**Comment by neuralian** [comment]
The script is scatter_lines.jl from the examples folder. It works if I add `using Colors ` to the script.  Probably should add that to the example script.  Thanks for your help!

**Comment by neuralian** [comment]
Two other example scripts crash:
shortexamples.jl  fails because `UndefVarError: volume not defined ` on the penultimate line.
theming.jl fails because `UndefVarError: to_markersize not defined` on line 18.

I'm guessing that these are caused by missing packages, but I don't know what package that is (or how to figure out what package that is).

**Comment by neuralian** [comment]
Thanks for your great work. I am slowly getting my head around Makie by analyzing the examples and tests.  Julia 1.0 + Makie will supersede MATLAB in my work.  I've done enough scientific programming/simulation to appreciate the huge effort required to get something like this into shape so others can use it.  Thanks for your help.
