### ISSUE TITLE
[Feature Request] - Minor ticks

### ISSUE THREAD

**Issue by kescobo** [JuliaPlots/Makie.jl#822]
Mentioned also in #183 #206, "minor" ticks are available in many plot packages, and serve primarily to subdivide ticks along an axis, often without labels. They can also be used for additional spans with different styling, eg
(shared by @fabgrei on slack):

![image](https://user-images.githubusercontent.com/3502975/105504185-76ec1d00-5c95-11eb-93cf-eb0da0ecd857.png)

As far as API, I can think of a couple of sensible options

- specifying # of subdivisions that are evenly spaced between major ticks. This may be complicated if major ticks are not evenly spaced. Also, need to consider if a log-scale is ever implemented (xref #557)
    - from wikipedia: ![image](https://user-images.githubusercontent.com/3502975/105505015-6f794380-5c96-11eb-9d6f-957b24a05269.png)
- If major ticks are entered manually, minor ticks could also be entered manually (and if overlapping with major ticks, the major should win) Eg `... ticks = 1:5:100, minorticks = 1:100...`

cc @jkrumbiegel, @greimel and @jerlich

**Comment by KronosTheLate** [comment]
I just want to chime in that support of logarithmic minor ticks would be amazing if Makie ever becomes the default backend for ControlSystems.jl, which I have been using for a university course. The current fix is a wacky function that creates them (using Plots.jl), but plotting-backend support would be much appreciated in communities like that.

Just in general, minor ticks add almost as much as if they were major, with a lot less clutter. I second this feature request.

**Comment by jkrumbiegel** [comment]
added in https://github.com/JuliaPlots/AbstractPlotting.jl/pull/620

let's open new issues for specific features regarding minor ticks

here's a simple implementation for something like logarithmically spaced ticks:

```julia
struct LogMinorTicks end


function MakieLayout.get_minor_tickvalues(::LogMinorTicks, tickvalues, vmin, vmax)
    vals = Float32[]
    for (lo, hi) in zip(@view(tickvalues[1:end-1]), @view(tickvalues[2:end]))
        interval = hi-lo
        steps = log10.(LinRange(10^lo, 10^hi, 11))
        append!(vals, steps[2:end-1])
    end
    vals
end

scatter(rand(200, 2) .* 3,
    figure = (fontsize = 12,),
    axis = (
        xtickformat = "10^{:.1f}",
        xminorticks = LogMinorTicks(),
        xminorticksvisible = true,
        xminorgridvisible = true,
    ))

```

<img width="461" alt="grafik" src="https://user-images.githubusercontent.com/22495855/106256492-a2ce4c00-621b-11eb-9335-0edbb375c03f.png">
