### ISSUE TITLE
Scaling Axis not working

### ISSUE THREAD

**Issue by tpdsantos** [JuliaPlots/Makie.jl#83]
Hi, I was creating the line plot from the examples. The plot was nice, but the y axis is too small, and I wanted the axes to fit the window size, so in the end I would have an image with almost no empty space. messing around with the line scale works, but with the axis scale it doesn't...

That's what I did so far : 

```julia
using Makie
scene = Scene(resolution=(1000,1000))
x = linspace(0,3pi,200) ; y = sin.(x)
lin = lines(scene, x, y)
ax = axis(scene, linspace(0,3pi,5), linspace(-1,1,5))
ax[:showgrid  ] = (false,false,false)
ax[:axisnames ] = (" "," "," ")
ax[:axiscolors] = (:black,:black,:black)
lin[:scale] = (1.0,4.0,1.0) # works fine
ax[:scale] = (1.0,4.0,1.0) # no changes are made
center!(scene)
```
Am I doing something wrong?

Thanks in advance

**Comment by SimonDanisch** [comment]
That's how this sample looks on master:
```Julia
using Makie
x = LinRange(0,3pi,200) ; y = sin.(x)
lin = lines(x, y, padding = (0.0, 0.0), axis = (
    names = (axisnames = ("", ""),),
    grid = (linewidth = (0, 0),),
))
```

![image](https://user-images.githubusercontent.com/1010467/47307156-9f0bf200-d62e-11e8-831b-2c63c21de726.png)

Please reopen with more infos if that's not what you wanted!
