### ISSUE TITLE
Colorbar in a heatmap

### ISSUE THREAD

**Issue by songhanzhang** [JuliaPlots/Makie.jl#835]
Hi, I am switching from Plots GR to GLMakie, but become quite confused. Today I am trying to draw heatmap with interpolation like this:
![GL_heatmap](https://user-images.githubusercontent.com/67284799/106895230-f0bae680-672a-11eb-8b07-dcb92e0037dc.png)

However, I am frustrated when adding a colorbar, while it is quite easy to implement (colorbar = true) in GR. I tried the commend "Colorbar" provided from the Makie documentation, but it gives error. I also tried a lot of codes (something like MakieLayout which looks quite complicated for me), but all these codes return error to me.

By the way, many code examples given in the documentation cannot work, even I directly take the code from the documentation website. It always gives me a lot of errors. For example:

---------------------------------------------
using GLMakie

julia> fig, ax, p = lines(cumsum(randn(1000)),
           figure = (resolution = (1000, 600),),
           axis = (ylabel = "Temperature",),
           color = :red)

ERROR: BoundsError: attempt to access Scene
  at index [3]
Stacktrace:
 [1] indexed_iterate(::Scene, ::Int64, ::Int64) at .\tuple.jl:90
 [2] top-level scope at none:1
---------------------------------------------

---------------------------------------------
using GLMakie

xs = LinRange(0, 10, 100)
ys = LinRange(0, 10, 100)
zs = [cos(x) * sin(y) for x in xs, y in ys]

f = Figure()

ERROR: UndefVarError: Figure not defined
Stacktrace:
 [1] top-level scope at none:1
---------------------------------------------

---------------------------------------------
julia> using CairoMakie

julia> layout[1, 1] = Axis(scene, title = "My column has size Relative(2/3)")

ERROR: MethodError: no method matching Axis(::Scene; title="My column has size Relative(2/3)")
Closest candidates are:
  Axis() at C:\Users\Songhan\.julia\packages\AbstractPlotting\40gRI\src\scenes.jl:271 got unsupported keyword argument "title"
Stacktrace:
 [1] top-level scope at none:1
---------------------------------------------

I am not sure whether the example codes are outdated, or something is missing from my side.

The examples given in the Gallery are helpful, but some cases are not included (e.g., how to add a colorbar, just a single colorbar). I believe that this is not a difficulty, but frustrated me indeed.

**Comment by jkrumbiegel** [comment]
hi, it seems like you're on an old version. Please only install GLMakie / CairoMakie and make sure you have no other packages holding them back. The current docs show with what versions they have been compiled http://makie.juliaplots.org/stable/#First-Steps

**Comment by jkrumbiegel** [comment]
colorbars are shown here http://makie.juliaplots.org/stable/makielayout/layoutables_examples.html#Colorbar

**Comment by songhanzhang** [comment]
Thank you @jkrumbiegel! I found that the package Makie was installed indeed. Maybe this is the old version as you mentioned. Now I have removed the package Pkg.rm("Makie"), and you can see the existing packages (also along with the version information):

julia> Pkg.installed()
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Pkg.jl:554
Dict{String,VersionNumber} with 16 entries:
  "Revise"           => v"3.1.3"
  "Gmsh"             => v"0.1.1"
  "Atom"             => v"0.12.25"
  "JLD"              => v"0.10.0"
  "Juno"             => v"0.8.4"
  "LaTeXStrings"     => v"1.2.0"
  "CairoMakie"       => v"0.3.9"
  "MAT"              => v"0.8.1"
  "SymPy"            => v"1.0.32"
  "AbstractPlotting" => v"0.14.2"
  "Plots"            => v"1.8.1"
  "PyPlot"           => v"2.9.0"
  "Measures"         => v"0.3.1"
  "GLMakie"          => v"0.1.20"
  "WAV"              => v"1.1.0"
  "FFTW"             => v"1.3.0"

julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) E-2236 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6

When I go into the colorbar example provided from the website, I still get nothing but error, even at the first step:

julia> using CairoMakie

julia> fig = Figure(resolution = (1200, 900))
ERROR: UndefVarError: Figure not defined
Stacktrace:
 [1] top-level scope at none:1

Everything is simple and correct as I just take the code from the website, but why this does not work?

**Comment by jkrumbiegel** [comment]
Note that you still have abstractplotting 0.14, which is an old version

**Comment by songhanzhang** [comment]
Thank you so much @jkrumbiegel. It works now!

I conclude that we only need GLMakie and CairoMakie, while the other relevant packages (e.g., AbstractPlotting, Makie, MakieLayout) should not be installed. I suggest to clarify this in the documentation. Otherwise, it is easy to make confusion, as we see all the examples in Gallery start from "using AbstractPlotting".

**Comment by jkrumbiegel** [comment]
Yes the example gallery just hasn't kept up with development. I suggest sticking to the docs themselves for exact syntax and gallery more for rough inspiration
