### ISSUE TITLE
Non-optimal stability of plotting window.

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPlots/Makie.jl#838]
![image](https://user-images.githubusercontent.com/61620837/107226555-910a5700-6a1a-11eb-874a-e88a8b35fcab.png)

Above you can see the code used to produce this crash. The crash occurred as I was panning around the plot. I present this anecdote as proof for my experience that the plotting window seems to struggle when I use it - it is generally a little slow and buggy. I have a feeling that the plotting window is less stable on windows, but I don't really know where that hunch comes from.

Info about my system
```
(@v1.5) pkg> status GLMakie
Status `C:\Users\username\.julia\environments\v1.5\Project.toml`
  [e9467ef8] GLMakie v0.1.26

julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER =
```

**Comment by jkrumbiegel** [comment]
yes we've seen multiple reports of instabilities on windows, although because there are no stacktraces it's difficult to find out what's causing these issues. e.g. https://github.com/JuliaPlots/Makie.jl/issues/793

**Comment by KronosTheLate** [comment]
Well that is just annoying to deal with. Time to switch to linux?

**Comment by jkrumbiegel** [comment]
It is. Mac has the problem that windows don't close reliably. I think those issues are mostly about glfw and not about makie per se

**Comment by SimonDanisch** [comment]
Possibly: https://github.com/JuliaPlots/Makie.jl/issues/1040
or: https://github.com/JuliaPlots/Makie.jl/issues/1398
