### ISSUE TITLE
[FR] Data on mouse hover

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPlots/Makie.jl#839]
Is it possible to add data-on-mouse-hover functionality? It is a feature that I am missing greatly from using Plotly(JS) through Plots.jl, and it may be a dealbreaker for me switching to Makie for day-to-day data-exploration, even though I love makie.

**Comment by jkrumbiegel** [comment]
do you mean little arrows and labels pointing at the data you're hovering over, or a label in the plot corner showing the data coordinates of the mouse? the latter should be relatively easy to add, while the former sounds difficult. both because it's not trivial to get the picked elements id'd for every primitive (especially not the mesh-based ones) and even less if they are nested within recipes

**Comment by KronosTheLate** [comment]
The latter. What you describe sounds like what I have seen from matplotlib, while I was imagining something like plotly, as shown below:
![image](https://user-images.githubusercontent.com/61620837/107236096-a8027680-6a25-11eb-82b7-5960967a0148.png)

Either is fine really, while I gotta say I am a sucker for the color-coding as seen, when working with multiple datasets.

In general, the UI for plot-exploration of PlotlyJS is so much more fluid to me personally that Makie right now, so getting inspiration from it's interactive elements is just perfect for my taste.

Another related feature would be the ability to click on a data-point data to make its value stay there, so that one can move the mouse and compare with another point to see a relative change - extremely convenient when estimating a slope on the fly. This would also be lovely, and it is one of the features of MatLab I am jealous of.

**Comment by KronosTheLate** [comment]
I think that Gadfly has done this very minimalistically and nicely - you press "c" (for cursor) to toggle showing the coordinates in a corner. Maybie some of that code could be re-used. But, if you say that it is simple enough, then it might not be nessecary...

**Comment by ffreyer** [comment]
Related discourse thread: 
https://discourse.julialang.org/t/interactive-plot-data-inspection-with-makie-a-la-plotlyjs/58095

**Comment by ffreyer** [comment]
I'll close this since `DataInspector` has been merged.
