### ISSUE TITLE
Installation fails at Lubuntu 20.04 and Julia 1.4.1

### ISSUE THREAD

**Issue by cryogenium** [JuliaPlots/Makie.jl#842]
Hello

When I tried to install GLMakie ((@v1.4) pkg> add GLMakie), I got error "ERROR: Unable to automatically install 'Xorg_libpthread_stubs' from '/home/mikko/.julia/packages/Xorg_libpthread_stubs_jll/zqOOX/Artifacts.toml". What could be problem and how to fix it? All necessary packages are installed.

**Comment by SimonDanisch** [comment]
Looks like a Julia issue with artifacts. Maybe ask on discourse or slack!
