### ISSUE TITLE
CairoMakie: wrong color interpretation in meshscatter

### ISSUE THREAD

**Issue by phlavenk** [JuliaPlots/Makie.jl#844]
The color interpretation in CairoMakie is wrong, compared to GL makie and Plots:

MWE:
```julia
a = 0:0.1:π/2
x = cos.(a)
y = [1.0 for xx in x]
z = sin.(a)

using Plots
Plots.scatter(x, y, z, marker_z = a )
using GLMakie
GLMakie.activate!()
fig = meshscatter(x, y, z, markersize = 0.05, color=a)
using CairoMakie
CairoMakie.activate!()
fig = meshscatter(x, y, z, markersize = 0.05, color=a)
```
Plots:
![plots](https://user-images.githubusercontent.com/12131440/108040836-1656c280-703e-11eb-8ba2-44bda385e2e8.png)
GLMakie:
![GLMakie](https://user-images.githubusercontent.com/12131440/108040858-1eaefd80-703e-11eb-87f0-a382f45f2ff4.png)
CairoMakie:
![CairoMakie](https://user-images.githubusercontent.com/12131440/108040885-25d60b80-703e-11eb-933b-56ab9ed1da2d.png)

**Comment by ffreyer** [comment]
Good catch, the pr should fix this :)
