### ISSUE TITLE
Unexpected figure change when move all points along x axis

### ISSUE THREAD

**Issue by lihua-cat** [JuliaPlots/Makie.jl#847]
```julia
using GLMakie
AbstractPlotting.inline!(true)

# generate points
x = -1:0.005:1
σ = 0.1
y = exp.(-x.^2 / (2 * σ^2)) / (σ * √(2π))
# plot points
fig = Figure(resolution = (1200, 1000))
scatter(fig[1,1], x, y, markersize = 2, color = :blue)
# move points along x axis
xt = x .+ 1000000
scatter(fig[2,1], xt, y, markersize = 2, color = :red)

display(fig)
```
![gl sample](https://user-images.githubusercontent.com/42488653/108599898-c6c21f00-73ce-11eb-9c13-a5384de6fb84.png)

**Comment by jkrumbiegel** [comment]
This is because Makie internally converts everything to Float32 because that's what GPUs can deal with. The precision of Float32 seems to be 7 decimal places, so I guess with an offset of 1_000_000 you lose the resolution for your curve.
