### ISSUE TITLE
Rename contourf to contourfill

### ISSUE THREAD

**Issue by jtrakk** [JuliaPlots/Makie.jl#848]
`contourf` isn't an obvious name for that function. `contourfill` says more about what it is without being too long.

**Comment by mkborregaard** [comment]
In other plotting systems this is called:
Plots: contourf
matplotlib: contourf
matlab: contourf
R: filled.contour

**Comment by jtrakk** [comment]
Good idea. 

ggplot2: [geom_contour_filled](https://ggplot2.tidyverse.org/reference/geom_contour.html)
d3: [contour](https://github.com/d3/d3-contour)
plotly: [contour](https://plotly.com/python/contour-plots/)

**Comment by jkrumbiegel** [comment]
Yeah I think we're not going to change this now, it's kind of well-known although I agree contourfill and friends are a bit more explicit
