### ISSUE TITLE
Figure not defined

### ISSUE THREAD

**Issue by nickkeepfer** [JuliaPlots/Makie.jl#849]
For the life of me, I can't get this package to work. I have tried removing the registries/General folder, updating all packages, freshly installing all packages. The documentation uses Figure() to generate subplots, but apparently it doesn't exist?

```julia
using Makie
using GLMakie
using AbstractPlotting

help?> Figure
search: launch_configuration

Couldn't find Figure
Perhaps you meant Core
  No documentation found.

  Binding Figure does not exist.
```
What am I doing wrong?

**Comment by ffreyer** [comment]
Your AbstractPlotting is most likely not up to date. You need at least 0.15. Makie might be holding it back, you can remove it and just use GLMakie instead

**Comment by jkrumbiegel** [comment]
Sorry you're having trouble! First of all only install GLMakie. AbstractPlotting is automatically reexported from that, and Makie.jl currently isn't needed as a package at all (historic reasons). Then check that you get the versions listed in the current docs, or at least comparable ones : http://makie.juliaplots.org/stable/#First-Steps

**Comment by LoganWalls** [comment]
I was having the same issue today with `CairoMakie` (even after removing `Makie`), but I managed to fix it by doing the following:

1.  Remove everything related to Makie (including `MakieGallery`, etc.)
```julia
]rm Makie CairoMakie AbstractPlotting
```
2. Update registries
```julia
]registry up
```
3. Reinstall only `CairoMakie` and `AbstractPlotting`: 
```julia
 ]add AbstractPlotting CairoMakie
```

Based on the posts above you may not need to install `AbstractPlotting` in step 3 if you're using `GLMakie`, but for `CairoMakie` I had to install it separately to import it.

**Comment by jkrumbiegel** [comment]
One really has to follow the instruction in the docs that says only to install one or more backend packages :) I'll close this as there doesn't seem to be a deeper underlying issue
