### ISSUE TITLE
Non-isotropic volume rendering

### ISSUE THREAD

**Issue by Cody-G** [JuliaPlots/Makie.jl#85]
GLVisualize scales a non-isotropic image appropriately if you encode the voxel spacing in an AxisArray and pass it to `visualize`.  It seems that Makie doesn't do this when passed an AxisArray.  Is this not implemented yet, or can I accomplish this in a different way with Makie?

**Comment by Cody-G** [comment]
Thanks Simon!  Another thing that I just noticed is that I'm unable to control the camera with a mouse if I set `camera=:orthographic`.  `camera=:perspective` works as expected.

**Comment by SimonDanisch** [comment]
Ah, I think you need to press ctrl, to move with orthographic! Btw, in the newdesign branch you will be able to customize this behaviour quite easily :) And I actually made the default to be more consitent.

**Comment by Cody-G** [comment]
> Ah, I think you need to press ctrl, to move with orthographic! 

Ah got it, thanks!

**Comment by SimonDanisch** [comment]
Do you have some GLVisualize example code I can run? That would make it a bit easier to add this to Makie!

**Comment by SimonEnsemble** [comment]
This is imperative to us, as we're visualizing contours of potential energies inside crystals with slanted unit cells.

At least in other viz software, we pass the vectors that define the voxels. In crystallography, this is the matrix that converts from fractional to Cartesian coordinates. This must be the `AxisArray`? 

e.g. in the beginning of a .cube file that contains volume data, the header lists the number of voxels in each direction and then the vector defining the unit cell axis in that direction. Here, 100 by 100 by 100.
```
Units of data: Float64
Loop order: x, y, z
0 0.000000 0.000000 0.000000 # origin
100 0.116193 0.000000 0.000000 # a direction
100 0.000000 0.055667 0.000000 # b direction
100 -0.043350 0.000000 0.225177 # c direction
```

**Comment by Cody-G** [comment]
Sorry for my delay in getting back to this!

>At least in other viz software, we pass the vectors that define the voxels. In crystallography, this is the matrix that converts from fractional to Cartesian coordinates. This must be the AxisArray?

`AxisArrays` don't use precisely that convention for mapping data to coordinates, but they can be used to achieve the same result.  When you create an `AxisArray` you pass a raw data array as well as a set of `Axis` types describing the spacing in a dimension.  See https://github.com/JuliaArrays/AxisArrays.jl

I realized however that this rendering issue is at a lower level than AxisArrays.  It seems that Makie is forcing every volume to render in a cubic shape.  Here you can see that behavior with a simple Array:

```julia
using Makie, ColorTypes

res=(800,600)
scene = Scene(resolution=res)

vol = rand(RGBA{Float32}, 100,50,50) # not a cube
volume(vol, algorithm=:absorptionrgba, camera=:perspective)
center!(scene)
```

**Comment by Cody-G** [comment]
I'm wondering whether [this line](https://github.com/JuliaPlots/Makie.jl/blob/035551140cbb290744a656338c20893c9e4db669/src/atomics/imagelike.jl#L67) is the culprit, will check when I get a chance.

**Comment by Cody-G** [comment]
Yes I think that's it.  If you specify `dimensions` it seems to scale correctly:

```julia
volume(vol, algorithm=:iso, camera=:perspective, dimensions=size(vol))
```

Now I understand that weird things happen when `dimensions` is not proportional to the size of the volume, BUT the advantage is that we can use that parameter to scale the array dimensions however we want with a raw data array.

Simon, what do you think about changing the default value of `dimensions` to consider the size of the input array?

Also for completeness I'll point out that this wouldn't address the issues discussed at the end of https://github.com/JuliaGL/GLVisualize.jl/pull/199 about how color intensity should scale with size and anisotropy of the inputs.

**Comment by SimonDanisch** [comment]
I think this should be fixed

**Comment by Cody-G** [comment]
Aweseome, thanks Simon!

**Comment by gszep** [comment]
is there a way of telling `volume` to plot voxels at the correct coordinate locations given by `image.axes` where `image::AxisArray` with something like this:
```julia
x,y,z = image.axes
volume( x,y,z, image.data) 
```
this way `volume` has a similar behaviour to `image(x, y, image)`

**Comment by gszep** [comment]
ah it works when you parse the axes like this
```julia
x,y,z = ( range( extrema(ax.val)..., length=length(ax)) for ax ∈ image.axes )
```
