### ISSUE TITLE
Add stem-plot

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPlots/Makie.jl#851]
I would love a feature for creating stem-plots in Makie, as it is just the right visual for signals that are discrete in x-values (IMO). Could something like this be added? Possibly it would return two plot-object, one for the lines and one for the scatters (in addition to an axis and/or figure) - or one could bundle them together in a single object that has attributes of both a line and a scatter.

Examples of what I am talking about:
https://goropikari.github.io/PlotsGallery.jl/src/stem.html
https://se.mathworks.com/help/matlab/ref/stem.html
https://matplotlib.org/stable/gallery/lines_bars_and_markers/stem_plot.html
https://github.com/GiovineItalia/Gadfly.jl/pull/1076

**Comment by ffreyer** [comment]
Duplicate of #818. I think it would be fairly easy to make a pr for it if you or @Uroc327 want to try. You can check the [docs](http://makie.juliaplots.org/stable/recipes.html#Plot-Recipes) for how to create recipes and compare to others in AbstractPlotting src/basic_recipes.

**Comment by Uroc327** [comment]
I tried to create a general (supporting 2D, 3D, all those attributes, sane default attributes and styles) recipe for a short while. As I had a really hard time to find documentation and examples that are existing and up-to-date and correct for this, I kind of stopped trying.

My last approach was someting like
```julia
# those are not strictly necessayr, but they allow to plot complex data as well.. yay
convert_arguments(::Type{<:Scatter}, coords::AbstractVector{<:Complex}) = (map(x -> Point(float(real(x)), float(imag(x))), coords),)
convert_arguments(::Type{<:Scatter}, coords::AbstractVector{<:Complex}, heights::AbstractVector{<:Real}) = (map((x, z) -> Point(float(real(x)), float(imag(x)), float(z)), coords, heights),)

@recipe(Stem, positions) do scene
	merge(default_theme(scene, Scatter), default_theme(scene, LineSegments))
end

function plot!(plot::Stem{<:NTuple{N, Any}}) where N
	y = p[N]
	lines = [Point(x..., (0, y)[i]) for (x..., y) in zip(p[1:N-1]..., p[N]) for i in 1:2]

	plot!(plot, Scatter, attributes_from(Scatter, plot), p[1:N]...)
	plot!(plot, LineSegments, attributes_from(LineSegments, plot), lines)
end
```

**Comment by ffreyer** [comment]
This is probably a good reference, since arrows do something similar. 
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/basic_recipes/arrows.jl

**Comment by jkrumbiegel** [comment]
https://github.com/JuliaPlots/AbstractPlotting.jl/pull/643

**Comment by jkrumbiegel** [comment]
does this look ok in terms of functionality (link should start working soon) http://makie.juliaplots.org/previews/PR643/plotting_functions.html#stemplot

**Comment by KronosTheLate** [comment]
> does this look ok in terms of functionality (link should start working soon) http://makie.juliaplots.org/previews/PR643/plotting_functions.html#stemplot
> 
> or maybe this temp link https://refined-github-html-preview.kidonng.workers.dev/JuliaPlots/MakieDocumentation/raw/gh-pages/previews/PR643/plotting_functions.html#stemplot

That looks AMAZING! The offset kwarg is not something I have seen before, but it is super-cool. And the 3D stuff is very nice, good job! 

Maybie one of the plots could be with everything default? That is the only thing I am feeling uncertain about in terms of looks.

I would also prefer to command to be `stem` as opposed to `stemplot`, as the commends don't typically end with "plot" in Makie (e.g. `scatterplot` or `lineplot`). I feel like it would be more consistent.

But for any more discussion, tag me over at the PR. I concider this issue closed. Thanks so much ❤️

**Comment by KronosTheLate** [comment]
I just wanted to add the following quote from my homework this morning:
"Again, note that each sample amplitude is plotted using a vertical bar with a solid dot. This notation is well accepted in the DSP literatures."

Thanks again for the fast response and action <3

**Comment by jkrumbiegel** [comment]
see that's why it's important to have different perspectives for this kind of thing. I've never needed a stem plot in neuroscience / psychology but it seems quite important in your field, so I'm glad to add it
