### ISSUE TITLE
GLMakie is incompatible with FileIO 1.6

### ISSUE THREAD

**Issue by Octogonapus** [JuliaPlots/Makie.jl#863]
I am using Julia 1.5.3, GLMakie 0.1.27. The recent FileIO update (1.6) is not compatible with GLMakie 0.1.27.

This code:

```
s = scatter(1:4);
display(s)
```
Results in this exception: https://pastebin.com/8LxCtqN2

This code:
```
s = scatter(1:4);
FileIO.save("s.png", s)
```
Results in this exception: https://pastebin.com/bYXAS3vp

Downgrading to FileIO 1.5 fixes this issue.

**Comment by SimonDanisch** [comment]
Should be fixed in https://github.com/JuliaPlots/GLMakie.jl/commit/b72c27acb70de26c935cacbfb41f4a5cacb1668f
