### ISSUE TITLE
`Plot` function returns a `FigureAxisPlot` object instead of a `Scene`

### ISSUE THREAD

**Issue by roland-KA** [JuliaPlots/Makie.jl#866]
The Tutorial [Adding to a scene](http://juliaplots.org/MakieGallery.jl/stable/basic-tutorials.html#Adding-to-a-scene) doesn't work as described (using GLMakie). 

When I enter the line
`scatter!(scene, x, y1, color = :red, markersize = 0.1)`

an error occurs as follows:

````ERROR: There was no `AbstractPlotting.convert_arguments` overload found for
the plot type Combined{AbstractPlotting.scatter,Tuple{Figure,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Array{Float64,1}}}, or its conversion trait AbstractPlotting.PointBased().
The arguments were:
(Figure, StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, Array{Float64,1}) ...````

I could track it down to the point that the previous line in the tutorial 
`scene = lines(x, y1, color = :blue)` 
doesn't really return a `Scene`-object but instead it returns a `FigureAxisPlot`-object.

When I replace that line by:
`figure, axis, plot = lines(x, y1, color = :blue)` 

then I can continue with:
`scatter!(plot, x, y1, color = :red, markersize = 0.1)`

But this replaces the `plot` which has been drawn previously instead of adding a `plot` to a `Scene`. 

How can I get the effects which are intended by the tutorial?

BTW: The return values of the above mentioned `lines` function call are:
figure --> `Figure`
axis --> `Axis`
plot --> `Combined{AbstractPlotting.lines,Tuple{Array{Point{2,Float32},1}}}`

**Comment by jkrumbiegel** [comment]
Hi, you've linked a very old version of the docs. Please check the latest version, that will work :)

**Comment by roland-KA** [comment]
Thank's for the hint :-) 

It would be perhaps helpful (and prevent further confusion) to mark this documentation as outdated.

Is there an up-to-date-version of these examples? The tutorial in the Makies-docs is quite nice as it shows all the fancy bells and whistles Makies offers. But the examples I linked, are a more step by step introduction and thus more adequate for newbies to Makies.
