### ISSUE TITLE
Innefficient use of space

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPlots/Makie.jl#868]
Here is an example-plot, just for sake of discussion:
![image](https://user-images.githubusercontent.com/61620837/110249773-09136080-7f78-11eb-93e2-60766d00083a.png)

I feel like there is a lot of space that is carelessly wasted all over the current default plot in Makie. Especially in the margins to the edges. I feel like maximising the space for the plot itself is very important, as I often plot in the plotting-pane of VSCode or a notebook, meaning that the plot itself only gets a fraction of my 13'' screen. As this is a highly subjective issue, more than requesting a specific change, I simply want to start a discussion of the state of real-estate-utilization in the default plot, and suggestions for what can be done to accomodate users like me who only give the plot a fraction of their small screen.

**Comment by ffreyer** [comment]
Julius has made a bunch of adjustment for the defaults, including smaller textsizes and less padding. It looks a lot better to me with respect to use of space, so I'll close this. We can re-open this if there is more to discuss.
