### ISSUE TITLE
3D stem plot on plane

### ISSUE THREAD

**Issue by Uroc327** [JuliaPlots/Makie.jl#881]
Thanks for implementing `stem`!

The function currently interprets inputs as `stem(<1D line>, <2D data>)`. Is there a way to customize this to `stem(<2D plane>, <1D data>)`?

The latter case is often used to show complex data with weights (e.g., a discrete probability distribution or a complex quadrature scheme). Also, the latter case is the default for [MATLAB's `stem3`](https://www.mathworks.com/help/matlab/ref/stem3.html).

Eventually, my use case is `stem(x::Vector{ComplexF64}, h::Vector{Float64})` plotting stems at positions `x` in an x-y plane with heights `h`. Of course, I can write the `convert_arguments` function converting from complex to tuple, array, point or whatever `stem()` would like to receive myself.

Probably an interface like `stem(::Vector{Point}, ::Vector{Real})` and `stem(::Vector{Real}, ::Vector{Point})` (including the framework to specify figure, axis, graph properties and everything else) makes sense?
Then, conversion rules like
```julia
convert_arguments(::Type{<:Stem}, coords::AbstractVector{<:Complex}, heights::AbstractVector{<:Real}) = ((Point.(float(real(coords)), float(imag(coords)))), float(heights),)
convert_arguments(::Type{<:Stem}, coords::AbstractVector{<:Real}, stems::AbstractVector{<:Complex}) = ((float(coords), Point.(float(real(stems)), float(imag(stems)))),)
```
should work, I guess?

**Comment by jkrumbiegel** [comment]
Hmm we could think about changing the stem interface for 3d, I don't use it much so might not have the best idea how it's normally done. Currently, this is how you'd do a plot like your example, although I agree the interface could be simpler for that use case:

```julia
julia> stem(1:100, 1:100, sin.(LinRange(0, pi, 100)), offset = Point3f0.(1:100, 1:100, 0),
    trunkcolor = :transparent, markersize = 1500, color = :transparent)
```

With my new 3d axis from a dev branch, and the markersize 1500 is because of a bug in scatter:

![grafik](https://user-images.githubusercontent.com/22495855/111198716-2cfe2400-85c0-11eb-9c4e-cfa2aff53a4a.png)

**Comment by jkrumbiegel** [comment]
aha I see where my mistake was, I just defined a helper function for 3d a bit weird, didn't think about it much. I'll change it and then by default, for a single number offset in the 3d case, it will be the z-coordinate and x/y will be copied from the data.

**Comment by jkrumbiegel** [comment]
https://github.com/JuliaPlots/AbstractPlotting.jl/pull/660

**Comment by Uroc327** [comment]
Awesome! Thank you. 

Out of curiosity, how would one replicate the old behavior with a trunk line and 2d/complex offsets?
Although, I have to admit this is a rather uncommon format at least in my area. I think, I've only seen this once for some polyphase multirate filter example.

**Comment by jkrumbiegel** [comment]
you can always use the 3d offset for 3d stems

**Comment by Uroc327** [comment]
Ah, that makes sense. Cool

**Comment by Uroc327** [comment]
I guess this can be closed now, as your merge is in the latest release. Thanks for you help!
