### ISSUE TITLE
Mask / clipping problems for SVG export in Adobe Illustrator.

### ISSUE THREAD

**Issue by kescobo** [JuliaPlots/Makie.jl#882]
Files display fine in browser and open fine in Inkscape, but in adobe illustrator I get

![image](https://user-images.githubusercontent.com/3502975/111347948-16a2a780-8656-11eb-939a-718cfbb9a410.png)

instead of

![image](https://user-images.githubusercontent.com/3502975/111348423-8fa1ff00-8656-11eb-87cb-81cfb387c973.png)

Doing select-all and cmd+alt+7 (release clipping mask) solves the issue without any apparent ill-effects, so it's not a critical problem, but is a minor annoyance, and I thought worth mentioning in case someone else runs into the same issue.

**Comment by jkrumbiegel** [comment]
can you check how illustrator opens the same plot as a pdf?

**Comment by kescobo** [comment]
Do you mean saving as PDF from CairoMakie? I'm having some issues with that (ImageMagick throwing errors)

**Comment by jkrumbiegel** [comment]
That sounds weird, why is ImageMagick involved in that? Cairo can save pdfs directly

**Comment by kescobo** [comment]
🤷‍♂️ when I first tried `CairoMakie.save("myfig.pdf", scene)` it have me an error saying ImageMagick wasn't installed. When I installed it, I got a different error. Worth a separate issue?

**Comment by jkrumbiegel** [comment]
Sure!

**Comment by kescobo** [comment]
:thinking: Can't reproduce the ImageMagick thing in a fresh environment :thinking:

**Comment by SimonDanisch** [comment]
Might be due to the FileIO update. I think there were certain version mixes, that could run into trouble. On the newest versions, everything should be fixed, so could make sense that it went away in a fresh environment ;)

**Comment by jkrumbiegel** [comment]
if pdfs work now, could you report back regarding the clipping problem in illustrator?

**Comment by kescobo** [comment]
Yeah, was just doing that. PDFs look fine

**Comment by jkrumbiegel** [comment]
good, then let's blame this on illustrator's svg import for now, because there's probably nothing we can do if that's the case
