### ISSUE TITLE
StackOverflowError when passing `color = nothing` to density plot

### ISSUE THREAD

**Issue by fbanning** [JuliaPlots/Makie.jl#883]
Using CairoMakie I encounter a StackOverflowError when trying to save or display a previously created density plot: 

```julia
ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] rgbatuple(::Nothing) at C:\Users\Frederik Banning\.julia\packages\CairoMakie\6qQNv\src\utils.jl:80 (repeats 79984 times)
in expression starting at c:\Users\Frederik Banning\path\to\script.jl:196
```

This does not happen when just creating the plot `fig` without attempting to save it (`save("plot.png", fig)`) or display it (`display(fig)`).
The StackOverflowError also does not occur when using GLMakie instead of CairoMakie so it seems to be a bug specifically related to the used backend.
As a workaround I can use GLMakie for the plots affected by this but this doesn't give me the same output quality as CairoMakie does and I can't save as SVG.

I've attempted to recreate a generic example to reproduce this error which is as close as possible to my use case:

```julia
using CairoMakie

const MY_COLORS = cgrad([
    "#c67", # rose
    "#328", # indigo
    "#dc7", # sand
    "#173", # green
    "#ddd", # grey
])

my_theme = Attributes(
    Axis = (
        rightspinevisible = false,
        topspinevisible = false,
        xgridcolor = MY_COLORS[end],
        ygridcolor = MY_COLORS[end],
    ), 
    Legend = (
        framevisible = false,
    ),
)

set_theme!(my_theme)

function add_plots()
    density!(randn(50000) .* rand(1:4) .+ rand(1:4); 
        color = (MY_COLORS[1], 0.25), strokecolor = MY_COLORS[1], label = "rose")
    density!(randn(50000) .* rand(1:4) .+ rand(1:4); 
        color = (MY_COLORS[2], 0.25), strokecolor = MY_COLORS[2], label = "indigo")
    density!(randn(50000) .* rand(1:4) .+ rand(1:4); 
        color = (MY_COLORS[3], 0.25), strokecolor = MY_COLORS[3], label = "sand")
    density!(randn(50000) .* rand(1:4) .+ rand(1:4); 
        color = (MY_COLORS[4], 0.25), strokecolor = MY_COLORS[4], label = "green")
end

fig = Figure(resolution = (1200, 1200))
ax1 = fig[1,1] = Axis(fig, title = "Number One")
add_plots()
ax2 = fig[2,1] = Axis(fig, title = "Number Two")
add_plots()
ax3 = fig[3,1] = Axis(fig, title = "Number Three")
add_plots()
ax4 = fig[1,2] = Axis(fig, title = "Number Four")
add_plots()
ax5 = fig[2,2] = Axis(fig, title = "Number Five")
add_plots()
ax6 = fig[3,2] = Axis(fig, title = "Number Six")
add_plots()

ax1.ylabel = ax2.ylabel = ax3.ylabel = "Density"
ax3.xlabel = ax6.xlabel =  "Random Numbers"
linkyaxes!(fig.content...)
ax4.yticklabelsvisible = ax5.yticklabelsvisible = ax6.yticklabelsvisible = false
ax4.yticksvisible = ax5.yticksvisible = ax6.yticksvisible = false
ax1.xticklabelsvisible = ax2.xticklabelsvisible = ax4.xticklabelsvisible = ax5.xticklabelsvisible = false
ax1.xticksvisible = ax2.xticksvisible = ax4.xticksvisible = ax5.xticksvisible = false

fig[end+1,1:2] = Legend(fig, ax1; 
    tellheight = true, orientation = :horizontal)

save("SO-MWE.png", fig)
```

![SO-MWE](https://user-images.githubusercontent.com/65158285/111359333-ab73c800-868b-11eb-83f0-6084f9db6eeb.png)

Alas it works just fine and I cannot reproduce the problem. :(

From looking at the provided example, do you have any idea why this SO might happen?

**Comment by SimonDanisch** [comment]
If you look at the definition of rgba_tuple:
```

function rgbatuple(c::Colorant)
    rgba = RGBA(c)
    red(rgba), green(rgba), blue(rgba), alpha(rgba)
end

rgbatuple(c) = rgbatuple(to_color(c))
```
It can stackoverflow if `to_color` returns nothing (which the `rgbatuple(::Nothing)` points to).
So I guess you should figure out what colors you might be using that pose a problem here?
`rgbatuple` is used in quite a few places, so the whole stacktrace would help in which plot this occurs.

**Comment by fbanning** [comment]
Sadly the stacktrace posted above is already complete and there's no other info provided by it.

**Comment by SimonDanisch** [comment]
Well, it must be something about the colors you're using (maybe also something like `color = [1,2,3], colormap = [...]`).

**Comment by fbanning** [comment]
Yep, thanks for that pointer. It really helped because I had a second (probably more close to 100th) look at the failing function and found the problem. Here's a real MWE to reproduce the issue:

```julia
using CairoMakie

fig = Figure(resolution = (600, 400))

ax1 = fig[1,1] = Axis(fig, title = "Test")
density!(randn(100) .* rand(1:4) .+ rand(1:4); 
    color = nothing, strokecolor = :red)

ax1.ylabel = "Density"
ax1.xlabel = "Random Numbers"

save("SO-MWE.png", fig)
```

My best guess would be that `CairoMakie.rgbatuple` should have an additional check for `nothing` as input and then return a fully transparent color so that it behaves the same as when using GLMakie backend. :)

**Comment by SimonDanisch** [comment]
>My best guess would be that CairoMakie.rgbatuple should have an additional check for nothing as input and then return a fully transparent color so that it behaves the same as when using GLMakie backend. :)

Ooh, GLMakie does that? :-O That's weird, such conversions should be defined by `to_color` ... 
Maybe it unintentionally works in GLMakie, since in the Julia -> OpenGL c type conversion, nothing gets converted to void, which then just ends up not setting any color^^

**Comment by fbanning** [comment]
Thank you for the response and quick fix, @SimonDanisch. Much appreciated. :)
As a workaround, I will use `color = (:white, 0.0)` until the fix is live.

**Comment by jkrumbiegel** [comment]
There's also `:transparent`

**Comment by fbanning** [comment]
Yep, that would work just as well. Thanks again, closing this now. :)

**Comment by SimonDanisch** [comment]
Just an update: The fix of defining `to_color(nothing)-> RGBAf0(0,0,0,0)` turned out to be a bit more complicated, since GLMakie actually relies on color set to nothing when using colormaps instead. That's a bit of a technical debt that I want to remove in the future, but that's a bigger project. So I guess, we can't have that anytime soon...
