### ISSUE TITLE
Rename poly to polygon

### ISSUE THREAD

**Issue by jtrakk** [JuliaPlots/Makie.jl#890]
Because polygon is a word and unambiguous. "poly" isn't really a word and could also mean "polynomial".

- Matplotlib: [Polygon](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Polygon.html#matplotlib.patches.Polygon)
- R: [polygon](https://stat.ethz.ch/R-manual/R-patched/library/graphics/html/polygon.html)
- Matlab: [polyshape](https://www.mathworks.com/help/matlab/ref/polyshape.html)

**Comment by jkrumbiegel** [comment]
I think the reason is that `Polygon` already exists in GeometryBasics
