### ISSUE TITLE
Colorbar/heatmap confusion

### ISSUE THREAD

**Issue by ericphanson** [JuliaPlots/Makie.jl#896]
The correct way to use them together is something like this:
```
begin 
    fig = Figure()
    ax, heatmap_plot = heatmap(fig[1,1], rand(100,100), colorrange=(0.4, 0.6), colormap=:heat)
    Colorbar(fig[1,2], heatmap_plot , width=25)
    fig
end
```

![image (1)](https://user-images.githubusercontent.com/5846501/112197162-141eef80-8c0c-11eb-984a-637baffc8e47.png)

(example from @SimonDanisch). If you want to adjust the color range, you just change `colorrange`, and everything works nicely.

What's confusing is that there are some ways that look like they might work, but do not.

For example, if you pass `limits` thinking that's the right way to adjust the color range, you get a plot that looks ok, but of course the colorbar does not correspond at all to the heatmap anymore:
```julia
begin
    fig = Figure()
    ax, heatmap_plot = heatmap(fig[1,1], rand(100,100), colorrange=(0.4, 0.6), colormap=:heat)
    Colorbar(fig[1,2], heatmap_plot, width=25, limits = (10, 20))
    fig
end
```

![test (1)](https://user-images.githubusercontent.com/5846501/112197261-2c8f0a00-8c0c-11eb-9d49-211d331d935a.png)

Or, what tripped me up, is if you think `limits` is the way to adjust the color range and don't know `colorrange` exists (since it's not in the `heatmap` docstring, for example).

```julia
begin 
    fig = Figure()
    ax, heatmap_plot = heatmap(fig[1,1], rand(100,100), colormap=:heat)
    Colorbar(fig[1,2], heatmap_plot, width=25, limits = (10, 20))
    fig
end
```

![test (2)](https://user-images.githubusercontent.com/5846501/112197500-72e46900-8c0c-11eb-873c-5246ff866007.png)

I think I get now why it works the way it does, but it can be very confusing if you don't really know what you're doing! I wonder if maybe a warning can be thrown if the `Colorbar` color limits don't match the heatmap `colorrange`, or something like that. Or at least `colorrange` should be documented in `heatmap` and maybe `Colorbar` should mention it too.

**Comment by jkrumbiegel** [comment]
I've mostly fixed it here https://github.com/JuliaPlots/AbstractPlotting.jl/pull/689

The attributes being set automatically when passing a plot are now disallowed when passing them also as keyword arguments.

I've also added information about this to the docs and the Colorbar docstring.

**Comment by ericphanson** [comment]
Awesome, thank you!

**Comment by SimonEnsemble** [comment]
I think adding `colorrange` for the `heatmap` documentation is necessary---took me a while to find this.
