### ISSUE TITLE
CairoMakie: Problems with NaN values in `scatter` 

### ISSUE THREAD

**Issue by lhupe** [JuliaPlots/Makie.jl#897]
`CairoMakie` seems to be allergic to `NaN` values in some cases:

```julia
fig = Figure()
scatter(fig[1, 1], randn(10), [randn(9); NaN])
scatter(fig[1, 2], randn(10), randn(10))
```
produces 
![fig](https://user-images.githubusercontent.com/34064555/112340086-86510c00-8cc0-11eb-805a-ec173dbc9c1b.png)
as expected, but changing the marker to a `Char` or `Symbol` specification, e.g.
```julia
fig = Figure()
scatter(fig[1, 1], randn(10), [randn(9); NaN], marker = :rect)
scatter(fig[1, 2], randn(10), randn(10), marker = :rect)
```
produces this
![fig2](https://user-images.githubusercontent.com/34064555/112340093-87823900-8cc0-11eb-833f-0f618adb9045.png)
where spines, ticks and other plots have vanished.
I cannot reproduce this behaviour in `GLMakie`.

I think I noticed similar behaviour with other plotting functions (e.g. `arrow`) in `CairoMakie` in the past, but I haven't tested it systematically.

**Comment by jkrumbiegel** [comment]
that certainly looks weird! thanks for the MWE, i'll investigate when I have time

**Comment by jkrumbiegel** [comment]
fixed by https://github.com/JuliaPlots/CairoMakie.jl/pull/149
