### ISSUE TITLE
Returning flat interactive surface

### ISSUE THREAD

**Issue by paurierap** [JuliaPlots/Makie.jl#899]
Hi all, 

I am quite new to Makie.jl and its features and I was trying to get to know the interactive layoutables for, for example, a surface plot:

```using GLMakie, AbstractPlotting

fig = Figure(resolution = (900,900))

lsgrid = labelslidergrid!(
    fig,
    ["Frequency", "Amplitude"],
    [1:0.1:3, 1:0.1:3];
    formats = [x -> "$(round(x, digits = 1))"],
    width = 350,
    tellheight = false)

fig[1,2] = lsgrid.layout

ax = Axis(fig[1, 1])

x = (-2:0.01:2).* π
y = x

sliderobservables = [s.value for s in lsgrid.sliders]

fun = lift(sliderobservables...) do slvalues...
    [slvalues[2]*sin.(slvalues[1]*xs)*cos.(slvalues[1]*ys) for xs in x, ys in y]
end

surface!(x,y,fun)

fig
```

However, the graph provided is completely flat, resembling a contour. I have tried adding ```zlims!``` unsuccessfully though. What is it that I am missing? Thanks in advance!

**Comment by jkrumbiegel** [comment]
Replace `Axis` with `LScene`. `Axis` is 2D only, so you're seeing an orthographic projection of the surface from the top. `LScene` is the current way to include a normal `Scene` which by default uses a 3D projection, in a layout.

**Comment by paurierap** [comment]
That's what I was looking for. Thanks!
