### ISSUE TITLE
heatmap's x and y coordinates are misleading

### ISSUE THREAD

**Issue by wsshin** [JuliaPlots/Makie.jl#900]
`heatmap(x, y, v)` appears to take `x` and `y` coordinates of the entries of the `v` matrix, but actually it doesn't; it simply takes the minimum and maximum entries of `x` and `y` and use them as the limits of the x- and y-axes.

Here is the result of `heatmap(1:5, 1:3, rand(5,3))`:
![hm1](https://user-images.githubusercontent.com/1783289/112912506-a8ce9500-90c5-11eb-8362-b10a2fa46078.png)
The axes may seem correct, but what users expect is probably to have the leftmost column centered at `x = 1` and the rightmost column centered at `x = 5`.  In the above image, `x = 1` is the left edge (not the center) of the leftmost column and `x = 5` is the right edge (not the center) of the rightmost column.  As a result, the second column fourth columns are not centered at `x = 2` and `x = 4`.

Here is the result of `heatmap([2,3,5,8,13], 1:3, rand(5,3))`, which uses uneven `x`:
![hm2](https://user-images.githubusercontent.com/1783289/112912827-838e5680-90c6-11eb-8b57-c1bc774a8999.png)
The unevenness of `x` is ignored, and we have uniformly sized pixels.

In fact, `length(x)` and `length(y)` don't even have to be `size(v, 1)` and `size(v, 2)`; things like `heatmap(1:10, 1:20, rand(100,100))` succeed without errors.  `x` and `y` don't even have to be sorted: it seems that only their minimum and maximum values are used.

One potential solution is to use the entries of `x` and `y` as the coordinates of the boundaries of pixels as
```
        (x[i], y[j+1])          (x[i+1], y[j+1])
                      +--------+
                      | v[i,j] |
                      +--------+
          (x[i], y[j])          (x[i+1], y[j])
```
This is essentially [what matplotlib does](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.pcolor.html) (except that matplotlib's `x` and `y` are 2D arrays and they transpose `v`).  However, this approach not implement the ideal solution suggested in the first example, which is to center `v[i,j]` at `(x[i], y[j])`.  The ideal solution has another benefit that we can achieve a consistent behavior between `interpolate = true` and `interpolate = false`.  When the keyword argument `interpolate = true` is passed, we can assign `v[i,j]` precisely at `(x[i], y[j])`, so centering the pixel `v[i,j]` at `(x[i], y[j])` for `interpolate = false` is consistent with the behavior for `interpolate = true`.

(If `x` and `y` are uneven, determining the boundaries of the pixels is nontrivial if `x` and `y` specify pixel centers.  This is probably why matplotlib chose to use `x` and `y` as the coordinates of the boundaries, rather than the centers, of the pixels, even if this leads to inconsistency between `interpolate = true` and `interpolate = false`.  However, I think we can easily devise the strategy to determine the boundaries of pixels for uneven `x` and `y`.  matplotlib's method also requires `length(x) == 1+size(v,1)` and `length(y) == 1+size(v,2)`, which is nuisance.

**Comment by jkrumbiegel** [comment]
Yes there is this issue https://github.com/JuliaPlots/Makie.jl/issues/661 about it. I share your critique and I hope we can get to including uneven heatmaps soon

**Comment by wsshin** [comment]
If I want to contribute on implementing this feature, where should I start?  I'm new to Julia plotting, and the code base looks very large.  If someone points out a specific part of the code to implement this feature, I want to look into it.

**Comment by jkrumbiegel** [comment]
I tried briefly to implement something a couple weeks ago, but stopped when I noticed the implementation in GLMakie was completely based on having limits and a number of steps for each dimension. So my approach would be to look at how GLMakie could draw rectilinear heatmaps, where the x and y vectors contain sorted values in arbitrary distances. This would probably involve looking at the code here https://github.com/JuliaPlots/GLMakie.jl/blob/master/src/drawing_primitives.jl#L324-L339 and here https://github.com/JuliaPlots/GLMakie.jl/blob/master/src/GLVisualize/visualize/image_like.jl#L45-L69 and in the shaders mentioned here https://github.com/JuliaPlots/GLMakie.jl/blob/master/src/GLVisualize/visualize/image_like.jl#L66

**Comment by SimonDanisch** [comment]
Well, I think I'd just try to create those heatmaps with a surface plot without shading

**Comment by ffreyer** [comment]
I'm fairly certain my pr was essentially done and could deal with anything you can specify as `heatmap(::Vector, ::Vector, ::Matrix)`. Though it probably didn't do centering

**Comment by wsshin** [comment]
@ffreyer, I think you mean this WIP PR https://github.com/JuliaPlots/GLMakie.jl/pull/137.  Thanks!  I will take a look at the PR.

Also, in the PR you mentioned that you are adding supports for various inputs.  What other inputs do you have in mind?

**Comment by ffreyer** [comment]
It was supposed to mirror whatever https://github.com/JuliaPlots/CairoMakie.jl/pull/111 did. I don't remember if there were things I wanted to do anymore. That comment might just be about getting ranges and Intervals to convert correctly, which I seem to have done.
