### ISSUE TITLE
xlims!() on lines!() changes y-limits as well

### ISSUE THREAD

**Issue by wsshin** [JuliaPlots/Makie.jl#902]
```julia
xs = rand(10); ys = rand(10);
lines(xs, ys)
```
The above code produces a plot like
![original](https://user-images.githubusercontent.com/1783289/113018392-7e74ea00-914e-11eb-89b5-7937e2b90d08.png)
If I subsequently do `xlims!(0, 2)`, I get
![after xlims](https://user-images.githubusercontent.com/1783289/113018472-99475e80-914e-11eb-85d7-4680c1b7247a.png)
Notice that the y-limits as well as x-limits have changed as well.

On the other hand, if I do `ylims!(0, 2)` instead of `xlims!(0, 2)`, I get
![after ylims](https://user-images.githubusercontent.com/1783289/113018634-be3bd180-914e-11eb-851a-0fd77c87ad3a.png)
This time only x-limits have changed and y-limits remain the same.

This problem could be specific to `lines()`; not all plot types have the same problem, though I haven't tested all the plot types.

**Comment by devmotion** [comment]
I ran into the same problem with `scatter`. Just calling `xlims!` messes up the y limits as well.

**Comment by jkrumbiegel** [comment]
thanks for the bug report, fixed here https://github.com/JuliaPlots/AbstractPlotting.jl/pull/688
