### ISSUE TITLE
Axis3 is not working with heatmaps

### ISSUE THREAD

**Issue by lazarusA** [JuliaPlots/Makie.jl#907]
The following works if one uses an `LScene, including a warning regarding [0.0] ticks size. 

```
fig = Figure(resolution = (400, 400), fontsize = 10)
ax = LScene(fig, scenekw = (camera = cam3d!, show_axis = true))
heatmap!(ax,0:0.1:1, 0:0.1:1, rand(10,10), transformation=(:xz, 1), limits= Rect(Vec3f0(-1), Vec3f0(2)))
fig[1,1]= ax
fig
```
and if one tries to do the same with the new axis, 

```
fig = Figure(resolution = (1000, 1000), fontsize = 10)
ax = Axis3(fig, aspect = :data)
heatmap!(ax, 0:0.1:1, 0:0.1:1, rand(10,10), transformation=(:xz, 1), limits= Rect(Vec3f0(-1), Vec3f0(2)))
fig[1,1]= ax
fig
```

I get the error: 
`InexactError: check_top_bit(UInt64, -9223372036854775481)`

**Comment by ffreyer** [comment]
I ran into the same thing in https://github.com/JuliaPlots/AbstractPlotting.jl/pull/680. There the error was related to finding ticks with 0 width along the z-axis. I don't know if `Axis3` uses the same function though. If that is the reason maybe the error goes away if you pass limits to `Axis3`?

**Comment by lazarusA** [comment]
in the example above I also pass` limits` to the `Axis3` script.

**Comment by ffreyer** [comment]
You're passing it to `heatmap`, not `Axis3`. It doesn't seem like that matters though. I get
```julia
ax.limits
Observable{GeometryBasics.HyperRectangle{3, Float32}} with 22 listeners. Value:
GeometryBasics.HyperRectangle{3, Float32}(Float32[-0.05, -0.05, 0.0], Float32[1.1, 1.1, 0.0])
```
in either case. So the issue here is (1) limits don't get passed/get recalculated and (2) 0-width limits along some axis throws an error.

**Comment by ffreyer** [comment]
If you want a quick and dirty fix you can throw something like `scatter!(ax, [Point3f0(0), Point3f0(1)], markersize=0)` before the `heatmap`. That'll stop the error and you can adjust limits with `ax.limits[] = Rect(Vec3f0(-1), Vec3f0(2))` afterwards.

**Comment by jkrumbiegel** [comment]
ah yeah I probably just forgot to include the more robust limit mechanism from Axis where 0 width limits are expanded a bit

**Comment by lazarusA** [comment]
Indeed, the trick above works fine. A related question, how do we go back to the previous projection given in a LScene. There are some distortions that I don't like with the new Axis3.  `:fit, :fitzoom, :stretch` don't take me back.

**Comment by jkrumbiegel** [comment]
The only thing that distorts is the :stretch viewmode, and perspectiveness just controls from how far away (with zoom to counter) you are

**Comment by jkrumbiegel** [comment]
This should be fixed with https://github.com/JuliaPlots/AbstractPlotting.jl/pull/686

There is still some more work left to assimilate how limits work in 3d
