### ISSUE TITLE
Crashing when running Figure the second time

### ISSUE THREAD

**Issue by jenfenghsu** [JuliaPlots/Makie.jl#908]
When I ran (either in Visual Studio Code or Julia REPL)

`
function make_plot2()

    fig = Makie.Figure(resolution = (1200, 900))

    ax = Axis(fig[1, 1])
    lsgrid = labelslidergrid!(

        fig,
        ["A", "B", "C"],
        [0:1:1, 0:1:3, 0:1:63];
        formats = [x -> "$(x)$s" for s in [" ", " ", " "]],
        width = 100,
        tellheight = true)

    fig[1, 2] = lsgrid.layout

    fig

end

make_plot2()
`

the second time, the terminal would crash.  Is there a proper procedure I should close the previous figure?  Thank you!
My versions are:
Julia: 1.5.3
  "Makie"            => v"0.12.0"
  "AbstractPlotting" => v"0.15.27"
  "Colors"           => v"0.12.7"
  "JSServe"          => v"1.2.0"
  "WGLMakie"         => v"0.3.4"
  "ImageMagick"      => v"1.2.0"
  "GLMakie"          => v"0.1.30"

**Comment by SimonDanisch** [comment]
I can't reproduce it... If this is still an issue, please make the MWE complete (e.g. backend used, how you redisplay the figure)
