### ISSUE TITLE
Pipe save no longer works for most filetypes [CairoMakie]

### ISSUE THREAD

**Issue by bensetterholm** [JuliaPlots/Makie.jl#911]
I am using CairoMakie to save figures to disk. I used to be able to write:

```
using CairoMakie
lines(1:10) |> save("test.pdf")
```

But this no longer works as of about a month ago or so. It also does not work for `png` output. I can however save this way if the filetype is `svg`, so for the past month I have been piping to svg and then using `rsvg-convert` shell command to make the pdf.

I noticed this morning that this does work

```
using CairoMakie
save("test.pdf", lines(1:10))
```

So the acceptable ordering of arguments to `save` seems to have changed.

AbstractPlotting v0.15.27
CairoMakie v0.3.19
Julia 1.6.0
macOS 10.14.6

**Comment by jkrumbiegel** [comment]
`save` is a `FileIO` function, so if something changed in its behavior, I would suggest to look over there. They had breaking changes recently. Maybe an older version made a closure out of `save(filepath)`, I don't know
