### ISSUE TITLE
Missing segmens in "lines" plot for duplicate points in GLMakie 

### ISSUE THREAD

**Issue by hexaeder** [JuliaPlots/Makie.jl#913]
GLMakie misses some lines if there are duplicate positions in the data:
```
using GLMakie
x = [0,1,2,2,3,4]
y = [0,1,2,2,3,4]
scatterlines(x, y)
```
<img width="542" alt="grafik" src="https://user-images.githubusercontent.com/35867212/114690405-f4fd1480-9d16-11eb-84ab-513c7a6d72ab.png">

```
using CairoMakie
x = [0,1,2,2,3,4]
y = [0,1,2,2,3,4]
save("scatterlines1.png", scatterlines(x, y))
```
![scatterlines](https://user-images.githubusercontent.com/35867212/114690548-1827c400-9d17-11eb-954a-94f11ce9b0a8.png)
```
using WGLMakie
x = [0,1,2,2,3,4]
y = [0,1,2,2,3,4]
scatterlines(x, y)
```
<img width="647" alt="grafik" src="https://user-images.githubusercontent.com/35867212/114691667-34783080-9d18-11eb-9564-6d159e236a62.png">

Thanks for creating makie, great plotting package :)

**Comment by ffreyer** [comment]
#1386 fixed this
