### ISSUE TITLE
Subpixel sized circles

### ISSUE THREAD

**Issue by mschauer** [JuliaPlots/Makie.jl#914]
I have experimented a bit with very small circles.
A little program is 
```
using Makie
using Colors
n = 1000
f0(x) = (x[1],x[2])
αs = vec(CartesianIndices((n,n))) 
scatter((first.(f0.(αs)))/n, (last.(f0.(αs)))/n, markersize=1/n^2, color=:black, strokewidth=0.0,  markerspace=SceneSpace)
```
If you run it, you should see nothing, because while there are `1000*1000` disks, their individual area is vanishingly small and the total area of them together is only above `0.0001%` of the unit square. But Makie displays a filled square. That is I believe because the shader adds a antialias padding with radius `ANTIALIAS_RADIUS 0.8` making them  `pi/40`  or so sized of a pixel. having enough of them fills the space.

https://github.com/JuliaPlots/GLMakie.jl/blob/60f6a12cd0561def60ee369da506a57f5ec99344/assets/shader/sprites.geom#L5

**Comment by SimonDanisch** [comment]
I think you fixed that ;)
