### ISSUE TITLE
`delete!` does not fully clean up `Axis3`

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Makie.jl#923]
I've noticed that calling `delete!` on an `Axis3` does not completely remove it:

```julia
julia> fig = Figure()

julia> ax = Axis3(fig[1, 1])
Axis3()

julia> surface!(ax, rand(100, 100))
Surface{Tuple{IntervalSets.ClosedInterval{Float32}, IntervalSets.ClosedInterval{Float32}, Matrix{Float32}}}

julia> delete!(ax)
```

![frame](https://user-images.githubusercontent.com/6333339/115960345-23e26a00-a511-11eb-9f1a-4b02cab04dea.png)

Is this a fundamental difficulty, or should it be possible to remove it just like a normal `Axis`?

**Comment by jkrumbiegel** [comment]
I just didn't implement it specifically, or I forgot to add the elements to the `elements` dict so they are not deleted. Will be trivial to fix :)
