### ISSUE TITLE
Test failing on Linux

### ISSUE THREAD

**Issue by hkraus94** [JuliaPlots/Makie.jl#930]
I did the procedure of running
`]add GLMakie`
and
`test GLMakie`.
However, tests run fine on my windows machines but I tried the tests on 3 Linux machines with Julia 1.5.3, 1.5.4, 1.6.0 and 1.6.1 and tests fail with the message
```.../packages/GLMakie/5uIRQ/test/unit_tests.jl:36
  Expression: idx == N - 1
   Evaluated: 0 == 99999
Stacktrace:
 [1] macro expansion
   @ .../packages/GLMakie/5uIRQ/test/unit_tests.jl:36 [inlined]
 [2] macro expansion
   @ .../julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] macro expansion
   @ .../packages/GLMakie/5uIRQ/test/unit_tests.jl:28 [inlined]
 [4] macro expansion
   @ .../julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [5] top-level scope
   @ .../packages/GLMakie/5uIRQ/test/unit_tests.jl:10
Test Summary:                                             | Pass  Fail  Total
unit tests                                                |    8     1      9
  Window handling                                         |    6            6
  Pick a plot element or plot elements inside a rectangle |    2     1      3
ERROR: LoadError: LoadError: Some tests did not pass: 8 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /.../packages/GLMakie/5uIRQ/test/unit_tests.jl:9
in expression starting at .../packages/GLMakie/5uIRQ/test/runtests.jl:14
ERROR: Package GLMakie errored during testing
```
The funny thing is that GLMakie can indeed produce plots, however I am unsure if it is safe to use and fully commit on, if the tests fail.

**Comment by ffreyer** [comment]
This happens for me too, no idea why. The linux ci is fine and I think I checked that test manually when it first happened to me. Maybe it's a timing thing and the point picking runs before the plot has updated?

**Comment by SimonDanisch** [comment]
I currently don't have a PC with linux to check this, so hard to debug... If anyone can try to make an mwe out of the test code that fails, we can try to pin it down...

**Comment by ffreyer** [comment]
So for me as well:
```
Test Summary:                                             | Pass  Fail  Total
unit tests                                                |    8     1      9
  Window handling                                         |    6            6
  Pick a plot element or plot elements inside a rectangle |    2     1      3
ERROR: LoadError: LoadError: Some tests did not pass: 8 passed, 1 failed, 0 errored, 0 broken.
```

Copying the offending `@testset begin ... end` into a julia instance (with the relevant surround code exectued) fails. Copying the **content** succeeds.

**Comment by SimonDanisch** [comment]
So indeed evidence for a timing problem...

**Comment by SimonDanisch** [comment]
Maybe this fixes it? https://github.com/JuliaPlots/GLMakie.jl/pull/187

**Comment by hkraus94** [comment]
That fixed it for me.
