### ISSUE TITLE
Logo & favicon proposal

### ISSUE THREAD

**Issue by dyogurt** [JuliaPlots/Makie.jl#934]
Hello everyone, I would like to propose a new logo and favicon for Makie.jl. 
@piever mentioned that @musm was talking about this on Slack.

I do not know the concept or story behind the current logo so take my suggestion with a grain of salt if it's going in a weird direction. Nevertheless, I would very much like to help you have a new logo :)

Feel free to leave feedback or other suggestions.

## Logo concept
The [maki-e](https://en.wikipedia.org/wiki/Maki-e) technique and plot related nature of the package are expressed as sprinkled gold dots (scatter data) with a smooth fitted line. The Julia component appears as a red sun and colourful leaves (a natural motif is usually used in maki-e), a call back to the 3 shapes of the current logo.
#### Dark version for light backgrounds
![makie-logo_proposal-dark-1](https://user-images.githubusercontent.com/15688153/116730995-73c9a100-a9e9-11eb-8b1a-994d4cc19e53.png)
#### Light version for dark backgrounds
![makie-logo_proposal-light-1](https://user-images.githubusercontent.com/15688153/116730998-74623780-a9e9-11eb-9330-356f58dcd6e0.png)

### Font
I used [Space Grotesk](https://github.com/floriankarsten/space-grotesk/), an open source font that includes an interesting uppercase "M", much like the current logo.

## Favicon
It would be used at a very small scale so it keeps only the Julia coloured "nature" motifs (sun, leaves) and the cup shape.
![makie-favicon_proposal-1](https://user-images.githubusercontent.com/15688153/116730991-73310a80-a9e9-11eb-920c-209717990263.png)

**Comment by musm** [comment]
Pretty good! Do you plan to post SVGs, I'd like to tweak around parts of it.

**Comment by jkrumbiegel** [comment]
Very cool! I like the plant with the curve plot stem, that's quite clever. I'm not so sure about the bowl, I know it's connected to the japanese technique, but still :)

**Comment by dyogurt** [comment]
Thank you both for the feedback :)

@jkrumbiegel I share a similar filling towards the cup, I used it because of its distinct shape. Because maki-e can be done in multiple objects we can choose one that makes more sense. For example, a box (squircle) can be associated with some package related messages—"makie is ready to use 'out of the box...'"; "makei is a tool-box..."

### Box version
Besides changing the cup to a box I made it so "makie" comes before the graphic element, like in the current logo.

![makie-logo_proposal-light-2](https://user-images.githubusercontent.com/15688153/116781239-ff8f0c00-aa81-11eb-8921-2bee45b870c0.png)

@musm you can access the SVGs files trough this [Dropbox link](https://www.dropbox.com/s/yrarixlxfok2d1b/makie-logo_favicon-2.svg?dl=0), let me know if it's not working.
There should be 4 layers:

- favicon
- logo light v2 (the box)
- logo light v1 (the cup)
- logo dark v1 

I prefer to work only in the light version for now and do a dark one once all the details are settled.

### Idea
If the logo can be made in code (beyond my skills) it could be used as a nice little challenge for the community :) For example, people can be invited to edit the code to make their own version of the box/cup—different plots, colours, natural motifs, etc.

**Comment by musm** [comment]
Many thanks @dyogurt for the svg:

Here is my current proposal, building of your great design.  

I wanted to simplify things and keep it more fun. I felt that the rigid font didn't quite feel right and went with something more 'playful'. The glittering gold was a great idea and built on that and used it as glitter throughout the font, where the glitters represent the 'i' dot exploding.  The flower petals were abused but created a nice visual design around the gold sun and I decided to use them around the sun. Finally, a  paint stroke is the backdrop, which I think gives it a more natural feel. I'm not 100% convinced that the petal are required: 

![image](https://user-images.githubusercontent.com/4319522/116803514-4ca4c980-aae6-11eb-9d94-267dfe151599.png)


Simpler design
![image](https://user-images.githubusercontent.com/4319522/116803588-17e54200-aae7-11eb-9f1f-9f51daa465df.png)

**Comment by jkrumbiegel** [comment]
While it looks kind of nice, I don't think a brush stroke like that is good for a logo. It only resolves well in large size, and is kind of lost at a smaller one. I much prefer simpler geometric logos that work well at favicon size as well.

Just for comparison some other plotting library logos:

ggplot, not great but not too bad

![grafik](https://user-images.githubusercontent.com/22495855/116805537-77634200-ab27-11eb-810f-d19cba9d9208.png)

matplotlib, too cluttered and no clear idea

![grafik](https://user-images.githubusercontent.com/22495855/116805564-9c57b500-ab27-11eb-816c-06877cd9ade4.png)

matlab, this actually works very well at small size

![grafik](https://user-images.githubusercontent.com/22495855/116805574-ab3e6780-ab27-11eb-819b-27f275cd7cd4.png)

plotly, this is also nice and abstract, with clear design

![grafik](https://user-images.githubusercontent.com/22495855/116805593-d032da80-ab27-11eb-8a8e-da7ac376f08e.png)

I'd focus on a design that works very well at small size, because that's what you usually see. That can then be embellished if necessary for larger sizes.

**Comment by jkrumbiegel** [comment]
This is what I just came up with. I went with the golden squiggly line plus scatter markers, which I liked, but simplified the rest more so that it works also as a small logo. I'm partial about the golden i dot, that was a last second idea ;)

<img width="984" alt="grafik" src="https://user-images.githubusercontent.com/22495855/116807326-ec884480-ab32-11eb-87f5-7b147fc9b0e5.png">

**Comment by musm** [comment]
@jkrumbiegel  really attractive design.

I  tweaked around your design with an update to the font and logo elements to give it  3D depth and additional visual interest. 

![makie-logo_favicon-2 - Copy](https://user-images.githubusercontent.com/4319522/116913530-980ac500-ac17-11eb-81f9-d36f631d4986.png)

**Comment by ffreyer** [comment]
It would be good to change the font color to something that's decently visible on dark themes as well I think. Maybe one of the blue tones or a gray?

**Comment by musm** [comment]
@ffreyer the only real solution to that is to have two logo a light version and a dark version and ensure that documenter.jl uses the correct one depending on the user selected theme setting.  I related issue is : https://github.com/JuliaDocs/Documenter.jl/issues/1573   (my personal opinion is that the developers of the site should be able to set their own user defined theme preference, IMO I'm not a fan of the user selectable theme setting respecting OS level theme preferences)

**Comment by ffreyer** [comment]
This is just a quick test, but picking some blue out of the circle as the font color is pretty visible on white and the dark theme color...
![test](https://user-images.githubusercontent.com/10947937/116925366-63b7f880-ac59-11eb-8d43-f7571380047f.png)

**Comment by mschauer** [comment]
There is something nonsensical about the curve... it seems to avoid the points and not being attracted to it. A Linear Largest Squares fit?

**Comment by jkrumbiegel** [comment]
Haha I knew someone was going to point that out. It's just an artistic choice

**Comment by juliohm** [comment]
I am preparing a presentation where I would like to include a logo for the Makie project. Did you converge on an official logo? All the options above look really nice. Just wondering which one I should add to the slides :)

**Comment by jkrumbiegel** [comment]
> Did you converge on an official logo? 

No, there was no more discussion than what's going on in this thread. I did however play around with designs a little more. I'm personally more fond of simple geometric logos with a few colors at most and no gradients or shadows. Here's another version where I parted ways with the dots again. I think this is calmer and cleaner than the previous versions.

![Artboard 1@4x](https://user-images.githubusercontent.com/22495855/120023510-2c393380-bfee-11eb-8cad-fc664e3ece95.png)

**Comment by jkrumbiegel** [comment]
another completely different idea. I got some feedback that the other one could be a waterworks logo

![Artboard 1@4x](https://user-images.githubusercontent.com/22495855/120079502-6cfb8000-c0b4-11eb-9ff6-fb1da749590c.png)

**Comment by juliohm** [comment]
These all look great. I am having a hard time choosing a single one!

**Comment by jkrumbiegel** [comment]
another iteration, picking up the previous floral element a little bit. It also reminds a bit of scatter and line plot in 3D

![flowermakie@4x](https://user-images.githubusercontent.com/22495855/120096165-28aac700-c12a-11eb-844e-ce775af3809a.png)

**Comment by jkrumbiegel** [comment]
or maybe also with a triangular leaf, so we have mesh, line plot and scatter 
![flowermakie@4x](https://user-images.githubusercontent.com/22495855/120096449-e4b8c180-c12b-11eb-9a9b-bad78c28a9b2.png)

**Comment by dyogurt** [comment]
## Replies 

> This is what I just came up with. I went with the golden squiggly line plus scatter markers, which I liked, but simplified the rest more so that it works also as a small logo. I'm partial about the golden i dot, that was a last second idea ;)
> 
> ![makie_logo](https://user-images.githubusercontent.com/22495855/116815260-063e8180-ab5d-11eb-859d-c46dfa9eed08.png)

I really liked this approach and it inspired me to rework the floral pattern (typical in maki-e) I had originally proposed. I tried to include the idea of axis plots but in a slightly different way and I kept the golden dot (love it!) 

## New logo proposal
### Construction

![makie-logo-construction-1](https://user-images.githubusercontent.com/15688153/120100079-19824400-c13f-11eb-9f32-27ede284d8f1.png)

The "leaves" of the floral pattern become the axis of the plot, creating a square empty space occupied by the scatter and line.

### Logotype variations

![makie-logo_colors-1](https://user-images.githubusercontent.com/15688153/120100130-5b12ef00-c13f-11eb-86ff-9f91c1d23ebd.png)

The logo and logotype should work well in light and dark backgrounds, both in coloured or black and white versions.

### Docs example + Favicon

![makie-logo-page_favicon-1](https://user-images.githubusercontent.com/15688153/120100193-a3321180-c13f-11eb-8d4f-a6ecb80d6d0a.png)

My proposal for the favicon is a simple golden dot. I think it's okay to simply use an element of the logo as a favicon.

## Thoughts 

I want to explore the "data as gold" and the maki-e technique in my logo proposals as much as possible :) but it is exciting to see so many nice ideas and concepts appearing! The 3D one is incredible!

At some point, if we distill some concepts (eg. Classic Julia + 3D, Floral gold scatter, Improved playful typography) we could present them for the Makie/Julia community for a vote? Perhaps it will be easier to develop a more specific logo if we know which "vibe" or "style" most people would prefer? I'm new to open source so please ignore this idea if it sounds unimplementable :)

**Comment by mschauer** [comment]
<img width="477" alt="Screen Shot 2021-05-30 at 12 50 39" src="https://user-images.githubusercontent.com/1923437/120101273-a4fed380-c145-11eb-92bd-0d3d36b1ec50.png">

Let's get this right, the stakes are high.

**Comment by jkrumbiegel** [comment]
wow that's hard to beat, especially if we did this with online voting :) MakieMcMakieFace

**Comment by mschauer** [comment]
Somehow I got distracted :-) What I meant to say was: I'd love if the ornamental Maki-e like line-stem and scatter-leaves somehow could be disrupted towards the upper-right corner showing the power of Makie, e.g. turning fractal, or some effect in demoscene tradition where the mesh or grid of the shape becomes visible. That runs the risk of creating too much detail going against a logo which works for small reproduction, but perhaps worth a try.

**Comment by jkrumbiegel** [comment]
Thanks everybody for your input and suggestions! Simon and I have decided on a new logo now after thinking about all the versions presented here, and trying out countless more designs. We have gone with something simpler than most versions here, so it works as well when it's in a smaller size, and geometric so the general shape can work in different colors. After all, a decision had to be made and the logo search already swallowed more time than anticipated, so hopefully nobody feels slighted if their ideas and suggestions haven't made it into the final version. Nevertheless, it was very helpful to see the wide range of ideas, we appreciate your input, and thanks to @dyogurt especially for getting the ball rolling here with some really nice designs!

Anyway, this is the logo, we hope you like it :)

![grafik](https://user-images.githubusercontent.com/22495855/128036385-41e3e1e4-42eb-4c60-aab1-97349480f03d.png)

**Comment by timholy** [comment]
I didn't participate, but I think your choice is elegant and appealing!

**Comment by cormullion** [comment]
For fun, I had a go at recreating this logo in Julia (Luxor.jl). I did quite well, but I had trouble reproducing the gradient blends precisely. 

![new-makie-logo](https://user-images.githubusercontent.com/52289/128605697-efcf99ed-ccb4-45a0-a67e-16bfb4809f92.png)

I wondered whether your blend specifications are defined anywhere (in the Makie.jl code perhaps?)  Perhaps it's not possible to make similar blends in plain Luxor/Cairo. It looks like there's an additional dimension which I was unable to capture.

Anyway, I'm glad you have a new design and I hope to see it everywhere soon, attached to all the best vizualisations!

**Comment by jkrumbiegel** [comment]
Here's the ai file https://github.com/JuliaPlots/Makie.jl/blob/master/assets/makie_logo.ai

It's a mesh gradient, which I've adjusted manually so it looks pretty messy if you look at it in Illustrator. The reason is that mesh gradients have four cornered cells, which I massaged to look like a three corner mesh. That's why the gradients go across the petals.

**Comment by dyogurt** [comment]
Thank you @jkrumbiegel for showing us the final result! I'm happy the flowery nature of previous ideas made it to this version and that it merges so well with the feel of a 3D space filled with a _rainbow_ of possibilities :) Nice work!

**Comment by musm** [comment]
@jkrumbiegel  Thanks for the new logo!  Is there any chance we could use the  variant posted by @cormullion. The current logo, has an oddly  muted gradient when compared to the more vibrant variant.
