### ISSUE TITLE
CairoMakie: Problems with NaN values in arrows

### ISSUE THREAD

**Issue by jensln** [JuliaPlots/Makie.jl#939]
As briefly mentioned in #897, `CairoMakie` acts odd sometimes when given `NaN` values; specifically in this issue: with `arrows`. In every plotting library I've tried, when given `NaN` values, the usual behavior is that nothing is plotted. This works as expected with `GLMakie`, but with Cairo when arrows have `NaN`-components, some unexpected arrows still appears, pointing up and to the left. 

Here's a MWE, the number `3` here is arbitrary; you get the same behavior with more realistic numbers `NaN`s mixed in between.

```julia
arrows(1:3, 1:3, fill(NaN,3,3), fill(NaN,3,3))
```
With `CairoMakie`:
![tmp](https://user-images.githubusercontent.com/71942129/117111165-80eae500-ad87-11eb-8c4f-d47ac8479220.png)
With `GLMakie` (correct output):
![tmp](https://user-images.githubusercontent.com/71942129/117111258-9bbd5980-ad87-11eb-8381-f0b126d9e69d.png)

**Comment by jensln** [comment]
If someone can point me to the relevant code I might be able to fix this.

**Comment by SimonDanisch** [comment]
Thanks! :) 
arrows uses linesegments under the hood, so I first would try to make an minimal working example with that.
The code to draw this is annoyingly complex, but maybe with a good MWE and some debugger (println? :D)  magic it could be easy to find a fix:
https://github.com/JuliaPlots/CairoMakie.jl/blob/master/src/primitives.jl#L94-L157

**Comment by jkrumbiegel** [comment]
fixed in https://github.com/JuliaPlots/CairoMakie.jl/pull/164
