### ISSUE TITLE
Camera weirdness

### ISSUE THREAD

**Issue by pfitzseb** [JuliaPlots/Makie.jl#941]
So I was playing around with a large(ish) point cloud (just a simple `scatter` call) and zooming (or whatever it is that the mouse wheel does) seems weird for a few reasons:
1. Too many points seem to be culled at the start of the video.
2. Zooming slows down tremendously inside of the dataset.
3. A bit further along the camera start wiggling around even though I'm still only zooming forward (fp precision issue?)
4. At the end the screen goes black and I can't recover from there (although this one might just a corrupted camera position, similar to the previous point)

https://user-images.githubusercontent.com/6735977/117438637-1b872780-af32-11eb-83ff-5ecb9d6785df.mp4

Am I doing something wrong or is this a genuine issue with the camera?

**Comment by ffreyer** [comment]
This is probably because `lookat` and `eyeposition` got very close together. (Zooming moves eyeposition towards lookat)

Maybe it would be good to have a 3d camera that acts more like a space ship, i.e. translates rather than zooms.

**Comment by ffreyer** [comment]
That pr has been merged now and the changes should be available in 0.14.3+. Zooming changes the fov with it and you can do translations along the view direction with w/s. I assume the changes fix your problem so I'll close this. Feel free to comment here or open a new issue if that's not the case.
