### ISSUE TITLE
quiver/arrows with variable linewidth

### ISSUE THREAD

**Issue by pedrozudo** [JuliaPlots/Makie.jl#943]
I have been trying to figure out a way to plot arrow where each arrow has  a different width.

```julia
arrows!(xs, ys, us, vs, linewidth=vec(ts))

```

I saw something similar in this issue: #356 

The above snippet does not work, there is simply no figure showing up.
Dropping the `linewidth` argument, in turn, produces an image.

From what I saw in the code the issue has to do with the linesegments! function.

Is this something that can be added, or is there possibly an other way around it?

**Comment by pedrozudo** [comment]
hmm, I did try the following.

```julia
ts = vec(Vec2f0.(ts,ts))
```
this makes `ts` a `Vector{Vec{2, Float32}}`

but it is still not showing me ant figure.


While I am here, is there also the possibility to to have varying colors, varying opacities, and so on for the bodies of the arrows?

**Comment by ffreyer** [comment]
I mean like this - two floats per arrow, not one Vec2f0
```julia
arrows(rand(Point2f0, 10), rand(Point2f0, 10), linewidth = [1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10])
```
