### ISSUE TITLE
hline(s) and vline(s) inconsistency

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPlots/Makie.jl#946]
In my examples I will only use hline, but I have not seen any difference between using hline and vline.

Take a look at the MWE below:

```julia
using GLMakie
fig = Figure()
obs = Observable(9)
ax = Axis(fig[1, 1])
ylims!(ax, (0, 10))

# Works:
#hlines!(ax, 5)
#hlines!(ax, [6])
#hlines!(ax, obs)

# Does not work:
#hline!(ax, [5])
#hline!(ax, 5)
#hline!(ax, obs)
#hline!(ax, [obs])
#hlines!(ax, [obs])

fig
```
## Problem 1 - hline/vline
By uncommenting a single line at a time and running the entire section, I find that some lines work and others don't, in a way that does not make sense. First of all it seems like the singular version is just broken, as using it gives:
```
ERROR: Cannot convert Axis to series data for plotting
Stacktrace:

[1] error(s::String)

@ Base .\error.jl:33

[2] _prepare_series_data(x::Axis)

@ RecipesPipeline ~.julia\packages\RecipesPipeline\CirY4\src\series.jl:8

[3] _series_data_vector(x::Axis, plotattributes::Dict{Symbol, Any})

@ RecipesPipeline ~.julia\packages\RecipesPipeline\CirY4\src\series.jl:27
...
```

## Problem 2 - vector of observables does not work
But why `hlines!(ax, [obs])` fails, I don't understand. The error given is ```ERROR: MethodError: Cannot `convert` an object of type Observable{Int64} to an object of type Float32``` . The problem here is differential treatment of Observables and normal values, and no clear way to make with work with a vector of observables.

## Problem 3 - single value hlines work, when the command is plural
Furthermore, I don't understand why `hlines!(ax, 5)` and `hlines!(ax, obs)` work, when there is the singular form `hline()`. The problem here is that the grammatical singular and plural don't map to the programical single value vs array of values.

## Proposed solution
Personally, I would vote for calling the function hline/vline singular only, and deprecating the plural versions. The singular versions would take a single Number/Observable, or a vector of them. This would be made clear in doc-strings I would be happy to write. Should this be implemented the docs also have to be updated, which I would also like to do.

My reasoning is that I find it conceptually much weirder to remember to call `hlines()` when I want a _single_ hline, than to pass a vector to `hline()`. An additional argument is that the singular version is, by my estimate, likely to be used more.  Favouring singular therefore makes sense, without the plural really suffering.

I also think that deprecating either the singular or plural version is of benefit, for two reasons:
1) Maintainance cost from having multiple functions doing the same thing is not worth it
2) There is a gain in simplivity for the user from not having multiple options with overlapping functionality

**Comment by jkrumbiegel** [comment]
There is no `hline` or `vline` at all, same as there is no `line`, only `lines`. That's why it's named that way. I guess it's debatable what's more weird, to give a vector to a function with a singular name, or to give a single value to a function with a plural name. For me, plural implies singular but not the other way around.

The only example from your list that then remains not working is `hlines!(ax, [obs])`, which is conceptually incorrect. You can't pass a vector of observables, you can always pass an observable of a vector though. This works the same way across the whole Makie ecosystem.

**Comment by KronosTheLate** [comment]
> There is no `hline` or `vline` at all, same as there is no `line`, only `lines`. That's why it's named that way. I guess it's debatable what's more weird, to give a vector to a function with a singular name, or to give a single value to a function with a plural name. For me, plural implies singular but not the other way around. I do concede though that we have some inconsistency with `scatter` instead of `scatters`, for example.
Then it seems as if I had the singular versions imported from Plots or something like it. That makes the entire post of mine pretty misguided.

> The only example from your list that then remains not working is `hlines!(ax, [obs])`, which is conceptually incorrect. You can't pass a vector of observables, you can always pass an observable of a vector though. This works the same way across the whole Makie ecosystem.
This makes sense. I think I was somewhat looking for mistakes at this point. I will add some method examples to the doc-strings, and make this more clear. Thanks for the feedback!
