### ISSUE TITLE
Represent multiple traces with single axislegend-entry

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPlots/Makie.jl#947]
The axislegend function is terrific. But when I was to create a legend with a single entry representing both a scatter-object and a line-object (two exmples of what I mean by trace), I did not know how. So I was unable to utilize the convenience provided by `axislegend()`.

I don't know how to implement this, but have two ideas for the API:
1) If the "label" string matches for two or more traces, they are automatically represented by a single line in the legend.
2) A kwarg to `axislegend` called `group`, which takes an iterable of the traces that should be grouped in a single line in the legend. The acutal legend text would in this case be taken from the first trace in the group with a label defined.

I would personally prefer the first solution, even if it requires redundant labels. The reason is that one of the major advantages of using `axislegend` is that the traces do not need to be saved as variables. The first solution would make this hold true, whereas the second one would require intermediate saving of the traces to be grouped.

**Comment by jkrumbiegel** [comment]
this is added with `merge` and `unique` keywords in https://github.com/JuliaPlots/Makie.jl/pull/980

**Comment by KronosTheLate** [comment]
The implementation looks fantastic!! And the docs are also excellent. Thank you so much <3
