### ISSUE TITLE
font assets and PackageCompiler

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaPlots/Makie.jl#949]
From what I can tell, these lines: https://github.com/JuliaPlots/AbstractPlotting.jl/blob/61c8b5d669be9eae4abedd45b43e1f0b07c6fc4d/src/AbstractPlotting.jl#L245 and https://github.com/JuliaPlots/AbstractPlotting.jl/blob/bd5ac67e022b09d7b66746e5856d97fa02c25ba9/src/conversions.jl#L918 aren't compatible with relocating a generated sysimg since they assume that the source directories still exist, which isn't always the case. Would it be possible to move `assets/fonts` into an artifact to avoid this issue?

**Comment by SimonDanisch** [comment]
Sure, would be great if someone could do that :)

**Comment by MichaelHatherly** [comment]
I'll try look into it over the weekend. It's a blocker for a release 😄
