### ISSUE TITLE
Inset legend

### ISSUE THREAD

**Issue by jtrakk** [JuliaPlots/Makie.jl#950]
Gadfly supports putting legend components inside the plot box. That would be nice in Makie because it takes less space.

![image](https://user-images.githubusercontent.com/43392409/118332666-4c7dd400-b4bf-11eb-8bdc-45bedb0e8088.png)

http://gadflyjl.org/stable/gallery/guides/#[Guide.colorkey](@ref)

**Comment by SimonDanisch** [comment]
This is supported:
https://makie.juliaplots.org/dev/makielayout/legend.html#Legend-Inside-An-Axis
I guess you can also make the background transparent and hide the spines ;)
