### ISSUE TITLE
hist! in error for yscale=log10 

### ISSUE THREAD

**Issue by walra356** [JuliaPlots/Makie.jl#951]
hist! works fine for yscale=identity but errors for yscale=log10.  xscale=log10 works fine. A log of zero is always a problem but how to avoid it in this case? See example below: 
```
using GLMakie
GLMakie.activate!()
AbstractPlotting.inline!(true) 
data = abs.(randn(500))
f = Figure()
ax = Axis(f[1,1],yscale=log10)
hst = hist!(ax,data;bins=25)
f
```
ans = Found invalid direct y-limits (0.0f0, 63.0f0) for scale log10 which is defined on the interval 0.0..Inf (open)

**Comment by walra356** [comment]
I made some progress: by setting the limits on axes I can suppress the error. I can nicely scroll the scale but the HISTOGRAM IS NOT DISPLAYED (see example below). I do not have this difficulty with xscale=log10. What to do to make the histogram visible?
```
using GLMakie
GLMakie.activate!()
data = abs.(randn(500))
f = Figure()
ax = Axis(f[1,1],yscale=log10)
ax.limits=(0.0011,3,0.0001,20)
hst = hist!(ax,data;bins=25)
AbstractPlotting.inline!(false) 
display(f)
``

**Comment by ffreyer** [comment]
The problem is that a histogram bar starts at 0 and `log10(0) = -Inf`, I assume. I'm not sure if this works with arbitrary scales, but if it does maybe `yscale = y -> log10(y+1)` would work?

**Comment by walra356** [comment]
Your suggestion did not work... I tend to agree with you. hist! cannot plot the lower end of the histogram bar. So, one has to set the lower end of the bar equal to the lower y-limit (for the log options). That would do the job. Do you know how to do that?

Maybe I should abandon the hist!  and do the binning myself. Then I can use a scatter plot...

As a physics user I would say that a y-log option is more or less indispensible.

Thanks for your comments and success with your studies!

**Comment by walra356** [comment]
I could not resist having a closer look at the code. The problem is that `hist!` depends on  `barplot`, which has an attribute called  `fillto` which is put on `automatic`. In `hist` `automatic` results in fillto=0.0,. So the histogram rectangle starts at 0 :

```
function bar_rectangle(x, y, width, fillto)
    # y could be smaller than fillto...
    ymin = min(fillto, y)
    ymax = max(fillto, y)
    w = abs(width)
    return FRect(x - (w / 2f0), ymin, w, ymax - ymin)
end
```
This causes the  `log10(0) = -Inf` problem in the backend. This can be prevented by setting `fillto`  manually to a nonzero value. 
This workaround is demonstrated in the following example.
```
data = abs.(randn(500))
f = Figure()
ax = Axis(f[1,1],yscale=log10)
ax.limits=(0.0011,3,0.0001,0.2)
hst = hist!(ax,data;bins=25,normalization=:probability)
hst.plots[1].attributes.fillto=0.0001
AbstractPlotting.inline!(true) 
display(f)
```
How to proceed? It is probably simplest to add `fillto` to the attributes of `hist`. Or, do something with the automatic settings fillto. I have no idea where the automatic settings are defined.

How to proceed?

**Comment by walra356** [comment]
Note that the same problem happens in `density plots`. Example:
```
set_theme!()
f = Figure()
Axis(f[1, 1])
for i in 1:6
    density!(randn(50) .+ 2i)
end
Axis(f[2, 1], palettes = (patchcolor = [:red, :green, :blue, :yellow, :orange, :pink],))
for i in 1:6
    density!(randn(50) .+ 2i)
end
set_theme!(Density = (cycle = [],))
Axis(f[3, 1],yscale=log10)
for i in 1:6
    density!(randn(50) .+ 2i)
end
f
```

**Comment by ffreyer** [comment]
> How to proceed? It is probably simplest to add fillto to the attributes of hist. Or, do something with the automatic settings fillto. I have no idea where the automatic settings are defined.

I think adding `fillto = automatic` to hist would reasonable. Should be fine to just pass that to barplot

**Comment by Moelf** [comment]
I like how physics leads to log/irregular histograms ;). Here's a one-liner to reproduce:

```julia
hist(rand(1000), axis=(title="charge", xlabel="blah", yscale=log10))
```

https://github.com/JuliaPlots/Plots.jl/pull/2962

later we will have error bar crossing to negative y-axis ;)

**Comment by walra356** [comment]
Did you see the suggestion in JuliaPlots/Makie.j#1016 ?
`hist(rand(1000), axis=(title="charge", xlabel="blah", yscale=log10))`
![image](https://user-images.githubusercontent.com/69215586/126348720-8b5f663d-7cb9-4e4b-8867-48d1b35e8ca8.png)

**Comment by walra356** [comment]
even better: now in standard Makie de semilog
`hist(rand(1000), axis=(title="charge", xlabel="blah", yscale=Makie.pseudolog10))`
![image](https://user-images.githubusercontent.com/69215586/126350486-85f04a81-6c5b-4555-ad3a-eead3de23471.png)

**Comment by Moelf** [comment]
![image](https://user-images.githubusercontent.com/5306213/126351456-78bde945-b149-40d4-b854-5096ff7dec2e.png)

guess I'm on a old Makie then

**Comment by walra356** [comment]
yes, look at the new docs under hist

**Comment by Moelf** [comment]
I'm confused. Where? http://makie.juliaplots.org/dev/plotting_functions/hist.html

**Comment by walra356** [comment]
https://makie.juliaplots.org/dev/plotting_functions/hist.html#hist

**Comment by walra356** [comment]
https://makie.juliaplots.org/dev/makielayout/axis.html#Pseudolog-and-symlog-scales
sorry!

**Comment by cossio** [comment]
If this is fixed on master, can we have a release including this?

**Comment by cossio** [comment]
Bump. Is there an accepted "recommended" solution to this?

**Comment by walra356** [comment]
See above, solved with pseudog10.

`hist(rand(1000), axis=(title="charge", xlabel="blah", yscale=Makie.pseudolog10))`

This works for me under CairoMakie.

I guess this issue should have been closed earlier

**Comment by cossio** [comment]
I would not say `Makie.pseudolog10` solves the issue, since `pseudolog10` scale is **not** the same as `log10` scale. They are different.

Ideally, I'd wish for a solution where Makie automatically clips the range to exclude 0 and make `log10` work.

**Comment by markub3327** [comment]
To scale it around zero you must use:

` t = sign(x)*log(1+abs(x)/10^C)`
