### ISSUE TITLE
Old axis labels showing up in new Figure with SVG in CairoMakie

### ISSUE THREAD

**Issue by palday** [JuliaPlots/Makie.jl#952]
When plotting successive figures to SVG with CairoMakie, the previous figures linger and contaminate the new figure. This is visible in a recent [docs preview in MixedModelsMakie](https://palday.github.io/MixedModelsMakie.jl/previews/PR9/api/). The first plot renders correctly, but the second and third plots have clear problems with overprinting in the y-axis labels. Likewise, the final plot, which is completely distinct clearly has some overplotted axis labels from the first three plots.

This problem does not occur with PNG output.

cc @dmbates

**Comment by SimonDanisch** [comment]
We switched the default to PNG because of this:
https://discourse.julialang.org/t/cairomakie-and-fontconfig/55931/4
https://github.com/JuliaPlots/CairoMakie.jl/pull/147

As far I can tell, there isn't much we can do on the Makie side of things...

**Comment by jkrumbiegel** [comment]
The problem is that Documenter's tagged version puts svgs directly into the page. This causes them to interact which each other because glyph ids are shared among them. The fix is to use svgs in `<img>` tags, as they don't interact anymore this way. (or to salt the ids of the svg to be unique, I think matplotlib does that to avoid the same issue). You can look at your "messed up" documentation examples in a new tab and they will be fine.

I fixed this issue on Documenter#master, which is what our docs currently build with until a new version is tagged.

**Comment by palday** [comment]
Is there a way to get different glyph ids? Pass a UUID or the like when constructing the SVG object?

**Comment by jkrumbiegel** [comment]
![grafik](https://user-images.githubusercontent.com/22495855/118498111-f8c0f400-b725-11eb-9cd9-0adace1d36a7.png)
 
here you can see it, these generic glyph ids repeat

**Comment by jkrumbiegel** [comment]
> 
> 
> Is there a way to get different glyph ids? Pass a UUID or the like when constructing the SVG object?

I guess we could look for `id="glyph` and add a uuid there, yes

**Comment by jkrumbiegel** [comment]
the other issue with directly embedded svgs is that they don't resize, so I find the `img` way in Documenter#master preferable, even without the glyphs

**Comment by palday** [comment]
I'm thinking more as a stop-gap until Documenter has a new release.

**Comment by jkrumbiegel** [comment]
maybe we should do this anyway if it messes up other tools as well, like jupyter notebooks

**Comment by knuesel** [comment]
Oh it does mess Jupyter notebooks :) I was going to file an issue about this after doing some research. I'll write my results here:

* The behavior is correct as far as browsers are concerned: SVGs are [allowed](https://stackoverflow.com/questions/16123721/how-to-use-local-defs-in-svg) to interact according to the spec.
* This causes much pain with notebooks and other projects. See for example:
   * https://github.com/igraph/python-igraph/issues/222
   * https://github.com/jupyter/jupyter/issues/298
   * https://github.com/jupyter/notebook/issues/333
   * https://github.com/JuliaLang/IJulia.jl/issues/662
* Many projects have implemented workarounds:
   * rewriting IDs: [TikzPictures.jl](https://github.com/JuliaTeX/TikzPictures.jl/blob/11d45949ba782f75dfe3206c3fb1933fc7fd2980/src/TikzPictures.jl#L389), [Luxor.jl](https://github.com/JuliaGraphics/Luxor.jl/blob/87c3afd565818d847ef10b99a13ab79d80c1a6aa/src/drawings.jl#L110), [RCall.jl](https://github.com/JuliaInterop/RCall.jl/blob/74e5af3670ab0d51217bdba3e281d906602802af/src/IJulia.jl#L36) but also for example [seqlogo](https://github.com/betteridiot/seqlogo/commit/66021f09437b655f65bef7eee664a9c86e623881), [Drawdown](https://github.com/ProjectDrawdown/solutions/commit/59caaa82b4d2ed1a61a9c4a35fa6245e9111eebc) and [matplotlib](https://github.com/matplotlib/matplotlib/blob/de2ea8bb5ed11f776087f71bcbfab4d5e45a1a14/lib/matplotlib/backends/backend_svg.py#L449).
   * base64-encoding the SVG in img data: [IHaskell](https://github.com/gibiansky/IHaskell/commit/df7625e8ca5e57372f11fc09053abd90a2894c83).
   * home-made iframe wrapper: [stata_kernel](https://github.com/kylebarron/stata_kernel/commit/30519b050806a6f9fbe690193188f223d0d56912).
   * using official solution for Jupyter (`isolated` metadata in kernel protocol): [igraph](https://github.com/igraph/python-igraph/pull/148/files).

For Jupyter the `isolated` metadata fixes this by wrapping the SVG in an iframe. It can be implemented by specializing the `IJulia.metadata` method but apparently that must be made for every type that can go through `display` or related methods (e.g. `IJulia.display_dict`):

```julia
# For plots shown as return value
IJulia.metadata(::AbstractPlotting.Figure) = Dict("isolated" => true)

# For plots shown by calling `display` explicitely
IJulia.metadata(::AbstractPlotting.Scene) = Dict("isolated" => true)

# For AlgebraOfGraphics plots shown by return value
IJulia.metadata(::AlgebraOfGraphics.FigureGrid) = Dict("isolated" => true)
```

So there are at least the following options:

* Use Jupyter `isolated` metadata: this only fixes it for Jupyter, and it requires a dependence on IJulia and must(?) be done for each figure type.
* Provide an API to optionally wrap the SVG in an HTML iframe.
* Make the IDs unique. There was a patch submitted to Cairo for this but the developers think it's best done downstream when several SVGs are put together: https://gitlab.freedesktop.org/cairo/cairo/-/issues/304

**Comment by jkrumbiegel** [comment]
I think I'll follow the matplotlib approach and replace the ids with salted versions, created with the shortened hash of the full svg. This means that the same file will have the same salt when reproducing figures.

**Comment by jkrumbiegel** [comment]
https://github.com/JuliaPlots/CairoMakie.jl/pull/163
