### ISSUE TITLE
Legend markerstroke mismatch

### ISSUE THREAD

**Issue by piever** [JuliaPlots/Makie.jl#955]
Given that `markerstrokecolor` is black by default, but `markerstrokewidth` is `0`, and `markerstrokewidth` is not forwarded to the legend, now the legend marker style is "mismatched" by default, in that it shows a marker stroke that the plot doesn't have. See [this example in the docs](https://makie.juliaplots.org/dev/makielayout/legend.html#Creating-A-Legend-From-Elements).

Maybe we should just forward `strokewidth` to the `MarkerElement`?

**Comment by piever** [comment]
I would actually take the value from the theme if the user is passing a vector for that attribute. My reasoning is that if the user is doing eg

```julia
scatter(rand(10), marker=:rect, color=rand(10))
```

then the color info should be encoded in a separate colorbar anyway and does not need to be part of the "discrete legend". It'd be a bit harsh to error, and confusing to take a random color from `viridis` to encode the trace.

(Just to clarify, on my end, the important thing is that `MarkerElement` supports all the necessary attributes, rather than how they are taken from the plot.)

**Comment by jkrumbiegel** [comment]
fixed this in https://github.com/JuliaPlots/Makie.jl/pull/971

for each attribute it is checked if it's `is_scalar_attribute` and if not the default is looked up in the legend, which inherits from the main theme
