### ISSUE TITLE
2D Histogram missing (didn't merge from StatsMakie)

### ISSUE THREAD

**Issue by Moelf** [JuliaPlots/Makie.jl#958]

**Comment by ffreyer** [comment]
Are you looking for `hist`?

**Comment by piever** [comment]
2D histogram was never a plotting recipe, it was an `Analysis` from StatsMakie, and analyses have been moved to AlgebraOfGraphics, see: http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/datatransformations/#Histogram

I guess it'd be possible to add `hist2D` here, but I confess I tend to be against plotting recipes that mainly do a statistical transformation. In practice, the 2D histogram is already possible via `heatmap(fit(Histogram, (x, y))`

**Comment by Moelf** [comment]
heatmap cannot do arbitrary edges

**Comment by Moelf** [comment]
https://seaborn.pydata.org/generated/seaborn.histplot.html
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist2d.html

actually now I'm wondering, would Makie be open to have a `hist2d`?
