### ISSUE TITLE
Allow general object in labels and co.

### ISSUE THREAD

**Issue by Kolaru** [JuliaPlots/Makie.jl#972]
As the work on [MathTeXEngine.jl](https://github.com/Kolaru/MathTeXEngine.jl) is slowly progressing, I have also started to look into allowing Makie to render TeX strings in labels. This is currently not possible because `LineAxis` is only accepting `String` as label. 

I am not really sure how to move forward (hence this issue), but after giving it some thoughts, I think it would be reasonnable to allow any types to be passed as label and to define an interface for labels. I looked into it and I think the following interface should be enough for a type `LabelInput`:

- A function `draw_label!(parent, label::LabelInput ; label_attrs...)` drawing the label on the parent scene and returning an object of type `LabelOutput`.
- A function `boundingbox(label::LabelOutput)` returning the size of the label.
- Optionnaly a function `isempty(label::LabelInput)` returning whether the label actually contain anything (this can be set to `false` by default for non-strings).

That way having TeX label would be as easy as writing `ax.xlabel = L"p_x"` (`L"..."` is LaTeXStrings.jl macro for... latex strings).

While maybe overkill, having the label code more generic in this way would have several additional advantages:
1. The label could in principle be an image, allowing a (hopefully) straightforward integration for [`MakieTeX.jl`](https://github.com/JuliaPlots/MakieTeX.jl) as well.
2. Additional options (e.g. mathematical font set) can be passed to the constructor of `LabelInput` and retrieve by `draw_labe!` without Makie having to do anything in between.
3. Kind of following from the previous, the new types of label could be added entirely in external packages without touching Makie.

If this sounds reasonnable enough, I'll look into making the modifications in a PR.

**Comment by jkrumbiegel** [comment]
That sounds like a good direction. One thing that's important is the ability to change the label, which is currently simple. But if you change from string to LatexString and back, the first Text object needs to be replaced etc.

So I would probably add another function that returns the label plot type for the label type. Then whenever the label changes, it needs to be checked if the current label object still has the same label plot type. If so, everything should be fine. If not, the current label plot needs to be replaced.

For example

```julia 
labelplottype(::String) = Text
labelplottype(::LatexString) = SpecialPlotType 
```

**Comment by jkrumbiegel** [comment]
The same logic should then be used for axis title and labels as well

**Comment by ffreyer** [comment]
What's stopping us from using the normal `Makie.Text` for this? We have `input_args` for the LaTeXString, `converted` for the final characters, and the `_glyphlayout` for positioning the characters... Isn't that all you need in the end? If we use that it should be enough to allow labels etc to an AbstractString.

I'm not sure if MakieTeX could work with this, though I think we could have some `CompiledTeXString` that gets lowered to an image/svg in the backends. (Generating an image shouldn't happen in general anyway - it's redundant for CairoMakie.)

**Comment by SimonDanisch** [comment]
I feel like this really should just be an overload of `plot!(text::Text{Tuple{<:LatexString}})`

**Comment by ffreyer** [comment]
`VLine` and `HLine` maybe a bit more difficult to deal with. Maybe those could be done by stretching out a full block character █?

**Comment by Kolaru** [comment]
> What's stopping us from using the normal Makie.Text for this?

> I feel like this really should just be an overload of `plot!(text::Text{Tuple{<:LatexString}})`

Fair points. I am rather new to Makie internals, so I did not know about those. It seems to be the way to go and doesn't change the core idea as far as I can tell.

> We have input_args for the LaTeXString, converted for the final characters, and the _glyphlayout for positioning the characters... Isn't that all you need in the end?

The main tricky thing I see here is the fact that for latex strings the font and the font size change from character to character, so the current `Glyphlayout` is insufficient.

> `VLine` and `HLine` maybe a bit more difficult to deal with. Maybe those could be done by stretching out a full block character █?

It should be fine to draw them as polygons. They should only mess with interactive text that relies on `_glyphlayout`, and this will be broken anyway.

**Comment by ffreyer** [comment]
> The main tricky thing I see here is the fact that for latex strings the font and the font size change from character to character, so the current Glyphlayout is insufficient.

Font size (or textsize) more or less controls the size of the glyphs. So that's adjustable. The font can be given per character as well, I think, but I'm not sure if it's easy to seperate from the user selected font.

> It should be fine to draw them as polygons. They should only mess with interactive text that relies on _glyphlayout, and this will be broken anyway.

The ideal thing would be to just use `Text` (without child plots) for latex strings. Because then it's treated like any other text in Makie and you can switch between normal strings and latex strings without any issues.

**Comment by jkrumbiegel** [comment]
I mean we can also easily dispatch what kind of layout algorithm gets called given the type of string. And it would be no problem to return scales per glyph there, which I'm just not doing currently because it's not needed for the normal case.

Can't we also change the status of Text to non-atomic and introduce another atomic subversion, so that we can add linesegments to the LatexString recipe? We do this kind of type dependent recipe for arrows for example, although that's not coded flexibly enough to change the type parameter. I guess that's also my problem with the Text approach, that you couldn't change back and forth between different types if the type parameter of the Text plot has to stay fixed.

**Comment by SimonDanisch** [comment]
I think we have this implemented now in https://github.com/JuliaPlots/Makie.jl/pull/1022 ?

**Comment by Kolaru** [comment]
Yes it solves the core problem discussed here.
