### ISSUE TITLE
Plotting lines with colormaps?

### ISSUE THREAD

**Issue by jaehongpark-neuro** [JuliaPlots/Makie.jl#981]
Hi,

I just started to use Makie.jl, which looks great.

I was wondering whether I could use colormaps such as thermal, or inferno to plot different lines with gradients in a single plot in addition to the colors.

I noticed that varying colors for lines only works with colors, such as green, blue or something that are define in Color.jl.

![image](https://user-images.githubusercontent.com/80608873/119436255-d6147980-bce9-11eb-99de-6a3c31c3ebed.png)

Based on the statements
"For line plots, you can provide a single color or symbol that will color the entire line, or you can provide an array of values that map to colors using a colormap." I thought my implementation bellow would work but it didn't
![image](https://user-images.githubusercontent.com/80608873/119448608-92c50580-bcff-11eb-936b-646fea337327.png)

Is there any way to use such colormaps to label different lines?

**Comment by jkrumbiegel** [comment]
There are many ways to do this, here are some options

```julia
f = Figure()
Axis(f[1, 1])

for i in 1:10
    lines!(1:100, x -> i * x, color = fill(i, 100), colorrange = (1, 10))
end

f
```

![grafik](https://user-images.githubusercontent.com/22495855/119460355-df7c0100-bd3e-11eb-9ba0-f438b2ba43a2.png)

```julia
f = Figure()
Axis(f[1, 1])

n = 10
for i in 1:n
    lines!(1:100, x -> i * x, color = cgrad(:thermal, n, categorical = true)[i])
end

f
```

![grafik](https://user-images.githubusercontent.com/22495855/119460501-0cc8af00-bd3f-11eb-90b0-8e287ba6bf04.png)

```julia
f = Figure()
Axis(f[1, 1])

n = 10
for i in 1:n
    lines!(1:100, x -> i * x, color = cgrad(:Blues, n)[range(0, 1, length = n)[i]])
end

f
```

![grafik](https://user-images.githubusercontent.com/22495855/119460688-38e43000-bd3f-11eb-85f1-39d0e1e2cb42.png)
