### ISSUE TITLE
Legend element color regression

### ISSUE THREAD

**Issue by Octogonapus** [JuliaPlots/Makie.jl#983]
Starting in Makie v0.13.3 and onwards, legend elements all render in a gray color:

Makie v0.13.2:
![makie 0-13-2](https://user-images.githubusercontent.com/4064722/119531288-c6c91680-bd51-11eb-9013-314799a48d5c.png)

Makie v0.13.3:
![makie 0-13-3](https://user-images.githubusercontent.com/4064722/119531302-c9c40700-bd51-11eb-964a-dd794a6a2168.png)

Makie v0.13.4:
![makie 0-13-4](https://user-images.githubusercontent.com/4064722/119531317-ccbef780-bd51-11eb-8819-118f84cacc7a.png)

Here is my code to reproduce:
```julia
using GLMakie, ColorTypes
f = Figure()
Legend(f, [PolyElement(color = HSV(120, 1, 1), strokecolor = :black, polypoints = Point2f0[(0, 0), (1, 0), (1, 1), (0, 1)])], ["A"])
```

I am using Julia 1.6.1.

**Comment by SimonDanisch** [comment]
The name has unfortunately changed from `color` to `polycolor` as an unintended consequence of improving the themeability.
I think this is to be treated as a bug and the plan is to bring back `color` as the keyword argument.

**Comment by SimonDanisch** [comment]
Fix: https://github.com/JuliaPlots/Makie.jl/pull/987
