### ISSUE TITLE
`scatter` + `Axis3` + `GLMakie` does not work

### ISSUE THREAD

**Issue by hexaeder** [JuliaPlots/Makie.jl#994]
This came up in slack:
```julia
f = Figure()
pos = rand(Point3f0, 10)
ax3 = f[1,1] = Axis3(f)
scatter!(ax3, pos)
lines!(ax3, pos)
```
The points do not show up in `GLMakie`:
<img width="500" alt="Screenshot 2021-05-27 at 11 51 17" src="https://user-images.githubusercontent.com/35867212/119806462-8351e200-bee2-11eb-9659-ea6b70156cbd.png">
as they do with `CairoMakie`
<img width="500" alt="Screenshot 2021-05-27 at 11 52 19" src="https://user-images.githubusercontent.com/35867212/119806502-8b118680-bee2-11eb-83a3-a27e7940c571.png">

~~This seems do be independent of the `markersize` argument.~~

**Comment by jkrumbiegel** [comment]
markersize = 3000 or something should show them in GLMakie. Axis3 has a scaled view matrix, and I think this view matrix is somehow not correctly incorporated when adjusting the scatter marker size. You can change the `ax3.perspectiveness` values between 0 and 1, and the closer the camera gets to the axis, the bigger the markers become (they should of course be independent)

**Comment by hexaeder** [comment]
Yes you are right, they show up and scale further with the `ax3.perspectiveness`. I was still using to small markers...

**Comment by jcbritobr** [comment]
The issue happens yet in this new version. I think for 2d line plot with lines function, it really dont works
![image](https://user-images.githubusercontent.com/6579862/160849904-f2e1ceb2-715a-429c-a909-5cd3c6f981c4.png)

Im following the basics tutorial in Makie.jl documentation
![image](https://user-images.githubusercontent.com/6579862/160850164-509595a8-c8e9-4bb5-acae-a0482615f189.png)

I think this issue should be reopened.

**Comment by jcbritobr** [comment]
> > I think for 2d line plot with scatter function, it really dont works
> 
> This seems to be another issue? Can you make the code copy & pastable and explain the expected behavior? I don't see a plot with 300 markersize, and you're creating multiple plots while only screenshotting one, so I'm not sure what's going on here

Realised that was my issue here. Problem was in a typo.
